<a href="https://colab.research.google.com/github/msankar/cheat-at-search/blob/main/2c_Query_Categories_Search_First.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Query to get candidates BEFORE classification

<small>
(from <a href="http://maven.com/softwaredoug/cheat-at-search">Cheat at Search with Agents</a> training course by Doug Turnbull.)
</small>

It might not be feasible to do a lot of LLM classification unless we can use a smaller model with fewer tokens. One approach is to search and THEN classify into some of the matching categories. That's what we do here.

This might let us get some of the benefit with less of the downside.

## Boilerplate

Install deps, mount GDrive, prompt for your OpenAI Key (placed in your GDrive), and import needed cheat at search helpers.

We cover this extensively in the [synonyms notebook](https://colab.research.google.com/drive/1aUCvcBa1YdmsbIgYc74jlknl9_iRotp1) walkthrough

In [ ]:
!pip install git+https://github.com/softwaredoug/cheat-at-search.git
from cheat_at_search.data_dir import mount
mount(use_gdrive=True)
from cheat_at_search.search import run_strategy, ndcgs, ndcg_delta, vs_ideal
from cheat_at_search.wands_data import products, judgments, labeled_query_products

products

Collecting git+https://github.com/softwaredoug/cheat-at-search.git
  Cloning https://github.com/softwaredoug/cheat-at-search.git to /tmp/pip-req-build-r0lot8ab
  Running command git clone --filter=blob:none --quiet https://github.com/softwaredoug/cheat-at-search.git /tmp/pip-req-build-r0lot8ab
  Resolved https://github.com/softwaredoug/cheat-at-search.git to commit edca45d487123153a7db11d7cd2c7bc088842e07
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting datasets<5.0.0,>=4.8.4 (from cheat_at_search==0.1.0)
  Downloading datasets-4.8.5-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: google-genai<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from cheat_at_search==0.1.0) (1.68.0)
Requirement already satisfied: lxml<7.0.0,>=6.0.2 in /usr/local/lib/python3.12/dist-packages (from cheat_at_search==0.1.0) (6.1.0)
Collecting openai<2.0.0,>=1.84.0 (from cheat_at_search==0.1.0)
  Downloading openai-1.109.1-py3-none-any.whl.metadata (29 kB)
Requirement already satisfied: pandas<3.0.0,>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from cheat_at_search==0.1.0) (2.2.2)
Requirement already satisfied: pyarrow<22.0.0,>=14.0.0 in /usr/local/lib/python3.12/dist-packages (from cheat_at_search==0.1.0) (18.1.0)
Requirement already satisfied: pydantic<3.0.0,>=2.11.0 in /usr/local/lib/python3.12/dist-packages (from cheat_at_search==0.1.0) (2.12.3)
Collecting pystemmer<4.0.0,>=3.0.0 (from cheat_at_search==0.1.0)
  Downloading PyStemmer-3.0.0-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: pyyaml<7.0.0,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from cheat_at_search==0.1.0) (6.0.3)
Collecting searcharray<0.0.74,>=0.0.73 (from cheat_at_search==0.1.0)
  Downloading searcharray-0.0.73-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Requirement already satisfied: sentence-transformers<6.0.0,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from cheat_at_search==0.1.0) (5.4.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (3.29.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (2.0.2)
Collecting pyarrow<22.0.0,>=14.0.0 (from cheat_at_search==0.1.0)
  Downloading pyarrow-21.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.3 kB)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (0.3.8)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (0.70.16)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (2025.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (1.11.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (26.1)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.2.0->cheat_at_search==0.1.0) (4.13.0)
Requirement already satisfied: google-auth<3.0.0,>=2.47.0 in /usr/local/lib/python3.12/dist-packages (from google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.2.0->cheat_at_search==0.1.0) (2.47.0)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.2.0->cheat_at_search==0.1.0) (9.1.4)
Requirement already satisfied: websockets<17.0,>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.2.0->cheat_at_search==0.1.0) (15.0.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.2.0->cheat_at_search==0.1.0) (4.15.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.2.0->cheat_at_search==0.1.0) (1.9.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.2.0->cheat_at_search==0.1.0) (1.3.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from openai<2.0.0,>=1.84.0->cheat_at_search==0.1.0) (0.14.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.2.0->cheat_at_search==0.1.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.2.0->cheat_at_search==0.1.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.2.0->cheat_at_search==0.1.0) (2026.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.11.0->cheat_at_search==0.1.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.11.0->cheat_at_search==0.1.0) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.11.0->cheat_at_search==0.1.0) (0.4.2)
Requirement already satisfied: Cython in /usr/local/lib/python3.12/dist-packages (from searcharray<0.0.74,>=0.0.73->cheat_at_search==0.1.0) (3.0.12)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (5.0.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (2.10.0+cpu)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (1.16.3)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5.0.0,>=4.8.0->google-genai<2.0.0,>=1.2.0->cheat_at_search==0.1.0) (3.13)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (3.13.5)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.2.0->cheat_at_search==0.1.0) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.2.0->cheat_at_search==0.1.0) (4.9.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (1.4.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (0.24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3.0.0,>=2.2.0->cheat_at_search==0.1.0) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (2.5.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (3.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (0.7.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (1.23.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.2.0->cheat_at_search==0.1.0) (0.6.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (0.1.2)
Downloading datasets-4.8.5-py3-none-any.whl (528 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 529.0/529.0 kB 3.4 MB/s eta 0:00:00
Downloading openai-1.109.1-py3-none-any.whl (948 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 948.6/948.6 kB 18.5 MB/s eta 0:00:00
Downloading pyarrow-21.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (42.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 MB 24.4 MB/s eta 0:00:00
Downloading PyStemmer-3.0.0-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (745 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 745.3/745.3 kB 38.1 MB/s eta 0:00:00
Downloading searcharray-0.0.73-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 10.6 MB/s eta 0:00:00
Building wheels for collected packages: cheat_at_search
  Building wheel for cheat_at_search (pyproject.toml) ... done
  Created wheel for cheat_at_search: filename=cheat_at_search-0.1.0-py3-none-any.whl size=1453000 sha256=b3b100a3b1d65b933ef2f6026ff877c996cd324be6461bc247a98b1813f069d2
  Stored in directory: /tmp/pip-ephem-wheel-cache-hz646pct/wheels/ea/96/d3/e69453e5f86e6f891864e5b5baf2b11ffda2d0981d9f8a138e
Successfully built cheat_at_search
Installing collected packages: pystemmer, pyarrow, searcharray, openai, datasets, cheat_at_search
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: openai
    Found existing installation: openai 2.32.0
    Uninstalling openai-2.32.0:
      Successfully uninstalled openai-2.32.0
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
Successfully installed cheat_at_search-0.1.0 datasets-4.8.5 openai-1.109.1 pyarrow-21.0.0 pystemmer-3.0.0 searcharray-0.0.73
Mounted at /content/drive

,product_id,product_name,product_class,category hierarchy,product_description,product_features,rating_count,average_rating,review_count,features,doc_id,title,description,category,sub_category,cat_subcat
0,0,solid wood platform bed,Beds,Furniture / Bedroom Furniture / Beds & Headboa...,"good , deep sleep can be quite difficult to ha...",overallwidth-sidetoside:64.7|dsprimaryproducts...,15.0,4.5,15.0,"[overallwidth-sidetoside:64.7, dsprimaryproduc...",0,solid wood platform bed,"good , deep sleep can be quite difficult to ha...",Furniture,Bedroom Furniture,Furniture / Bedroom Furniture
1,1,all-clad 7 qt . slow cooker,Slow Cookers,Kitchen & Tabletop / Small Kitchen Appliances ...,"create delicious slow-cooked meals , from tend...",capacityquarts:7|producttype : slow cooker|pro...,100.0,2.0,98.0,"[capacityquarts:7, producttype : slow cooker, ...",1,all-clad 7 qt . slow cooker,"create delicious slow-cooked meals , from tend...",Kitchen & Tabletop,Small Kitchen Appliances,Kitchen & Tabletop / Small Kitchen Appliances
2,2,all-clad electrics 6.5 qt . slow cooker,Slow Cookers,Kitchen & Tabletop / Small Kitchen Appliances ...,prepare home-cooked meals on any schedule with...,features : keep warm setting|capacityquarts:6....,208.0,3.0,181.0,"[features : keep warm setting, capacityquarts:...",2,all-clad electrics 6.5 qt . slow cooker,prepare home-cooked meals on any schedule with...,Kitchen & Tabletop,Small Kitchen Appliances,Kitchen & Tabletop / Small Kitchen Appliances
3,3,all-clad all professional tools pizza cutter,"Slicers, Peelers And Graters",Browse By Brand / All-Clad,this original stainless tool was designed to c...,overallwidth-sidetoside:3.5|warrantylength : l...,69.0,4.5,42.0,"[overallwidth-sidetoside:3.5, warrantylength :...",3,all-clad all professional tools pizza cutter,this original stainless tool was designed to c...,Browse By Brand,All-Clad,Browse By Brand / All-Clad
4,4,baldwin prestige alcott passage knob with roun...,Door Knobs,Home Improvement / Doors & Door Hardware / Doo...,the hardware has a rich heritage of delivering...,compatibledoorthickness:1.375 '' |countryofori...,70.0,5.0,42.0,"[compatibledoorthickness:1.375 '' , countryofo...",4,baldwin prestige alcott passage knob with roun...,the hardware has a rich heritage of delivering...,Home Improvement,Doors & Door Hardware,Home Improvement / Doors & Door Hardware
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42989,42989,malibu pressure balanced diverter fixed shower...,Shower Panels,Home Improvement / Bathroom Remodel & Bathroom...,the malibu pressure balanced diverter fixed sh...,producttype : shower panel|spraypattern : rain...,3.0,4.5,2.0,"[producttype : shower panel, spraypattern : ra...",42989,malibu pressure balanced diverter fixed shower...,the malibu pressure balanced diverter fixed sh...,Home Improvement,Bathroom Remodel & Bathroom Fixtures,Home Improvement / Bathroom Remodel & Bathroom...
42990,42990,emmeline 5 piece breakfast dining set,Dining Table Sets,Furniture / Kitchen & Dining Furniture / Dinin...,,basematerialdetails : steel| : gray wood|ofhar...,1314.0,4.5,864.0,"[basematerialdetails : steel, : gray wood, of...",42990,emmeline 5 piece breakfast dining set,,Furniture,Kitchen & Dining Furniture,Furniture / Kitchen & Dining Furniture
42991,42991,maloney 3 piece pub table set,Dining Table Sets,Furniture / Kitchen & Dining Furniture / Dinin...,this pub table set includes 1 counter height t...,additionaltoolsrequirednotincluded : power dri...,49.0,4.0,41.0,[additionaltoolsrequirednotincluded : power dr...,42991,maloney 3 piece pub table set,this pub table set includes 1 counter height t...,Furniture,Kitchen & Dining Furniture,Furniture / Kitchen & Dining Furniture
42992,42992,fletcher 27.5 '' wide polyester armchair,Teen Lounge Furniture|Accent Chairs,Furniture / Living Room Furniture / Chairs & S...,"bring iconic , modern style to your space in a...",legmaterialdetails : rubberwood|backheight-sea...,1746.0,4.5,1226.0,"[legmaterialdetails : rubberwood, backheight-s...",42992,fletcher 27.5 '' wide polyester armchair,"bring iconic , modern style to your space in a...",Furniture,Living Room Furniture,Furniture / Living Room Furniture
42993,42993,griffin 29 '' bar stool,Bar Stools,Furniture / Kitchen & Dining Furniture / Bar F...,this set of two barstools features a minimalis...,distancebetweenfloorandfootrest:7.5|dssecondar...,20.0,4.5,20.0,"[distancebetweenfloorandfootrest:7.5, dssecond...",42993,griffin 29 '' bar stool,this set of two barstools features a minimalis...,Furniture,Kitchen & Dining Furniture,Furniture / Kitchen & Dining Furniture

## Search function for search -> categorize

Note in this notebook we do two searches. One at classification time, a second the actual query. This recreates the search we might perform offline, during some batch process of query classification.

In [ ]:
from searcharray import SearchArray
from cheat_at_search.tokenizers import snowball_tokenizer
import numpy as np
import pandas as pd

product_name_index = SearchArray.index(products['product_name'], snowball_tokenizer)
product_desc_index  = SearchArray.index(products['product_description'], snowball_tokenizer)

def matching_classifications(query, k=10):
    """Issue a search then get all category hierarchy for matches."""
    tokenized = snowball_tokenizer(query)
    bm25_scores = np.zeros(len(products))
    for token in tokenized:
        bm25_scores += product_name_index.score(token) * 7
        bm25_scores += product_desc_index.score(token) * 4
    # Get top 300 bm25_scores, set all others to 0
    # bm25_scores[bm25_scores.argsort()[:-300]] = 0

    matches = products[bm25_scores > 0]
    top_10 = matches.groupby('category hierarchy')['product_id'].nunique().sort_values(ascending=False).head(25)
    return top_10

2026-05-20 12:54:28,005 - searcharray.indexing - INFO - Indexing begins w/ 4 workers

INFO:searcharray.indexing:Indexing begins w/ 4 workers

2026-05-20 12:54:28,013 - searcharray.indexing - INFO - 0 Batch Start tokenization

INFO:searcharray.indexing:0 Batch Start tokenization

2026-05-20 12:54:28,016 - searcharray.indexing - INFO - Tokenizing 42994 documents

INFO:searcharray.indexing:Tokenizing 42994 documents

2026-05-20 12:54:28,547 - searcharray.indexing - INFO - Tokenized 10000 (23.259059403637718%)

INFO:searcharray.indexing:Tokenized 10000 (23.259059403637718%)

2026-05-20 12:54:29,108 - searcharray.indexing - INFO - Tokenized 20000 (46.518118807275435%)

INFO:searcharray.indexing:Tokenized 20000 (46.518118807275435%)

2026-05-20 12:54:29,613 - searcharray.indexing - INFO - Tokenized 30000 (69.77717821091315%)

INFO:searcharray.indexing:Tokenized 30000 (69.77717821091315%)

2026-05-20 12:54:30,416 - searcharray.indexing - INFO - Tokenized 40000 (93.03623761455087%)

INFO:searcharray.indexing:Tokenized 40000 (93.03623761455087%)

2026-05-20 12:54:31,119 - searcharray.indexing - INFO - Tokenization -- vstacking

INFO:searcharray.indexing:Tokenization -- vstacking

2026-05-20 12:54:31,166 - searcharray.indexing - INFO - Tokenization -- DONE

INFO:searcharray.indexing:Tokenization -- DONE

2026-05-20 12:54:31,205 - searcharray.indexing - INFO - Inverting docs->terms

INFO:searcharray.indexing:Inverting docs->terms

2026-05-20 12:54:31,403 - searcharray.indexing - INFO - Encoding positions to bit array

INFO:searcharray.indexing:Encoding positions to bit array

2026-05-20 12:54:31,640 - searcharray.indexing - INFO - Batch tokenization complete

INFO:searcharray.indexing:Batch tokenization complete

2026-05-20 12:54:31,647 - searcharray.indexing - INFO - (main thread) Processing 1 batch results

INFO:searcharray.indexing:(main thread) Processing 1 batch results

2026-05-20 12:54:31,756 - searcharray.indexing - INFO - Indexing from tokenization complete

INFO:searcharray.indexing:Indexing from tokenization complete

2026-05-20 12:54:31,829 - searcharray.indexing - INFO - Indexing begins w/ 4 workers

INFO:searcharray.indexing:Indexing begins w/ 4 workers

2026-05-20 12:54:31,852 - searcharray.indexing - INFO - 0 Batch Start tokenization

INFO:searcharray.indexing:0 Batch Start tokenization

2026-05-20 12:54:31,855 - searcharray.indexing - INFO - Tokenizing 42994 documents

INFO:searcharray.indexing:Tokenizing 42994 documents

2026-05-20 12:54:34,900 - searcharray.indexing - INFO - Tokenized 10000 (23.259059403637718%)

INFO:searcharray.indexing:Tokenized 10000 (23.259059403637718%)

2026-05-20 12:54:37,147 - searcharray.indexing - INFO - Tokenized 20000 (46.518118807275435%)

INFO:searcharray.indexing:Tokenized 20000 (46.518118807275435%)

2026-05-20 12:54:39,505 - searcharray.indexing - INFO - Tokenized 30000 (69.77717821091315%)

INFO:searcharray.indexing:Tokenized 30000 (69.77717821091315%)

2026-05-20 12:54:41,746 - searcharray.indexing - INFO - Tokenized 40000 (93.03623761455087%)

INFO:searcharray.indexing:Tokenized 40000 (93.03623761455087%)

2026-05-20 12:54:42,299 - searcharray.indexing - INFO - Tokenization -- vstacking

INFO:searcharray.indexing:Tokenization -- vstacking

2026-05-20 12:54:42,333 - searcharray.indexing - INFO - Tokenization -- DONE

INFO:searcharray.indexing:Tokenization -- DONE

2026-05-20 12:54:42,380 - searcharray.indexing - INFO - Inverting docs->terms

INFO:searcharray.indexing:Inverting docs->terms

2026-05-20 12:54:42,928 - searcharray.indexing - INFO - Encoding positions to bit array

INFO:searcharray.indexing:Encoding positions to bit array

2026-05-20 12:54:43,106 - searcharray.indexing - INFO - Batch tokenization complete

INFO:searcharray.indexing:Batch tokenization complete

2026-05-20 12:54:43,108 - searcharray.indexing - INFO - (main thread) Processing 1 batch results

INFO:searcharray.indexing:(main thread) Processing 1 batch results

2026-05-20 12:54:43,249 - searcharray.indexing - INFO - Indexing from tokenization complete

INFO:searcharray.indexing:Indexing from tokenization complete

In [ ]:
matching_classifications("couch")

category hierarchy
Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows                                                    49
Furniture / Living Room Furniture / Sectionals                                                                     28
Furniture / Living Room Furniture / Coffee Tables & End Tables / End & Side Tables                                 26
Furniture / Living Room Furniture / Sofas                                                                          25
Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables                                     24
Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows / Blue Throw Pillows                               15
Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables / Rectangle Coffee Tables           14
Furniture / Living Room Furniture / Chairs & Seating / Chaise Lounge Chairs                                         9
Furniture / Bedroom Furniture / Daybeds                                                                             9
Outdoor / Outdoor & Patio Furniture / Outdoor Seating & Patio Chairs / Patio Seating / Patio Sofas & Sectionals     8
Baby & Kids / Toddler & Kids Playroom / Playroom Furniture / Toddler & Kids Chairs & Seating                        8
Furniture / Living Room Furniture / Console Tables                                                                  7
Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs                                                6
Décor & Pillows / Decorative Pillows & Blankets / Blankets & Throws                                                 6
Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows / Black Throw Pillows                               6
Furniture / Living Room Furniture / TV Stands & Media Storage Furniture / TV Stands & Entertainment Centers         5
Storage & Organization / Garage & Outdoor Storage & Organization / Outdoor Covers / Patio Furniture Covers          4
Outdoor / Outdoor & Patio Furniture / Patio Furniture Sets / Patio Conversation Sets                                4
Furniture / Living Room Furniture / Living Room Sets                                                                3
Lighting / Table & Floor Lamps / Table Lamps                                                                        3
Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows / Green Throw Pillows                               3
Furniture / Game Tables & Game Room Furniture / Gaming Chairs                                                       3
Furniture / Office Furniture / Desks / Writing Desks                                                                3
Lighting / Table & Floor Lamps / Floor Lamps                                                                        3
Contractor / Entry & Hallway / Coat Racks & Umbrella Stands                                                         3
Name: product_id, dtype: int64

## Dynamically build classification model

Here we dynamically bulid the classification model from the labels. Notice below we just test with 'a', 'b', 'c'. But in reality we'de take the list of top N classifications from above to classify with.

In [ ]:

from enum import Enum
from pydantic import BaseModel, Field, ConfigDict, create_model

def make_classifier_model(labels: list[str]) -> type[BaseModel]:
    # Remove any label with illegal chars
    illegal_chars = '"'
    labels = [label for label in labels if all(c not in illegal_chars for c in label)]

    # Use safe member names; preserve the *actual* label as the Enum value.
    members = {f"v{i}": label for i, label in enumerate(labels)}
    LabelEnum = Enum("LabelEnum", members)

    # Make a model whose field is restricted to those enum values
    Model = create_model(
        "QueryClassification",
        __doc__="A classification of the query.",
        classification=(list[LabelEnum], Field("Which classifications might make sense for the query. Leave blank if none.")),
        __config__=ConfigDict(use_enum_values=True),

    )
    # print(Model.model_json_schema())
    return Model


model = make_classifier_model(["a", "b", "c"])
model.model_json_schema()

{'$defs': {'LabelEnum': {'enum': ['a', 'b', 'c'],
   'title': 'LabelEnum',
   'type': 'string'}},
 'description': 'A classification of the query.',
 'properties': {'classification': {'default': 'Which classifications might make sense for the query. Leave blank if none.',
   'items': {'$ref': '#/$defs/LabelEnum'},
   'title': 'Classification',
   'type': 'array'}},
 'title': 'QueryClassification',
 'type': 'object'}

In [ ]:
# Remove cache as needed
!rm /content/drive/MyDrive/cheat-at-search-data/search_then_classify/cache.json

In [ ]:
from re import sub
from cheat_at_search.data_dir import key_for_provider, ensure_data_subdir
from openai import OpenAI
import json

OPENAI_KEY = key_for_provider("openai")

openai = OpenAI(api_key=OPENAI_KEY)

cache_dir = ensure_data_subdir("search_then_classify")
try:
    with open(cache_dir / "cache.json", 'rb') as f:
        cache = json.load(f)
except FileNotFoundError:
    cache = {}


class StructuredClassification(BaseModel):
    classifications: list[str]

    categories: list[str]

    sub_categories: list[str]

    cat_subcat: list[str]


def get_category_subcategory(classifications) -> StructuredClassification:
    categories = set()
    sub_categories = set()
    cat_subcat = set()
    if not classifications:
        return StructuredClassification(classifications=classifications,
                                        categories=[],
                                        sub_categories=[],
                                        cat_subcat=[])
    for classification in classifications:
        splits = classification.split('/')
        if splits:
            category = splits[0].strip()
            sub_category = splits[1].strip() if len(splits) > 1 else "No SubCategory Found"
            categories.add(category)
            sub_categories.add(sub_category)
            cat_subcat.add(f"{category} / {sub_category}")
        return StructuredClassification(classifications=classifications,
                                        categories=list(categories),
                                        sub_categories=list(sub_categories),
                                        cat_subcat=list(cat_subcat))

def enrich_query(query):
    """Use responses.parse with the dynamic classifaciots schema to classify query."""
    if query in cache:
        return get_category_subcategory(cache[query])
    best_classifications = matching_classifications(query)
    if len(best_classifications) == 0:
        return get_category_subcategory([])
    ClassificationModel = make_classifier_model(best_classifications.index.tolist())
    system_prompt = "Map user furniture search queries to classifications"
    prompt = f"""
        Return all relevant classifications for this search query
        If none / not sure return an empty list

        Query: {query}
    """
    resp = openai.responses.parse(
        model="gpt-4.1-nano",
        input=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt}
        ],
        text_format=ClassificationModel
    )
    usage = resp.usage
    print(f"Input tokens {usage.input_tokens}, output tokens {usage.output_tokens}")
    classification = resp.output_parsed
    cache[query] = classification.classification
    with open(cache_dir / "cache.json", "w") as f:
        json.dump(cache, f)
    return get_category_subcategory(classification.classification)


enrich_query("sofa")

Input tokens 485, output tokens 14

StructuredClassification(classifications=['Furniture / Living Room Furniture / Sofas'], categories=['Furniture'], sub_categories=['Living Room Furniture'], cat_subcat=['Furniture / Living Room Furniture'])

In [ ]:
labeled_query_products[['query', 'doc_id', 'category', 'grade']]

              query  doc_id                category  grade
0       salon chair      17        Home Improvement    0.0
1       salon chair      63               Furniture    1.0
2       salon chair      65               Furniture    1.0
3       salon chair      95               Furniture    1.0
4       salon chair     130               Furniture    1.0
...             ...     ...                     ...    ...
231868   rack glass   42869      Kitchen & Tabletop    0.0
231869   rack glass   42870      Kitchen & Tabletop    0.0
231870   rack glass   42871      Kitchen & Tabletop    0.0
231871   rack glass   42872                            0.0
231872   rack glass   42930  Storage & Organization    1.0

[231873 rows x 4 columns]

## Run Category search strategy with classifier

Our search strategy here is identical, **however note** when the LLM does not predict a category / sub category we do not provide a boost.

In [ ]:
from searcharray import SearchArray
from cheat_at_search.tokenizers import snowball_tokenizer
from cheat_at_search.strategy.strategy import SearchStrategy
import numpy as np


class CategorySearch(SearchStrategy):
    def __init__(self, products, query_to_cat,
                 name_boost=9.3,
                 description_boost=4.1,
                 category_boost=10,
                 sub_category_boost=5,
                 cat_subcat_boost=10):
        super().__init__(products)
        self.index = products
        self.index['product_name_snowball'] = SearchArray.index(
            products['product_name'], snowball_tokenizer)
        self.index['product_description_snowball'] = SearchArray.index(
            products['product_description'], snowball_tokenizer)

        cat_split = products['category hierarchy'].fillna('').str.split("/")

        products['category'] = cat_split.apply(
            lambda x: x[0].strip() if len(x) > 0 else ""
        )
        products['subcategory'] = cat_split.apply(
            lambda x: x[1].strip() if len(x) > 1 else ""
        )
        self.index['category_snowball'] = SearchArray.index(
            products['category'], snowball_tokenizer
        )
        self.index['subcategory_snowball'] = SearchArray.index(
            products['subcategory'], snowball_tokenizer
        )

        self.index['cat_subcat'] = products['category'] + products['subcategory']
        self.index['cat_subcat'] = self.index['cat_subcat'].fillna('')
        self.index['cat_subcat_snowball'] = SearchArray.index(
            self.index['cat_subcat'], snowball_tokenizer
        )

        self.query_to_cat = query_to_cat
        self.name_boost = name_boost
        self.description_boost = description_boost
        self.category_boost = category_boost
        self.sub_category_boost = sub_category_boost
        self.cat_subcat_boost = cat_subcat_boost

    def search(self, query, k=10):
        """Dumb baseline lexical search, but add a constant boost when
           the desired category or subcategory"""
        bm25_scores = np.zeros(len(self.index))
        structured = self.query_to_cat(query)
        tokenized = snowball_tokenizer(query)

        print(structured)

        # ****
        # Baseline BM25 search from before
        for token in tokenized:
            bm25_scores += self.index['product_name_snowball'].array.score(token) * self.name_boost
            bm25_scores += self.index['product_description_snowball'].array.score(
                token) * self.description_boost

        # ****
        # If there's a subcategory, boost that by a constant amount
        for sub_category in structured.sub_categories:
            tokenized_subcategory = snowball_tokenizer(sub_category)
            subcategory_match = np.zeros(len(self.index))
            if tokenized_subcategory:
                subcategory_match = self.index['subcategory_snowball'].array.score(tokenized_subcategory) > 0
            bm25_scores[subcategory_match] += self.sub_category_boost

        # ****
        # If there's a category, boost that by a constant amount
        for category in structured.categories:
            print(category)
            tokenized_category = snowball_tokenizer(category)
            category_match = np.zeros(len(self.index))
            if tokenized_category:
                category_match = self.index['category_snowball'].array.score(tokenized_category) > 0
            bm25_scores[category_match] += self.category_boost

        # ***
        # If they occur togethere, boost by a constant amount
        for cat_subcat in structured.cat_subcat:
            tokenized_cat_subcat = snowball_tokenizer(cat_subcat)
            cat_subcat_match = np.zeros(len(self.index))
            if tokenized_cat_subcat:
                cat_subcat_match = self.index['cat_subcat_snowball'].array.score(tokenized_cat_subcat) > 0
            bm25_scores[cat_subcat_match] += self.cat_subcat_boost

        top_k = np.argsort(-bm25_scores)[:k]
        scores = bm25_scores[top_k]

        return top_k, scores

categorized_search = CategorySearch(products, enrich_query)
categorized_search.search('medium clips')

2026-05-20 12:54:54,001 - searcharray.indexing - INFO - Indexing begins w/ 4 workers

INFO:searcharray.indexing:Indexing begins w/ 4 workers

2026-05-20 12:54:54,007 - searcharray.indexing - INFO - 0 Batch Start tokenization

INFO:searcharray.indexing:0 Batch Start tokenization

2026-05-20 12:54:54,009 - searcharray.indexing - INFO - Tokenizing 42994 documents

INFO:searcharray.indexing:Tokenizing 42994 documents

2026-05-20 12:54:54,318 - searcharray.indexing - INFO - Tokenized 10000 (23.259059403637718%)

INFO:searcharray.indexing:Tokenized 10000 (23.259059403637718%)

2026-05-20 12:54:54,633 - searcharray.indexing - INFO - Tokenized 20000 (46.518118807275435%)

INFO:searcharray.indexing:Tokenized 20000 (46.518118807275435%)

2026-05-20 12:54:54,932 - searcharray.indexing - INFO - Tokenized 30000 (69.77717821091315%)

INFO:searcharray.indexing:Tokenized 30000 (69.77717821091315%)

2026-05-20 12:54:55,271 - searcharray.indexing - INFO - Tokenized 40000 (93.03623761455087%)

INFO:searcharray.indexing:Tokenized 40000 (93.03623761455087%)

2026-05-20 12:54:55,478 - searcharray.indexing - INFO - Tokenization -- vstacking

INFO:searcharray.indexing:Tokenization -- vstacking

2026-05-20 12:54:55,480 - searcharray.indexing - INFO - Tokenization -- DONE

INFO:searcharray.indexing:Tokenization -- DONE

2026-05-20 12:54:55,485 - searcharray.indexing - INFO - Inverting docs->terms

INFO:searcharray.indexing:Inverting docs->terms

2026-05-20 12:54:55,512 - searcharray.indexing - INFO - Encoding positions to bit array

INFO:searcharray.indexing:Encoding positions to bit array

2026-05-20 12:54:55,547 - searcharray.indexing - INFO - Batch tokenization complete

INFO:searcharray.indexing:Batch tokenization complete

2026-05-20 12:54:55,549 - searcharray.indexing - INFO - (main thread) Processing 1 batch results

INFO:searcharray.indexing:(main thread) Processing 1 batch results

2026-05-20 12:54:55,589 - searcharray.indexing - INFO - Indexing from tokenization complete

INFO:searcharray.indexing:Indexing from tokenization complete

2026-05-20 12:54:55,614 - searcharray.indexing - INFO - Indexing begins w/ 4 workers

INFO:searcharray.indexing:Indexing begins w/ 4 workers

2026-05-20 12:54:55,625 - searcharray.indexing - INFO - 0 Batch Start tokenization

INFO:searcharray.indexing:0 Batch Start tokenization

2026-05-20 12:54:55,627 - searcharray.indexing - INFO - Tokenizing 42994 documents

INFO:searcharray.indexing:Tokenizing 42994 documents

2026-05-20 12:54:56,517 - searcharray.indexing - INFO - Tokenized 10000 (23.259059403637718%)

INFO:searcharray.indexing:Tokenized 10000 (23.259059403637718%)

2026-05-20 12:54:57,463 - searcharray.indexing - INFO - Tokenized 20000 (46.518118807275435%)

INFO:searcharray.indexing:Tokenized 20000 (46.518118807275435%)

2026-05-20 12:54:58,777 - searcharray.indexing - INFO - Tokenized 30000 (69.77717821091315%)

INFO:searcharray.indexing:Tokenized 30000 (69.77717821091315%)

2026-05-20 12:55:00,098 - searcharray.indexing - INFO - Tokenized 40000 (93.03623761455087%)

INFO:searcharray.indexing:Tokenized 40000 (93.03623761455087%)

2026-05-20 12:55:00,554 - searcharray.indexing - INFO - Tokenization -- vstacking

INFO:searcharray.indexing:Tokenization -- vstacking

2026-05-20 12:55:00,568 - searcharray.indexing - INFO - Tokenization -- DONE

INFO:searcharray.indexing:Tokenization -- DONE

2026-05-20 12:55:00,581 - searcharray.indexing - INFO - Inverting docs->terms

INFO:searcharray.indexing:Inverting docs->terms

2026-05-20 12:55:01,127 - searcharray.indexing - INFO - Encoding positions to bit array

INFO:searcharray.indexing:Encoding positions to bit array

2026-05-20 12:55:01,285 - searcharray.indexing - INFO - Batch tokenization complete

INFO:searcharray.indexing:Batch tokenization complete

2026-05-20 12:55:01,287 - searcharray.indexing - INFO - (main thread) Processing 1 batch results

INFO:searcharray.indexing:(main thread) Processing 1 batch results

2026-05-20 12:55:01,435 - searcharray.indexing - INFO - Indexing from tokenization complete

INFO:searcharray.indexing:Indexing from tokenization complete

2026-05-20 12:55:01,913 - searcharray.indexing - INFO - Indexing begins w/ 4 workers

INFO:searcharray.indexing:Indexing begins w/ 4 workers

2026-05-20 12:55:01,922 - searcharray.indexing - INFO - 0 Batch Start tokenization

INFO:searcharray.indexing:0 Batch Start tokenization

2026-05-20 12:55:01,924 - searcharray.indexing - INFO - Tokenizing 42994 documents

INFO:searcharray.indexing:Tokenizing 42994 documents

2026-05-20 12:55:02,072 - searcharray.indexing - INFO - Tokenized 10000 (23.259059403637718%)

INFO:searcharray.indexing:Tokenized 10000 (23.259059403637718%)

2026-05-20 12:55:02,221 - searcharray.indexing - INFO - Tokenized 20000 (46.518118807275435%)

INFO:searcharray.indexing:Tokenized 20000 (46.518118807275435%)

2026-05-20 12:55:02,404 - searcharray.indexing - INFO - Tokenized 30000 (69.77717821091315%)

INFO:searcharray.indexing:Tokenized 30000 (69.77717821091315%)

2026-05-20 12:55:02,573 - searcharray.indexing - INFO - Tokenized 40000 (93.03623761455087%)

INFO:searcharray.indexing:Tokenized 40000 (93.03623761455087%)

2026-05-20 12:55:02,699 - searcharray.indexing - INFO - Tokenization -- vstacking

INFO:searcharray.indexing:Tokenization -- vstacking

2026-05-20 12:55:02,703 - searcharray.indexing - INFO - Tokenization -- DONE

INFO:searcharray.indexing:Tokenization -- DONE

2026-05-20 12:55:02,707 - searcharray.indexing - INFO - Inverting docs->terms

INFO:searcharray.indexing:Inverting docs->terms

2026-05-20 12:55:02,713 - searcharray.indexing - INFO - Encoding positions to bit array

INFO:searcharray.indexing:Encoding positions to bit array

2026-05-20 12:55:02,718 - searcharray.indexing - INFO - Batch tokenization complete

INFO:searcharray.indexing:Batch tokenization complete

2026-05-20 12:55:02,719 - searcharray.indexing - INFO - (main thread) Processing 1 batch results

INFO:searcharray.indexing:(main thread) Processing 1 batch results

2026-05-20 12:55:02,734 - searcharray.indexing - INFO - Indexing from tokenization complete

INFO:searcharray.indexing:Indexing from tokenization complete

2026-05-20 12:55:02,743 - searcharray.indexing - INFO - Indexing begins w/ 4 workers

INFO:searcharray.indexing:Indexing begins w/ 4 workers

2026-05-20 12:55:02,749 - searcharray.indexing - INFO - 0 Batch Start tokenization

INFO:searcharray.indexing:0 Batch Start tokenization

2026-05-20 12:55:02,751 - searcharray.indexing - INFO - Tokenizing 42994 documents

INFO:searcharray.indexing:Tokenizing 42994 documents

2026-05-20 12:55:02,933 - searcharray.indexing - INFO - Tokenized 10000 (23.259059403637718%)

INFO:searcharray.indexing:Tokenized 10000 (23.259059403637718%)

2026-05-20 12:55:03,098 - searcharray.indexing - INFO - Tokenized 20000 (46.518118807275435%)

INFO:searcharray.indexing:Tokenized 20000 (46.518118807275435%)

2026-05-20 12:55:03,256 - searcharray.indexing - INFO - Tokenized 30000 (69.77717821091315%)

INFO:searcharray.indexing:Tokenized 30000 (69.77717821091315%)

2026-05-20 12:55:03,426 - searcharray.indexing - INFO - Tokenized 40000 (93.03623761455087%)

INFO:searcharray.indexing:Tokenized 40000 (93.03623761455087%)

2026-05-20 12:55:03,566 - searcharray.indexing - INFO - Tokenization -- vstacking

INFO:searcharray.indexing:Tokenization -- vstacking

2026-05-20 12:55:03,570 - searcharray.indexing - INFO - Tokenization -- DONE

INFO:searcharray.indexing:Tokenization -- DONE

2026-05-20 12:55:03,576 - searcharray.indexing - INFO - Inverting docs->terms

INFO:searcharray.indexing:Inverting docs->terms

2026-05-20 12:55:03,593 - searcharray.indexing - INFO - Encoding positions to bit array

INFO:searcharray.indexing:Encoding positions to bit array

2026-05-20 12:55:03,599 - searcharray.indexing - INFO - Batch tokenization complete

INFO:searcharray.indexing:Batch tokenization complete

2026-05-20 12:55:03,601 - searcharray.indexing - INFO - (main thread) Processing 1 batch results

INFO:searcharray.indexing:(main thread) Processing 1 batch results

2026-05-20 12:55:03,620 - searcharray.indexing - INFO - Indexing from tokenization complete

INFO:searcharray.indexing:Indexing from tokenization complete

2026-05-20 12:55:03,636 - searcharray.indexing - INFO - Indexing begins w/ 4 workers

INFO:searcharray.indexing:Indexing begins w/ 4 workers

2026-05-20 12:55:03,641 - searcharray.indexing - INFO - 0 Batch Start tokenization

INFO:searcharray.indexing:0 Batch Start tokenization

2026-05-20 12:55:03,644 - searcharray.indexing - INFO - Tokenizing 42994 documents

INFO:searcharray.indexing:Tokenizing 42994 documents

2026-05-20 12:55:03,829 - searcharray.indexing - INFO - Tokenized 10000 (23.259059403637718%)

INFO:searcharray.indexing:Tokenized 10000 (23.259059403637718%)

2026-05-20 12:55:04,022 - searcharray.indexing - INFO - Tokenized 20000 (46.518118807275435%)

INFO:searcharray.indexing:Tokenized 20000 (46.518118807275435%)

2026-05-20 12:55:04,202 - searcharray.indexing - INFO - Tokenized 30000 (69.77717821091315%)

INFO:searcharray.indexing:Tokenized 30000 (69.77717821091315%)

2026-05-20 12:55:04,431 - searcharray.indexing - INFO - Tokenized 40000 (93.03623761455087%)

INFO:searcharray.indexing:Tokenized 40000 (93.03623761455087%)

2026-05-20 12:55:04,601 - searcharray.indexing - INFO - Tokenization -- vstacking

INFO:searcharray.indexing:Tokenization -- vstacking

2026-05-20 12:55:04,603 - searcharray.indexing - INFO - Tokenization -- DONE

INFO:searcharray.indexing:Tokenization -- DONE

2026-05-20 12:55:04,606 - searcharray.indexing - INFO - Inverting docs->terms

INFO:searcharray.indexing:Inverting docs->terms

2026-05-20 12:55:04,622 - searcharray.indexing - INFO - Encoding positions to bit array

INFO:searcharray.indexing:Encoding positions to bit array

2026-05-20 12:55:04,643 - searcharray.indexing - INFO - Batch tokenization complete

INFO:searcharray.indexing:Batch tokenization complete

2026-05-20 12:55:04,646 - searcharray.indexing - INFO - (main thread) Processing 1 batch results

INFO:searcharray.indexing:(main thread) Processing 1 batch results

2026-05-20 12:55:04,680 - searcharray.indexing - INFO - Indexing from tokenization complete

INFO:searcharray.indexing:Indexing from tokenization complete

Input tokens 441, output tokens 11
classifications=['Clips/Clamps'] categories=['Clips'] sub_categories=['Clamps'] cat_subcat=['Clips / Clamps']
Clips

(array([36813, 37397, 34050, 36809, 37396, 37398, 36810, 11295, 37007,
        16370]),
 array([85.35794735, 84.99754143, 68.97158527, 68.62535572, 67.39479828,
        66.0164814 , 64.83574677, 62.97011852, 62.32560349, 60.5767231 ]))

In [ ]:
from cheat_at_search.wands_data import judgments, graded_bm25

In [ ]:
graded_categorized = run_strategy(categorized_search, judgments)
graded_categorized

Searching:   0%|          | 1/480 [00:01<11:50,  1.48s/it]

Input tokens 526, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:   0%|          | 2/480 [00:03<16:09,  2.03s/it]

Input tokens 591, output tokens 28
classifications=['Home Improvement / Flooring, Walls & Ceiling / Walls & Ceilings / Peel & Stick Backsplash Tile'] categories=['Home Improvement'] sub_categories=['Flooring, Walls & Ceiling'] cat_subcat=['Home Improvement / Flooring, Walls & Ceiling']
Home Improvement

Searching:   1%|          | 3/480 [00:07<21:00,  2.64s/it]

Input tokens 489, output tokens 18
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Recliners'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:   1%|          | 4/480 [00:08<15:19,  1.93s/it]

Input tokens 554, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:   1%|          | 5/480 [00:09<12:27,  1.57s/it]

Input tokens 484, output tokens 18
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:   1%|▏         | 6/480 [00:09<10:10,  1.29s/it]

Input tokens 455, output tokens 20
classifications=['Bed & Bath / Bathroom Accessories & Organization / Countertop Bath Accessories'] categories=['Bed & Bath'] sub_categories=['Bathroom Accessories & Organization'] cat_subcat=['Bed & Bath / Bathroom Accessories & Organization']
Bed & Bath

Searching:   1%|▏         | 7/480 [00:10<08:52,  1.13s/it]

Input tokens 618, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:   2%|▏         | 8/480 [00:12<10:48,  1.37s/it]

Input tokens 504, output tokens 26
classifications=['Appliances / Kitchen Appliances / Range Hoods / All Range Hoods / Wall Mount Range Hoods'] categories=['Appliances'] sub_categories=['Kitchen Appliances'] cat_subcat=['Appliances / Kitchen Appliances']
Appliances

Searching:   2%|▏         | 9/480 [00:13<09:30,  1.21s/it]

Input tokens 525, output tokens 22
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs / Arm Accent Chairs'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:   2%|▏         | 10/480 [00:15<11:11,  1.43s/it]

Input tokens 468, output tokens 22
classifications=['Furniture / Living Room Furniture / Coffee Tables & End Tables / End & Side Tables'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:   2%|▏         | 11/480 [00:17<11:57,  1.53s/it]

Input tokens 525, output tokens 37
classifications=['Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables', 'Outdoor / Outdoor & Patio Furniture / Patio Furniture Sets / Patio Conversation Sets'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:   2%|▎         | 12/480 [00:17<10:33,  1.35s/it]

Input tokens 459, output tokens 22
classifications=['Furniture / Kitchen & Dining Furniture / Dining Tables & Seating / Kitchen & Dining Tables'] categories=['Furniture'] sub_categories=['Kitchen & Dining Furniture'] cat_subcat=['Furniture / Kitchen & Dining Furniture']
Furniture

Searching:   3%|▎         | 13/480 [00:18<09:02,  1.16s/it]

Input tokens 548, output tokens 22
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs / Arm Accent Chairs'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:   3%|▎         | 14/480 [00:20<11:14,  1.45s/it]

Input tokens 554, output tokens 23
classifications=['Décor & Pillows / Art / All Wall Art / Pink Wall Art'] categories=['Décor & Pillows'] sub_categories=['Art'] cat_subcat=['Décor & Pillows / Art']
Décor & Pillows

Searching:   3%|▎         | 15/480 [00:22<10:50,  1.40s/it]

Input tokens 486, output tokens 26
classifications=['Home Improvement / Hardware / Cabinet Hardware / Cabinet & Drawer Pulls / Black Cabinet & Drawer Pulls'] categories=['Home Improvement'] sub_categories=['Hardware'] cat_subcat=['Home Improvement / Hardware']
Home Improvement

Searching:   3%|▎         | 16/480 [00:23<09:51,  1.28s/it]

Input tokens 537, output tokens 29
classifications=['Outdoor / Outdoor & Patio Furniture / Patio Furniture Sets / Patio Conversation Sets', 'Furniture / Living Room Furniture / Sectionals'] categories=['Outdoor'] sub_categories=['Outdoor & Patio Furniture'] cat_subcat=['Outdoor / Outdoor & Patio Furniture']
Outdoor

Searching:   4%|▎         | 17/480 [00:24<09:40,  1.25s/it]

Input tokens 515, output tokens 22
classifications=["Rugs / Area Rugs / 4' x 6' Area Rugs"] categories=['Rugs'] sub_categories=['Area Rugs'] cat_subcat=['Rugs / Area Rugs']
Rugs

Searching:   4%|▍         | 18/480 [00:25<08:47,  1.14s/it]

Input tokens 478, output tokens 17
classifications=['Furniture / Bedroom Furniture / Dressers & Chests'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:   4%|▍         | 19/480 [00:26<08:27,  1.10s/it]

Input tokens 539, output tokens 44
classifications=['Home Improvement / Flooring, Walls & Ceiling / Floor Tiles & Wall Tiles / Ceramic Floor Tiles & Wall Tiles', 'Home Improvement / Flooring, Walls & Ceiling / Floor Tiles & Wall Tiles'] categories=['Home Improvement'] sub_categories=['Flooring, Walls & Ceiling'] cat_subcat=['Home Improvement / Flooring, Walls & Ceiling']
Home Improvement

Searching:   4%|▍         | 20/480 [00:27<08:17,  1.08s/it]

Input tokens 512, output tokens 27
classifications=['Storage & Organization / Garage & Outdoor Storage & Organization / Outdoor Covers / Grill Covers / Gas Grill Grill Covers'] categories=['Storage & Organization'] sub_categories=['Garage & Outdoor Storage & Organization'] cat_subcat=['Storage & Organization / Garage & Outdoor Storage & Organization']
Storage & Organization

Searching:   4%|▍         | 21/480 [00:28<08:10,  1.07s/it]

Input tokens 500, output tokens 14
classifications=['Lighting / Ceiling Lights / Chandeliers'] categories=['Lighting'] sub_categories=['Ceiling Lights'] cat_subcat=['Lighting / Ceiling Lights']
Lighting

Searching:   5%|▍         | 22/480 [00:29<09:29,  1.24s/it]

Input tokens 511, output tokens 20
classifications=['Décor & Pillows / Wall Décor / Wall Accents'] categories=['Décor & Pillows'] sub_categories=['Wall Décor'] cat_subcat=['Décor & Pillows / Wall Décor']
Décor & Pillows

Searching:   5%|▍         | 23/480 [00:31<09:14,  1.21s/it]

Input tokens 538, output tokens 17
classifications=['Furniture / Bedroom Furniture / Dressers & Chests'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:   5%|▌         | 24/480 [00:32<10:37,  1.40s/it]

Input tokens 481, output tokens 17
classifications=['Furniture / Bedroom Furniture / Beds & Headboards / Beds'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:   5%|▌         | 25/480 [00:33<09:39,  1.27s/it]

Input tokens 479, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:   5%|▌         | 26/480 [00:35<09:24,  1.24s/it]

Input tokens 565, output tokens 49
classifications=['Home Improvement / Kitchen Remodel & Kitchen Fixtures / Kitchen Sinks & Faucet Components / Kitchen Sinks / Farmhouse & Apron Kitchen Sinks', 'Appliances / Kitchen Appliances / Range Hoods / All Range Hoods'] categories=['Home Improvement'] sub_categories=['Kitchen Remodel & Kitchen Fixtures'] cat_subcat=['Home Improvement / Kitchen Remodel & Kitchen Fixtures']
Home Improvement

Searching:   6%|▌         | 27/480 [00:36<09:31,  1.26s/it]

Input tokens 530, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:   6%|▌         | 28/480 [00:37<08:55,  1.18s/it]

Input tokens 509, output tokens 17
classifications=['Furniture / Office Furniture / Desks / Writing Desks'] categories=['Furniture'] sub_categories=['Office Furniture'] cat_subcat=['Furniture / Office Furniture']
Furniture

Searching:   6%|▌         | 29/480 [00:38<09:08,  1.22s/it]

Input tokens 484, output tokens 17
classifications=['Furniture / Bedroom Furniture / Beds & Headboards / Beds'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:   6%|▋         | 30/480 [00:39<08:19,  1.11s/it]

Input tokens 547, output tokens 18
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:   6%|▋         | 31/480 [00:40<08:49,  1.18s/it]

Input tokens 460, output tokens 21
classifications=['Furniture / Bedroom Furniture / Beds & Headboards / Beds / Queen Size Beds'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:   7%|▋         | 32/480 [00:41<08:02,  1.08s/it]

Input tokens 498, output tokens 21
classifications=["Rugs / Area Rugs / 5' x 8' Area Rugs"] categories=['Rugs'] sub_categories=['Area Rugs'] cat_subcat=['Rugs / Area Rugs']
Rugs

Searching:   7%|▋         | 33/480 [00:45<13:14,  1.78s/it]

Input tokens 527, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:   7%|▋         | 34/480 [00:45<11:10,  1.50s/it]

Input tokens 473, output tokens 17
classifications=['Furniture / Bedroom Furniture / Beds & Headboards / Beds'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:   8%|▊         | 36/480 [00:51<15:24,  2.08s/it]

Input tokens 460, output tokens 39
classifications=['Storage & Organization / Bathroom Storage & Organization / Bathroom Cabinets & Shelving', 'Storage & Organization / Garage & Outdoor Storage & Organization / Storage Racks & Shelving Units'] categories=['Storage & Organization'] sub_categories=['Bathroom Storage & Organization'] cat_subcat=['Storage & Organization / Bathroom Storage & Organization']
Storage & Organization

Searching:   8%|▊         | 37/480 [00:52<13:36,  1.84s/it]

Input tokens 465, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:   8%|▊         | 38/480 [01:01<27:45,  3.77s/it]

Input tokens 517, output tokens 60
classifications=["Rugs / Area Rugs / 2' x 3' Area Rugs", "Rugs / Area Rugs / 3' x 5' Area Rugs", "Rugs / Area Rugs / 4' x 6' Area Rugs", 'Rugs / Doormats'] categories=['Rugs'] sub_categories=['Area Rugs'] cat_subcat=['Rugs / Area Rugs']
Rugs

Searching:   8%|▊         | 39/480 [01:02<22:12,  3.02s/it]

Input tokens 505, output tokens 38
classifications=['Home Improvement / Doors & Door Hardware / Door Hardware & Accessories / Barn Door Hardware', 'Outdoor / Front Door Décor & Curb Appeal / Mailboxes'] categories=['Home Improvement'] sub_categories=['Doors & Door Hardware'] cat_subcat=['Home Improvement / Doors & Door Hardware']
Home Improvement

Searching:   8%|▊         | 40/480 [01:03<17:53,  2.44s/it]

Input tokens 515, output tokens 15
classifications=['Lighting / Wall Lights / Bathroom Vanity Lighting'] categories=['Lighting'] sub_categories=['Wall Lights'] cat_subcat=['Lighting / Wall Lights']
Lighting

Searching:   9%|▊         | 41/480 [01:05<15:47,  2.16s/it]

Input tokens 581, output tokens 28
classifications=['Décor & Pillows / Home Accessories / Decorative Plates & Bowls / Glass Decorative Plates & Bowls'] categories=['Décor & Pillows'] sub_categories=['Home Accessories'] cat_subcat=['Décor & Pillows / Home Accessories']
Décor & Pillows

Searching:   9%|▉         | 42/480 [01:06<13:24,  1.84s/it]

Input tokens 461, output tokens 24
classifications=['Storage & Organization / Garage & Outdoor Storage & Organization / Storage Racks & Shelving Units'] categories=['Storage & Organization'] sub_categories=['Garage & Outdoor Storage & Organization'] cat_subcat=['Storage & Organization / Garage & Outdoor Storage & Organization']
Storage & Organization

Searching:   9%|▉         | 43/480 [01:07<12:25,  1.71s/it]

Input tokens 492, output tokens 28
classifications=['Outdoor / Outdoor & Patio Furniture / Outdoor Seating & Patio Chairs / Patio Seating / Patio Sofas & Sectionals'] categories=['Outdoor'] sub_categories=['Outdoor & Patio Furniture'] cat_subcat=['Outdoor / Outdoor & Patio Furniture']
Outdoor

Searching:   9%|▉         | 44/480 [01:08<11:05,  1.53s/it]

Input tokens 464, output tokens 34
classifications=['Baby & Kids / Toddler & Kids Bedroom Furniture / Kids Beds', 'Furniture / Bedroom Furniture / Beds & Headboards / Beds / Twin Beds'] categories=['Baby & Kids'] sub_categories=['Toddler & Kids Bedroom Furniture'] cat_subcat=['Baby & Kids / Toddler & Kids Bedroom Furniture']
Baby & Kids

Searching:   9%|▉         | 45/480 [01:10<10:46,  1.49s/it]

Input tokens 468, output tokens 18
classifications=['Storage & Organization / Jewelry Organization / All Jewelry Organizers'] categories=['Storage & Organization'] sub_categories=['Jewelry Organization'] cat_subcat=['Storage & Organization / Jewelry Organization']
Storage & Organization

Searching:  10%|▉         | 46/480 [01:10<09:23,  1.30s/it]

Input tokens 518, output tokens 22
classifications=['Furniture / Kitchen & Dining Furniture / Dining Tables & Seating / Kitchen & Dining Tables'] categories=['Furniture'] sub_categories=['Kitchen & Dining Furniture'] cat_subcat=['Furniture / Kitchen & Dining Furniture']
Furniture

Searching:  10%|▉         | 47/480 [01:14<13:31,  1.87s/it]

Input tokens 584, output tokens 47
classifications=['Baby & Kids / Toddler & Kids Playroom / Playroom Furniture / Toddler & Kids Chairs & Seating', 'Home Improvement / Flooring, Walls & Ceiling / Walls & Ceilings / Wall Paneling'] categories=['Baby & Kids'] sub_categories=['Toddler & Kids Playroom'] cat_subcat=['Baby & Kids / Toddler & Kids Playroom']
Baby & Kids

Searching:  10%|█         | 48/480 [01:15<12:04,  1.68s/it]

Input tokens 480, output tokens 34
classifications=['Home Improvement / Doors & Door Hardware / Door Hardware & Accessories / Barn Door Hardware', 'Storage & Organization / Closet Storage & Organization / Closet Systems'] categories=['Home Improvement'] sub_categories=['Doors & Door Hardware'] cat_subcat=['Home Improvement / Doors & Door Hardware']
Home Improvement

Searching:  10%|█         | 49/480 [01:16<10:41,  1.49s/it]

Input tokens 505, output tokens 19
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  10%|█         | 50/480 [01:17<09:13,  1.29s/it]

Input tokens 528, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  11%|█         | 51/480 [01:18<09:05,  1.27s/it]

Input tokens 453, output tokens 14
classifications=['Lighting / Ceiling Lights / Chandeliers'] categories=['Lighting'] sub_categories=['Ceiling Lights'] cat_subcat=['Lighting / Ceiling Lights']
Lighting

Searching:  11%|█         | 52/480 [01:19<07:57,  1.12s/it]

Input tokens 442, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  11%|█         | 53/480 [01:21<09:20,  1.31s/it]

Input tokens 492, output tokens 50
classifications=['Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables', 'Furniture / Kitchen & Dining Furniture / Dining Tables & Seating / Kitchen & Dining Tables', 'Furniture / Living Room Furniture / Living Room Sets'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  11%|█▏        | 54/480 [01:22<09:07,  1.28s/it]

Input tokens 489, output tokens 32
classifications=['Furniture / Kitchen & Dining Furniture / Bar Furniture / Bar Stools & Counter Stools / All Bar Stools & Counter Stools'] categories=['Furniture'] sub_categories=['Kitchen & Dining Furniture'] cat_subcat=['Furniture / Kitchen & Dining Furniture']
Furniture

Searching:  11%|█▏        | 55/480 [01:23<09:08,  1.29s/it]

Input tokens 484, output tokens 37
classifications=['Décor & Pillows / Mirrors / All Mirrors / Bathroom & Vanity Mirrors', 'Décor & Pillows / Mirrors / All Mirrors / Accent Mirrors'] categories=['Décor & Pillows'] sub_categories=['Mirrors'] cat_subcat=['Décor & Pillows / Mirrors']
Décor & Pillows

Searching:  12%|█▏        | 56/480 [01:24<07:58,  1.13s/it]

Input tokens 518, output tokens 11
classifications=['Rugs / Kitchen Mats'] categories=['Rugs'] sub_categories=['Kitchen Mats'] cat_subcat=['Rugs / Kitchen Mats']
Rugs

Searching:  12%|█▏        | 57/480 [01:25<07:47,  1.10s/it]

Input tokens 481, output tokens 23
classifications=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / All Bathroom Vanities'] categories=['Home Improvement'] sub_categories=['Bathroom Remodel & Bathroom Fixtures'] cat_subcat=['Home Improvement / Bathroom Remodel & Bathroom Fixtures']
Home Improvement

Searching:  12%|█▏        | 58/480 [01:26<07:31,  1.07s/it]

Input tokens 488, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  12%|█▏        | 59/480 [01:27<07:11,  1.03s/it]

Input tokens 629, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  12%|█▎        | 60/480 [01:28<06:41,  1.04it/s]

Input tokens 441, output tokens 27
classifications=['Lighting / Light Bulbs & Hardware / Light Bulbs / All Light Bulbs / LED Light Bulbs'] categories=['Lighting'] sub_categories=['Light Bulbs & Hardware'] cat_subcat=['Lighting / Light Bulbs & Hardware']
Lighting

Searching:  13%|█▎        | 61/480 [01:32<13:50,  1.98s/it]

Input tokens 454, output tokens 17
classifications=['Décor & Pillows / Mirrors / All Mirrors'] categories=['Décor & Pillows'] sub_categories=['Mirrors'] cat_subcat=['Décor & Pillows / Mirrors']
Décor & Pillows

Searching:  13%|█▎        | 62/480 [01:33<11:58,  1.72s/it]

Input tokens 491, output tokens 21
classifications=['Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Table Sets'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  13%|█▎        | 63/480 [01:34<10:10,  1.46s/it]

Input tokens 432, output tokens 23
classifications=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / All Bathroom Vanities'] categories=['Home Improvement'] sub_categories=['Bathroom Remodel & Bathroom Fixtures'] cat_subcat=['Home Improvement / Bathroom Remodel & Bathroom Fixtures']
Home Improvement

Searching:  13%|█▎        | 64/480 [01:35<09:33,  1.38s/it]

Input tokens 516, output tokens 17
classifications=['Furniture / Office Furniture / Desks / Computer Desks'] categories=['Furniture'] sub_categories=['Office Furniture'] cat_subcat=['Furniture / Office Furniture']
Furniture

Searching:  14%|█▎        | 65/480 [01:36<08:56,  1.29s/it]

Input tokens 482, output tokens 43
classifications=['Outdoor / Outdoor & Patio Furniture / Patio Furniture Sets / Patio Conversation Sets', 'Outdoor / Outdoor & Patio Furniture / Outdoor Seating & Patio Chairs / Patio Seating / Patio Sofas & Sectionals'] categories=['Outdoor'] sub_categories=['Outdoor & Patio Furniture'] cat_subcat=['Outdoor / Outdoor & Patio Furniture']
Outdoor

Searching:  14%|█▍        | 66/480 [01:37<07:56,  1.15s/it]

Input tokens 509, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  14%|█▍        | 67/480 [01:38<07:20,  1.07s/it]

Input tokens 487, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  14%|█▍        | 68/480 [01:39<07:22,  1.07s/it]

Input tokens 630, output tokens 40
classifications=['Kitchen & Tabletop / Tableware & Drinkware / Serveware / Serving Trays & Boards / Serving Trays & Platters / Serving Serving Trays & Platters'] categories=['Kitchen & Tabletop'] sub_categories=['Tableware & Drinkware'] cat_subcat=['Kitchen & Tabletop / Tableware & Drinkware']
Kitchen & Tabletop

Searching:  14%|█▍        | 69/480 [01:40<06:50,  1.00it/s]

Input tokens 441, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  15%|█▍        | 70/480 [01:41<07:34,  1.11s/it]

Input tokens 508, output tokens 23
classifications=['Furniture / Living Room Furniture / Coffee Tables & End Tables / End & Side Tables'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture
classifications=['Clips/Clamps'] categories=['Clips'] sub_categories=['Clamps'] cat_subcat=['Clips / Clamps']
Clips

Searching:  15%|█▌        | 72/480 [01:42<05:22,  1.27it/s]

Input tokens 517, output tokens 13
classifications=['Outdoor / Garden / Greenhouses'] categories=['Outdoor'] sub_categories=['Garden'] cat_subcat=['Outdoor / Garden']
Outdoor

Searching:  15%|█▌        | 73/480 [01:43<05:25,  1.25it/s]

Input tokens 488, output tokens 12
classifications=['Rugs / Area Rugs'] categories=['Rugs'] sub_categories=['Area Rugs'] cat_subcat=['Rugs / Area Rugs']
Rugs

Searching:  15%|█▌        | 74/480 [01:44<05:34,  1.21it/s]

Input tokens 512, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  16%|█▌        | 75/480 [01:45<05:37,  1.20it/s]

Input tokens 440, output tokens 17
classifications=['Furniture / Bedroom Furniture / Beds & Headboards / Beds'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  16%|█▌        | 76/480 [01:46<06:27,  1.04it/s]

Input tokens 564, output tokens 41
classifications=['Décor & Pillows / Art / All Wall Art / Green Wall Art', 'Décor & Pillows / Art / All Wall Art / Orange Wall Art'] categories=['Décor & Pillows'] sub_categories=['Art'] cat_subcat=['Décor & Pillows / Art']
Décor & Pillows

Searching:  16%|█▌        | 77/480 [01:47<06:09,  1.09it/s]

Input tokens 567, output tokens 33
classifications=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Sinks & Faucet Components / Bathroom Sink Faucets / Single Hole Bathroom Sink Faucets'] categories=['Home Improvement'] sub_categories=['Bathroom Remodel & Bathroom Fixtures'] cat_subcat=['Home Improvement / Bathroom Remodel & Bathroom Fixtures']
Home Improvement

Searching:  16%|█▋        | 78/480 [01:48<07:30,  1.12s/it]

Input tokens 499, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  16%|█▋        | 79/480 [01:52<13:31,  2.02s/it]

Input tokens 549, output tokens 34
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs', 'Furniture / Living Room Furniture / Chairs & Seating / Rocking Chairs'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  17%|█▋        | 80/480 [01:56<15:52,  2.38s/it]

Input tokens 471, output tokens 20
classifications=['Bed & Bath / Bathroom Accessories & Organization / Countertop Bath Accessories'] categories=['Bed & Bath'] sub_categories=['Bathroom Accessories & Organization'] cat_subcat=['Bed & Bath / Bathroom Accessories & Organization']
Bed & Bath

Searching:  17%|█▋        | 81/480 [01:57<12:45,  1.92s/it]

Input tokens 551, output tokens 20
classifications=['Home Improvement / Flooring, Walls & Ceiling / Floor Tiles & Wall Tiles'] categories=['Home Improvement'] sub_categories=['Flooring, Walls & Ceiling'] cat_subcat=['Home Improvement / Flooring, Walls & Ceiling']
Home Improvement

Searching:  17%|█▋        | 82/480 [01:57<10:28,  1.58s/it]

Input tokens 453, output tokens 16
classifications=['Furniture / Bedroom Furniture / Dressers & Chests'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  17%|█▋        | 83/480 [01:58<08:53,  1.34s/it]

Input tokens 503, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  18%|█▊        | 84/480 [01:59<08:27,  1.28s/it]

Input tokens 447, output tokens 32
classifications=['Furniture / Kitchen & Dining Furniture / Bar Furniture / Bar Stools & Counter Stools / All Bar Stools & Counter Stools'] categories=['Furniture'] sub_categories=['Kitchen & Dining Furniture'] cat_subcat=['Furniture / Kitchen & Dining Furniture']
Furniture

Searching:  18%|█▊        | 85/480 [02:00<07:35,  1.15s/it]

Input tokens 551, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  18%|█▊        | 86/480 [02:01<06:46,  1.03s/it]

Input tokens 463, output tokens 18
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Recliners'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  18%|█▊        | 87/480 [02:05<13:10,  2.01s/it]

Input tokens 490, output tokens 34
classifications=['Outdoor / Garden / Plant Stands & Accessories', 'Storage & Organization / Garage & Outdoor Storage & Organization / Deck Boxes & Patio Storage'] categories=['Outdoor'] sub_categories=['Garden'] cat_subcat=['Outdoor / Garden']
Outdoor

Searching:  18%|█▊        | 88/480 [02:06<11:33,  1.77s/it]

Input tokens 523, output tokens 29
classifications=['Furniture / Kitchen & Dining Furniture / Dining Tables & Seating / Kitchen & Dining Chairs / Armed Kitchen & Dining Chairs'] categories=['Furniture'] sub_categories=['Kitchen & Dining Furniture'] cat_subcat=['Furniture / Kitchen & Dining Furniture']
Furniture

Searching:  19%|█▊        | 89/480 [02:07<09:48,  1.51s/it]

Input tokens 216, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  19%|█▉        | 90/480 [02:08<08:39,  1.33s/it]

Input tokens 485, output tokens 16
classifications=['Furniture / Bedroom Furniture / Dressers & Chests'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  19%|█▉        | 91/480 [02:09<08:27,  1.30s/it]

Input tokens 533, output tokens 23
classifications=['Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows'] categories=['Décor & Pillows'] sub_categories=['Decorative Pillows & Blankets'] cat_subcat=['Décor & Pillows / Decorative Pillows & Blankets']
Décor & Pillows

Searching:  19%|█▉        | 92/480 [02:11<08:08,  1.26s/it]

Input tokens 524, output tokens 19
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Recliners'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  19%|█▉        | 93/480 [02:12<09:03,  1.41s/it]

Input tokens 485, output tokens 19
classifications=['Décor & Pillows / Clocks / Wall Clocks'] categories=['Décor & Pillows'] sub_categories=['Clocks'] cat_subcat=['Décor & Pillows / Clocks']
Décor & Pillows

Searching:  20%|█▉        | 94/480 [02:13<08:29,  1.32s/it]

Input tokens 691, output tokens 25
classifications=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Towel Storage / Towel & Robe Hooks'] categories=['Home Improvement'] sub_categories=['Bathroom Remodel & Bathroom Fixtures'] cat_subcat=['Home Improvement / Bathroom Remodel & Bathroom Fixtures']
Home Improvement

Searching:  20%|█▉        | 95/480 [02:18<14:22,  2.24s/it]

Input tokens 619, output tokens 25
classifications=['Décor & Pillows / Flowers & Plants / Faux Flowers / Sunflower Faux Flowers'] categories=['Décor & Pillows'] sub_categories=['Flowers & Plants'] cat_subcat=['Décor & Pillows / Flowers & Plants']
Décor & Pillows

Searching:  20%|██        | 96/480 [02:20<14:41,  2.30s/it]

Input tokens 467, output tokens 22
classifications=['Furniture / Living Room Furniture / Coffee Tables & End Tables / End & Side Tables'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  20%|██        | 97/480 [02:21<12:22,  1.94s/it]

Input tokens 488, output tokens 18
classifications=['Furniture / Kitchen & Dining Furniture / Sideboards & Buffets'] categories=['Furniture'] sub_categories=['Kitchen & Dining Furniture'] cat_subcat=['Furniture / Kitchen & Dining Furniture']
Furniture

Searching:  20%|██        | 98/480 [02:22<10:10,  1.60s/it]

Input tokens 459, output tokens 16
classifications=['Furniture / Bedroom Furniture / Dressers & Chests'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  21%|██        | 99/480 [02:23<09:22,  1.48s/it]

Input tokens 494, output tokens 18
classifications=['Furniture / Bedroom Furniture / Beds & Headboards / Headboards'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  21%|██        | 100/480 [02:24<08:07,  1.28s/it]

Input tokens 472, output tokens 20
classifications=['Baby & Kids / Toddler & Kids Bedroom Furniture / Kids Beds'] categories=['Baby & Kids'] sub_categories=['Toddler & Kids Bedroom Furniture'] cat_subcat=['Baby & Kids / Toddler & Kids Bedroom Furniture']
Baby & Kids

Searching:  21%|██        | 101/480 [02:26<08:34,  1.36s/it]

Input tokens 270, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  21%|██▏       | 102/480 [02:27<07:54,  1.25s/it]

Input tokens 462, output tokens 21
classifications=['Furniture / Bedroom Furniture / Beds & Headboards / Beds / Queen Size Beds'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  21%|██▏       | 103/480 [02:28<08:02,  1.28s/it]

Input tokens 480, output tokens 23
classifications=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / All Bathroom Vanities'] categories=['Home Improvement'] sub_categories=['Bathroom Remodel & Bathroom Fixtures'] cat_subcat=['Home Improvement / Bathroom Remodel & Bathroom Fixtures']
Home Improvement

Searching:  22%|██▏       | 104/480 [02:29<07:47,  1.24s/it]

Input tokens 688, output tokens 27
classifications=['Kitchen & Tabletop / Tableware & Drinkware / Flatware & Cutlery / Flatware Sets'] categories=['Kitchen & Tabletop'] sub_categories=['Tableware & Drinkware'] cat_subcat=['Kitchen & Tabletop / Tableware & Drinkware']
Kitchen & Tabletop

Searching:  22%|██▏       | 105/480 [02:30<07:06,  1.14s/it]

Input tokens 495, output tokens 21
classifications=['Furniture / Kitchen & Dining Furniture / Bar Furniture / Home Bars & Bar Sets'] categories=['Furniture'] sub_categories=['Kitchen & Dining Furniture'] cat_subcat=['Furniture / Kitchen & Dining Furniture']
Furniture

Searching:  22%|██▏       | 106/480 [02:32<08:46,  1.41s/it]

Input tokens 483, output tokens 23
classifications=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / All Bathroom Vanities'] categories=['Home Improvement'] sub_categories=['Bathroom Remodel & Bathroom Fixtures'] cat_subcat=['Home Improvement / Bathroom Remodel & Bathroom Fixtures']
Home Improvement

Searching:  22%|██▏       | 107/480 [02:34<09:18,  1.50s/it]

Input tokens 553, output tokens 33
classifications=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Towel Storage / Towel & Robe Hooks / Black Towel & Robe Hooks'] categories=['Home Improvement'] sub_categories=['Bathroom Remodel & Bathroom Fixtures'] cat_subcat=['Home Improvement / Bathroom Remodel & Bathroom Fixtures']
Home Improvement

Searching:  22%|██▎       | 108/480 [02:35<09:13,  1.49s/it]

Input tokens 462, output tokens 24
classifications=['Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows'] categories=['Décor & Pillows'] sub_categories=['Decorative Pillows & Blankets'] cat_subcat=['Décor & Pillows / Decorative Pillows & Blankets']
Décor & Pillows

Searching:  23%|██▎       | 109/480 [02:37<10:26,  1.69s/it]

Input tokens 482, output tokens 39
classifications=['Storage & Organization / Bathroom Storage & Organization / Bathroom Cabinets & Shelving', 'Storage & Organization / Garage & Outdoor Storage & Organization / Storage Racks & Shelving Units'] categories=['Storage & Organization'] sub_categories=['Bathroom Storage & Organization'] cat_subcat=['Storage & Organization / Bathroom Storage & Organization']
Storage & Organization

Searching:  23%|██▎       | 110/480 [02:39<09:18,  1.51s/it]

Input tokens 519, output tokens 35
classifications=['Furniture / Bedroom Furniture / Beds & Headboards / Headboards', 'Décor & Pillows / Wall Décor / Wall Accents'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  23%|██▎       | 111/480 [02:40<09:50,  1.60s/it]

Input tokens 539, output tokens 47
classifications=['Furniture / Kitchen & Dining Furniture / Dining Tables & Seating / Kitchen & Dining Chairs', 'Furniture / Kitchen & Dining Furniture / Dining Tables & Seating / Kitchen & Dining Chairs / Side Kitchen & Dining Chairs'] categories=['Furniture'] sub_categories=['Kitchen & Dining Furniture'] cat_subcat=['Furniture / Kitchen & Dining Furniture']
Furniture

Searching:  23%|██▎       | 112/480 [02:41<08:28,  1.38s/it]

Input tokens 485, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  24%|██▎       | 113/480 [02:43<09:47,  1.60s/it]

Input tokens 553, output tokens 57
classifications=['Baby & Kids / Toddler & Kids Playroom / Playroom Furniture / Toddler & Kids Chairs & Seating', 'Baby & Kids / Toddler & Kids Bedroom Furniture / Kids Desks', 'Baby & Kids / Toddler & Kids Bedroom Furniture / Kids Beds'] categories=['Baby & Kids'] sub_categories=['Toddler & Kids Playroom'] cat_subcat=['Baby & Kids / Toddler & Kids Playroom']
Baby & Kids

Searching:  24%|██▍       | 114/480 [02:46<12:07,  1.99s/it]

Input tokens 459, output tokens 22
classifications=['Storage & Organization / Garage & Outdoor Storage & Organization / Deck Boxes & Patio Storage'] categories=['Storage & Organization'] sub_categories=['Garage & Outdoor Storage & Organization'] cat_subcat=['Storage & Organization / Garage & Outdoor Storage & Organization']
Storage & Organization

Searching:  24%|██▍       | 115/480 [02:47<10:27,  1.72s/it]

Input tokens 500, output tokens 13
classifications=['Furniture / Office Furniture / Office Chairs'] categories=['Furniture'] sub_categories=['Office Furniture'] cat_subcat=['Furniture / Office Furniture']
Furniture

Searching:  24%|██▍       | 116/480 [02:48<09:08,  1.51s/it]

Input tokens 487, output tokens 17
classifications=['Furniture / Bedroom Furniture / Beds & Headboards / Beds'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  24%|██▍       | 117/480 [02:49<08:13,  1.36s/it]

Input tokens 472, output tokens 24
classifications=['Storage & Organization / Garage & Outdoor Storage & Organization / Storage Racks & Shelving Units'] categories=['Storage & Organization'] sub_categories=['Garage & Outdoor Storage & Organization'] cat_subcat=['Storage & Organization / Garage & Outdoor Storage & Organization']
Storage & Organization

Searching:  25%|██▍       | 118/480 [02:50<07:42,  1.28s/it]

Input tokens 492, output tokens 28
classifications=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Showers & Bathtubs / Shower & Bathtub Accessories'] categories=['Home Improvement'] sub_categories=['Bathroom Remodel & Bathroom Fixtures'] cat_subcat=['Home Improvement / Bathroom Remodel & Bathroom Fixtures']
Home Improvement

Searching:  25%|██▍       | 119/480 [02:52<07:16,  1.21s/it]

Input tokens 502, output tokens 40
classifications=['Outdoor / Outdoor Décor / Statues & Sculptures', 'Outdoor / Outdoor Décor / Statues & Sculptures / People Themed Statues & Sculptures'] categories=['Outdoor'] sub_categories=['Outdoor Décor'] cat_subcat=['Outdoor / Outdoor Décor']
Outdoor

Searching:  25%|██▌       | 120/480 [02:52<06:34,  1.09s/it]

Input tokens 467, output tokens 20
classifications=['Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  25%|██▌       | 121/480 [02:53<05:57,  1.00it/s]

Input tokens 479, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  25%|██▌       | 122/480 [02:54<06:05,  1.02s/it]

Input tokens 288, output tokens 13
classifications=['Outdoor / Outdoor Shades / Pergolas'] categories=['Outdoor'] sub_categories=['Outdoor Shades'] cat_subcat=['Outdoor / Outdoor Shades']
Outdoor

Searching:  26%|██▌       | 123/480 [02:55<05:36,  1.06it/s]

Input tokens 460, output tokens 13
classifications=['Lighting / Ceiling Lights / Chandeliers'] categories=['Lighting'] sub_categories=['Ceiling Lights'] cat_subcat=['Lighting / Ceiling Lights']
Lighting

Searching:  26%|██▌       | 124/480 [02:56<06:32,  1.10s/it]

Input tokens 521, output tokens 44
classifications=['Outdoor / Garden / Planters / Plastic Planters', 'Décor & Pillows / Flowers & Plants / Faux Flowers', 'Décor & Pillows / Flowers & Plants / Faux Plants'] categories=['Outdoor'] sub_categories=['Garden'] cat_subcat=['Outdoor / Garden']
Outdoor

Searching:  26%|██▌       | 125/480 [02:58<07:00,  1.19s/it]

Input tokens 600, output tokens 30
classifications=['Décor & Pillows / Window Treatments / Curtains & Drapes / 63 Inch and Less Curtains & Drapes'] categories=['Décor & Pillows'] sub_categories=['Window Treatments'] cat_subcat=['Décor & Pillows / Window Treatments']
Décor & Pillows

Searching:  26%|██▋       | 126/480 [02:59<07:05,  1.20s/it]

Input tokens 446, output tokens 17
classifications=['Furniture / Bedroom Furniture / Beds & Headboards / Beds'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  26%|██▋       | 127/480 [03:00<06:56,  1.18s/it]

Input tokens 512, output tokens 74
classifications=['Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables', 'Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Table Sets', 'Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables / Rectangle Coffee Tables', 'Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables / Round Coffee Tables'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  27%|██▋       | 128/480 [03:01<06:15,  1.07s/it]

Input tokens 529, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  27%|██▋       | 129/480 [03:02<05:43,  1.02it/s]

Input tokens 509, output tokens 15
classifications=['Bed & Bath / Bedding / All Bedding'] categories=['Bed & Bath'] sub_categories=['Bedding'] cat_subcat=['Bed & Bath / Bedding']
Bed & Bath

Searching:  27%|██▋       | 130/480 [03:03<05:24,  1.08it/s]

Input tokens 439, output tokens 14
classifications=['Lighting / Outdoor Lighting / Outdoor Wall Lighting'] categories=['Lighting'] sub_categories=['Outdoor Lighting'] cat_subcat=['Lighting / Outdoor Lighting']
Lighting

Searching:  27%|██▋       | 131/480 [03:04<05:43,  1.02it/s]

Input tokens 558, output tokens 34
classifications=['Home Improvement / Kitchen Remodel & Kitchen Fixtures / Kitchen Sinks & Faucet Components / Kitchen Sinks / Farmhouse & Apron Kitchen Sinks'] categories=['Home Improvement'] sub_categories=['Kitchen Remodel & Kitchen Fixtures'] cat_subcat=['Home Improvement / Kitchen Remodel & Kitchen Fixtures']
Home Improvement

Searching:  28%|██▊       | 132/480 [03:04<05:22,  1.08it/s]

Input tokens 469, output tokens 24
classifications=['Storage & Organization / Garage & Outdoor Storage & Organization / Storage Racks & Shelving Units'] categories=['Storage & Organization'] sub_categories=['Garage & Outdoor Storage & Organization'] cat_subcat=['Storage & Organization / Garage & Outdoor Storage & Organization']
Storage & Organization

Searching:  28%|██▊       | 133/480 [03:05<05:26,  1.06it/s]

Input tokens 508, output tokens 28
classifications=['Home Improvement / Flooring, Walls & Ceiling / Floor Tiles & Wall Tiles / Porcelain Floor Tiles & Wall Tiles'] categories=['Home Improvement'] sub_categories=['Flooring, Walls & Ceiling'] cat_subcat=['Home Improvement / Flooring, Walls & Ceiling']
Home Improvement

Searching:  28%|██▊       | 134/480 [03:06<05:35,  1.03it/s]

Input tokens 470, output tokens 22
classifications=['Furniture / Living Room Furniture / Coffee Tables & End Tables / End & Side Tables'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  28%|██▊       | 135/480 [03:07<05:09,  1.11it/s]

Input tokens 481, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  28%|██▊       | 136/480 [03:08<05:05,  1.13it/s]

Input tokens 482, output tokens 18
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  29%|██▊       | 137/480 [03:09<04:53,  1.17it/s]

Input tokens 495, output tokens 21
classifications=['Furniture / Living Room Furniture / Bookcases / 6 Shelf Bookcases'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  29%|██▉       | 138/480 [03:10<04:55,  1.16it/s]

Input tokens 479, output tokens 14
classifications=['Furniture / Living Room Furniture / Sofas'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  29%|██▉       | 139/480 [03:11<04:57,  1.15it/s]

Input tokens 516, output tokens 21
classifications=['Décor & Pillows / Window Treatments / Curtains & Drapes'] categories=['Décor & Pillows'] sub_categories=['Window Treatments'] cat_subcat=['Décor & Pillows / Window Treatments']
Décor & Pillows

Searching:  29%|██▉       | 140/480 [03:11<04:42,  1.20it/s]

Input tokens 523, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  29%|██▉       | 141/480 [03:13<05:14,  1.08it/s]

Input tokens 514, output tokens 47
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs', 'Furniture / Living Room Furniture / Chairs & Seating / Recliners', 'Furniture / Living Room Furniture / Ottomans & Poufs'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  30%|██▉       | 142/480 [03:13<05:00,  1.13it/s]

Input tokens 550, output tokens 28
classifications=['Baby & Kids / Toddler & Kids Playroom / Playroom Furniture / Toddler & Kids Chairs & Seating'] categories=['Baby & Kids'] sub_categories=['Toddler & Kids Playroom'] cat_subcat=['Baby & Kids / Toddler & Kids Playroom']
Baby & Kids

Searching:  30%|██▉       | 143/480 [03:14<05:10,  1.08it/s]

Input tokens 508, output tokens 18
classifications=['Furniture / Living Room Furniture / Ottomans & Poufs'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  30%|███       | 144/480 [03:15<05:03,  1.11it/s]

Input tokens 482, output tokens 29
classifications=['Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows / Blue Throw Pillows'] categories=['Décor & Pillows'] sub_categories=['Decorative Pillows & Blankets'] cat_subcat=['Décor & Pillows / Decorative Pillows & Blankets']
Décor & Pillows

Searching:  30%|███       | 145/480 [03:16<05:00,  1.11it/s]

Input tokens 488, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  30%|███       | 146/480 [03:17<05:12,  1.07it/s]

Input tokens 499, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  31%|███       | 147/480 [03:18<04:48,  1.15it/s]

Input tokens 531, output tokens 13
classifications=['Furniture / Office Furniture / Office Chairs'] categories=['Furniture'] sub_categories=['Office Furniture'] cat_subcat=['Furniture / Office Furniture']
Furniture

Searching:  31%|███       | 148/480 [03:19<05:27,  1.01it/s]

Input tokens 471, output tokens 17
classifications=['Furniture / Bedroom Furniture / Dressers & Chests'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  31%|███       | 149/480 [03:20<05:39,  1.03s/it]

Input tokens 483, output tokens 18
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  31%|███▏      | 150/480 [03:21<05:30,  1.00s/it]

Input tokens 569, output tokens 26
classifications=['Home Improvement / Hardware / Cabinet Hardware / Cabinet & Drawer Knobs / Black Cabinet & Drawer Knobs'] categories=['Home Improvement'] sub_categories=['Hardware'] cat_subcat=['Home Improvement / Hardware']
Home Improvement

Searching:  31%|███▏      | 151/480 [03:22<05:50,  1.07s/it]

Input tokens 483, output tokens 21
classifications=['Furniture / Office Furniture / Desks', 'Furniture / Office Furniture / Office Chairs'] categories=['Furniture'] sub_categories=['Office Furniture'] cat_subcat=['Furniture / Office Furniture']
Furniture

Searching:  32%|███▏      | 152/480 [03:23<05:54,  1.08s/it]

Input tokens 502, output tokens 26
classifications=['Home Improvement / Kitchen Remodel & Kitchen Fixtures / Kitchen Sinks & Faucet Components / Kitchen Sinks'] categories=['Home Improvement'] sub_categories=['Kitchen Remodel & Kitchen Fixtures'] cat_subcat=['Home Improvement / Kitchen Remodel & Kitchen Fixtures']
Home Improvement

Searching:  32%|███▏      | 153/480 [03:25<05:56,  1.09s/it]

Input tokens 528, output tokens 19
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  32%|███▏      | 154/480 [03:26<06:21,  1.17s/it]

Input tokens 472, output tokens 21
classifications=['Décor & Pillows / Mirrors / All Mirrors / Accent Mirrors'] categories=['Décor & Pillows'] sub_categories=['Mirrors'] cat_subcat=['Décor & Pillows / Mirrors']
Décor & Pillows

Searching:  32%|███▏      | 155/480 [03:27<06:42,  1.24s/it]

Input tokens 509, output tokens 68
classifications=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / All Bathroom Vanities', 'Storage & Organization / Bathroom Storage & Organization / Bathroom Cabinets & Shelving', 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Toilets & Bidets / Toilet Paper Holders / Wall Mounted Toilet Paper Holders'] categories=['Home Improvement'] sub_categories=['Bathroom Remodel & Bathroom Fixtures'] cat_subcat=['Home Improvement / Bathroom Remodel & Bathroom Fixtures']
Home Improvement

Searching:  32%|███▎      | 156/480 [03:28<06:25,  1.19s/it]

Input tokens 578, output tokens 33
classifications=['Furniture / Kitchen & Dining Furniture / Kitchen Islands & Carts', 'Furniture / Kitchen & Dining Furniture / Kitchen Islands & Carts'] categories=['Furniture'] sub_categories=['Kitchen & Dining Furniture'] cat_subcat=['Furniture / Kitchen & Dining Furniture']
Furniture

Searching:  33%|███▎      | 157/480 [03:30<07:03,  1.31s/it]

Input tokens 508, output tokens 32
classifications=['Furniture / Kitchen & Dining Furniture / Bar Furniture / Bar Stools & Counter Stools / All Bar Stools & Counter Stools'] categories=['Furniture'] sub_categories=['Kitchen & Dining Furniture'] cat_subcat=['Furniture / Kitchen & Dining Furniture']
Furniture

Searching:  33%|███▎      | 158/480 [03:31<06:23,  1.19s/it]

Input tokens 448, output tokens 17
classifications=['Furniture / Bedroom Furniture / Nightstands / Black Nightstands'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  33%|███▎      | 159/480 [03:32<05:51,  1.10s/it]

Input tokens 474, output tokens 21
classifications=["Rugs / Area Rugs / 4' x 6' Area Rugs"] categories=['Rugs'] sub_categories=['Area Rugs'] cat_subcat=['Rugs / Area Rugs']
Rugs

Searching:  33%|███▎      | 160/480 [03:33<05:41,  1.07s/it]

Input tokens 496, output tokens 17
classifications=['Bed & Bath / Bedding / Sheets & Pillowcases'] categories=['Bed & Bath'] sub_categories=['Bedding'] cat_subcat=['Bed & Bath / Bedding']
Bed & Bath

Searching:  34%|███▎      | 161/480 [03:36<09:02,  1.70s/it]

Input tokens 468, output tokens 33
classifications=['Furniture / Bedroom Furniture / Beds & Headboards / Beds / Queen Size Beds', 'Furniture / Bedroom Furniture / Beds & Headboards / Beds'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  34%|███▍      | 162/480 [03:37<08:13,  1.55s/it]

Input tokens 567, output tokens 14
classifications=['Furniture / Living Room Furniture / Sofas'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  34%|███▍      | 163/480 [03:38<07:10,  1.36s/it]

Input tokens 494, output tokens 26
classifications=['Furniture / Kitchen & Dining Furniture / Kitchen Islands & Carts / Kitchen Islands Kitchen Islands & Carts'] categories=['Furniture'] sub_categories=['Kitchen & Dining Furniture'] cat_subcat=['Furniture / Kitchen & Dining Furniture']
Furniture

Searching:  34%|███▍      | 164/480 [03:40<08:33,  1.63s/it]

Input tokens 499, output tokens 122
classifications=['Rugs / Area Rugs', "Rugs / Area Rugs / 2' x 3' Area Rugs", "Rugs / Area Rugs / 3' x 5' Area Rugs", "Rugs / Area Rugs / 4' x 6' Area Rugs", "Rugs / Area Rugs / 5' x 8' Area Rugs", "Rugs / Area Rugs / 8' x 10' Area Rugs", "Rugs / Area Rugs / 9' x 12' Area Rugs", 'Rugs / Doormats'] categories=['Rugs'] sub_categories=['Area Rugs'] cat_subcat=['Rugs / Area Rugs']
Rugs

Searching:  34%|███▍      | 165/480 [03:41<07:46,  1.48s/it]

Input tokens 494, output tokens 35
classifications=['Décor & Pillows / Wall Décor / Wall Accents', 'Décor & Pillows / Art / All Wall Art'] categories=['Décor & Pillows'] sub_categories=['Wall Décor'] cat_subcat=['Décor & Pillows / Wall Décor']
Décor & Pillows

Searching:  35%|███▍      | 166/480 [03:42<06:58,  1.33s/it]

Input tokens 504, output tokens 28
classifications=['Outdoor / Outdoor & Patio Furniture / Outdoor Seating & Patio Chairs / Patio Seating / Patio Sofas & Sectionals'] categories=['Outdoor'] sub_categories=['Outdoor & Patio Furniture'] cat_subcat=['Outdoor / Outdoor & Patio Furniture']
Outdoor

Searching:  35%|███▍      | 167/480 [03:43<06:25,  1.23s/it]

Input tokens 485, output tokens 13
classifications=['Outdoor / Garden / Planters'] categories=['Outdoor'] sub_categories=['Garden'] cat_subcat=['Outdoor / Garden']
Outdoor

Searching:  35%|███▌      | 168/480 [03:44<05:43,  1.10s/it]

Input tokens 515, output tokens 13
classifications=['Furniture / Bedroom Furniture / Nightstands'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  35%|███▌      | 169/480 [03:45<05:44,  1.11s/it]

Input tokens 463, output tokens 33
classifications=['Bed & Bath / Mattresses & Foundations / Hybrid Mattresses', 'Bed & Bath / Mattresses & Foundations / Innerspring Mattresses'] categories=['Bed & Bath'] sub_categories=['Mattresses & Foundations'] cat_subcat=['Bed & Bath / Mattresses & Foundations']
Bed & Bath

Searching:  35%|███▌      | 170/480 [03:48<07:27,  1.44s/it]

Input tokens 491, output tokens 14
classifications=['Lighting / Wall Lights / Bathroom Vanity Lighting'] categories=['Lighting'] sub_categories=['Wall Lights'] cat_subcat=['Lighting / Wall Lights']
Lighting

Searching:  36%|███▌      | 171/480 [03:49<07:21,  1.43s/it]

Input tokens 479, output tokens 21
classifications=['Furniture / Office Furniture / Desks', 'Furniture / Office Furniture / Office Chairs'] categories=['Furniture'] sub_categories=['Office Furniture'] cat_subcat=['Furniture / Office Furniture']
Furniture

Searching:  36%|███▌      | 172/480 [03:50<06:38,  1.30s/it]

Input tokens 455, output tokens 20
classifications=['Décor & Pillows / Mirrors / All Mirrors / Accent Mirrors'] categories=['Décor & Pillows'] sub_categories=['Mirrors'] cat_subcat=['Décor & Pillows / Mirrors']
Décor & Pillows

Searching:  36%|███▌      | 173/480 [03:51<06:15,  1.22s/it]

Input tokens 484, output tokens 22
classifications=['Décor & Pillows / Mirrors / All Mirrors / Bathroom & Vanity Mirrors'] categories=['Décor & Pillows'] sub_categories=['Mirrors'] cat_subcat=['Décor & Pillows / Mirrors']
Décor & Pillows

Searching:  36%|███▋      | 174/480 [03:54<08:34,  1.68s/it]

Input tokens 512, output tokens 16
classifications=['Furniture / Bedroom Furniture / Dressers & Chests'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  36%|███▋      | 175/480 [03:55<08:24,  1.65s/it]

Input tokens 523, output tokens 18
classifications=['Furniture / Kitchen & Dining Furniture / Sideboards & Buffets'] categories=['Furniture'] sub_categories=['Kitchen & Dining Furniture'] cat_subcat=['Furniture / Kitchen & Dining Furniture']
Furniture

Searching:  37%|███▋      | 176/480 [04:00<12:23,  2.45s/it]

Input tokens 534, output tokens 26
classifications=['Kitchen & Tabletop / Kitchen Utensils & Tools / Kitchen Gadgets / Pasta Makers & Accessories'] categories=['Kitchen & Tabletop'] sub_categories=['Kitchen Utensils & Tools'] cat_subcat=['Kitchen & Tabletop / Kitchen Utensils & Tools']
Kitchen & Tabletop

Searching:  37%|███▋      | 177/480 [04:03<13:01,  2.58s/it]

Input tokens 479, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  37%|███▋      | 178/480 [04:05<13:16,  2.64s/it]

Input tokens 450, output tokens 20
classifications=['Furniture / Office Furniture / Chair Mats / Low Pile Carpet Chair Mats'] categories=['Furniture'] sub_categories=['Office Furniture'] cat_subcat=['Furniture / Office Furniture']
Furniture

Searching:  37%|███▋      | 179/480 [04:06<10:45,  2.14s/it]

Input tokens 501, output tokens 22
classifications=["Rugs / Area Rugs / 5' x 8' Area Rugs"] categories=['Rugs'] sub_categories=['Area Rugs'] cat_subcat=['Rugs / Area Rugs']
Rugs

Searching:  38%|███▊      | 180/480 [04:08<09:18,  1.86s/it]

Input tokens 450, output tokens 22
classifications=['Lighting / Light Bulbs & Hardware / Light Bulbs / All Light Bulbs'] categories=['Lighting'] sub_categories=['Light Bulbs & Hardware'] cat_subcat=['Lighting / Light Bulbs & Hardware']
Lighting

Searching:  38%|███▊      | 181/480 [04:09<09:18,  1.87s/it]

Input tokens 555, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  38%|███▊      | 182/480 [04:10<07:55,  1.60s/it]

Input tokens 542, output tokens 35
classifications=['Home Improvement / Hardware / Home Hardware / Switches, Dimmers & Outlets / Outlets For Switches, Dimmers & Outlets'] categories=['Home Improvement'] sub_categories=['Hardware'] cat_subcat=['Home Improvement / Hardware']
Home Improvement

Searching:  38%|███▊      | 183/480 [04:11<07:11,  1.45s/it]

Input tokens 548, output tokens 22
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs / Arm Accent Chairs'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  38%|███▊      | 184/480 [04:12<06:17,  1.28s/it]

Input tokens 467, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  39%|███▊      | 185/480 [04:14<06:15,  1.27s/it]

Input tokens 542, output tokens 24
classifications=['Décor & Pillows / Clocks / Wall Clocks / Digital Wall Clocks'] categories=['Décor & Pillows'] sub_categories=['Clocks'] cat_subcat=['Décor & Pillows / Clocks']
Décor & Pillows

Searching:  39%|███▉      | 186/480 [04:15<06:00,  1.22s/it]

Input tokens 551, output tokens 22
classifications=['Décor & Pillows / Art / All Wall Art / Brown Wall Art'] categories=['Décor & Pillows'] sub_categories=['Art'] cat_subcat=['Décor & Pillows / Art']
Décor & Pillows

Searching:  39%|███▉      | 187/480 [04:16<06:16,  1.29s/it]

Input tokens 464, output tokens 37
classifications=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / All Bathroom Vanities', 'Furniture / Bedroom Furniture / Beds & Headboards / Beds'] categories=['Home Improvement'] sub_categories=['Bathroom Remodel & Bathroom Fixtures'] cat_subcat=['Home Improvement / Bathroom Remodel & Bathroom Fixtures']
Home Improvement

Searching:  39%|███▉      | 188/480 [04:17<06:16,  1.29s/it]

Input tokens 557, output tokens 18
classifications=['Décor & Pillows / Art / All Wall Art'] categories=['Décor & Pillows'] sub_categories=['Art'] cat_subcat=['Décor & Pillows / Art']
Décor & Pillows

Searching:  39%|███▉      | 189/480 [04:18<05:44,  1.18s/it]

Input tokens 505, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  40%|███▉      | 190/480 [04:19<05:23,  1.12s/it]

Input tokens 628, output tokens 31
classifications=['Home Improvement / Kitchen Remodel & Kitchen Fixtures / Kitchen Sinks & Faucet Components / Kitchen Faucets / Black Kitchen Faucets'] categories=['Home Improvement'] sub_categories=['Kitchen Remodel & Kitchen Fixtures'] cat_subcat=['Home Improvement / Kitchen Remodel & Kitchen Fixtures']
Home Improvement

Searching:  40%|███▉      | 191/480 [04:20<05:04,  1.05s/it]

Input tokens 336, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  40%|████      | 192/480 [04:22<06:27,  1.34s/it]

Input tokens 479, output tokens 33
classifications=['Bed & Bath / Bedding Essentials / Mattress Pads & Toppers', 'Bed & Bath / Mattresses & Foundations / Queen Mattresses'] categories=['Bed & Bath'] sub_categories=['Bedding Essentials'] cat_subcat=['Bed & Bath / Bedding Essentials']
Bed & Bath

Searching:  40%|████      | 193/480 [04:23<05:48,  1.21s/it]

Input tokens 518, output tokens 20
classifications=['Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  40%|████      | 194/480 [04:25<06:35,  1.38s/it]

Input tokens 594, output tokens 18
classifications=['School Furniture and Supplies / Facilities & Maintenance / Trash & Recycling'] categories=['School Furniture and Supplies'] sub_categories=['Facilities & Maintenance'] cat_subcat=['School Furniture and Supplies / Facilities & Maintenance']
School Furniture and Supplies

Searching:  41%|████      | 195/480 [04:26<06:38,  1.40s/it]

Input tokens 518, output tokens 20
classifications=['Décor & Pillows / Wall Décor / Wall Accents'] categories=['Décor & Pillows'] sub_categories=['Wall Décor'] cat_subcat=['Décor & Pillows / Wall Décor']
Décor & Pillows

Searching:  41%|████      | 196/480 [04:28<06:13,  1.32s/it]

Input tokens 561, output tokens 18
classifications=['Furniture / Living Room Furniture / Ottomans & Poufs'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  41%|████      | 197/480 [04:30<08:22,  1.78s/it]

Input tokens 518, output tokens 33
classifications=['Outdoor / Outdoor & Patio Furniture / Patio Furniture Sets / Patio Conversation Sets', 'Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs'] categories=['Outdoor'] sub_categories=['Outdoor & Patio Furniture'] cat_subcat=['Outdoor / Outdoor & Patio Furniture']
Outdoor

Searching:  41%|████▏     | 198/480 [04:31<06:50,  1.46s/it]

Input tokens 435, output tokens 13
classifications=['Furniture / Bedroom Furniture / Daybeds'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  41%|████▏     | 199/480 [04:32<06:15,  1.33s/it]

Input tokens 506, output tokens 20
classifications=['Décor & Pillows / Wall Décor / Wall Accents'] categories=['Décor & Pillows'] sub_categories=['Wall Décor'] cat_subcat=['Décor & Pillows / Wall Décor']
Décor & Pillows

Searching:  42%|████▏     | 200/480 [04:34<06:30,  1.39s/it]

Input tokens 476, output tokens 39
classifications=['Furniture / Kitchen & Dining Furniture / Dining Tables & Seating / Kitchen & Dining Tables', 'Furniture / Kitchen & Dining Furniture / Dining Tables & Seating / Kitchen & Dining Chairs'] categories=['Furniture'] sub_categories=['Kitchen & Dining Furniture'] cat_subcat=['Furniture / Kitchen & Dining Furniture']
Furniture

Searching:  42%|████▏     | 201/480 [04:36<07:14,  1.56s/it]

Input tokens 516, output tokens 28
classifications=['Décor & Pillows / Window Treatments / Curtain Hardware & Accessories / Single Rod Curtain Hardware & Accessories'] categories=['Décor & Pillows'] sub_categories=['Window Treatments'] cat_subcat=['Décor & Pillows / Window Treatments']
Décor & Pillows

Searching:  42%|████▏     | 202/480 [04:37<06:25,  1.39s/it]

Input tokens 517, output tokens 33
classifications=['Furniture / Kitchen & Dining Furniture / Kitchen Islands & Carts', 'Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables'] categories=['Furniture'] sub_categories=['Kitchen & Dining Furniture'] cat_subcat=['Furniture / Kitchen & Dining Furniture']
Furniture

Searching:  42%|████▏     | 203/480 [04:37<05:40,  1.23s/it]

Input tokens 546, output tokens 14
classifications=['Furniture / Office Furniture / Office Chairs'] categories=['Furniture'] sub_categories=['Office Furniture'] cat_subcat=['Furniture / Office Furniture']
Furniture

Searching:  42%|████▎     | 204/480 [04:38<05:22,  1.17s/it]

Input tokens 514, output tokens 17
classifications=['Furniture / Office Furniture / Desks / Writing Desks'] categories=['Furniture'] sub_categories=['Office Furniture'] cat_subcat=['Furniture / Office Furniture']
Furniture

Searching:  43%|████▎     | 205/480 [04:39<04:54,  1.07s/it]

Input tokens 479, output tokens 17
classifications=['Furniture / Bedroom Furniture / Beds & Headboards / Beds'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  43%|████▎     | 206/480 [04:40<04:30,  1.01it/s]

Input tokens 480, output tokens 24
classifications=['Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows'] categories=['Décor & Pillows'] sub_categories=['Decorative Pillows & Blankets'] cat_subcat=['Décor & Pillows / Decorative Pillows & Blankets']
Décor & Pillows

Searching:  43%|████▎     | 207/480 [04:42<05:33,  1.22s/it]

Input tokens 504, output tokens 28
classifications=['Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows / Green Throw Pillows'] categories=['Décor & Pillows'] sub_categories=['Decorative Pillows & Blankets'] cat_subcat=['Décor & Pillows / Decorative Pillows & Blankets']
Décor & Pillows

Searching:  43%|████▎     | 208/480 [04:43<05:00,  1.11s/it]

Input tokens 499, output tokens 21
classifications=['Pet / Dog / Pet Gates, Fences & Doors / Pet Gates'] categories=['Pet'] sub_categories=['Dog'] cat_subcat=['Pet / Dog']
Pet

Searching:  44%|████▎     | 209/480 [04:44<05:17,  1.17s/it]

Input tokens 739, output tokens 34
classifications=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Sinks & Faucet Components / Bathroom Sink Faucets / Widespread Bathroom Sink Faucets'] categories=['Home Improvement'] sub_categories=['Bathroom Remodel & Bathroom Fixtures'] cat_subcat=['Home Improvement / Bathroom Remodel & Bathroom Fixtures']
Home Improvement

Searching:  44%|████▍     | 210/480 [04:45<04:50,  1.08s/it]

Input tokens 516, output tokens 15
classifications=['Pet / Bird / All Bird Cages'] categories=['Pet'] sub_categories=['Bird'] cat_subcat=['Pet / Bird']
Pet

Searching:  44%|████▍     | 211/480 [04:46<04:37,  1.03s/it]

Input tokens 460, output tokens 21
classifications=['Furniture / Bedroom Furniture / Beds & Headboards / Beds / Queen Size Beds'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  44%|████▍     | 212/480 [04:46<04:04,  1.09it/s]

Input tokens 665, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  44%|████▍     | 213/480 [04:47<03:40,  1.21it/s]

Input tokens 578, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  45%|████▍     | 214/480 [04:50<06:09,  1.39s/it]

Input tokens 498, output tokens 18
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  45%|████▍     | 215/480 [04:51<05:27,  1.23s/it]

Input tokens 515, output tokens 23
classifications=['Furniture / Kitchen & Dining Furniture / Dining Tables & Seating / Kitchen & Dining Tables'] categories=['Furniture'] sub_categories=['Kitchen & Dining Furniture'] cat_subcat=['Furniture / Kitchen & Dining Furniture']
Furniture

Searching:  45%|████▌     | 216/480 [04:51<04:47,  1.09s/it]

Input tokens 564, output tokens 18
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  45%|████▌     | 217/480 [04:52<04:31,  1.03s/it]

Input tokens 291, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  45%|████▌     | 218/480 [04:53<04:36,  1.06s/it]

Input tokens 532, output tokens 29
classifications=['Outdoor / Outdoor & Patio Furniture / Outdoor Seating & Patio Chairs / Patio Seating / Patio Rocking Chairs & Gliders'] categories=['Outdoor'] sub_categories=['Outdoor & Patio Furniture'] cat_subcat=['Outdoor / Outdoor & Patio Furniture']
Outdoor

Searching:  46%|████▌     | 219/480 [04:54<04:21,  1.00s/it]

Input tokens 602, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  46%|████▌     | 220/480 [04:55<04:29,  1.04s/it]

Input tokens 189, output tokens 24
classifications=['Storage & Organization / Garage & Outdoor Storage & Organization / Storage Racks & Shelving Units'] categories=['Storage & Organization'] sub_categories=['Garage & Outdoor Storage & Organization'] cat_subcat=['Storage & Organization / Garage & Outdoor Storage & Organization']
Storage & Organization

Searching:  46%|████▌     | 221/480 [04:58<06:07,  1.42s/it]

Input tokens 467, output tokens 17
classifications=['Outdoor / Hot Tubs & Saunas / Saunas'] categories=['Outdoor'] sub_categories=['Hot Tubs & Saunas'] cat_subcat=['Outdoor / Hot Tubs & Saunas']
Outdoor

Searching:  46%|████▋     | 222/480 [04:59<05:40,  1.32s/it]

Input tokens 607, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  46%|████▋     | 223/480 [05:00<05:17,  1.24s/it]

Input tokens 512, output tokens 29
classifications=['Storage & Organization / Bathroom Storage & Organization / Hampers & Laundry Baskets / Laundry Hampers & Laundry Baskets'] categories=['Storage & Organization'] sub_categories=['Bathroom Storage & Organization'] cat_subcat=['Storage & Organization / Bathroom Storage & Organization']
Storage & Organization

Searching:  47%|████▋     | 224/480 [05:02<06:08,  1.44s/it]

Input tokens 486, output tokens 13
classifications=['Furniture / Office Furniture / Desks'] categories=['Furniture'] sub_categories=['Office Furniture'] cat_subcat=['Furniture / Office Furniture']
Furniture

Searching:  47%|████▋     | 225/480 [05:03<05:29,  1.29s/it]

Input tokens 449, output tokens 21
classifications=['Furniture / Bedroom Furniture / Beds & Headboards / Beds / Queen Size Beds'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  47%|████▋     | 226/480 [05:04<04:52,  1.15s/it]

Input tokens 548, output tokens 23
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs / Arm Accent Chairs'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  47%|████▋     | 227/480 [05:04<04:30,  1.07s/it]

Input tokens 556, output tokens 11
classifications=['Rugs / Kitchen Mats'] categories=['Rugs'] sub_categories=['Kitchen Mats'] cat_subcat=['Rugs / Kitchen Mats']
Rugs

Searching:  48%|████▊     | 228/480 [05:05<04:13,  1.01s/it]

Input tokens 516, output tokens 25
classifications=['Furniture / Office Furniture / Desks / Computer Desks', 'Furniture / Office Furniture / Desks'] categories=['Furniture'] sub_categories=['Office Furniture'] cat_subcat=['Furniture / Office Furniture']
Furniture

Searching:  48%|████▊     | 229/480 [05:06<04:00,  1.04it/s]

Input tokens 555, output tokens 29
classifications=['Outdoor / Outdoor & Patio Furniture / Outdoor Seating & Patio Chairs / Patio Seating / Patio Rocking Chairs & Gliders'] categories=['Outdoor'] sub_categories=['Outdoor & Patio Furniture'] cat_subcat=['Outdoor / Outdoor & Patio Furniture']
Outdoor

Searching:  48%|████▊     | 230/480 [05:07<04:18,  1.04s/it]

Input tokens 447, output tokens 27
classifications=['Lighting / Light Bulbs & Hardware / Light Bulbs / All Light Bulbs / LED Light Bulbs'] categories=['Lighting'] sub_categories=['Light Bulbs & Hardware'] cat_subcat=['Lighting / Light Bulbs & Hardware']
Lighting

Searching:  48%|████▊     | 231/480 [05:08<04:03,  1.02it/s]

Input tokens 490, output tokens 14
classifications=['Furniture / Office Furniture / Office Storage Cabinets'] categories=['Furniture'] sub_categories=['Office Furniture'] cat_subcat=['Furniture / Office Furniture']
Furniture

Searching:  48%|████▊     | 232/480 [05:09<03:57,  1.04it/s]

Input tokens 501, output tokens 20
classifications=['Décor & Pillows / Wall Décor / Wall Accents'] categories=['Décor & Pillows'] sub_categories=['Wall Décor'] cat_subcat=['Décor & Pillows / Wall Décor']
Décor & Pillows

Searching:  49%|████▊     | 233/480 [05:10<03:37,  1.14it/s]

Input tokens 534, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  49%|████▉     | 234/480 [05:11<04:05,  1.00it/s]

Input tokens 458, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  49%|████▉     | 235/480 [05:14<06:39,  1.63s/it]

Input tokens 495, output tokens 24
classifications=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / All Bathroom Vanities'] categories=['Home Improvement'] sub_categories=['Bathroom Remodel & Bathroom Fixtures'] cat_subcat=['Home Improvement / Bathroom Remodel & Bathroom Fixtures']
Home Improvement

Searching:  49%|████▉     | 236/480 [05:15<05:51,  1.44s/it]

Input tokens 466, output tokens 21
classifications=["Rugs / Area Rugs / 5' x 8' Area Rugs"] categories=['Rugs'] sub_categories=['Area Rugs'] cat_subcat=['Rugs / Area Rugs']
Rugs

Searching:  49%|████▉     | 237/480 [05:16<05:36,  1.39s/it]

Input tokens 515, output tokens 36
classifications=['Furniture / Living Room Furniture / TV Stands & Media Storage Furniture / TV Stands & Entertainment Centers / Modern & Contemporary TV Stands & Entertainment Centers'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  50%|████▉     | 238/480 [05:19<07:33,  1.87s/it]

Input tokens 485, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  50%|████▉     | 239/480 [05:21<06:53,  1.71s/it]

Input tokens 451, output tokens 28
classifications=['Lighting / Outdoor Lighting / Outdoor Wall Lighting', 'Lighting / Outdoor Lighting / Landscape Lighting / All Landscape Lighting'] categories=['Lighting'] sub_categories=['Outdoor Lighting'] cat_subcat=['Lighting / Outdoor Lighting']
Lighting

Searching:  50%|█████     | 240/480 [05:22<06:16,  1.57s/it]

Input tokens 472, output tokens 23
classifications=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / All Bathroom Vanities'] categories=['Home Improvement'] sub_categories=['Bathroom Remodel & Bathroom Fixtures'] cat_subcat=['Home Improvement / Bathroom Remodel & Bathroom Fixtures']
Home Improvement

Searching:  50%|█████     | 241/480 [05:23<05:36,  1.41s/it]

Input tokens 485, output tokens 82
classifications=['Outdoor / Outdoor & Patio Furniture / Patio Furniture Sets / Patio Conversation Sets', 'Outdoor / Outdoor & Patio Furniture / Outdoor Seating & Patio Chairs / Patio Seating / Patio Sofas & Sectionals', 'Outdoor / Outdoor & Patio Furniture / Patio Furniture Sets / Patio Dining Sets', 'Outdoor / Outdoor & Patio Furniture / Outdoor Seating & Patio Chairs / Patio Seating / Outdoor Club Chairs'] categories=['Outdoor'] sub_categories=['Outdoor & Patio Furniture'] cat_subcat=['Outdoor / Outdoor & Patio Furniture']
Outdoor

Searching:  50%|█████     | 242/480 [05:24<05:28,  1.38s/it]

Input tokens 571, output tokens 23
classifications=['Kitchen & Tabletop / Kitchen Organization / Food Storage & Canisters / Food Storage Containers'] categories=['Kitchen & Tabletop'] sub_categories=['Kitchen Organization'] cat_subcat=['Kitchen & Tabletop / Kitchen Organization']
Kitchen & Tabletop

Searching:  51%|█████     | 243/480 [05:25<04:51,  1.23s/it]

Input tokens 538, output tokens 18
classifications=['Décor & Pillows / Art / All Wall Art'] categories=['Décor & Pillows'] sub_categories=['Art'] cat_subcat=['Décor & Pillows / Art']
Décor & Pillows

Searching:  51%|█████     | 244/480 [05:26<04:21,  1.11s/it]

Input tokens 612, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  51%|█████     | 245/480 [05:27<04:10,  1.07s/it]

Input tokens 507, output tokens 22
classifications=['Furniture / Living Room Furniture / Coffee Tables & End Tables / End & Side Tables'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  51%|█████▏    | 246/480 [05:28<04:17,  1.10s/it]

Input tokens 547, output tokens 28
classifications=['Furniture / Office Furniture / Office Chairs', 'Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs'] categories=['Furniture'] sub_categories=['Office Furniture'] cat_subcat=['Furniture / Office Furniture']
Furniture

Searching:  51%|█████▏    | 247/480 [05:29<04:10,  1.08s/it]

Input tokens 484, output tokens 20
classifications=['Décor & Pillows / Wall Décor / Wall Accents'] categories=['Décor & Pillows'] sub_categories=['Wall Décor'] cat_subcat=['Décor & Pillows / Wall Décor']
Décor & Pillows

Searching:  52%|█████▏    | 248/480 [05:30<04:06,  1.06s/it]

Input tokens 454, output tokens 16
classifications=['Home Improvement / Hardware / Home Hardware / Switch Plates'] categories=['Home Improvement'] sub_categories=['Hardware'] cat_subcat=['Home Improvement / Hardware']
Home Improvement

Searching:  52%|█████▏    | 249/480 [05:33<05:36,  1.46s/it]

Input tokens 519, output tokens 22
classifications=['Furniture / Kitchen & Dining Furniture / Dining Tables & Seating / Kitchen & Dining Tables'] categories=['Furniture'] sub_categories=['Kitchen & Dining Furniture'] cat_subcat=['Furniture / Kitchen & Dining Furniture']
Furniture

Searching:  52%|█████▏    | 250/480 [05:34<04:54,  1.28s/it]

Input tokens 467, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  52%|█████▏    | 251/480 [05:35<04:54,  1.29s/it]

Input tokens 494, output tokens 20
classifications=['Décor & Pillows / Wall Décor / Wall Accents'] categories=['Décor & Pillows'] sub_categories=['Wall Décor'] cat_subcat=['Décor & Pillows / Wall Décor']
Décor & Pillows

Searching:  52%|█████▎    | 252/480 [05:37<05:30,  1.45s/it]

Input tokens 533, output tokens 18
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  53%|█████▎    | 253/480 [05:38<05:05,  1.35s/it]

Input tokens 465, output tokens 23
classifications=['Furniture / Living Room Furniture / Coffee Tables & End Tables / Plant Stands & Tables'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  53%|█████▎    | 254/480 [05:39<04:34,  1.21s/it]

Input tokens 471, output tokens 11
classifications=['Rugs / Area Rugs'] categories=['Rugs'] sub_categories=['Area Rugs'] cat_subcat=['Rugs / Area Rugs']
Rugs

Searching:  53%|█████▎    | 255/480 [05:40<04:27,  1.19s/it]

Input tokens 480, output tokens 14
classifications=['Bed & Bath / Bedding / All Bedding'] categories=['Bed & Bath'] sub_categories=['Bedding'] cat_subcat=['Bed & Bath / Bedding']
Bed & Bath

Searching:  53%|█████▎    | 256/480 [05:41<04:34,  1.22s/it]

Input tokens 519, output tokens 13
classifications=['Furniture / Office Furniture / Office Chairs'] categories=['Furniture'] sub_categories=['Office Furniture'] cat_subcat=['Furniture / Office Furniture']
Furniture

Searching:  54%|█████▎    | 257/480 [05:42<04:05,  1.10s/it]

Input tokens 467, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  54%|█████▍    | 258/480 [05:43<03:54,  1.05s/it]

Input tokens 615, output tokens 34
classifications=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Sinks & Faucet Components / Bathroom Sink Faucets / Widespread Bathroom Sink Faucets'] categories=['Home Improvement'] sub_categories=['Bathroom Remodel & Bathroom Fixtures'] cat_subcat=['Home Improvement / Bathroom Remodel & Bathroom Fixtures']
Home Improvement

Searching:  54%|█████▍    | 259/480 [05:44<04:02,  1.10s/it]

Input tokens 439, output tokens 53
classifications=['Furniture / Bedroom Furniture / Beds & Headboards / Beds / Queen Size Beds', 'Furniture / Bedroom Furniture / Beds & Headboards / Beds / Full & Double Beds', 'Furniture / Bedroom Furniture / Beds & Headboards / Beds / Twin Beds'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  54%|█████▍    | 260/480 [05:46<04:33,  1.24s/it]

Input tokens 668, output tokens 119
classifications=['Kitchen & Tabletop / Kitchen Organization / Food Storage & Canisters / Food Storage Containers / Containers Food Storage Containers', 'Kitchen & Tabletop / Kitchen Organization / Food Storage & Canisters / Kitchen Canisters & Jars / Metal Kitchen Canisters & Jars', 'Kitchen & Tabletop / Kitchen Organization / Food Storage & Canisters / Kitchen Canisters & Jars / Glass Kitchen Canisters & Jars', 'Kitchen & Tabletop / Kitchen Organization / Food Storage & Canisters / Kitchen Canisters & Jars / Ceramic Kitchen Canisters & Jars'] categories=['Kitchen & Tabletop'] sub_categories=['Kitchen Organization'] cat_subcat=['Kitchen & Tabletop / Kitchen Organization']
Kitchen & Tabletop

Searching:  54%|█████▍    | 261/480 [05:47<04:08,  1.14s/it]

Input tokens 506, output tokens 21
classifications=["Rugs / Area Rugs / 5' x 8' Area Rugs"] categories=['Rugs'] sub_categories=['Area Rugs'] cat_subcat=['Rugs / Area Rugs']
Rugs

Searching:  55%|█████▍    | 262/480 [05:49<05:15,  1.45s/it]

Input tokens 505, output tokens 11
classifications=['Rugs / Area Rugs'] categories=['Rugs'] sub_categories=['Area Rugs'] cat_subcat=['Rugs / Area Rugs']
Rugs

Searching:  55%|█████▍    | 263/480 [05:50<04:37,  1.28s/it]

Input tokens 468, output tokens 18
classifications=['Furniture / Living Room Furniture / Ottomans & Poufs'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  55%|█████▌    | 264/480 [05:51<04:21,  1.21s/it]

Input tokens 466, output tokens 23
classifications=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / All Bathroom Vanities'] categories=['Home Improvement'] sub_categories=['Bathroom Remodel & Bathroom Fixtures'] cat_subcat=['Home Improvement / Bathroom Remodel & Bathroom Fixtures']
Home Improvement

Searching:  55%|█████▌    | 265/480 [05:52<04:06,  1.15s/it]

Input tokens 479, output tokens 15
classifications=['Bed & Bath / Bedding / All Bedding'] categories=['Bed & Bath'] sub_categories=['Bedding'] cat_subcat=['Bed & Bath / Bedding']
Bed & Bath

Searching:  55%|█████▌    | 266/480 [05:53<03:55,  1.10s/it]

Input tokens 473, output tokens 28
classifications=['Home Improvement / Flooring, Walls & Ceiling / Floor Tiles & Wall Tiles / Porcelain Floor Tiles & Wall Tiles'] categories=['Home Improvement'] sub_categories=['Flooring, Walls & Ceiling'] cat_subcat=['Home Improvement / Flooring, Walls & Ceiling']
Home Improvement

Searching:  56%|█████▌    | 267/480 [05:54<03:43,  1.05s/it]

Input tokens 513, output tokens 12
classifications=['Outdoor / Garden / Planters'] categories=['Outdoor'] sub_categories=['Garden'] cat_subcat=['Outdoor / Garden']
Outdoor

Searching:  56%|█████▌    | 268/480 [05:54<03:31,  1.00it/s]

Input tokens 458, output tokens 35
classifications=['Contractor / Entry & Hallway / Coat Racks & Umbrella Stands', 'Furniture / Living Room Furniture / Chairs & Seating / Benches'] categories=['Contractor'] sub_categories=['Entry & Hallway'] cat_subcat=['Contractor / Entry & Hallway']
Contractor

Searching:  56%|█████▌    | 269/480 [05:57<04:50,  1.38s/it]

Input tokens 458, output tokens 22
classifications=['Furniture / Bedroom Furniture / Beds & Headboards / Beds / Queen Size Beds'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  56%|█████▋    | 270/480 [05:58<04:34,  1.31s/it]

Input tokens 517, output tokens 22
classifications=['Furniture / Living Room Furniture / Coffee Tables & End Tables / End & Side Tables'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  56%|█████▋    | 271/480 [06:00<05:04,  1.46s/it]

Input tokens 564, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  57%|█████▋    | 272/480 [06:04<08:22,  2.41s/it]

Input tokens 530, output tokens 22
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs / Arm Accent Chairs'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  57%|█████▋    | 273/480 [06:05<06:59,  2.02s/it]

Input tokens 516, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  57%|█████▋    | 274/480 [06:07<06:21,  1.85s/it]

Input tokens 608, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  57%|█████▋    | 275/480 [06:09<07:07,  2.09s/it]

Input tokens 521, output tokens 44
classifications=['Décor & Pillows / Clocks / Wall Clocks', 'Outdoor / Outdoor Décor / Outdoor Wall Décor', 'Outdoor / Outdoor Décor / Statues & Sculptures'] categories=['Décor & Pillows'] sub_categories=['Clocks'] cat_subcat=['Décor & Pillows / Clocks']
Décor & Pillows

Searching:  57%|█████▊    | 276/480 [06:11<06:11,  1.82s/it]

Input tokens 538, output tokens 17
classifications=['Décor & Pillows / Mirrors / All Mirrors'] categories=['Décor & Pillows'] sub_categories=['Mirrors'] cat_subcat=['Décor & Pillows / Mirrors']
Décor & Pillows

Searching:  58%|█████▊    | 277/480 [06:12<05:17,  1.56s/it]

Input tokens 491, output tokens 18
classifications=['Bed & Bath / Bedding / All Bedding / Twin Bedding'] categories=['Bed & Bath'] sub_categories=['Bedding'] cat_subcat=['Bed & Bath / Bedding']
Bed & Bath

Searching:  58%|█████▊    | 278/480 [06:13<04:56,  1.47s/it]

Input tokens 452, output tokens 18
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  58%|█████▊    | 279/480 [06:14<04:29,  1.34s/it]

Input tokens 515, output tokens 16
classifications=['Lighting / Table & Floor Lamps / Table Lamps'] categories=['Lighting'] sub_categories=['Table & Floor Lamps'] cat_subcat=['Lighting / Table & Floor Lamps']
Lighting

Searching:  58%|█████▊    | 280/480 [06:15<03:50,  1.15s/it]

Input tokens 525, output tokens 15
classifications=['Furniture / Living Room Furniture / Console Tables'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  59%|█████▊    | 281/480 [06:16<03:40,  1.11s/it]

Input tokens 453, output tokens 22
classifications=['Furniture / Bedroom Furniture / Beds & Headboards / Beds / Full & Double Beds'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  59%|█████▉    | 282/480 [06:17<03:36,  1.09s/it]

Input tokens 516, output tokens 52
classifications=['Home Improvement / Flooring, Walls & Ceiling / Flooring Installation & Accessories / Molding & Millwork / Wall Molding & Millwork', 'Home Improvement / Flooring, Walls & Ceiling / Flooring Installation & Accessories / Molding & Millwork'] categories=['Home Improvement'] sub_categories=['Flooring, Walls & Ceiling'] cat_subcat=['Home Improvement / Flooring, Walls & Ceiling']
Home Improvement

Searching:  59%|█████▉    | 283/480 [06:18<03:47,  1.16s/it]

Input tokens 512, output tokens 36
classifications=['Furniture / Bedroom Furniture / Beds & Headboards / Beds', 'Furniture / Bedroom Furniture / Beds & Headboards / Bed Frames / Twin Bed Frames'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  59%|█████▉    | 284/480 [06:19<03:36,  1.11s/it]

Input tokens 541, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  59%|█████▉    | 285/480 [06:20<03:29,  1.07s/it]

Input tokens 488, output tokens 25
classifications=['Outdoor / Outdoor & Patio Furniture / Outdoor Seating & Patio Chairs / Patio Seating / Outdoor Club Chairs'] categories=['Outdoor'] sub_categories=['Outdoor & Patio Furniture'] cat_subcat=['Outdoor / Outdoor & Patio Furniture']
Outdoor

Searching:  60%|█████▉    | 286/480 [06:21<03:33,  1.10s/it]

Input tokens 498, output tokens 26
classifications=['Home Improvement / Hardware / Cabinet Hardware / Cabinet & Drawer Pulls / Black Cabinet & Drawer Pulls'] categories=['Home Improvement'] sub_categories=['Hardware'] cat_subcat=['Home Improvement / Hardware']
Home Improvement

Searching:  60%|█████▉    | 287/480 [06:22<03:17,  1.02s/it]

Input tokens 510, output tokens 19
classifications=['Furniture / Living Room Furniture / Sectionals / Stationary Sectionals'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  60%|██████    | 288/480 [06:23<03:21,  1.05s/it]

Input tokens 460, output tokens 20
classifications=['Décor & Pillows / Mirrors / All Mirrors / Accent Mirrors'] categories=['Décor & Pillows'] sub_categories=['Mirrors'] cat_subcat=['Décor & Pillows / Mirrors']
Décor & Pillows

Searching:  60%|██████    | 289/480 [06:25<03:51,  1.21s/it]

Input tokens 480, output tokens 40
classifications=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / All Bathroom Vanities', 'Décor & Pillows / Wall Décor / Wall Accents'] categories=['Home Improvement'] sub_categories=['Bathroom Remodel & Bathroom Fixtures'] cat_subcat=['Home Improvement / Bathroom Remodel & Bathroom Fixtures']
Home Improvement

Searching:  60%|██████    | 290/480 [06:26<03:28,  1.10s/it]

Input tokens 522, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  61%|██████    | 291/480 [06:28<04:55,  1.57s/it]

Input tokens 475, output tokens 18
classifications=['Furniture / Living Room Furniture / Sectionals / Modular Sectionals'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  61%|██████    | 292/480 [06:29<04:09,  1.33s/it]

Input tokens 491, output tokens 14
classifications=['Bed & Bath / Bedding / All Bedding'] categories=['Bed & Bath'] sub_categories=['Bedding'] cat_subcat=['Bed & Bath / Bedding']
Bed & Bath

Searching:  61%|██████    | 293/480 [06:30<03:52,  1.24s/it]

Input tokens 484, output tokens 40
classifications=['Storage & Organization / Wall Shelving & Organization / Wall and Display Shelves', 'Storage & Organization / Garage & Outdoor Storage & Organization / Storage Racks & Shelving Units'] categories=['Storage & Organization'] sub_categories=['Wall Shelving & Organization'] cat_subcat=['Storage & Organization / Wall Shelving & Organization']
Storage & Organization

Searching:  61%|██████▏   | 294/480 [06:31<03:40,  1.19s/it]

Input tokens 424, output tokens 18
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  61%|██████▏   | 295/480 [06:33<04:21,  1.41s/it]

Input tokens 580, output tokens 28
classifications=['Home Improvement / Flooring, Walls & Ceiling / Floor Tiles & Wall Tiles / Shell Floor Tiles & Wall Tiles'] categories=['Home Improvement'] sub_categories=['Flooring, Walls & Ceiling'] cat_subcat=['Home Improvement / Flooring, Walls & Ceiling']
Home Improvement

Searching:  62%|██████▏   | 296/480 [06:34<04:12,  1.37s/it]

Input tokens 529, output tokens 35
classifications=['Furniture / Kitchen & Dining Furniture / Sideboards & Buffets', 'Storage & Organization / Bathroom Storage & Organization / Bathroom Cabinets & Shelving'] categories=['Furniture'] sub_categories=['Kitchen & Dining Furniture'] cat_subcat=['Furniture / Kitchen & Dining Furniture']
Furniture

Searching:  62%|██████▏   | 297/480 [06:35<03:45,  1.23s/it]

Input tokens 476, output tokens 11
classifications=['Rugs / Area Rugs'] categories=['Rugs'] sub_categories=['Area Rugs'] cat_subcat=['Rugs / Area Rugs']
Rugs

Searching:  62%|██████▏   | 298/480 [06:36<03:27,  1.14s/it]

Input tokens 586, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  62%|██████▏   | 299/480 [06:37<03:23,  1.12s/it]

Input tokens 496, output tokens 23
classifications=['Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows'] categories=['Décor & Pillows'] sub_categories=['Decorative Pillows & Blankets'] cat_subcat=['Décor & Pillows / Decorative Pillows & Blankets']
Décor & Pillows

Searching:  62%|██████▎   | 300/480 [06:40<04:28,  1.49s/it]

Input tokens 563, output tokens 90
classifications=['Décor & Pillows / Art / All Wall Art / Green Wall Art', 'Décor & Pillows / Art / All Wall Art / Blue Wall Art', 'Décor & Pillows / Art / All Wall Art / Pink Wall Art', 'Décor & Pillows / Art / All Wall Art / Red Wall Art', 'Décor & Pillows / Art / All Wall Art / Yellow Wall Art'] categories=['Décor & Pillows'] sub_categories=['Art'] cat_subcat=['Décor & Pillows / Art']
Décor & Pillows

Searching:  63%|██████▎   | 301/480 [06:41<04:36,  1.55s/it]

Input tokens 594, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  63%|██████▎   | 302/480 [06:42<03:54,  1.32s/it]

Input tokens 492, output tokens 20
classifications=['Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  63%|██████▎   | 303/480 [06:43<03:29,  1.18s/it]

Input tokens 455, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  63%|██████▎   | 304/480 [06:44<03:19,  1.13s/it]

Input tokens 541, output tokens 40
classifications=['Home Improvement / Hardware / Cabinet Hardware / Cabinet & Drawer Pulls / Black Cabinet & Drawer Pulls', 'Home Improvement / Hardware / Cabinet Hardware / Cabinet & Drawer Pulls'] categories=['Home Improvement'] sub_categories=['Hardware'] cat_subcat=['Home Improvement / Hardware']
Home Improvement

Searching:  64%|██████▎   | 305/480 [06:50<07:50,  2.69s/it]

Input tokens 460, output tokens 14
classifications=['Bed & Bath / Bedding / All Bedding'] categories=['Bed & Bath'] sub_categories=['Bedding'] cat_subcat=['Bed & Bath / Bedding']
Bed & Bath

Searching:  64%|██████▍   | 306/480 [06:51<06:14,  2.15s/it]

Input tokens 478, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  64%|██████▍   | 307/480 [06:55<08:01,  2.78s/it]

Input tokens 499, output tokens 20
classifications=['Outdoor / Outdoor & Patio Furniture / Patio Furniture Sets / Patio Dining Sets'] categories=['Outdoor'] sub_categories=['Outdoor & Patio Furniture'] cat_subcat=['Outdoor / Outdoor & Patio Furniture']
Outdoor

Searching:  64%|██████▍   | 308/480 [06:57<07:25,  2.59s/it]

Input tokens 519, output tokens 25
classifications=['Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables / Rectangle Coffee Tables'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  64%|██████▍   | 309/480 [06:59<06:29,  2.28s/it]

Input tokens 511, output tokens 59
classifications=['Décor & Pillows / Wall Décor / Wall Accents', 'Storage & Organization / Bathroom Storage & Organization / Bathroom Cabinets & Shelving', 'Furniture / Living Room Furniture / TV Stands & Media Storage Furniture / TV Stands & Entertainment Centers'] categories=['Décor & Pillows'] sub_categories=['Wall Décor'] cat_subcat=['Décor & Pillows / Wall Décor']
Décor & Pillows

Searching:  65%|██████▍   | 310/480 [07:00<05:32,  1.95s/it]

Input tokens 471, output tokens 14
classifications=['Lighting / Outdoor Lighting / Outdoor Wall Lighting'] categories=['Lighting'] sub_categories=['Outdoor Lighting'] cat_subcat=['Lighting / Outdoor Lighting']
Lighting

Searching:  65%|██████▍   | 311/480 [07:01<04:32,  1.61s/it]

Input tokens 564, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  65%|██████▌   | 312/480 [07:02<04:05,  1.46s/it]

Input tokens 480, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  65%|██████▌   | 313/480 [07:03<03:46,  1.36s/it]

Input tokens 474, output tokens 18
classifications=['Furniture / Kitchen & Dining Furniture / Sideboards & Buffets'] categories=['Furniture'] sub_categories=['Kitchen & Dining Furniture'] cat_subcat=['Furniture / Kitchen & Dining Furniture']
Furniture

Searching:  65%|██████▌   | 314/480 [07:05<03:47,  1.37s/it]

Input tokens 552, output tokens 39
classifications=['Outdoor / Outdoor Décor / Statues & Sculptures / Fairy Statues & Sculptures', 'Outdoor / Garden / Garden Décor / Lawn & Garden Accents'] categories=['Outdoor'] sub_categories=['Outdoor Décor'] cat_subcat=['Outdoor / Outdoor Décor']
Outdoor

Searching:  66%|██████▌   | 315/480 [07:06<03:41,  1.34s/it]

Input tokens 465, output tokens 21
classifications=['Outdoor / Outdoor & Patio Furniture / Patio Furniture Sets / Patio Conversation Sets'] categories=['Outdoor'] sub_categories=['Outdoor & Patio Furniture'] cat_subcat=['Outdoor / Outdoor & Patio Furniture']
Outdoor

Searching:  66%|██████▌   | 316/480 [07:07<03:08,  1.15s/it]

Input tokens 450, output tokens 15
classifications=['Bed & Bath / Bedding / All Bedding'] categories=['Bed & Bath'] sub_categories=['Bedding'] cat_subcat=['Bed & Bath / Bedding']
Bed & Bath

Searching:  66%|██████▌   | 317/480 [07:08<02:55,  1.08s/it]

Input tokens 574, output tokens 21
classifications=['Bed & Bath / Shower Curtains & Accessories / Shower Curtains & Shower Liners'] categories=['Bed & Bath'] sub_categories=['Shower Curtains & Accessories'] cat_subcat=['Bed & Bath / Shower Curtains & Accessories']
Bed & Bath

Searching:  66%|██████▋   | 318/480 [07:09<03:15,  1.21s/it]

Input tokens 484, output tokens 20
classifications=['Décor & Pillows / Wall Décor / Wall Accents'] categories=['Décor & Pillows'] sub_categories=['Wall Décor'] cat_subcat=['Décor & Pillows / Wall Décor']
Décor & Pillows

Searching:  66%|██████▋   | 319/480 [07:10<03:14,  1.21s/it]

Input tokens 547, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  67%|██████▋   | 320/480 [07:11<02:56,  1.10s/it]

Input tokens 477, output tokens 21
classifications=['Décor & Pillows / Wall Décor / Wall Accents'] categories=['Décor & Pillows'] sub_categories=['Wall Décor'] cat_subcat=['Décor & Pillows / Wall Décor']
Décor & Pillows

Searching:  67%|██████▋   | 321/480 [07:12<03:01,  1.14s/it]

Input tokens 478, output tokens 16
classifications=['Storage & Organization / Shoe Storage / All Shoe Storage'] categories=['Storage & Organization'] sub_categories=['Shoe Storage'] cat_subcat=['Storage & Organization / Shoe Storage']
Storage & Organization

Searching:  67%|██████▋   | 322/480 [07:14<03:36,  1.37s/it]

Input tokens 481, output tokens 40
classifications=['Décor & Pillows / Wall Décor / Wall Accents', 'Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows'] categories=['Décor & Pillows'] sub_categories=['Wall Décor'] cat_subcat=['Décor & Pillows / Wall Décor']
Décor & Pillows

Searching:  67%|██████▋   | 323/480 [07:15<03:11,  1.22s/it]

Input tokens 471, output tokens 18
classifications=['Bed & Bath / Mattresses & Foundations / Queen Mattresses'] categories=['Bed & Bath'] sub_categories=['Mattresses & Foundations'] cat_subcat=['Bed & Bath / Mattresses & Foundations']
Bed & Bath

Searching:  68%|██████▊   | 324/480 [07:16<03:10,  1.22s/it]

Input tokens 534, output tokens 41
classifications=['Furniture / Kitchen & Dining Furniture / Kitchen Islands & Carts', 'Outdoor / Garden / Plant Stands & Accessories', 'Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs'] categories=['Furniture'] sub_categories=['Kitchen & Dining Furniture'] cat_subcat=['Furniture / Kitchen & Dining Furniture']
Furniture

Searching:  68%|██████▊   | 325/480 [07:17<02:50,  1.10s/it]

Input tokens 505, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  68%|██████▊   | 326/480 [07:18<02:43,  1.06s/it]

Input tokens 484, output tokens 24
classifications=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / All Bathroom Vanities'] categories=['Home Improvement'] sub_categories=['Bathroom Remodel & Bathroom Fixtures'] cat_subcat=['Home Improvement / Bathroom Remodel & Bathroom Fixtures']
Home Improvement

Searching:  68%|██████▊   | 327/480 [07:19<02:23,  1.07it/s]

Input tokens 496, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  68%|██████▊   | 328/480 [07:21<03:10,  1.25s/it]

Input tokens 510, output tokens 43
classifications=['Furniture / Living Room Furniture / TV Stands & Media Storage Furniture / TV Stands & Entertainment Centers', 'Furniture / Living Room Furniture / Coffee Tables & End Tables / End & Side Tables'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  69%|██████▊   | 329/480 [07:22<03:02,  1.21s/it]

Input tokens 460, output tokens 17
classifications=['Furniture / Bedroom Furniture / Dressers & Chests'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  69%|██████▉   | 330/480 [07:24<03:19,  1.33s/it]

Input tokens 481, output tokens 14
classifications=['Furniture / Living Room Furniture / Sofas'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  69%|██████▉   | 331/480 [07:25<03:28,  1.40s/it]

Input tokens 481, output tokens 20
classifications=['Outdoor / Outdoor & Patio Furniture / Patio Furniture Sets / Patio Conversation Sets'] categories=['Outdoor'] sub_categories=['Outdoor & Patio Furniture'] cat_subcat=['Outdoor / Outdoor & Patio Furniture']
Outdoor

Searching:  69%|██████▉   | 332/480 [07:26<03:07,  1.27s/it]

Input tokens 548, output tokens 19
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  69%|██████▉   | 333/480 [07:27<03:11,  1.30s/it]

Input tokens 481, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  70%|██████▉   | 334/480 [07:29<03:03,  1.26s/it]

Input tokens 488, output tokens 19
classifications=['Home Improvement / Hardware / Cabinet Hardware / Cabinet & Drawer Pulls'] categories=['Home Improvement'] sub_categories=['Hardware'] cat_subcat=['Home Improvement / Hardware']
Home Improvement

Searching:  70%|██████▉   | 335/480 [07:30<03:05,  1.28s/it]

Input tokens 517, output tokens 31
classifications=['Outdoor / Garden / Outdoor Animal Care / Wild Bird Care / Bird Feeders / Nyjer & Thistle Bird Feeders'] categories=['Outdoor'] sub_categories=['Garden'] cat_subcat=['Outdoor / Garden']
Outdoor

Searching:  70%|███████   | 336/480 [07:31<02:55,  1.22s/it]

Input tokens 514, output tokens 19
classifications=['Home Improvement / Hardware / Cabinet Hardware / Cabinet & Drawer Pulls'] categories=['Home Improvement'] sub_categories=['Hardware'] cat_subcat=['Home Improvement / Hardware']
Home Improvement

Searching:  70%|███████   | 337/480 [07:32<02:46,  1.17s/it]

Input tokens 524, output tokens 21
classifications=['Storage & Organization / Wall Shelving & Organization / Wall and Display Shelves'] categories=['Storage & Organization'] sub_categories=['Wall Shelving & Organization'] cat_subcat=['Storage & Organization / Wall Shelving & Organization']
Storage & Organization

Searching:  70%|███████   | 338/480 [07:33<02:45,  1.17s/it]

Input tokens 515, output tokens 21
classifications=['Furniture / Kitchen & Dining Furniture / Bar Furniture / Home Bars & Bar Sets'] categories=['Furniture'] sub_categories=['Kitchen & Dining Furniture'] cat_subcat=['Furniture / Kitchen & Dining Furniture']
Furniture

Searching:  71%|███████   | 339/480 [07:34<02:35,  1.10s/it]

Input tokens 502, output tokens 25
classifications=['Outdoor / Outdoor & Patio Furniture / Outdoor Seating & Patio Chairs / Patio Seating / Outdoor Club Chairs'] categories=['Outdoor'] sub_categories=['Outdoor & Patio Furniture'] cat_subcat=['Outdoor / Outdoor & Patio Furniture']
Outdoor

Searching:  71%|███████   | 340/480 [07:35<02:19,  1.00it/s]

Input tokens 462, output tokens 18
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Recliners'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  71%|███████   | 341/480 [07:36<02:24,  1.04s/it]

Input tokens 469, output tokens 14
classifications=['Outdoor / Outdoor Shades / Awnings'] categories=['Outdoor'] sub_categories=['Outdoor Shades'] cat_subcat=['Outdoor / Outdoor Shades']
Outdoor

Searching:  71%|███████▏  | 342/480 [07:41<05:22,  2.34s/it]

Input tokens 479, output tokens 22
classifications=['Furniture / Kitchen & Dining Furniture / Dining Tables & Seating / Kitchen & Dining Chairs'] categories=['Furniture'] sub_categories=['Kitchen & Dining Furniture'] cat_subcat=['Furniture / Kitchen & Dining Furniture']
Furniture

Searching:  71%|███████▏  | 343/480 [07:46<06:44,  2.96s/it]

Input tokens 452, output tokens 36
classifications=['Furniture / Bedroom Furniture / Beds & Headboards / Beds / Queen Size Beds', 'Furniture / Bedroom Furniture / Beds & Headboards / Beds / Twin Beds'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  72%|███████▏  | 344/480 [07:47<05:15,  2.32s/it]

Input tokens 504, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  72%|███████▏  | 345/480 [07:48<04:19,  1.92s/it]

Input tokens 457, output tokens 33
classifications=['Furniture / Bedroom Furniture / Beds & Headboards / Beds / Queen Size Beds', 'Furniture / Bedroom Furniture / Beds & Headboards / Beds'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  72%|███████▏  | 346/480 [07:49<03:43,  1.66s/it]

Input tokens 574, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  72%|███████▏  | 347/480 [07:49<02:59,  1.35s/it]

Input tokens 335, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  72%|███████▎  | 348/480 [07:50<02:47,  1.27s/it]

Input tokens 492, output tokens 14
classifications=['Lighting / Ceiling Fans / All Ceiling Fans'] categories=['Lighting'] sub_categories=['Ceiling Fans'] cat_subcat=['Lighting / Ceiling Fans']
Lighting

Searching:  73%|███████▎  | 349/480 [07:52<02:40,  1.22s/it]

Input tokens 440, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  73%|███████▎  | 350/480 [07:53<02:39,  1.22s/it]

Input tokens 558, output tokens 30
classifications=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Towel Storage / Towel Bars, Racks, and Stands'] categories=['Home Improvement'] sub_categories=['Bathroom Remodel & Bathroom Fixtures'] cat_subcat=['Home Improvement / Bathroom Remodel & Bathroom Fixtures']
Home Improvement

Searching:  73%|███████▎  | 351/480 [07:54<02:37,  1.22s/it]

Input tokens 469, output tokens 32
classifications=['Furniture / Kitchen & Dining Furniture / Bar Furniture / Bar Stools & Counter Stools / All Bar Stools & Counter Stools'] categories=['Furniture'] sub_categories=['Kitchen & Dining Furniture'] cat_subcat=['Furniture / Kitchen & Dining Furniture']
Furniture

Searching:  73%|███████▎  | 352/480 [08:00<05:25,  2.54s/it]

Input tokens 745, output tokens 37
classifications=['Kitchen & Tabletop / Cookware & Bakeware / Baking Sheets & Pans / Bread & Loaf Pans / Ceramic Bread & Loaf Pans'] categories=['Kitchen & Tabletop'] sub_categories=['Cookware & Bakeware'] cat_subcat=['Kitchen & Tabletop / Cookware & Bakeware']
Kitchen & Tabletop

Searching:  74%|███████▎  | 353/480 [08:01<04:29,  2.12s/it]

Input tokens 485, output tokens 16
classifications=['Furniture / Bedroom Furniture / Dressers & Chests'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  74%|███████▍  | 354/480 [08:02<03:46,  1.80s/it]

Input tokens 523, output tokens 20
classifications=['Décor & Pillows / Flowers & Plants / Faux Flowers'] categories=['Décor & Pillows'] sub_categories=['Flowers & Plants'] cat_subcat=['Décor & Pillows / Flowers & Plants']
Décor & Pillows

Searching:  74%|███████▍  | 355/480 [08:03<03:12,  1.54s/it]

Input tokens 522, output tokens 25
classifications=['Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables / Rectangle Coffee Tables'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  74%|███████▍  | 356/480 [08:04<02:46,  1.35s/it]

Input tokens 464, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  74%|███████▍  | 357/480 [08:06<03:14,  1.58s/it]

Input tokens 457, output tokens 70
classifications=['Storage & Organization / Closet Storage & Organization / Closet Accessories', 'Storage & Organization / Closet Storage & Organization / Hangers', 'Storage & Organization / Shoe Storage / All Shoe Storage', 'Storage & Organization / Shoe Storage / All Shoe Storage / Rack Shoe Storage', 'Storage & Organization / Shoe Storage / All Shoe Storage / Cabinet Shoe Storage'] categories=['Storage & Organization'] sub_categories=['Closet Storage & Organization'] cat_subcat=['Storage & Organization / Closet Storage & Organization']
Storage & Organization

Searching:  75%|███████▍  | 358/480 [08:07<02:59,  1.47s/it]

Input tokens 519, output tokens 18
classifications=['Rugs / Area Rugs', 'Rugs / Doormats'] categories=['Rugs'] sub_categories=['Area Rugs'] cat_subcat=['Rugs / Area Rugs']
Rugs

Searching:  75%|███████▍  | 359/480 [08:08<02:49,  1.40s/it]

Input tokens 476, output tokens 23
classifications=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / All Bathroom Vanities'] categories=['Home Improvement'] sub_categories=['Bathroom Remodel & Bathroom Fixtures'] cat_subcat=['Home Improvement / Bathroom Remodel & Bathroom Fixtures']
Home Improvement

Searching:  75%|███████▌  | 360/480 [08:09<02:24,  1.21s/it]

Input tokens 524, output tokens 23
classifications=['Décor & Pillows / Flowers & Plants / Faux Flowers / Orchid Faux Flowers'] categories=['Décor & Pillows'] sub_categories=['Flowers & Plants'] cat_subcat=['Décor & Pillows / Flowers & Plants']
Décor & Pillows

Searching:  75%|███████▌  | 361/480 [08:10<02:22,  1.19s/it]

Input tokens 497, output tokens 77
classifications=['Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows / Blue Throw Pillows', 'Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows / Black Throw Pillows', 'Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows / Green Throw Pillows'] categories=['Décor & Pillows'] sub_categories=['Decorative Pillows & Blankets'] cat_subcat=['Décor & Pillows / Decorative Pillows & Blankets']
Décor & Pillows

Searching:  75%|███████▌  | 362/480 [08:11<02:18,  1.18s/it]

Input tokens 478, output tokens 23
classifications=['Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows'] categories=['Décor & Pillows'] sub_categories=['Decorative Pillows & Blankets'] cat_subcat=['Décor & Pillows / Decorative Pillows & Blankets']
Décor & Pillows

Searching:  76%|███████▌  | 363/480 [08:12<02:13,  1.14s/it]

Input tokens 553, output tokens 51
classifications=['Décor & Pillows / Window Treatments / Curtains & Drapes', 'School Furniture and Supplies / School Boards & Technology / AV, Mounts & Tech Accessories / Electronic Mounts & Stands / Computer Mounts'] categories=['Décor & Pillows'] sub_categories=['Window Treatments'] cat_subcat=['Décor & Pillows / Window Treatments']
Décor & Pillows

Searching:  76%|███████▌  | 364/480 [08:13<02:01,  1.05s/it]

Input tokens 556, output tokens 33
classifications=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Toilets & Bidets / Toilet Paper Holders / Wall Mounted Toilet Paper Holders'] categories=['Home Improvement'] sub_categories=['Bathroom Remodel & Bathroom Fixtures'] cat_subcat=['Home Improvement / Bathroom Remodel & Bathroom Fixtures']
Home Improvement

Searching:  76%|███████▌  | 365/480 [08:14<02:03,  1.08s/it]

Input tokens 458, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  76%|███████▋  | 366/480 [08:15<01:58,  1.04s/it]

Input tokens 568, output tokens 29
classifications=['Kitchen & Tabletop / Small Kitchen Appliances / Pressure & Slow Cookers / Slow Cookers / Slow Slow Cookers'] categories=['Kitchen & Tabletop'] sub_categories=['Small Kitchen Appliances'] cat_subcat=['Kitchen & Tabletop / Small Kitchen Appliances']
Kitchen & Tabletop

Searching:  76%|███████▋  | 367/480 [08:17<02:12,  1.18s/it]

Input tokens 527, output tokens 19
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Recliners'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  77%|███████▋  | 368/480 [08:19<02:50,  1.52s/it]

Input tokens 505, output tokens 39
classifications=['Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables / Rectangle Coffee Tables', 'Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  77%|███████▋  | 369/480 [08:20<02:26,  1.32s/it]

Input tokens 513, output tokens 20
classifications=['Outdoor / Outdoor & Patio Furniture / Patio Furniture Sets / Patio Dining Sets'] categories=['Outdoor'] sub_categories=['Outdoor & Patio Furniture'] cat_subcat=['Outdoor / Outdoor & Patio Furniture']
Outdoor

Searching:  77%|███████▋  | 370/480 [08:21<02:21,  1.29s/it]

Input tokens 465, output tokens 35
classifications=['Décor & Pillows / Wall Décor / Wall Accents', 'Décor & Pillows / Home Accessories / Decorative Objects'] categories=['Décor & Pillows'] sub_categories=['Wall Décor'] cat_subcat=['Décor & Pillows / Wall Décor']
Décor & Pillows

Searching:  77%|███████▋  | 371/480 [08:22<02:05,  1.15s/it]

Input tokens 482, output tokens 34
classifications=['Baby & Kids / Toddler & Kids Bedroom Furniture / Kids Beds', 'Furniture / Bedroom Furniture / Beds & Headboards / Beds / Twin Beds'] categories=['Baby & Kids'] sub_categories=['Toddler & Kids Bedroom Furniture'] cat_subcat=['Baby & Kids / Toddler & Kids Bedroom Furniture']
Baby & Kids

Searching:  78%|███████▊  | 372/480 [08:23<02:02,  1.14s/it]

Input tokens 454, output tokens 17
classifications=['Furniture / Bedroom Furniture / Beds & Headboards / Beds'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  78%|███████▊  | 373/480 [08:24<01:54,  1.07s/it]

Input tokens 522, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  78%|███████▊  | 374/480 [08:25<01:53,  1.07s/it]

Input tokens 427, output tokens 27
classifications=['Lighting / Light Bulbs & Hardware / Light Bulbs / All Light Bulbs / LED Light Bulbs'] categories=['Lighting'] sub_categories=['Light Bulbs & Hardware'] cat_subcat=['Lighting / Light Bulbs & Hardware']
Lighting

Searching:  78%|███████▊  | 375/480 [08:29<03:33,  2.03s/it]

Input tokens 459, output tokens 17
classifications=['Furniture / Bedroom Furniture / Beds & Headboards / Beds'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  78%|███████▊  | 376/480 [08:33<04:10,  2.41s/it]

Input tokens 483, output tokens 26
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Chaise Lounge Chairs / Velvet Chaise Lounge Chairs'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  79%|███████▊  | 377/480 [08:33<03:16,  1.90s/it]

Input tokens 511, output tokens 13
classifications=['Furniture / Office Furniture / Office Chairs'] categories=['Furniture'] sub_categories=['Office Furniture'] cat_subcat=['Furniture / Office Furniture']
Furniture

Searching:  79%|███████▉  | 378/480 [08:34<02:45,  1.62s/it]

Input tokens 536, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  79%|███████▉  | 379/480 [08:36<02:52,  1.71s/it]

Input tokens 546, output tokens 25
classifications=['Outdoor / Outdoor & Patio Furniture / Outdoor Seating & Patio Chairs / Patio Seating / Outdoor Club Chairs'] categories=['Outdoor'] sub_categories=['Outdoor & Patio Furniture'] cat_subcat=['Outdoor / Outdoor & Patio Furniture']
Outdoor

Searching:  79%|███████▉  | 380/480 [08:38<03:08,  1.88s/it]

Input tokens 471, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  79%|███████▉  | 381/480 [08:40<02:42,  1.65s/it]

Input tokens 539, output tokens 25
classifications=['Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables / Rectangle Coffee Tables'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  80%|███████▉  | 382/480 [08:41<02:41,  1.65s/it]

Input tokens 517, output tokens 21
classifications=['Storage & Organization / Wall Shelving & Organization / Wall and Display Shelves'] categories=['Storage & Organization'] sub_categories=['Wall Shelving & Organization'] cat_subcat=['Storage & Organization / Wall Shelving & Organization']
Storage & Organization

Searching:  80%|███████▉  | 383/480 [08:42<02:18,  1.43s/it]

Input tokens 458, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  80%|████████  | 384/480 [08:43<02:09,  1.35s/it]

Input tokens 510, output tokens 22
classifications=['Furniture / Kitchen & Dining Furniture / Dining Tables & Seating / Kitchen & Dining Chairs'] categories=['Furniture'] sub_categories=['Kitchen & Dining Furniture'] cat_subcat=['Furniture / Kitchen & Dining Furniture']
Furniture

Searching:  80%|████████  | 385/480 [08:45<02:08,  1.35s/it]

Input tokens 565, output tokens 22
classifications=['Décor & Pillows / Art / All Wall Art / Brown Wall Art'] categories=['Décor & Pillows'] sub_categories=['Art'] cat_subcat=['Décor & Pillows / Art']
Décor & Pillows

Searching:  80%|████████  | 386/480 [08:46<01:53,  1.21s/it]

Input tokens 503, output tokens 14
classifications=['Furniture / Living Room Furniture / Sofas'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  81%|████████  | 387/480 [08:47<01:58,  1.27s/it]

Input tokens 453, output tokens 21
classifications=['Furniture / Bedroom Furniture / Beds & Headboards / Beds / Queen Size Beds'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  81%|████████  | 388/480 [08:48<01:41,  1.11s/it]

Input tokens 464, output tokens 11
classifications=['Rugs / Area Rugs'] categories=['Rugs'] sub_categories=['Area Rugs'] cat_subcat=['Rugs / Area Rugs']
Rugs

Searching:  81%|████████  | 389/480 [08:49<01:36,  1.06s/it]

Input tokens 518, output tokens 26
classifications=['Outdoor / Outdoor & Patio Furniture / Outdoor Seating & Patio Chairs / Patio Seating / Outdoor Club Chairs'] categories=['Outdoor'] sub_categories=['Outdoor & Patio Furniture'] cat_subcat=['Outdoor / Outdoor & Patio Furniture']
Outdoor

Searching:  81%|████████▏ | 390/480 [08:50<01:35,  1.06s/it]

Input tokens 481, output tokens 21
classifications=['Furniture / Office Furniture / Office Chairs', 'Furniture / Office Furniture / Desks'] categories=['Furniture'] sub_categories=['Office Furniture'] cat_subcat=['Furniture / Office Furniture']
Furniture

Searching:  81%|████████▏ | 391/480 [08:52<02:13,  1.50s/it]

Input tokens 581, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  82%|████████▏ | 392/480 [08:53<01:57,  1.33s/it]

Input tokens 526, output tokens 20
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Chaise Lounge Chairs'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  82%|████████▏ | 393/480 [08:57<02:53,  2.00s/it]

Input tokens 458, output tokens 28
classifications=['Lighting / Light Bulbs & Hardware / Light Bulbs / All Light Bulbs / LED Light Bulbs'] categories=['Lighting'] sub_categories=['Light Bulbs & Hardware'] cat_subcat=['Lighting / Light Bulbs & Hardware']
Lighting

Searching:  82%|████████▏ | 394/480 [08:58<02:26,  1.70s/it]

Input tokens 469, output tokens 34
classifications=['Furniture / Bedroom Furniture / Beds & Headboards / Beds', 'Furniture / Living Room Furniture / Coffee Tables & End Tables / End & Side Tables'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  82%|████████▏ | 395/480 [08:59<02:13,  1.57s/it]

Input tokens 526, output tokens 27
classifications=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Showers & Bathtubs / Shower & Bathtub Accessories'] categories=['Home Improvement'] sub_categories=['Bathroom Remodel & Bathroom Fixtures'] cat_subcat=['Home Improvement / Bathroom Remodel & Bathroom Fixtures']
Home Improvement

Searching:  82%|████████▎ | 396/480 [09:00<02:01,  1.45s/it]

Input tokens 479, output tokens 37
classifications=['Décor & Pillows / Wall Décor / Wall Accents', 'Décor & Pillows / Wall Décor / Wall Accents'] categories=['Décor & Pillows'] sub_categories=['Wall Décor'] cat_subcat=['Décor & Pillows / Wall Décor']
Décor & Pillows

Searching:  83%|████████▎ | 397/480 [09:01<01:50,  1.33s/it]

Input tokens 547, output tokens 18
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  83%|████████▎ | 398/480 [09:02<01:44,  1.27s/it]

Input tokens 496, output tokens 23
classifications=['Furniture / Living Room Furniture / Coffee Tables & End Tables / End & Side Tables'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  83%|████████▎ | 399/480 [09:03<01:40,  1.24s/it]

Input tokens 476, output tokens 39
classifications=['Furniture / Kitchen & Dining Furniture / Dining Tables & Seating / Kitchen & Dining Tables', 'Furniture / Kitchen & Dining Furniture / Dining Tables & Seating / Kitchen & Dining Chairs'] categories=['Furniture'] sub_categories=['Kitchen & Dining Furniture'] cat_subcat=['Furniture / Kitchen & Dining Furniture']
Furniture

Searching:  83%|████████▎ | 400/480 [09:05<01:43,  1.29s/it]

Input tokens 523, output tokens 15
classifications=['Lighting / Table & Floor Lamps / Table Lamps'] categories=['Lighting'] sub_categories=['Table & Floor Lamps'] cat_subcat=['Lighting / Table & Floor Lamps']
Lighting

Searching:  84%|████████▎ | 401/480 [09:07<02:08,  1.62s/it]

Input tokens 479, output tokens 38
classifications=['Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows', 'Décor & Pillows / Window Treatments / Curtains & Drapes'] categories=['Décor & Pillows'] sub_categories=['Decorative Pillows & Blankets'] cat_subcat=['Décor & Pillows / Decorative Pillows & Blankets']
Décor & Pillows

Searching:  84%|████████▍ | 402/480 [09:08<01:46,  1.37s/it]

Input tokens 499, output tokens 21
classifications=['Décor & Pillows / Window Treatments / Curtain Hardware & Accessories'] categories=['Décor & Pillows'] sub_categories=['Window Treatments'] cat_subcat=['Décor & Pillows / Window Treatments']
Décor & Pillows

Searching:  84%|████████▍ | 403/480 [09:09<01:42,  1.33s/it]

Input tokens 512, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  84%|████████▍ | 404/480 [09:10<01:34,  1.25s/it]

Input tokens 534, output tokens 14
classifications=['Furniture / Living Room Furniture / Console Tables'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  84%|████████▍ | 405/480 [09:11<01:30,  1.21s/it]

Input tokens 486, output tokens 20
classifications=['Storage & Organization / Storage Containers & Drawers / All Storage Containers'] categories=['Storage & Organization'] sub_categories=['Storage Containers & Drawers'] cat_subcat=['Storage & Organization / Storage Containers & Drawers']
Storage & Organization

Searching:  85%|████████▍ | 406/480 [09:13<01:27,  1.18s/it]

Input tokens 516, output tokens 20
classifications=['Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  85%|████████▍ | 407/480 [09:14<01:24,  1.16s/it]

Input tokens 554, output tokens 41
classifications=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / All Bathroom Vanities', 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / Vanity Bases'] categories=['Home Improvement'] sub_categories=['Bathroom Remodel & Bathroom Fixtures'] cat_subcat=['Home Improvement / Bathroom Remodel & Bathroom Fixtures']
Home Improvement

Searching:  85%|████████▌ | 408/480 [09:15<01:20,  1.11s/it]

Input tokens 465, output tokens 24
classifications=['Storage & Organization / Garage & Outdoor Storage & Organization / Storage Racks & Shelving Units'] categories=['Storage & Organization'] sub_categories=['Garage & Outdoor Storage & Organization'] cat_subcat=['Storage & Organization / Garage & Outdoor Storage & Organization']
Storage & Organization

Searching:  85%|████████▌ | 409/480 [09:16<01:28,  1.25s/it]

Input tokens 498, output tokens 33
classifications=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Towel Storage / Towel & Robe Hooks / Black Towel & Robe Hooks'] categories=['Home Improvement'] sub_categories=['Bathroom Remodel & Bathroom Fixtures'] cat_subcat=['Home Improvement / Bathroom Remodel & Bathroom Fixtures']
Home Improvement

Searching:  85%|████████▌ | 410/480 [09:17<01:20,  1.16s/it]

Input tokens 482, output tokens 16
classifications=['Furniture / Bedroom Furniture / Dressers & Chests'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  86%|████████▌ | 411/480 [09:18<01:19,  1.15s/it]

Input tokens 510, output tokens 30
classifications=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / All Bathroom Vanities / Modern & Contemporary Bathroom Vanities'] categories=['Home Improvement'] sub_categories=['Bathroom Remodel & Bathroom Fixtures'] cat_subcat=['Home Improvement / Bathroom Remodel & Bathroom Fixtures']
Home Improvement

Searching:  86%|████████▌ | 412/480 [09:20<01:24,  1.25s/it]

Input tokens 481, output tokens 32
classifications=['Furniture / Kitchen & Dining Furniture / Bar Furniture / Bar Stools & Counter Stools / All Bar Stools & Counter Stools'] categories=['Furniture'] sub_categories=['Kitchen & Dining Furniture'] cat_subcat=['Furniture / Kitchen & Dining Furniture']
Furniture

Searching:  86%|████████▌ | 413/480 [09:21<01:18,  1.17s/it]

Input tokens 574, output tokens 28
classifications=['Home Improvement / Flooring, Walls & Ceiling / Floor Tiles & Wall Tiles / Natural Stone Floor Tiles & Wall Tiles'] categories=['Home Improvement'] sub_categories=['Flooring, Walls & Ceiling'] cat_subcat=['Home Improvement / Flooring, Walls & Ceiling']
Home Improvement

Searching:  86%|████████▋ | 414/480 [09:21<01:06,  1.01s/it]

Input tokens 460, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  86%|████████▋ | 415/480 [09:23<01:09,  1.07s/it]

Input tokens 519, output tokens 22
classifications=['Furniture / Kitchen & Dining Furniture / Dining Tables & Seating / Kitchen & Dining Tables'] categories=['Furniture'] sub_categories=['Kitchen & Dining Furniture'] cat_subcat=['Furniture / Kitchen & Dining Furniture']
Furniture

Searching:  87%|████████▋ | 416/480 [09:24<01:06,  1.04s/it]

Input tokens 456, output tokens 36
classifications=['Furniture / Bedroom Furniture / Beds & Headboards / Beds / Queen Size Beds', 'Furniture / Living Room Furniture / Ottomans & Poufs'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  87%|████████▋ | 417/480 [09:24<01:01,  1.02it/s]

Input tokens 437, output tokens 16
classifications=['Furniture / Bedroom Furniture / Armoires & Wardrobes'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  87%|████████▋ | 418/480 [09:26<01:03,  1.02s/it]

Input tokens 518, output tokens 24
classifications=['Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables / Rectangle Coffee Tables'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  87%|████████▋ | 419/480 [09:27<01:02,  1.03s/it]

Input tokens 508, output tokens 40
classifications=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / All Bathroom Vanities', 'Storage & Organization / Bathroom Storage & Organization / Bathroom Cabinets & Shelving'] categories=['Home Improvement'] sub_categories=['Bathroom Remodel & Bathroom Fixtures'] cat_subcat=['Home Improvement / Bathroom Remodel & Bathroom Fixtures']
Home Improvement

Searching:  88%|████████▊ | 420/480 [09:28<01:00,  1.01s/it]

Input tokens 502, output tokens 23
classifications=['Outdoor / Outdoor Shades / Outdoor Umbrellas / Patio Umbrella Stands & Bases'] categories=['Outdoor'] sub_categories=['Outdoor Shades'] cat_subcat=['Outdoor / Outdoor Shades']
Outdoor

Searching:  88%|████████▊ | 421/480 [09:29<00:59,  1.00s/it]

Input tokens 494, output tokens 19
classifications=['Décor & Pillows / Home Accessories / Decorative Objects'] categories=['Décor & Pillows'] sub_categories=['Home Accessories'] cat_subcat=['Décor & Pillows / Home Accessories']
Décor & Pillows

Searching:  88%|████████▊ | 422/480 [09:30<00:57,  1.01it/s]

Input tokens 554, output tokens 42
classifications=['Décor & Pillows / Wall Décor / Wall Accents', 'Outdoor / Outdoor & Patio Furniture / Outdoor Seating & Patio Chairs / Patio Seating / Outdoor Club Chairs'] categories=['Décor & Pillows'] sub_categories=['Wall Décor'] cat_subcat=['Décor & Pillows / Wall Décor']
Décor & Pillows

Searching:  88%|████████▊ | 423/480 [09:33<01:42,  1.80s/it]

Input tokens 484, output tokens 65
classifications=['Furniture / Living Room Furniture / Bookcases / 2 Shelf Bookcases', 'Furniture / Living Room Furniture / Bookcases / 3 Shelf Bookcases', 'Furniture / Living Room Furniture / Bookcases / 4 Shelf Bookcases', 'Furniture / Living Room Furniture / Bookcases / 5 Shelf Bookcases'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  88%|████████▊ | 424/480 [09:34<01:28,  1.58s/it]

Input tokens 515, output tokens 18
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  89%|████████▊ | 425/480 [09:36<01:21,  1.48s/it]

Input tokens 557, output tokens 25
classifications=['Appliances / Washers & Dryers / Dryers / All Dryers / Gas Dryers'] categories=['Appliances'] sub_categories=['Washers & Dryers'] cat_subcat=['Appliances / Washers & Dryers']
Appliances

Searching:  89%|████████▉ | 426/480 [09:37<01:11,  1.33s/it]

Input tokens 514, output tokens 47
classifications=['Furniture / Kitchen & Dining Furniture / Bar Furniture / Bar Stools & Counter Stools / All Bar Stools & Counter Stools', 'Outdoor / Outdoor & Patio Furniture / Patio Furniture Sets / Patio Dining Sets'] categories=['Furniture'] sub_categories=['Kitchen & Dining Furniture'] cat_subcat=['Furniture / Kitchen & Dining Furniture']
Furniture

Searching:  89%|████████▉ | 427/480 [09:37<01:02,  1.18s/it]

Input tokens 615, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  89%|████████▉ | 428/480 [09:38<00:59,  1.14s/it]

Input tokens 485, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  89%|████████▉ | 429/480 [09:39<00:52,  1.03s/it]

Input tokens 472, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  90%|████████▉ | 430/480 [09:40<00:50,  1.01s/it]

Input tokens 478, output tokens 15
classifications=['Furniture / Living Room Furniture / Bookcases'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  90%|████████▉ | 431/480 [09:43<01:11,  1.46s/it]

Input tokens 480, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  90%|█████████ | 432/480 [09:44<01:05,  1.37s/it]

Input tokens 481, output tokens 20
classifications=['Décor & Pillows / Window Treatments / Curtains & Drapes'] categories=['Décor & Pillows'] sub_categories=['Window Treatments'] cat_subcat=['Décor & Pillows / Window Treatments']
Décor & Pillows

Searching:  90%|█████████ | 433/480 [09:45<01:01,  1.32s/it]

Input tokens 511, output tokens 53
classifications=['Storage & Organization / Storage Containers & Drawers / All Storage Containers', 'Storage & Organization / Bathroom Storage & Organization / Bathroom Cabinets & Shelving', 'Storage & Organization / Garage & Outdoor Storage & Organization / Storage Racks & Shelving Units'] categories=['Storage & Organization'] sub_categories=['Storage Containers & Drawers'] cat_subcat=['Storage & Organization / Storage Containers & Drawers']
Storage & Organization

Searching:  90%|█████████ | 434/480 [09:46<00:58,  1.26s/it]

Input tokens 593, output tokens 21
classifications=['Décor & Pillows / Window Treatments / Curtains & Drapes'] categories=['Décor & Pillows'] sub_categories=['Window Treatments'] cat_subcat=['Décor & Pillows / Window Treatments']
Décor & Pillows

Searching:  91%|█████████ | 435/480 [09:47<00:53,  1.18s/it]

Input tokens 468, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  91%|█████████ | 436/480 [09:50<01:15,  1.71s/it]

Input tokens 553, output tokens 26
classifications=['Furniture / Living Room Furniture / TV Stands & Media Storage Furniture / TV Stands & Entertainment Centers'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  91%|█████████ | 437/480 [09:51<01:01,  1.44s/it]

Input tokens 481, output tokens 18
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  91%|█████████▏| 438/480 [09:53<01:15,  1.79s/it]

Input tokens 515, output tokens 16
classifications=['Outdoor / Garden / Planters / Plastic Planters'] categories=['Outdoor'] sub_categories=['Garden'] cat_subcat=['Outdoor / Garden']
Outdoor

Searching:  91%|█████████▏| 439/480 [09:55<01:06,  1.63s/it]

Input tokens 503, output tokens 19
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Recliners'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  92%|█████████▏| 440/480 [09:55<00:54,  1.37s/it]

Input tokens 489, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  92%|█████████▏| 441/480 [09:56<00:46,  1.20s/it]

Input tokens 473, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  92%|█████████▏| 442/480 [09:57<00:42,  1.12s/it]

Input tokens 587, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  92%|█████████▏| 443/480 [09:59<00:51,  1.38s/it]

Input tokens 466, output tokens 20
classifications=['Lighting / Ceiling Lights / Chandeliers / Candle-Style Chandeliers'] categories=['Lighting'] sub_categories=['Ceiling Lights'] cat_subcat=['Lighting / Ceiling Lights']
Lighting

Searching:  92%|█████████▎| 444/480 [10:01<00:56,  1.58s/it]

Input tokens 522, output tokens 15
classifications=['Lighting / Table & Floor Lamps / Table Lamps'] categories=['Lighting'] sub_categories=['Table & Floor Lamps'] cat_subcat=['Lighting / Table & Floor Lamps']
Lighting

Searching:  93%|█████████▎| 445/480 [10:02<00:47,  1.36s/it]

Input tokens 476, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  93%|█████████▎| 446/480 [10:04<00:47,  1.40s/it]

Input tokens 577, output tokens 33
classifications=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Sinks & Faucet Components / Bathroom Sink Faucets / Single Hole Bathroom Sink Faucets'] categories=['Home Improvement'] sub_categories=['Bathroom Remodel & Bathroom Fixtures'] cat_subcat=['Home Improvement / Bathroom Remodel & Bathroom Fixtures']
Home Improvement

Searching:  93%|█████████▎| 447/480 [10:05<00:46,  1.39s/it]

Input tokens 443, output tokens 21
classifications=['Furniture / Bedroom Furniture / Beds & Headboards / Beds / Twin Beds'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  93%|█████████▎| 448/480 [10:06<00:40,  1.27s/it]

Input tokens 493, output tokens 31
classifications=['Décor & Pillows / Window Treatments / Curtains & Drapes / 63 Inch and Less Curtains & Drapes'] categories=['Décor & Pillows'] sub_categories=['Window Treatments'] cat_subcat=['Décor & Pillows / Window Treatments']
Décor & Pillows

Searching:  94%|█████████▎| 449/480 [10:07<00:37,  1.21s/it]

Input tokens 492, output tokens 47
classifications=['Lighting / Outdoor Lighting / Outdoor Wall Lighting', 'Lighting / Outdoor Lighting / Outdoor Lanterns & Lamps', 'Décor & Pillows / Candles & Holders / Candle Holders / Lantern Candle Holders'] categories=['Lighting'] sub_categories=['Outdoor Lighting'] cat_subcat=['Lighting / Outdoor Lighting']
Lighting

Searching:  94%|█████████▍| 450/480 [10:08<00:37,  1.24s/it]

Input tokens 519, output tokens 31
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs', 'Furniture / Living Room Furniture / Chairs & Seating / Recliners'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  94%|█████████▍| 451/480 [10:09<00:32,  1.12s/it]

Input tokens 483, output tokens 17
classifications=['Furniture / Office Furniture / Desks / Writing Desks'] categories=['Furniture'] sub_categories=['Office Furniture'] cat_subcat=['Furniture / Office Furniture']
Furniture

Searching:  94%|█████████▍| 452/480 [10:11<00:33,  1.20s/it]

Input tokens 480, output tokens 67
classifications=['Furniture / Living Room Furniture / Sofas', 'Furniture / Living Room Furniture / Chairs & Seating / Recliners', 'Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables', 'Furniture / Living Room Furniture / TV Stands & Media Storage Furniture / TV Stands & Entertainment Centers'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  94%|█████████▍| 453/480 [10:11<00:29,  1.08s/it]

Input tokens 500, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  95%|█████████▍| 454/480 [10:12<00:27,  1.05s/it]

Input tokens 485, output tokens 17
classifications=['Furniture / Office Furniture / Desks / Writing Desks'] categories=['Furniture'] sub_categories=['Office Furniture'] cat_subcat=['Furniture / Office Furniture']
Furniture

Searching:  95%|█████████▍| 455/480 [10:14<00:30,  1.20s/it]

Input tokens 499, output tokens 44
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Recliners', 'Furniture / Living Room Furniture / Ottomans & Poufs', 'Furniture / Living Room Furniture / Chairs & Seating / Benches'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  95%|█████████▌| 456/480 [10:15<00:27,  1.14s/it]

Input tokens 476, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  95%|█████████▌| 457/480 [10:18<00:38,  1.69s/it]

Input tokens 502, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  95%|█████████▌| 458/480 [10:19<00:31,  1.45s/it]

Input tokens 464, output tokens 13
classifications=['Lighting / Ceiling Lights / Chandeliers'] categories=['Lighting'] sub_categories=['Ceiling Lights'] cat_subcat=['Lighting / Ceiling Lights']
Lighting

Searching:  96%|█████████▌| 459/480 [10:20<00:27,  1.29s/it]

Input tokens 501, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  96%|█████████▌| 460/480 [10:20<00:22,  1.12s/it]

Input tokens 470, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  96%|█████████▌| 461/480 [10:23<00:30,  1.63s/it]

Input tokens 523, output tokens 26
classifications=['Furniture / Living Room Furniture / TV Stands & Media Storage Furniture / TV Stands & Entertainment Centers'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  96%|█████████▋| 462/480 [10:24<00:25,  1.40s/it]

Input tokens 528, output tokens 37
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs', 'Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs / Arm Accent Chairs'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  96%|█████████▋| 463/480 [10:26<00:26,  1.57s/it]

Input tokens 575, output tokens 24
classifications=['Home Improvement / Kitchen Remodel & Kitchen Fixtures / Smoke Detectors / Portable Smoke Detectors'] categories=['Home Improvement'] sub_categories=['Kitchen Remodel & Kitchen Fixtures'] cat_subcat=['Home Improvement / Kitchen Remodel & Kitchen Fixtures']
Home Improvement

Searching:  97%|█████████▋| 464/480 [10:27<00:23,  1.49s/it]

Input tokens 532, output tokens 39
classifications=['Holiday Décor / Christmas / Christmas Trees / All Christmas Trees', 'Holiday Décor / Christmas / Christmas Tree Decorations / Christmas Ornaments / All Christmas Ornaments'] categories=['Holiday Décor'] sub_categories=['Christmas'] cat_subcat=['Holiday Décor / Christmas']
Holiday Décor

Searching:  97%|█████████▋| 465/480 [10:29<00:21,  1.40s/it]

Input tokens 454, output tokens 13
classifications=['Lighting / Ceiling Lights / Chandeliers'] categories=['Lighting'] sub_categories=['Ceiling Lights'] cat_subcat=['Lighting / Ceiling Lights']
Lighting

Searching:  97%|█████████▋| 466/480 [10:30<00:18,  1.34s/it]

Input tokens 511, output tokens 19
classifications=['Furniture / Living Room Furniture / Sectionals / Modular Sectionals'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  97%|█████████▋| 467/480 [10:31<00:18,  1.41s/it]

Input tokens 490, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  98%|█████████▊| 468/480 [10:32<00:14,  1.22s/it]

Input tokens 551, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  98%|█████████▊| 469/480 [10:33<00:12,  1.14s/it]

Input tokens 452, output tokens 34
classifications=['Baby & Kids / Toddler & Kids Bedroom Furniture / Kids Beds', 'Furniture / Bedroom Furniture / Beds & Headboards / Beds / Twin Beds'] categories=['Baby & Kids'] sub_categories=['Toddler & Kids Bedroom Furniture'] cat_subcat=['Baby & Kids / Toddler & Kids Bedroom Furniture']
Baby & Kids

Searching:  98%|█████████▊| 470/480 [10:37<00:18,  1.88s/it]

Input tokens 520, output tokens 36
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs', 'Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  98%|█████████▊| 471/480 [10:38<00:15,  1.70s/it]

Input tokens 477, output tokens 17
classifications=['Furniture / Bedroom Furniture / Beds & Headboards / Beds'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching:  98%|█████████▊| 472/480 [10:39<00:12,  1.60s/it]

Input tokens 492, output tokens 46
classifications=['Storage & Organization / Garage & Outdoor Storage & Organization / Bike & Sport Racks', 'Home Improvement / Flooring, Walls & Ceiling / Floor Tiles & Wall Tiles / Glass Floor Tiles & Wall Tiles'] categories=['Storage & Organization'] sub_categories=['Garage & Outdoor Storage & Organization'] cat_subcat=['Storage & Organization / Garage & Outdoor Storage & Organization']
Storage & Organization

Searching:  99%|█████████▊| 473/480 [10:40<00:09,  1.34s/it]

Input tokens 481, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching:  99%|█████████▉| 474/480 [10:41<00:07,  1.25s/it]

Input tokens 508, output tokens 18
classifications=['Furniture / Living Room Furniture / Chairs & Seating / Recliners'] categories=['Furniture'] sub_categories=['Living Room Furniture'] cat_subcat=['Furniture / Living Room Furniture']
Furniture

Searching:  99%|█████████▉| 475/480 [10:42<00:05,  1.09s/it]

Input tokens 468, output tokens 17
classifications=['Baby & Kids / Nursery Bedding / Crib Bedding Sets'] categories=['Baby & Kids'] sub_categories=['Nursery Bedding'] cat_subcat=['Baby & Kids / Nursery Bedding']
Baby & Kids

Searching:  99%|█████████▉| 476/480 [10:43<00:04,  1.08s/it]

Input tokens 452, output tokens 14
classifications=['Bed & Bath / Bedding / All Bedding'] categories=['Bed & Bath'] sub_categories=['Bedding'] cat_subcat=['Bed & Bath / Bedding']
Bed & Bath

Searching:  99%|█████████▉| 477/480 [10:44<00:03,  1.02s/it]

Input tokens 455, output tokens 17
classifications=['Furniture / Office Furniture / Desks / Writing Desks'] categories=['Furniture'] sub_categories=['Office Furniture'] cat_subcat=['Furniture / Office Furniture']
Furniture

Searching: 100%|█████████▉| 478/480 [10:45<00:02,  1.06s/it]

Input tokens 503, output tokens 12
classifications=['Rugs / Area Rugs'] categories=['Rugs'] sub_categories=['Area Rugs'] cat_subcat=['Rugs / Area Rugs']
Rugs

Searching: 100%|█████████▉| 479/480 [10:46<00:01,  1.10s/it]

Input tokens 471, output tokens 17
classifications=['Furniture / Bedroom Furniture / Beds & Headboards / Beds'] categories=['Furniture'] sub_categories=['Bedroom Furniture'] cat_subcat=['Furniture / Bedroom Furniture']
Furniture

Searching: 100%|██████████| 480/480 [10:47<00:00,  1.02it/s]

Input tokens 576, output tokens 5
classifications=[] categories=[] sub_categories=[] cat_subcat=[]

Searching: 100%|██████████| 480/480 [10:48<00:00,  1.35s/it]

,product_id,product_name,product_class,category hierarchy,product_description,product_features,rating_count,average_rating,review_count,features,...,score,query,query_id,rank,grade,discounted_gain,idcg,dcg,ndcg,mrr
0,26644,international harvester melamine serving tray,Serving Dishes & Platters|Licensed Products,Kitchen & Tabletop / Tableware & Drinkware / S...,this case ih serving tray is a perfect additio...,overalllength-endtoend:11.5|pattern : no patte...,NaN,NaN,NaN,"[overalllength-endtoend:11.5, pattern : no pat...",...,69.232885,certified international melamine,73,1,1.0,1.000000,8.786905,2.828968,0.321953,0.0
1,9709,certified international gather oval baking dish,NaN,Kitchen & Tabletop / Cookware & Bakeware / Bak...,simple crockery with the look of hand-thrown p...,overalllength-endtoend:14.25|productcare : dis...,2.0,5.0,1.0,"[overalllength-endtoend:14.25, productcare : d...",...,62.629265,certified international melamine,73,2,1.0,0.500000,8.786905,2.828968,0.321953,0.0
2,26646,international harvester melamine cereal bowl,Dining Bowls|Licensed Products,Kitchen & Tabletop / Tableware & Drinkware / D...,this four pack of cereal or soup bowls feature...,color : red/white|productcare : dishwasher saf...,NaN,NaN,NaN,"[color : red/white, productcare : dishwasher s...",...,57.511242,certified international melamine,73,3,1.0,0.333333,8.786905,2.828968,0.321953,0.0
3,9707,certified international piazzette 3d villa sal...,Salt And Pepper Shakers / Grinders (Mills),Kitchen & Tabletop / Tableware & Drinkware / S...,,productweight:1.5|trend : novelty|productcare ...,15.0,5.0,12.0,"[productweight:1.5, trend : novelty, productca...",...,52.439243,certified international melamine,73,4,1.0,0.250000,8.786905,2.828968,0.321953,0.0
4,26645,international harvester melamine chip and dip ...,Serving Dishes & Platters|Licensed Products,Kitchen & Tabletop / Tableware & Drinkware / S...,"perfect for the case ih enthusiast , serve you...",producttype : chips and dip platter|overallwid...,NaN,NaN,NaN,"[producttype : chips and dip platter, overallw...",...,50.514072,certified international melamine,73,5,1.0,0.200000,8.786905,2.828968,0.321953,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4795,2207,flamingo magnet wall décor,Wall Décor,Sale / Closeout / Wall Accents / Blue Wall Acc...,this beautifully handcrafted flamingo wooden d...,productcare : wipe clean with a dry cloth . do...,NaN,NaN,NaN,[productcare : wipe clean with a dry cloth . d...,...,50.694689,flamingo,102,6,2.0,0.500000,8.786905,8.786905,1.000000,1.0
4796,17391,rondon a pink flamingo paper print,Kids Wall Décor,Baby & Kids / Baby & Kids Décor & Lighting / A...,perfect for the nursery or a little girl 's be...,gender : girl / woman+|primarymaterialdetails ...,1.0,5.0,1.0,"[gender : girl / woman+, primarymaterialdetail...",...,48.986856,flamingo,102,7,2.0,0.428571,8.786905,8.786905,1.000000,1.0
4797,3267,flamingos green by cat coquillette - print,Wall Art,Décor & Pillows / Art / All Wall Art / Green W...,showcasing a pair of flamingos encircled by ve...,holidayoccasion : no holiday|shape : square|co...,1.0,4.0,1.0,"[holidayoccasion : no holiday, shape : square,...",...,48.481298,flamingo,102,8,2.0,0.375000,8.786905,8.786905,1.000000,1.0
4798,13948,cervantes whimsical flamingo & pineapple micro...,Sheets And Sheet Sets,Bed & Bath / Bedding / Sheets & Pillowcases,a great whimsical print of flamingo and pineap...,fittedsheetlength-headtotoe:80|flatsheetwidth-...,12.0,5.0,11.0,"[fittedsheetlength-headtotoe:80, flatsheetwidt...",...,45.647358,flamingo,102,9,2.0,0.333333,8.786905,8.786905,1.000000,1.0
4799,2777,flamingo- unframed print on canvas,Wall Art,Décor & Pillows / Art / All Wall Art,bay isle home 15 '' x30 '' flamingo i & ii set...,foodbeverage : not food & beverage|orientation...,NaN,NaN,NaN,"[foodbeverage : not food & beverage, orientati...",...,45.176806,flamingo,102,10,2.0,0.300000,8.786905,8.786905,1.000000,1.0

### Analyze results

We note:
1. NDCG down a bit from earlier
2. Though fewer queries have been harmed

In [ ]:
from cheat_at_search.search import graded_bm25

ndcgs(graded_bm25).mean(), ndcgs(graded_categorized).mean()

(np.float64(0.5411098691836396), np.float64(0.5506616086347829))

In [ ]:
deltas = ndcg_delta(graded_categorized, graded_bm25)
deltas

query
drum picture                  0.506435
bathroom vanity knobs         0.486519
non slip shower floor tile    0.477081
outdoor lounge chair          0.456442
modern outdoor furniture      0.365533
                                ...
sugar canister               -0.224721
outdoor privacy wall         -0.345075
outdoor lounge cushions      -0.471391
above toilet cabinet         -0.665763
dining table vinyl cloth     -0.745427
Name: ndcg, Length: 181, dtype: float64

In [ ]:
sig_improved = len(deltas[deltas > 0.1])
print(f"Num Significatly Improved: {sig_improved}")
deltas[deltas > 0.1]

Num Significatly Improved: 33

query
drum picture                                                       0.506435
bathroom vanity knobs                                              0.486519
non slip shower floor tile                                         0.477081
outdoor lounge chair                                               0.456442
modern outdoor furniture                                           0.365533
twin bed frame                                                     0.359391
desk for kids                                                      0.344262
outdoor light fixtures                                             0.320553
turquoise chair                                                    0.310979
accent leather chair                                               0.248882
storage dresser                                                    0.236147
hardwood beds                                                      0.235334
wooden chair outdoor                                               0.200063
china clock                                                        0.189044
beds that have leds                                                0.186289
family lamp                                                        0.178612
dark gray dresser                                                  0.175902
bathroom lighting                                                  0.167547
teal chair                                                         0.164251
carpet 5x6                                                         0.158831
town & country living curtains                                     0.154089
driftwood mirror                                                   0.151199
acrylic clear chair                                                0.142257
bedroom wall decor floral, multicolored with some teal (prints)    0.136883
light and navy blue decorative pillow                              0.124690
auburn throw pillows                                               0.122341
medium size chandelier                                             0.119812
small wardrobe grey                                                0.113806
pantry grey                                                        0.111773
industrial pipe dining  table                                      0.110419
podium with locking cabinet                                        0.106535
midcentury tv unit                                                 0.102425
floating bed                                                       0.101928
Name: ndcg, dtype: float64

In [ ]:
sig_harmed = len(deltas[deltas < -0.1])
print(f"Num Significatly Harmed: {sig_harmed}")
print(f"Prop improved/harmed: {sig_improved / (sig_harmed + sig_improved)} | {sig_harmed / (sig_harmed + sig_improved)}")
deltas[deltas < -0.1]

Num Significatly Harmed: 14
Prop improved/harmed: 0.7021276595744681 | 0.2978723404255319

query
zodiac pillow                    -0.113806
papasan chair frame only         -0.123290
3/4 size mattress                -0.128031
bathroom freestanding cabinet    -0.155670
tall storage cabinet             -0.158063
adjustable height artist stool   -0.170709
wall design shelf                -0.187825
chair pillow cushion             -0.190625
sheffield home bath set          -0.219708
sugar canister                   -0.224721
outdoor privacy wall             -0.345075
outdoor lounge cushions          -0.471391
above toilet cabinet             -0.665763
dining table vinyl cloth         -0.745427
Name: ndcg, dtype: float64

### Analyze a query

Let's look at a negative query to see how its harmed.

In [ ]:
QUERY = "chair pillow cushion"
graded_bm25[graded_bm25['query'] == QUERY][['product_name', 'product_description', 'category hierarchy', 'grade']]

,product_name,product_description,category hierarchy,grade
4660,replacement pillows outdoor lounge chair cushion,this replacement pillows outdoor lounge chair ...,NaN,2.0
4661,indoor/outdoor dining chair cushion and pillow...,go bold and spicy with a fun geometric print o...,Outdoor / Outdoor Décor / Outdoor Pillows & Cu...,2.0
4662,abbottsmoor dining chair cushion,the dining chair cushion ( set of 4 ) is apt f...,NaN,2.0
4663,zipparoll indoor chair cushion,zips from round pillow to flat pillow . the zi...,Kitchen & Tabletop / Tableware & Drinkware / T...,2.0
4664,indoor chair cushion,brighten your indoor seating area with this se...,NaN,2.0
4665,chair pad cushion,are your dining chair ’ s feeling a little sti...,NaN,2.0
4666,chair indoor seat cushion,add a splash of vibrant color and radiant styl...,NaN,2.0
4667,chair outdoor seat cushion,add a splash of vibrant color and radiant styl...,NaN,2.0
4668,dining chair cushion,add a splash of personality and create a cozy ...,Kitchen & Tabletop / Tableware & Drinkware / T...,2.0
4669,tropical outdoor lounge chair cushion,enhance your outdoor space with the addition o...,NaN,2.0

In [ ]:
graded_categorized[graded_categorized['query'] == QUERY][['product_name', 'product_description', 'category hierarchy', 'grade']]

,product_name,product_description,category hierarchy,grade
4690,replacement pillows outdoor lounge chair cushion,this replacement pillows outdoor lounge chair ...,NaN,2.0
4691,indoor/outdoor dining chair cushion and pillow...,go bold and spicy with a fun geometric print o...,Outdoor / Outdoor Décor / Outdoor Pillows & Cu...,2.0
4692,julep cushioned stackable chair,this stylish & playful chair was created by aw...,School Furniture and Supplies / School Furnitu...,0.0
4693,hard tufted vinyl chiavari chair cushion,hard cushions are the most popular choice in t...,Furniture / Office Furniture / Office Chair Ac...,2.0
4694,abbottsmoor dining chair cushion,the dining chair cushion ( set of 4 ) is apt f...,NaN,2.0
4695,zipparoll indoor chair cushion,zips from round pillow to flat pillow . the zi...,Kitchen & Tabletop / Tableware & Drinkware / T...,2.0
4696,indoor chair cushion,brighten your indoor seating area with this se...,NaN,2.0
4697,rotan 32 '' wide down cushion wingback chair,perfect for rounding out a living room seating...,Furniture / Living Room Furniture / Chairs & S...,0.0
4698,creative office chair pillow plush back seat c...,"the product is full filling , not afraid of ex...",Furniture / Office Furniture / Office Chair Ac...,2.0
4699,clarissa twin 32 '' wide pillow back futon chair,this convertible chair is ideal for small livi...,Furniture / Living Room Furniture / Chairs & S...,0.0