<a href="https://colab.research.google.com/github/msankar/cheat-at-search/blob/main/2d_Query_Categories_Hypothetical_Categorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Query -> Hypothetical Classification -> Real Classification

<small>
(from <a href="http://maven.com/softwaredoug/cheat-at-search">Cheat at Search with LLMs</a> training course by Doug Turnbull.)
</small>

We previously constrained the LLM to a set of outputs using `Literal` what if we just ask the LLM to return a fake classification that looks like one of ours. Then we use an embedding to resolve to the "real" entity.

We can do this when we have a large-ish set of labels (brands, etc) to do a kind of large multi-label classification

**Refinement** -- Let the model hallucinate a classification, then do an embedding lookup to get a real classification

## Boilerplate

Install deps, mount GDrive, prompt for your OpenAI Key (placed in your GDrive)

In [ ]:
!pip install git+https://github.com/softwaredoug/cheat-at-search.git
from cheat_at_search.data_dir import mount
mount(use_gdrive=True)
from cheat_at_search.search import run_strategy, graded_bm25, ndcgs, ndcg_delta
from cheat_at_search.wands_data import corpus, judgments

CAT_SEP = "/"

corpus

Collecting git+https://github.com/softwaredoug/cheat-at-search.git
  Cloning https://github.com/softwaredoug/cheat-at-search.git to /tmp/pip-req-build-sywndz8h
  Running command git clone --filter=blob:none --quiet https://github.com/softwaredoug/cheat-at-search.git /tmp/pip-req-build-sywndz8h
  Resolved https://github.com/softwaredoug/cheat-at-search.git to commit edca45d487123153a7db11d7cd2c7bc088842e07
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting datasets<5.0.0,>=4.8.4 (from cheat_at_search==0.1.0)
  Downloading datasets-4.8.5-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: google-genai<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from cheat_at_search==0.1.0) (1.68.0)
Requirement already satisfied: lxml<7.0.0,>=6.0.2 in /usr/local/lib/python3.12/dist-packages (from cheat_at_search==0.1.0) (6.1.0)
Collecting openai<2.0.0,>=1.84.0 (from cheat_at_search==0.1.0)
  Downloading openai-1.109.1-py3-none-any.whl.metadata (29 kB)
Requirement already satisfied: pandas<3.0.0,>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from cheat_at_search==0.1.0) (2.2.2)
Requirement already satisfied: pyarrow<22.0.0,>=14.0.0 in /usr/local/lib/python3.12/dist-packages (from cheat_at_search==0.1.0) (18.1.0)
Requirement already satisfied: pydantic<3.0.0,>=2.11.0 in /usr/local/lib/python3.12/dist-packages (from cheat_at_search==0.1.0) (2.12.3)
Collecting pystemmer<4.0.0,>=3.0.0 (from cheat_at_search==0.1.0)
  Downloading PyStemmer-3.0.0-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: pyyaml<7.0.0,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from cheat_at_search==0.1.0) (6.0.3)
Collecting searcharray<0.0.74,>=0.0.73 (from cheat_at_search==0.1.0)
  Downloading searcharray-0.0.73-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Requirement already satisfied: sentence-transformers<6.0.0,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from cheat_at_search==0.1.0) (5.4.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (3.29.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (2.0.2)
Collecting pyarrow<22.0.0,>=14.0.0 (from cheat_at_search==0.1.0)
  Downloading pyarrow-21.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.3 kB)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (0.3.8)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (0.70.16)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (2025.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (1.11.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (26.1)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.2.0->cheat_at_search==0.1.0) (4.13.0)
Requirement already satisfied: google-auth<3.0.0,>=2.47.0 in /usr/local/lib/python3.12/dist-packages (from google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.2.0->cheat_at_search==0.1.0) (2.47.0)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.2.0->cheat_at_search==0.1.0) (9.1.4)
Requirement already satisfied: websockets<17.0,>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.2.0->cheat_at_search==0.1.0) (15.0.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.2.0->cheat_at_search==0.1.0) (4.15.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.2.0->cheat_at_search==0.1.0) (1.9.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.2.0->cheat_at_search==0.1.0) (1.3.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from openai<2.0.0,>=1.84.0->cheat_at_search==0.1.0) (0.14.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.2.0->cheat_at_search==0.1.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.2.0->cheat_at_search==0.1.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.2.0->cheat_at_search==0.1.0) (2026.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.11.0->cheat_at_search==0.1.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.11.0->cheat_at_search==0.1.0) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.11.0->cheat_at_search==0.1.0) (0.4.2)
Requirement already satisfied: Cython in /usr/local/lib/python3.12/dist-packages (from searcharray<0.0.74,>=0.0.73->cheat_at_search==0.1.0) (3.0.12)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (5.0.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (2.10.0+cpu)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (1.16.3)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5.0.0,>=4.8.0->google-genai<2.0.0,>=1.2.0->cheat_at_search==0.1.0) (3.13)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (3.13.5)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.2.0->cheat_at_search==0.1.0) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.2.0->cheat_at_search==0.1.0) (4.9.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (1.4.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (0.24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3.0.0,>=2.2.0->cheat_at_search==0.1.0) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (2.5.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (3.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (0.7.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (1.23.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.2.0->cheat_at_search==0.1.0) (0.6.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers<6.0.0,>=5.0.0->cheat_at_search==0.1.0) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets<5.0.0,>=4.8.4->cheat_at_search==0.1.0) (0.1.2)
Downloading datasets-4.8.5-py3-none-any.whl (528 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 529.0/529.0 kB 17.4 MB/s eta 0:00:00
Downloading openai-1.109.1-py3-none-any.whl (948 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 948.6/948.6 kB 43.8 MB/s eta 0:00:00
Downloading pyarrow-21.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (42.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 MB 22.6 MB/s eta 0:00:00
Downloading PyStemmer-3.0.0-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (745 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 745.3/745.3 kB 35.7 MB/s eta 0:00:00
Downloading searcharray-0.0.73-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 54.7 MB/s eta 0:00:00
Building wheels for collected packages: cheat_at_search
  Building wheel for cheat_at_search (pyproject.toml) ... done
  Created wheel for cheat_at_search: filename=cheat_at_search-0.1.0-py3-none-any.whl size=1453000 sha256=b3b100a3b1d65b933ef2f6026ff877c996cd324be6461bc247a98b1813f069d2
  Stored in directory: /tmp/pip-ephem-wheel-cache-rbca80fy/wheels/ea/96/d3/e69453e5f86e6f891864e5b5baf2b11ffda2d0981d9f8a138e
Successfully built cheat_at_search
Installing collected packages: pystemmer, pyarrow, searcharray, openai, datasets, cheat_at_search
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: openai
    Found existing installation: openai 2.32.0
    Uninstalling openai-2.32.0:
      Successfully uninstalled openai-2.32.0
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
Successfully installed cheat_at_search-0.1.0 datasets-4.8.5 openai-1.109.1 pyarrow-21.0.0 pystemmer-3.0.0 searcharray-0.0.73
Mounted at /content/drive

,product_id,product_name,product_class,category hierarchy,product_description,product_features,rating_count,average_rating,review_count,features,doc_id,title,description,category,sub_category,cat_subcat,title_snowball,description_snowball
0,0,solid wood platform bed,Beds,Furniture / Bedroom Furniture / Beds & Headboa...,"good , deep sleep can be quite difficult to ha...",overallwidth-sidetoside:64.7|dsprimaryproducts...,15.0,4.5,15.0,"[overallwidth-sidetoside:64.7, dsprimaryproduc...",0,solid wood platform bed,"good , deep sleep can be quite difficult to ha...",Furniture,Bedroom Furniture,Furniture / Bedroom Furniture,"Terms({'platform', 'solid', 'wood', 'bed'})","Terms({'than', 'ampl', 'hard', 'act', 'fit', '..."
1,1,all-clad 7 qt . slow cooker,Slow Cookers,Kitchen & Tabletop / Small Kitchen Appliances ...,"create delicious slow-cooked meals , from tend...",capacityquarts:7|producttype : slow cooker|pro...,100.0,2.0,98.0,"[capacityquarts:7, producttype : slow cooker, ...",1,all-clad 7 qt . slow cooker,"create delicious slow-cooked meals , from tend...",Kitchen & Tabletop,Small Kitchen Appliances,Kitchen & Tabletop / Small Kitchen Appliances,"Terms({'7', 'qt', 'slow', 'clad', 'cooker', 'a...","Terms({'day', 'tabl', 'ingredi', 'veggi', 'sle..."
2,2,all-clad electrics 6.5 qt . slow cooker,Slow Cookers,Kitchen & Tabletop / Small Kitchen Appliances ...,prepare home-cooked meals on any schedule with...,features : keep warm setting|capacityquarts:6....,208.0,3.0,181.0,"[features : keep warm setting, capacityquarts:...",2,all-clad electrics 6.5 qt . slow cooker,prepare home-cooked meals on any schedule with...,Kitchen & Tabletop,Small Kitchen Appliances,Kitchen & Tabletop / Small Kitchen Appliances,"Terms({'electr', 'qt', '5', 'slow', 'clad', '6...","Terms({'on', 'hour', 'meal', 'featur', 'cooker..."
3,3,all-clad all professional tools pizza cutter,"Slicers, Peelers And Graters",Browse By Brand / All-Clad,this original stainless tool was designed to c...,overallwidth-sidetoside:3.5|warrantylength : l...,69.0,4.5,42.0,"[overallwidth-sidetoside:3.5, warrantylength :...",3,all-clad all professional tools pizza cutter,this original stainless tool was designed to c...,Browse By Brand,All-Clad,Browse By Brand / All-Clad,"Terms({'cutter', 'tool', 'clad', 'profession',...","Terms({'easili', 'dough', 'pasta', 'cut', 'ori..."
4,4,baldwin prestige alcott passage knob with roun...,Door Knobs,Home Improvement / Doors & Door Hardware / Doo...,the hardware has a rich heritage of delivering...,compatibledoorthickness:1.375 '' |countryofori...,70.0,5.0,42.0,"[compatibledoorthickness:1.375 '' , countryofo...",4,baldwin prestige alcott passage knob with roun...,the hardware has a rich heritage of delivering...,Home Improvement,Doors & Door Hardware,Home Improvement / Doors & Door Hardware,"Terms({'alcott', 'prestig', 'round', 'passag',...","Terms({'offer', 'on', 'dummi', 'deliv', 'featu..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42989,42989,malibu pressure balanced diverter fixed shower...,Shower Panels,Home Improvement / Bathroom Remodel & Bathroom...,the malibu pressure balanced diverter fixed sh...,producttype : shower panel|spraypattern : rain...,3.0,4.5,2.0,"[producttype : shower panel, spraypattern : ra...",42989,malibu pressure balanced diverter fixed shower...,the malibu pressure balanced diverter fixed sh...,Home Improvement,Bathroom Remodel & Bathroom Fixtures,Home Improvement / Bathroom Remodel & Bathroom...,"Terms({'pressur', 'divert', 'fix', 'head', 'sh...","Terms({'easili', 'spray', 'fixtur', 'into', 'b..."
42990,42990,emmeline 5 piece breakfast dining set,Dining Table Sets,Furniture / Kitchen & Dining Furniture / Dinin...,,basematerialdetails : steel| : gray wood|ofhar...,1314.0,4.5,864.0,"[basematerialdetails : steel, : gray wood, of...",42990,emmeline 5 piece breakfast dining set,,Furniture,Kitchen & Dining Furniture,Furniture / Kitchen & Dining Furniture,"Terms({'piec', 'dine', '5', 'breakfast', 'emme...",Terms(set())
42991,42991,maloney 3 piece pub table set,Dining Table Sets,Furniture / Kitchen & Dining Furniture / Dinin...,this pub table set includes 1 counter height t...,additionaltoolsrequirednotincluded : power dri...,49.0,4.0,41.0,[additionaltoolsrequirednotincluded : power dr...,42991,maloney 3 piece pub table set,this pub table set includes 1 counter height t...,Furniture,Kitchen & Dining Furniture,Furniture / Kitchen & Dining Furniture,"Terms({'piec', 'set', 'pub', 'maloney', 'tabl'...","Terms({'wheel', '1', 'into', 'meal', 'rectangu..."
42992,42992,fletcher 27.5 '' wide polyester armchair,Teen Lounge Furniture|Accent Chairs,Furniture / Living Room Furniture / Chairs & S...,"bring iconic , modern style to your space in a...",legmaterialdetails : rubberwood|backheight-sea...,1746.0,4.5,1226.0,"[legmaterialdetails : rubberwood, backheight-s...",42992,fletcher 27.5 '' wide polyester armchair,"bring iconic , modern style to your space in a...",Furniture,Living Room Furniture,Furniture / Living Room Furniture,"Terms({'fletcher', '27', 'wide', '5', 'polyest...","Terms({'curv', 'style', 'armchair', 'tailor', ..."
42993,42993,griffin 29 '' bar stool,Bar Stools,Furniture / Kitchen & Dining Furniture / Bar F...,this set of two barstools features a minimalis...,distancebetweenfloorandfootrest:7.5|dssecondar...,20.0,4.5,20.0,"[distancebetweenfloorandfootrest:7.5, dssecond...",42993,griffin 29 '' bar stool,this set of two barstools features a minimalis...,Furniture,Kitchen & Dining Furniture,Furniture / Kitchen & Dining Furniture,"Terms({'stool', '29', 'bar', 'griffin'})","Terms({'décor', 'powder', 'barstool', 'day', '..."

## Query -> Full classification

Our usual list of classifications

**EXCEPT** - we're not passing them to the LLM, we're building an embedding index of them on this line

```
model = SentenceTransformer('all-MiniLM-L6-v2')
real_classifications = model.encode(classifications_list)
top_level_category_list = np.asarray([c.split(" / ")[0].strip() for c in classifications_list])
```

**Lookup** we also do a lookup in `classifications` to map a hallucinated classification to our real classifications

```
    @property
    def classifications(self):
        """Search with model to resolve to real classification."""
        actuals = []
        for halluc_class in self.hallucinated_classification:
            top_level_halluc_category = halluc_class.split(" / ")[0].strip()

            query_embedding = model.encode(halluc_class)
            dot_prods = np.dot(real_classifications, query_embedding)
            actual = classifications_list[np.argmax(dot_prods)]
            while actual in actuals:
                dot_prods[np.argmax(dot_prods)] = -1
                actual = classifications_list[np.argmax(dot_prods)]
```

In [ ]:
import numpy as np

classifications_list = np.asarray([
 'Furniture / Bedroom Furniture / Beds & Headboards / Beds',
 'Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs',
 'Rugs / Area Rugs',
 'Furniture / Office Furniture / Desks',
 'Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables',
 'Furniture / Living Room Furniture / Coffee Tables & End Tables / End & Side Tables',
 'Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows',
 'Furniture / Bedroom Furniture / Dressers & Chests',
 'Outdoor / Outdoor & Patio Furniture / Patio Furniture Sets / Patio Conversation Sets',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / All Bathroom Vanities',
 'Furniture / Living Room Furniture / Console Tables',
 'Décor & Pillows / Art / All Wall Art',
 'Furniture / Kitchen & Dining Furniture / Bar Furniture / Bar Stools & Counter Stools / All Bar Stools & Counter Stools',
 'Furniture / Kitchen & Dining Furniture / Dining Tables & Seating / Kitchen & Dining Chairs',
 'Furniture / Office Furniture / Office Chairs',
 'Décor & Pillows / Mirrors / All Mirrors',
 'Bed & Bath / Bedding / All Bedding',
 'Décor & Pillows / Wall Décor / Wall Accents',
 'Furniture / Living Room Furniture / Chairs & Seating / Recliners',
 'Furniture / Kitchen & Dining Furniture / Dining Tables & Seating / Kitchen and Dining Sets',
 'Décor & Pillows / Window Treatments / Curtains & Drapes',
 'Furniture / Living Room Furniture / Sectionals',
 'Baby & Kids / Toddler & Kids Bedroom Furniture / Kids Beds',
 'Furniture / Living Room Furniture / TV Stands & Media Storage Furniture / TV Stands & Entertainment Centers',
 'Lighting / Ceiling Lights / Chandeliers',
 'Furniture / Bedroom Furniture / Nightstands',
 'Baby & Kids / Toddler & Kids Bedroom Furniture / Kids Desks',
 'Décor & Pillows / Home Accessories / Decorative Objects',
 'Furniture / Bedroom Furniture / Beds & Headboards / Headboards',
 'Furniture / Living Room Furniture / Sofas',
 'Furniture / Living Room Furniture / Cabinets & Chests',
 'Décor & Pillows / Clocks / Wall Clocks',
 'Storage & Organization / Bathroom Storage & Organization / Bathroom Cabinets & Shelving',
 'Lighting / Table & Floor Lamps / Table Lamps',
 'Furniture / Living Room Furniture / Ottomans & Poufs',
 'Furniture / Kitchen & Dining Furniture / Kitchen Islands & Carts',
 'Furniture / Living Room Furniture / Bookcases',
 'Outdoor / Outdoor & Patio Furniture / Outdoor Seating & Patio Chairs / Patio Seating / Patio Sofas & Sectionals',
 'Furniture / Office Furniture / Office Storage Cabinets',
 'Furniture / Kitchen & Dining Furniture / Dining Tables & Seating / Kitchen & Dining Tables',
 'Contractor / Entry & Hallway / Coat Racks & Umbrella Stands',
 'Bed & Bath / Bedding Essentials / Mattress Pads & Toppers',
 'Home Improvement / Hardware / Home Hardware / Switch Plates',
 'Baby & Kids / Toddler & Kids Playroom / Playroom Furniture / Toddler & Kids Chairs & Seating',
 'Storage & Organization / Garage & Outdoor Storage & Organization / Outdoor Covers / Patio Furniture Covers',
 'Rugs / Doormats',
 'Rugs / Kitchen Mats',
 'Furniture / Bedroom Furniture / Beds & Headboards / Beds / Queen Size Beds',
 'Furniture / Bedroom Furniture / Daybeds',
 'Furniture / Living Room Furniture / Living Room Sets',
 'Outdoor / Outdoor & Patio Furniture / Patio Furniture Sets / Patio Dining Sets',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Sinks & Faucet Components / Bathroom Sink Faucets / Single Hole Bathroom Sink Faucets',
 'Outdoor / Outdoor Décor / Statues & Sculptures',
 'Décor & Pillows / Art / All Wall Art / Green Wall Art',
 'Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Table Sets',
 'Furniture / Living Room Furniture / Chairs & Seating / Chaise Lounge Chairs',
 'Storage & Organization / Wall Shelving & Organization / Wall and Display Shelves',
 'Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables / Rectangle Coffee Tables',
 'Décor & Pillows / Art / All Wall Art / Brown Wall Art',
 'Furniture / Kitchen & Dining Furniture / Bar Furniture / Bar Stools & Counter Stools / All Bar Stools & Counter Stools / Counter (24-27) Bar Stools & Counter Stools',
 'Furniture / Living Room Furniture / Coffee Tables & End Tables / Plant Stands & Tables',
 'Décor & Pillows / Window Treatments / Curtain Hardware & Accessories',
 'Furniture / Kitchen & Dining Furniture / Dining Tables & Seating / Kitchen & Dining Chairs / Side Kitchen & Dining Chairs',
 'Outdoor / Outdoor & Patio Furniture / Outdoor Seating & Patio Chairs / Patio Seating / Outdoor Club Chairs',
 'Furniture / Living Room Furniture / Chairs & Seating / Benches',
 'Home Improvement / Kitchen Remodel & Kitchen Fixtures / Kitchen Sinks & Faucet Components / Kitchen Sinks / Farmhouse & Apron Kitchen Sinks',
 'Kitchen & Tabletop / Kitchen Organization / Food Pantries',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Towel Storage / Towel & Robe Hooks / Black Towel & Robe Hooks',
 'Storage & Organization / Garage & Outdoor Storage & Organization / Deck Boxes & Patio Storage',
 'Outdoor / Garden / Planters',
 'Lighting / Wall Lights / Bathroom Vanity Lighting',
 'Furniture / Kitchen & Dining Furniture / Sideboards & Buffets',
 'Storage & Organization / Garage & Outdoor Storage & Organization / Storage Racks & Shelving Units',
 'Home Improvement / Hardware / Cabinet Hardware / Cabinet & Drawer Pulls / Bronze Cabinet & Drawer Pulls',
 'Storage & Organization / Storage Containers & Drawers / All Storage Containers',
 'Bed & Bath / Shower Curtains & Accessories / Shower Curtains & Shower Liners',
 'Storage & Organization / Bathroom Storage & Organization / Hampers & Laundry Baskets',
 'Lighting / Light Bulbs & Hardware / Light Bulbs / All Light Bulbs / LED Light Bulbs',
 'Décor & Pillows / Art / All Wall Art / Blue Wall Art',
 'Bed & Bath / Mattresses & Foundations / Innerspring Mattresses',
 'Lighting / Outdoor Lighting / Outdoor Wall Lighting',
 'Storage & Organization / Garage & Outdoor Storage & Organization / Natural Material Storage / Log Storage',
 'Bed & Bath / Bathroom Accessories & Organization / Countertop Bath Accessories',
 'Storage & Organization / Shoe Storage / All Shoe Storage',
 'Home Improvement / Flooring, Walls & Ceiling / Floor Tiles & Wall Tiles / Ceramic Floor Tiles & Wall Tiles',
 'Home Improvement / Hardware / Cabinet Hardware / Cabinet & Drawer Pulls / Black Cabinet & Drawer Pulls',
 'Bed & Bath / Mattresses & Foundations / Adjustable Beds',
 "Rugs / Area Rugs / 2' x 3' Area Rugs",
 'Commercial Business Furniture / Commercial Office Furniture / Office Storage & Filing / Office Carts & Stands / All Carts & Stands',
 'Furniture / Bedroom Furniture / Beds & Headboards / Beds / Twin Beds',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Sinks & Faucet Components / Bathroom Sink Faucets / Widespread Bathroom Sink Faucets',
 "Rugs / Area Rugs / 4' x 6' Area Rugs",
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Sinks & Faucet Components / Bathroom Sink Faucets',
 'Kitchen & Tabletop / Tableware & Drinkware / Table & Kitchen Linens / All Table Linens',
 'Kitchen & Tabletop / Kitchen Organization / Food Storage & Canisters / Food Storage Containers',
 'Décor & Pillows / Flowers & Plants / Faux Flowers',
 'Bed & Bath / Bedding / All Bedding / Twin Bedding',
 'Furniture / Bedroom Furniture / Dressers & Chests / White Dressers & Chests',
 'Home Improvement / Flooring, Walls & Ceiling / Floor Tiles & Wall Tiles / Porcelain Floor Tiles & Wall Tiles',
 'Home Improvement / Flooring, Walls & Ceiling / Flooring Installation & Accessories / Molding & Millwork / Wall Molding & Millwork',
 'Home Improvement / Doors & Door Hardware / Door Hardware & Accessories / Barn Door Hardware',
 'Bed & Bath / Bedding / Sheets & Pillowcases',
 'Furniture / Office Furniture / Chair Mats / Hard Floor Chair Mats',
 'Outdoor / Outdoor Fencing & Flooring / All Fencing',
 'Storage & Organization / Closet Storage & Organization / Clothes Racks & Garment Racks',
 'Kitchen & Tabletop / Kitchen Utensils & Tools / Colanders, Strainers, & Salad Spinners',
 'Outdoor / Hot Tubs & Saunas / Saunas',
 'Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows / Blue Throw Pillows',
 'Bed & Bath / Bedding Essentials / Bed Pillows',
 'Lighting / Wall Lights / Wall Sconces',
 'Outdoor / Front Door Décor & Curb Appeal / Mailboxes',
 'Outdoor / Garden / Greenhouses',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Showers & Bathtubs / Showers & Bathtubs Plumbing / Shower Faucets & Systems',
 'Bed & Bath / Mattresses & Foundations / Queen Mattresses',
 'Furniture / Bedroom Furniture / Jewelry Armoires',
 'Outdoor / Outdoor Shades / Awnings',
 'Baby & Kids / Nursery Bedding / Crib Bedding Sets',
 'Home Improvement / Hardware / Cabinet Hardware / Cabinet & Drawer Knobs / Brass Cabinet & Drawer Knobs',
 'Décor & Pillows / Art / All Wall Art / Red Wall Art',
 'Lighting / Ceiling Lights / All Ceiling Lights',
 'Lighting / Light Bulbs & Hardware / Lighting Components',
 'Furniture / Game Tables & Game Room Furniture / Poker & Card Tables',
 'Appliances / Kitchen Appliances / Range Hoods / All Range Hoods',
 'Home Improvement / Flooring, Walls & Ceiling / Floor Tiles & Wall Tiles / Natural Stone Floor Tiles & Wall Tiles',
 'Furniture / Kitchen & Dining Furniture / Bar Furniture / Bar Stools & Counter Stools / All Bar Stools & Counter Stools / Bar (28-33) Bar Stools & Counter Stools',
 'Outdoor / Outdoor Cooking & Tableware / Outdoor Serving & Tableware / Coolers, Baskets & Tubs / Picnic Baskets & Backpacks',
 'Décor & Pillows / Picture Frames & Albums / All Picture Frames',
 'Bed & Bath / Shower Curtains & Accessories / Shower Curtain Hooks',
 'Outdoor / Outdoor Shades / Outdoor Umbrellas / Patio Umbrella Stands & Bases',
 'Outdoor / Outdoor & Patio Furniture / Patio Bar Furniture / Patio Bar Stools',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Toilets & Bidets / Toilet Paper Holders / Free Standing Toilet Paper Holders',
 'Storage & Organization / Garage & Outdoor Storage & Organization / Bike & Sport Racks',
 'Appliances / Kitchen Appliances / Refrigerators & Freezers / All Refrigerators / French Door Refrigerators',
 'Décor & Pillows / Home Accessories / Decorative Trays',
 'School Furniture and Supplies / School Spaces / Computer Lab Furniture / Podiums & Lecterns',
 'Lighting / Light Bulbs & Hardware / Lighting Shades',
 'Furniture / Kitchen & Dining Furniture / Bar Furniture / Home Bars & Bar Sets',
 'Lighting / Table & Floor Lamps / Floor Lamps',
 'Décor & Pillows / Wall Décor / Wall Accents / Brown Wall Accents',
 'Kitchen & Tabletop / Small Kitchen Appliances / Pressure & Slow Cookers / Slow Cookers / Slow Slow Cookers',
 'Décor & Pillows / Window Treatments / Curtains & Drapes / 90 Inch Curtains & Drapes',
 'Furniture / Bedroom Furniture / Armoires & Wardrobes',
 'Kitchen & Tabletop / Tableware & Drinkware / Flatware & Cutlery / Serving Utensils',
 'Baby & Kids / Baby & Kids Décor & Lighting / All Baby & Kids Wall Art',
 'Furniture / Office Furniture / Desks / Writing Desks',
 'Furniture / Office Furniture / Office Chairs / Task Office Chairs',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Showers & Bathtubs / Shower & Bathtub Doors',
 'Outdoor / Outdoor & Patio Furniture / Outdoor Seating & Patio Chairs / Patio Seating / Patio Rocking Chairs & Gliders',
 'Home Improvement / Flooring, Walls & Ceiling / Walls & Ceilings / Wall Paneling',
 'Outdoor / Garden / Plant Stands & Accessories',
 'Furniture / Kitchen & Dining Furniture / Dining Tables & Seating / Kitchen & Dining Tables / 4 Seat Kitchen & Dining Tables',
 'Décor & Pillows / Home Accessories / Vases, Urns, Jars & Bottles',
 'Lighting / Wall Lights / Under Cabinet Lighting / Strip Under Cabinet Lighting',
 'Furniture / Bedroom Furniture / Bedroom and Makeup Vanities',
 'Pet / Dog / Dog Bowls & Feeding Supplies / Pet Bowls & Feeders',
 'Décor & Pillows / Candles & Holders / Candle Holders',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Showers & Bathtubs / Shower & Bathtub Accessories',
 'Furniture / Office Furniture / Office Chair Accessories / Seat Cushion Office Chair Accessories',
 'Furniture / Office Furniture / Chair Mats',
 'Furniture / Living Room Furniture / Chairs & Seating / Massage Chairs',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / All Bathroom Vanities / Modern & Contemporary Bathroom Vanities',
 'Lighting / Ceiling Fans / All Ceiling Fans',
 'Home Improvement / Kitchen Remodel & Kitchen Fixtures / Kitchen Sinks & Faucet Components / Kitchen Faucets / Black Kitchen Faucets',
 'Lighting / Light Bulbs & Hardware / Light Bulbs / All Light Bulbs / Incandescent Light Bulbs',
 'Home Improvement / Flooring, Walls & Ceiling / Flooring Installation & Accessories / Molding & Millwork',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Showers & Bathtubs / Bathtubs',
 'Décor & Pillows / Art / All Wall Art / Yellow Wall Art',
 'Pet / Dog / Pet Gates, Fences & Doors / Pet Gates',
 'Furniture / Bedroom Furniture / Beds & Headboards / Bed Frames / Twin Bed Frames',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Towel Storage / Towel Bars, Racks, and Stands / Metal Towel Bars, Racks, and Stands',
 'Décor & Pillows / Art / All Wall Art / Pink Wall Art',
 'Home Improvement / Kitchen Remodel & Kitchen Fixtures / Smoke Detectors / Wall & Ceiling Mounted Smoke Detectors',
 'Outdoor / Garden / Planters / Plastic Planters',
 'Décor & Pillows / Mirrors / All Mirrors / Accent Mirrors',
 'Appliances / Kitchen Appliances / Range Hoods / All Range Hoods / Wall Mount Range Hoods',
 'Outdoor / Garden / Garden Décor / Lawn & Garden Accents',
 'Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables / Round Coffee Tables',
 'Kitchen & Tabletop / Tableware & Drinkware / Dinnerware / Dining Bowls',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Showers & Bathtubs / Showers & Bathtubs Plumbing / Shower Heads / Dual Shower Heads',
 'Home Improvement / Flooring, Walls & Ceiling / Floor Tiles & Wall Tiles / Glass Floor Tiles & Wall Tiles',
 'School Furniture and Supplies / Facilities & Maintenance / Trash & Recycling',
 'Home Improvement / Hardware / Cabinet Hardware / Cabinet & Drawer Pulls / Nickel Cabinet & Drawer Pulls',
 'Storage & Organization / Closet Storage & Organization / Closet Systems',
 'Furniture / Bedroom Furniture / Beds & Headboards / Beds / Full & Double Beds',
 'Commercial Business Furniture / Commercial Office Furniture / Office Storage & Filing / Office Carts & Stands / All Carts & Stands / Printer Carts & Stands',
 'Storage & Organization / Closet Storage & Organization / Closet Accessories',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / All Bathroom Vanities / Traditional Bathroom Vanities',
 'Home Improvement / Plumbing / Core Plumbing / Parts & Components',
 'Holiday Décor / Christmas / Christmas Trees / All Christmas Trees',
 'Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows / Black Throw Pillows',
 'Furniture / Game Tables & Game Room Furniture / Sports Team Fan Shop & Memorabillia / Life Size Cutouts',
 'Lighting / Ceiling Lights / Pendant Lighting',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Towel Storage / Towel & Robe Hooks',
 'Appliances / Washers & Dryers / Dryers / All Dryers / Gas Dryers',
 'Outdoor / Outdoor Recreation / Backyard Play / Kids Cars & Ride-On Toys',
 'Kitchen & Tabletop / Small Kitchen Appliances / Coffee, Espresso, & Tea / Coffee Makers',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Showers & Bathtubs / Showers & Bathtubs Plumbing / Shower Heads',
 'Outdoor / Outdoor & Patio Furniture / Outdoor Seating & Patio Chairs / Patio Seating / Patio Sofas & Sectionals / Sectional Patio Sofas & Sectionals',
 'Lighting / Wall Lights / Under Cabinet Lighting',
 'Foodservice / Foodservice Tables / Table Parts',
 'Lighting / Outdoor Lighting / Landscape Lighting / All Landscape Lighting / Fence Post Cap Landscape Lighting',
 'Lighting / Outdoor Lighting / Landscape Lighting / All Landscape Lighting',
 'Outdoor / Outdoor & Patio Furniture / Outdoor Tables / All Patio Tables',
 'Commercial Business Furniture / Commercial Office Furniture / Office Storage & Filing / Office Carts & Stands / All Carts & Stands / Utility Carts & Stands',
 'Outdoor / Outdoor & Patio Furniture / Outdoor Seating & Patio Chairs / Outdoor Chaise & Lounge Chairs',
 'Furniture / Living Room Furniture / Chairs & Seating / Recliners / Brown Recliners',
 'Pet / Bird / Bird Perches & Play Gyms',
 'Décor & Pillows / Picture Frames & Albums / All Picture Frames / Single Picture Picture Frames',
 'Lighting / Outdoor Lighting / Outdoor Lanterns & Lamps',
 'Home Improvement / Hardware / Cabinet Hardware / Cabinet & Drawer Pulls',
 'Bed Accessories',
 'Clips/Clamps',
 'Décor & Pillows / Wall Décor / Wall Decals',
 'Home Improvement / Flooring, Walls & Ceiling / Floor Tiles & Wall Tiles',
 'Bed & Bath / Bedding / Sheets & Pillowcases / Twin XL Sheets & Pillowcases',
 'Kitchen & Tabletop / Tableware & Drinkware / Serveware / Serving Trays & Boards / Serving Trays & Platters / Serving Serving Trays & Platters',
 'Holiday Décor / Holiday Lighting',
 'Décor & Pillows / Wall Décor / Memo Boards',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Toilets & Bidets / Toilet Paper Holders / Wall Mounted Toilet Paper Holders',
 'Décor & Pillows / Window Treatments / Curtains & Drapes / 63 Inch and Less Curtains & Drapes',
 'Home Improvement / Doors & Door Hardware / Door Hardware & Accessories / Door Knobs / Egg Door Knobs',
 'Décor & Pillows / Clocks / Wall Clocks / Analog Wall Clocks',
 'Home Improvement / Doors & Door Hardware / Interior Doors / Sliding Interior Doors',
 'Outdoor / Outdoor Recreation / Outdoor Games / All Outdoor Games',
 'Home Improvement / Doors & Door Hardware / Door Hardware & Accessories / Door Levers / Round Door Levers',
 'Storage & Organization / Garage & Outdoor Storage & Organization / Sheds / Storage Sheds',
 'Home Improvement / Doors & Door Hardware / Door Hardware & Accessories / Door Levers',
 'School Furniture and Supplies / School Furniture / School Tables / Folding Tables / Wood Folding Tables',
 'Décor & Pillows / Wall Décor / Wall Accents / Green Wall Accents',
 'School Furniture and Supplies / Facilities & Maintenance / Commercial Signage',
 'Storage & Organization / Garage & Outdoor Storage & Organization / Garage Storage Cabinets',
 'Furniture / Bedroom Furniture / Dressers & Chests / Beige Dressers & Chests',
 'Storage & Organization / Wall Shelving & Organization / Wall & Display Shelves',
 'Furniture / Game Tables & Game Room Furniture / Dartboards & Cabinets',
 'Outdoor / Outdoor Décor / Outdoor Pillows & Cushions / Patio Furniture Cushions / Lounge Chair Patio Furniture Cushions',
 'Outdoor / Outdoor & Patio Furniture / Patio Furniture Sets / Patio Dining Sets / Two Person Patio Dining Sets',
 'Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows / Ivory & Cream Throw Pillows',
 'Appliances / Washers & Dryers / Washer & Dryer Sets / Black Washer & Dryer Sets',
 'School Furniture and Supplies / School Furniture / School Chairs & Seating / Stackable Chairs',
 'Home Improvement / Hardware / Cabinet Hardware / Cabinet & Drawer Pulls / Brass Cabinet & Drawer Pulls',
 'School Furniture and Supplies / School Boards & Technology / AV, Mounts & Tech Accessories / Electronic Mounts & Stands / Computer Mounts',
 'Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs / Papasan Accent Chairs',
 'Storage & Organization / Shoe Storage / All Shoe Storage / Rack Shoe Storage',
 'Storage & Organization / Shoe Storage / All Shoe Storage / Cabinet Shoe Storage',
 'Storage & Organization / Storage Containers & Drawers / Storage Drawers',
 'Appliances / Kitchen Appliances / Wine & Beverage Coolers / Water Coolers',
 'Furniture / Living Room Furniture / Chairs & Seating / Rocking Chairs',
 'Kitchen & Tabletop / Tableware & Drinkware / Serveware / Serving Bowls & Baskets / Serving Bowls / NA Serving Bowls',
 'Furniture / Living Room Furniture / TV Stands & Media Storage Furniture / Projection Screens / Inflatable Projection Screens',
 'Appliances / Kitchen Appliances / Large Appliance Parts & Accessories',
 'Storage & Organization / Bathroom Storage & Organization / Hampers & Laundry Baskets / Laundry Hampers & Laundry Baskets',
 'Furniture / Office Furniture / Office Stools',
 'Outdoor / Outdoor & Patio Furniture / Outdoor Seating & Patio Chairs / Patio Seating / Outdoor Club Chairs / Metal Outdoor Club Chairs',
 'School Furniture and Supplies / School Furniture / School Tables / Folding Tables',
 'Lighting / Wall Lights / Bathroom Vanity Lighting / Traditional Bathroom Vanity Lighting',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Sinks & Faucet Components / Bathroom Sink Faucets / Centerset Bathroom Sink Faucets',
 'Décor & Pillows / Flowers & Plants / Faux Flowers / Orchid Faux Flowers',
 'Home Improvement / Flooring, Walls & Ceiling / Floor Tiles & Wall Tiles / Metal Floor Tiles & Wall Tiles',
 'Home Improvement / Kitchen Remodel & Kitchen Fixtures / Kitchen Sinks & Faucet Components / Kitchen Sinks',
 'Storage & Organization / Garage & Outdoor Storage & Organization / Outdoor Covers / Grill Covers / Charcoal Grill Grill Covers',
 'Outdoor / Outdoor Décor / Outdoor Wall Décor',
 'Storage & Organization / Cleaning & Laundry Organization / Laundry Room Organizers',
 'Reception Area / Reception Seating / Reception Sofas & Loveseats',
 'Kitchen & Tabletop / Cookware & Bakeware / Baking Sheets & Pans / Bread & Loaf Pans / Steel Bread & Loaf Pans',
 'Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs / Wingback Accent Chairs',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Showers & Bathtubs / Showers & Bathtubs Plumbing / Shower Heads / Fixed Shower Heads',
 'Kitchen & Tabletop / Kitchen Utensils & Tools / Kitchen Gadgets / Pasta Makers & Accessories',
 'School Furniture and Supplies / School Furniture / School Chairs & Seating / Classroom Chairs / High School & College Classroom Chairs',
 'Furniture / Living Room Furniture / Sectionals / Stationary Sectionals',
 'Furniture / Kitchen & Dining Furniture / Sideboards & Buffets / Drawer Equipped Sideboards & Buffets',
 'Kitchen & Tabletop / Cookware & Bakeware / Baking Sheets & Pans / Bread & Loaf Pans',
 'Kitchen & Tabletop / Kitchen Utensils & Tools / Cooking Utensils / All Cooking Utensils / Kitchen Cooking Utensils',
 'Décor & Pillows / Flowers & Plants / Live Plants',
 'Furniture / Living Room Furniture / TV Stands & Media Storage Furniture / Projection Screens / Folding Frame Projection Screens',
 'Kitchen & Tabletop / Kitchen Organization / Food Storage & Canisters / Kitchen Canisters & Jars / Metal Kitchen Canisters & Jars',
 'Outdoor / Outdoor Décor / Outdoor Fountains',
 'Outdoor / Outdoor Shades / Pergolas / Wood Pergolas',
 'Décor & Pillows / Candles & Holders / Candle Holders / Sconce Candle Holders',
 'Kitchen & Tabletop / Tableware & Drinkware / Serveware / Cake & Tiered Stands',
 'Home Improvement / Kitchen Remodel & Kitchen Fixtures / Kitchen Sinks & Faucet Components / Kitchen Faucets / Chrome Kitchen Faucets',
 'Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows / White Throw Pillows',
 'Outdoor / Outdoor Fencing & Flooring / Turf',
 'Décor & Pillows / Window Treatments / Valances & Kitchen Curtains',
 'Home Improvement / Hardware / Cabinet Hardware / Cabinet & Drawer Knobs / Black Cabinet & Drawer Knobs',
 'Home Improvement / Kitchen Remodel & Kitchen Fixtures / Kitchen Sinks & Faucet Components / Kitchen Faucets / Bronze Kitchen Faucets',
 'Appliances / Washers & Dryers / Washer & Dryer Sets',
 'Décor & Pillows / Clocks / Mantel & Tabletop Clocks',
 'Home Improvement / Doors & Door Hardware / Interior Doors',
 'Storage & Organization / Wall Shelving & Organization / Wall & Display Shelves / Floating Wall & Display Shelves',
 'Outdoor / Outdoor Recreation / Backyard Play / Climbing Toys & Slides',
 'Home Improvement / Building Equipment / Dollies / Hand Truck Dollies',
 'Baby & Kids / Toddler & Kids Bedroom Furniture / Baby & Kids Dressers',
 'Décor & Pillows / Mirrors / All Mirrors / Leaning & Floor Mirrors',
 'Kitchen & Tabletop / Tableware & Drinkware / Drinkware / Mugs & Teacups',
 'Décor & Pillows / Flowers & Plants / Wreaths',
 'Outdoor / Outdoor Shades / Pergolas / Metal Pergolas',
 'Bed & Bath / Bedding / Sheets & Pillowcases / Twin Sheets & Pillowcases',
 'Outdoor / Outdoor Shades / Pergolas',
 'Reception Area / Reception Seating / Office Sofas & Loveseats',
 'Décor & Pillows / Home Accessories / Indoor Fountains',
 'Kitchen & Tabletop / Kitchen Organization / Food Storage & Canisters / Kitchen Canisters & Jars / Ceramic Kitchen Canisters & Jars',
 'Décor & Pillows / Window Treatments / Curtain Hardware & Accessories / Bracket Curtain Hardware & Accessories',
 'Home Improvement / Flooring, Walls & Ceiling / Walls & Ceilings / Accent Tiles / Ceramic Accent Tiles',
 'Home Improvement / Flooring, Walls & Ceiling / Walls & Ceilings / Accent Tiles',
 'Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs / Arm Accent Chairs',
 'Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables / Free Form Coffee Tables',
 'Décor & Pillows / Flowers & Plants / Faux Flowers / Rose Faux Flowers',
 'Bed & Bath / Mattresses & Foundations / Innerspring Mattresses / Twin Innerspring Mattresses',
 'Outdoor / Outdoor Décor / Outdoor Pillows & Cushions / Patio Furniture Cushions / Dining Chair Patio Furniture Cushions',
 'Furniture / Living Room Furniture / TV Stands & Media Storage Furniture / TV Stands & Entertainment Centers / Traditional TV Stands & Entertainment Centers',
 'Furniture / Living Room Furniture / Coffee Tables & End Tables / Plant Stands & Tables / Square Plant Stands & Tables',
 'Storage & Organization / Wall Shelving & Organization / Wall & Display Shelves / Corner Wall & Display Shelves',
 "Rugs / Area Rugs / 3' x 5' Area Rugs",
 'Kitchen & Tabletop / Tableware & Drinkware / Drinkware / Mugs & Teacups / Coffee Mugs & Teacups',
 'Contractor / Entry & Hallway / Coat Racks & Umbrella Stands / Wall Mounted Coat Racks & Umbrella Stands',
 "Baby & Kids / Toddler & Kids Playroom / Indoor Play / Kids' Playhouses",
 'Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables / Square Coffee Tables',
 'Baby & Kids / Toddler & Kids Playroom / Indoor Play / Dollhouses & Accessories',
 'Bed & Bath / Bedding / All Bedding / Queen Bedding',
])

from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('all-MiniLM-L6-v2')
real_classifications = model.encode(classifications_list)
top_level_category_list = np.asarray([c.split(CAT_SEP)[0].strip() for c in classifications_list])
top_level_category_list

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

array(['Furniture', 'Furniture', 'Rugs', 'Furniture', 'Furniture',
       'Furniture', 'Décor & Pillows', 'Furniture', 'Outdoor',
       'Home Improvement', 'Furniture', 'Décor & Pillows', 'Furniture',
       'Furniture', 'Furniture', 'Décor & Pillows', 'Bed & Bath',
       'Décor & Pillows', 'Furniture', 'Furniture', 'Décor & Pillows',
       'Furniture', 'Baby & Kids', 'Furniture', 'Lighting', 'Furniture',
       'Baby & Kids', 'Décor & Pillows', 'Furniture', 'Furniture',
       'Furniture', 'Décor & Pillows', 'Storage & Organization',
       'Lighting', 'Furniture', 'Furniture', 'Furniture', 'Outdoor',
       'Furniture', 'Furniture', 'Contractor', 'Bed & Bath',
       'Home Improvement', 'Baby & Kids', 'Storage & Organization',
       'Rugs', 'Rugs', 'Furniture', 'Furniture', 'Furniture', 'Outdoor',
       'Home Improvement', 'Outdoor', 'Décor & Pillows', 'Furniture',
       'Furniture', 'Storage & Organization', 'Furniture',
       'Décor & Pillows', 'Furniture', 'Furniture', 'Décor & Pillows',
       'Furniture', 'Outdoor', 'Furniture', 'Home Improvement',
       'Kitchen & Tabletop', 'Home Improvement', 'Storage & Organization',
       'Outdoor', 'Lighting', 'Furniture', 'Storage & Organization',
       'Home Improvement', 'Storage & Organization', 'Bed & Bath',
       'Storage & Organization', 'Lighting', 'Décor & Pillows',
       'Bed & Bath', 'Lighting', 'Storage & Organization', 'Bed & Bath',
       'Storage & Organization', 'Home Improvement', 'Home Improvement',
       'Bed & Bath', 'Rugs', 'Commercial Business Furniture', 'Furniture',
       'Home Improvement', 'Rugs', 'Home Improvement',
       'Kitchen & Tabletop', 'Kitchen & Tabletop', 'Décor & Pillows',
       'Bed & Bath', 'Furniture', 'Home Improvement', 'Home Improvement',
       'Home Improvement', 'Bed & Bath', 'Furniture', 'Outdoor',
       'Storage & Organization', 'Kitchen & Tabletop', 'Outdoor',
       'Décor & Pillows', 'Bed & Bath', 'Lighting', 'Outdoor', 'Outdoor',
       'Home Improvement', 'Bed & Bath', 'Furniture', 'Outdoor',
       'Baby & Kids', 'Home Improvement', 'Décor & Pillows', 'Lighting',
       'Lighting', 'Furniture', 'Appliances', 'Home Improvement',
       'Furniture', 'Outdoor', 'Décor & Pillows', 'Bed & Bath', 'Outdoor',
       'Outdoor', 'Home Improvement', 'Storage & Organization',
       'Appliances', 'Décor & Pillows', 'School Furniture and Supplies',
       'Lighting', 'Furniture', 'Lighting', 'Décor & Pillows',
       'Kitchen & Tabletop', 'Décor & Pillows', 'Furniture',
       'Kitchen & Tabletop', 'Baby & Kids', 'Furniture', 'Furniture',
       'Home Improvement', 'Outdoor', 'Home Improvement', 'Outdoor',
       'Furniture', 'Décor & Pillows', 'Lighting', 'Furniture', 'Pet',
       'Décor & Pillows', 'Home Improvement', 'Furniture', 'Furniture',
       'Furniture', 'Home Improvement', 'Lighting', 'Home Improvement',
       'Lighting', 'Home Improvement', 'Home Improvement',
       'Décor & Pillows', 'Pet', 'Furniture', 'Home Improvement',
       'Décor & Pillows', 'Home Improvement', 'Outdoor',
       'Décor & Pillows', 'Appliances', 'Outdoor', 'Furniture',
       'Kitchen & Tabletop', 'Home Improvement', 'Home Improvement',
       'School Furniture and Supplies', 'Home Improvement',
       'Storage & Organization', 'Furniture',
       'Commercial Business Furniture', 'Storage & Organization',
       'Home Improvement', 'Home Improvement', 'Holiday Décor',
       'Décor & Pillows', 'Furniture', 'Lighting', 'Home Improvement',
       'Appliances', 'Outdoor', 'Kitchen & Tabletop', 'Home Improvement',
       'Outdoor', 'Lighting', 'Foodservice', 'Lighting', 'Lighting',
       'Outdoor', 'Commercial Business Furniture', 'Outdoor', 'Furniture',
       'Pet', 'Décor & Pillows', 'Lighting', 'Home Improvement',
       'Bed Accessories', 'Clips', 'Décor & Pillows', 'Home Improvement',
       'Bed & Bath', 'Kitchen & Tabletop', 'Holiday Décor',
       'Décor & Pillows', 'Home Improvement', 'Décor & Pillows',
       'Home Improvement', 'Décor & Pillows', 'Home Improvement',
       'Outdoor', 'Home Improvement', 'Storage & Organization',
       'Home Improvement', 'School Furniture and Supplies',
       'Décor & Pillows', 'School Furniture and Supplies',
       'Storage & Organization', 'Furniture', 'Storage & Organization',
       'Furniture', 'Outdoor', 'Outdoor', 'Décor & Pillows', 'Appliances',
       'School Furniture and Supplies', 'Home Improvement',
       'School Furniture and Supplies', 'Furniture',
       'Storage & Organization', 'Storage & Organization',
       'Storage & Organization', 'Appliances', 'Furniture',
       'Kitchen & Tabletop', 'Furniture', 'Appliances',
       'Storage & Organization', 'Furniture', 'Outdoor',
       'School Furniture and Supplies', 'Lighting', 'Home Improvement',
       'Décor & Pillows', 'Home Improvement', 'Home Improvement',
       'Storage & Organization', 'Outdoor', 'Storage & Organization',
       'Reception Area', 'Kitchen & Tabletop', 'Furniture',
       'Home Improvement', 'Kitchen & Tabletop',
       'School Furniture and Supplies', 'Furniture', 'Furniture',
       'Kitchen & Tabletop', 'Kitchen & Tabletop', 'Décor & Pillows',
       'Furniture', 'Kitchen & Tabletop', 'Outdoor', 'Outdoor',
       'Décor & Pillows', 'Kitchen & Tabletop', 'Home Improvement',
       'Décor & Pillows', 'Outdoor', 'Décor & Pillows',
       'Home Improvement', 'Home Improvement', 'Appliances',
       'Décor & Pillows', 'Home Improvement', 'Storage & Organization',
       'Outdoor', 'Home Improvement', 'Baby & Kids', 'Décor & Pillows',
       'Kitchen & Tabletop', 'Décor & Pillows', 'Outdoor', 'Bed & Bath',
       'Outdoor', 'Reception Area', 'Décor & Pillows',
       'Kitchen & Tabletop', 'Décor & Pillows', 'Home Improvement',
       'Home Improvement', 'Furniture', 'Furniture', 'Décor & Pillows',
       'Bed & Bath', 'Outdoor', 'Furniture', 'Furniture',
       'Storage & Organization', 'Rugs', 'Kitchen & Tabletop',
       'Contractor', 'Baby & Kids', 'Furniture', 'Baby & Kids',
       'Bed & Bath'], dtype='<U29')

### Structured types

* Returns a `hallucinated_classification` that we turn into a real classification via finding the most similar embedding

In [ ]:
from pydantic import BaseModel, Field
from typing import List, Literal
from cheat_at_search.enrich import AutoEnricher
import numpy as np

known_categories = set([c.split(CAT_SEP)[0].strip() for c in classifications_list])
known_sub_categories = set([c.split(CAT_SEP)[1].strip() for c in classifications_list if len(c.split(CAT_SEP)) > 1])

known_sub_categories


class Query(BaseModel):
    """
    Base model for search queries, containing common query attributes.
    """
    keywords: str = Field(
        ...,
        description="The original search query keywords sent in as input"
    )


CAT_SEP = '/'


class QueryClassification(Query):
    """
    Represents a classification of a product.

    In this case, hallucinated, something the model is making up that looks like one
    of our classifications
    """
    hallucinated_classification: List[str] = Field(
        description="The classification you created for the query."
    )

    @property
    def classifications(self):
        """Search with model to resolve to real classification."""
        actuals = []
        for halluc_class in self.hallucinated_classification:
            query_embedding = model.encode(halluc_class)
            dot_prods = np.dot(real_classifications, query_embedding)
            actual = classifications_list[np.argmax(dot_prods)]
            while actual in actuals:
                dot_prods[np.argmax(dot_prods)] = -1
                actual = classifications_list[np.argmax(dot_prods)]

            actuals.append(actual)
        return actuals

    @property
    def categories(self):
        resolved_classification = self.classifications
        if len(resolved_classification) == 0 or resolved_classification == ["No Classification Fits"]:
            return []
        cats = []
        for c in resolved_classification:
            cats.append(c.split(CAT_SEP)[0].strip())
        return set(cats)

    @property
    def sub_categories(self):
        resolved_classification = self.classifications
        if len(resolved_classification) == 0 or resolved_classification == ["No Classification Fits"]:
            return []

        cats = []
        for c in resolved_classification:
            c_split = c.split(CAT_SEP)
            if len(c_split) < 2:
                continue
            cats.append(c.split(CAT_SEP)[1].strip())
        return set(cats)

    @property
    def cat_subcat(self):
        resolved_classification = self.classifications
        if len(resolved_classification) == 0 or resolved_classification == ["No Classification Fits"]:
            return []
        cat_subcats = []
        for c in resolved_classification:
            c_split = c.split(CAT_SEP)
            if len(c_split) < 2:
                continue
            cat_subcats.append(f"{c_split[0].strip()} / {c_split[1].strip()}")
        return set(cat_subcats)

### Query classification code

Notice our prompt:
1. Is given some examples of what classifications might look like
2. Asked to "be creative" to give us a diverse set of top level categories

In [ ]:
enricher = AutoEnricher(
     model="openai/gpt-4.1-nano",
     system_prompt="Your task is to create novel, never seen before, furniture, home goods, or hardware classification that best fit a search query. ",
     response_model=QueryClassification
)

def get_prompt_fully_qualified(query):
        prompt = f"""

        Some inspiration on what these look like is at the bottom.

        Here is the users request:

        {query}

        Product classifications might look like:

        'Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables'
        'Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows'
        'Furniture / Bedroom Furniture / Dressers & Chests'
        'Outdoor / Outdoor & Patio Furniture / Patio Furniture Sets / Patio Conversation Sets'
        'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / All Bathroom Vanities'
        'Lighting / Wall Lights / Bathroom Vanity Lighting'
        'Kitchen & Tabletop / Kitchen Organization / Food Storage & Canisters'
        'School Furniture and Supplies / School Furniture / School Chairs & Seating / Stackable Chairs',
        'Baby & Kids / Toddler & Kids Bedroom Furniture / Kids Beds',

        If you feel inspired, return many unique values in a list. Be creative. Cast a wide net with related but diverse categories.

        Return empty list if no clear classification could be inferred, the query is not clearly a furniture query

        """

        return prompt

def fully_classified(query):
    prompt = get_prompt_fully_qualified(query)
    return enricher.enrich(prompt)


def get_num_tokens(query):
    prompt = get_prompt_fully_qualified(query)
    return enricher.get_num_tokens(prompt)

fully_classified("dinosaur"), fully_classified("sofa loveseat"), fully_classified("sofa loveseat").classifications

(QueryClassification(keywords='dinosaur', hallucinated_classification=['Decor & Wall Art / Dinosaur Themed Decor / Dinosaur Wall Hangings and Art', 'Kids & Baby Furniture / Dinosaur Themed Bedroom Furniture / Dinosaur Bed Frames and Dressers', 'Toys & Games / Dinosaur Toys / Dinosaur Action Figures and Plush Toys', 'Outdoor & Garden / Dinosaur Garden Statues / Dinosaur Garden Decor', 'Party Supplies / Dinosaur Party Decorations / Dinosaur Balloons and Banners', 'Educational & Learning / Dinosaur Educational Toys / Dinosaur Puzzle and Learning Kits']),
 QueryClassification(keywords='sofa loveseat', hallucinated_classification=['Furniture / Living Room Furniture / Sofas & Loveseats / Loveseats and Small Sofas', 'Furniture / Modular & Sectional Sofas / Sectional Sofas', 'Furniture / Convertible & Sleeper Sofas / Sleeper Sofas and Futons', 'Furniture / Customizable & Modular Furniture / Modular Sofas and Sectionals', 'Furniture / Vintage & Retro Furniture / Retro Sofas and Loveseats', 'Furniture / Eco-Friendly & Sustainable Furniture / Eco Sofas and Loveseats']),
 [np.str_('Furniture / Living Room Furniture / Sofas'),
  np.str_('Furniture / Living Room Furniture / Sectionals'),
  np.str_('Furniture / Bedroom Furniture / Daybeds'),
  np.str_('Furniture / Living Room Furniture / Sectionals / Stationary Sectionals'),
  np.str_('Reception Area / Reception Seating / Reception Sofas & Loveseats'),
  np.str_('Outdoor / Outdoor & Patio Furniture / Outdoor Seating & Patio Chairs / Patio Seating / Patio Sofas & Sectionals')])

### Much lower number of tokens

We are using a cheaper model, and also we observe many fewer tokens

In [ ]:
get_num_tokens("sofa loveseat")

(380, 93)

### Run an example

Notice how the hallucinated classifications look very specific, but then look at how they are resolved.

**Consider** What problems exist here? Or might creep up?

In [ ]:
fully_classified("barnyard style doors").hallucinated_classification

['Home Improvement / Doors & Windows / Barn Doors & Sliding Doors / Barnyard Style Doors',
 'Furniture / Entryway Furniture / Barnyard Style Doors',
 'Decor / Rustic Decor / Barnyard Theme Accessories',
 'Architectural Elements / Barnyard Style Features / Barnyard Style Doors']

In [ ]:
fully_classified("barnyard style doors").classifications

[np.str_('Home Improvement / Doors & Door Hardware / Interior Doors / Sliding Interior Doors'),
 np.str_('Home Improvement / Doors & Door Hardware / Interior Doors'),
 np.str_('Décor & Pillows / Home Accessories / Decorative Objects'),
 np.str_('Home Improvement / Doors & Door Hardware / Door Hardware & Accessories / Barn Door Hardware')]

In [ ]:
fully_classified("barnyard style doors").cat_subcat

{'Décor & Pillows / Home Accessories',
 'Home Improvement / Doors & Door Hardware'}

## Run Category search strategy with classifier

Identical to previous runs with a classifier of query -> list of classifications. We ask for the `categories` (which behind the scenes does teh embedding lookup). We then go through our usual boosting dance:

1. BM25 search
2. Boost category / subcategory matches

**Something to try (easy)** - change away from the MiniLM model and see if anything changes

**Something to try (advanced)** - What if we embedded the classification directly in the index, and searched that with the hallucinated classification?

In [ ]:
from searcharray import SearchArray
from cheat_at_search.tokenizers import snowball_tokenizer
from cheat_at_search.strategy.strategy import SearchStrategy
import numpy as np


class CategorySearch(SearchStrategy):
    def __init__(self, products, query_to_cat,
                 name_boost=9.3,
                 description_boost=4.1,
                 category_boost=10,
                 sub_category_boost=5,
                 cat_subcat_boost=10):
        super().__init__(products)
        self.index = products
        self.index['product_name_snowball'] = SearchArray.index(
            products['product_name'], snowball_tokenizer)
        self.index['product_description_snowball'] = SearchArray.index(
            products['product_description'], snowball_tokenizer)

        cat_split = products['category hierarchy'].fillna('').str.split("/")

        products['category'] = cat_split.apply(
            lambda x: x[0].strip() if len(x) > 0 else ""
        )
        products['subcategory'] = cat_split.apply(
            lambda x: x[1].strip() if len(x) > 1 else ""
        )
        self.index['category_snowball'] = SearchArray.index(
            products['category'], snowball_tokenizer
        )
        self.index['subcategory_snowball'] = SearchArray.index(
            products['subcategory'], snowball_tokenizer
        )

        self.index['cat_subcat'] = products['category'] + products['subcategory']
        self.index['cat_subcat'] = self.index['cat_subcat'].fillna('')
        self.index['cat_subcat_snowball'] = SearchArray.index(
            self.index['cat_subcat'], snowball_tokenizer
        )

        self.query_to_cat = query_to_cat
        self.name_boost = name_boost
        self.description_boost = description_boost
        self.category_boost = category_boost
        self.sub_category_boost = sub_category_boost
        self.cat_subcat_boost = cat_subcat_boost

    def search(self, query, k=10):
        """Dumb baseline lexical search, but add a constant boost when
           the desired category or subcategory"""
        bm25_scores = np.zeros(len(self.index))
        structured = self.query_to_cat(query)
        tokenized = snowball_tokenizer(query)

        print(structured)

        # ****
        # Baseline BM25 search from before
        for token in tokenized:
            bm25_scores += self.index['product_name_snowball'].array.score(token) * self.name_boost
            bm25_scores += self.index['product_description_snowball'].array.score(
                token) * self.description_boost

        # ****
        # If there's a subcategory, boost that by a constant amount
        for sub_category in structured.sub_categories:
            tokenized_subcategory = snowball_tokenizer(sub_category)
            subcategory_match = np.zeros(len(self.index))
            if tokenized_subcategory:
                subcategory_match = self.index['subcategory_snowball'].array.score(tokenized_subcategory) > 0
            bm25_scores[subcategory_match] += self.sub_category_boost

        # ****
        # If there's a category, boost that by a constant amount
        for category in structured.categories:
            print(category)
            tokenized_category = snowball_tokenizer(category)
            category_match = np.zeros(len(self.index))
            if tokenized_category:
                category_match = self.index['category_snowball'].array.score(tokenized_category) > 0
            bm25_scores[category_match] += self.category_boost

        # ***
        # If they occur togethere, boost by a constant amount
        for cat_subcat in structured.cat_subcat:
            tokenized_cat_subcat = snowball_tokenizer(cat_subcat)
            cat_subcat_match = np.zeros(len(self.index))
            if tokenized_cat_subcat:
                cat_subcat_match = self.index['cat_subcat_snowball'].array.score(tokenized_cat_subcat) > 0
            bm25_scores[cat_subcat_match] += self.cat_subcat_boost

        top_k = np.argsort(-bm25_scores)[:k]
        scores = bm25_scores[top_k]

        return top_k, scores

categorized_search = CategorySearch(corpus, fully_classified)
categorized_search.search('medium clips')

2026-05-20 13:03:45,048 - searcharray.indexing - INFO - Indexing begins w/ 4 workers

INFO:searcharray.indexing:Indexing begins w/ 4 workers

2026-05-20 13:03:45,063 - searcharray.indexing - INFO - 0 Batch Start tokenization

INFO:searcharray.indexing:0 Batch Start tokenization

2026-05-20 13:03:45,066 - searcharray.indexing - INFO - Tokenizing 42994 documents

INFO:searcharray.indexing:Tokenizing 42994 documents

2026-05-20 13:03:45,383 - searcharray.indexing - INFO - Tokenized 10000 (23.259059403637718%)

INFO:searcharray.indexing:Tokenized 10000 (23.259059403637718%)

2026-05-20 13:03:45,671 - searcharray.indexing - INFO - Tokenized 20000 (46.518118807275435%)

INFO:searcharray.indexing:Tokenized 20000 (46.518118807275435%)

2026-05-20 13:03:46,049 - searcharray.indexing - INFO - Tokenized 30000 (69.77717821091315%)

INFO:searcharray.indexing:Tokenized 30000 (69.77717821091315%)

2026-05-20 13:03:46,415 - searcharray.indexing - INFO - Tokenized 40000 (93.03623761455087%)

INFO:searcharray.indexing:Tokenized 40000 (93.03623761455087%)

2026-05-20 13:03:46,702 - searcharray.indexing - INFO - Tokenization -- vstacking

INFO:searcharray.indexing:Tokenization -- vstacking

2026-05-20 13:03:46,711 - searcharray.indexing - INFO - Tokenization -- DONE

INFO:searcharray.indexing:Tokenization -- DONE

2026-05-20 13:03:46,725 - searcharray.indexing - INFO - Inverting docs->terms

INFO:searcharray.indexing:Inverting docs->terms

2026-05-20 13:03:46,775 - searcharray.indexing - INFO - Encoding positions to bit array

INFO:searcharray.indexing:Encoding positions to bit array

2026-05-20 13:03:46,832 - searcharray.indexing - INFO - Batch tokenization complete

INFO:searcharray.indexing:Batch tokenization complete

2026-05-20 13:03:46,834 - searcharray.indexing - INFO - (main thread) Processing 1 batch results

INFO:searcharray.indexing:(main thread) Processing 1 batch results

2026-05-20 13:03:46,873 - searcharray.indexing - INFO - Indexing from tokenization complete

INFO:searcharray.indexing:Indexing from tokenization complete

2026-05-20 13:03:46,904 - searcharray.indexing - INFO - Indexing begins w/ 4 workers

INFO:searcharray.indexing:Indexing begins w/ 4 workers

2026-05-20 13:03:46,918 - searcharray.indexing - INFO - 0 Batch Start tokenization

INFO:searcharray.indexing:0 Batch Start tokenization

2026-05-20 13:03:46,921 - searcharray.indexing - INFO - Tokenizing 42994 documents

INFO:searcharray.indexing:Tokenizing 42994 documents

2026-05-20 13:03:47,965 - searcharray.indexing - INFO - Tokenized 10000 (23.259059403637718%)

INFO:searcharray.indexing:Tokenized 10000 (23.259059403637718%)

2026-05-20 13:03:48,990 - searcharray.indexing - INFO - Tokenized 20000 (46.518118807275435%)

INFO:searcharray.indexing:Tokenized 20000 (46.518118807275435%)

2026-05-20 13:03:50,484 - searcharray.indexing - INFO - Tokenized 30000 (69.77717821091315%)

INFO:searcharray.indexing:Tokenized 30000 (69.77717821091315%)

2026-05-20 13:03:52,146 - searcharray.indexing - INFO - Tokenized 40000 (93.03623761455087%)

INFO:searcharray.indexing:Tokenized 40000 (93.03623761455087%)

2026-05-20 13:03:52,766 - searcharray.indexing - INFO - Tokenization -- vstacking

INFO:searcharray.indexing:Tokenization -- vstacking

2026-05-20 13:03:52,797 - searcharray.indexing - INFO - Tokenization -- DONE

INFO:searcharray.indexing:Tokenization -- DONE

2026-05-20 13:03:52,817 - searcharray.indexing - INFO - Inverting docs->terms

INFO:searcharray.indexing:Inverting docs->terms

2026-05-20 13:03:53,379 - searcharray.indexing - INFO - Encoding positions to bit array

INFO:searcharray.indexing:Encoding positions to bit array

2026-05-20 13:03:53,517 - searcharray.indexing - INFO - Batch tokenization complete

INFO:searcharray.indexing:Batch tokenization complete

2026-05-20 13:03:53,520 - searcharray.indexing - INFO - (main thread) Processing 1 batch results

INFO:searcharray.indexing:(main thread) Processing 1 batch results

2026-05-20 13:03:53,650 - searcharray.indexing - INFO - Indexing from tokenization complete

INFO:searcharray.indexing:Indexing from tokenization complete

2026-05-20 13:03:54,563 - searcharray.indexing - INFO - Indexing begins w/ 4 workers

INFO:searcharray.indexing:Indexing begins w/ 4 workers

2026-05-20 13:03:54,570 - searcharray.indexing - INFO - 0 Batch Start tokenization

INFO:searcharray.indexing:0 Batch Start tokenization

2026-05-20 13:03:54,572 - searcharray.indexing - INFO - Tokenizing 42994 documents

INFO:searcharray.indexing:Tokenizing 42994 documents

2026-05-20 13:03:54,718 - searcharray.indexing - INFO - Tokenized 10000 (23.259059403637718%)

INFO:searcharray.indexing:Tokenized 10000 (23.259059403637718%)

2026-05-20 13:03:54,922 - searcharray.indexing - INFO - Tokenized 20000 (46.518118807275435%)

INFO:searcharray.indexing:Tokenized 20000 (46.518118807275435%)

2026-05-20 13:03:55,166 - searcharray.indexing - INFO - Tokenized 30000 (69.77717821091315%)

INFO:searcharray.indexing:Tokenized 30000 (69.77717821091315%)

2026-05-20 13:03:55,471 - searcharray.indexing - INFO - Tokenized 40000 (93.03623761455087%)

INFO:searcharray.indexing:Tokenized 40000 (93.03623761455087%)

2026-05-20 13:03:55,648 - searcharray.indexing - INFO - Tokenization -- vstacking

INFO:searcharray.indexing:Tokenization -- vstacking

2026-05-20 13:03:55,651 - searcharray.indexing - INFO - Tokenization -- DONE

INFO:searcharray.indexing:Tokenization -- DONE

2026-05-20 13:03:55,653 - searcharray.indexing - INFO - Inverting docs->terms

INFO:searcharray.indexing:Inverting docs->terms

2026-05-20 13:03:55,660 - searcharray.indexing - INFO - Encoding positions to bit array

INFO:searcharray.indexing:Encoding positions to bit array

2026-05-20 13:03:55,665 - searcharray.indexing - INFO - Batch tokenization complete

INFO:searcharray.indexing:Batch tokenization complete

2026-05-20 13:03:55,667 - searcharray.indexing - INFO - (main thread) Processing 1 batch results

INFO:searcharray.indexing:(main thread) Processing 1 batch results

2026-05-20 13:03:55,684 - searcharray.indexing - INFO - Indexing from tokenization complete

INFO:searcharray.indexing:Indexing from tokenization complete

2026-05-20 13:03:55,695 - searcharray.indexing - INFO - Indexing begins w/ 4 workers

INFO:searcharray.indexing:Indexing begins w/ 4 workers

2026-05-20 13:03:55,703 - searcharray.indexing - INFO - 0 Batch Start tokenization

INFO:searcharray.indexing:0 Batch Start tokenization

2026-05-20 13:03:55,706 - searcharray.indexing - INFO - Tokenizing 42994 documents

INFO:searcharray.indexing:Tokenizing 42994 documents

2026-05-20 13:03:55,902 - searcharray.indexing - INFO - Tokenized 10000 (23.259059403637718%)

INFO:searcharray.indexing:Tokenized 10000 (23.259059403637718%)

2026-05-20 13:03:56,071 - searcharray.indexing - INFO - Tokenized 20000 (46.518118807275435%)

INFO:searcharray.indexing:Tokenized 20000 (46.518118807275435%)

2026-05-20 13:03:56,255 - searcharray.indexing - INFO - Tokenized 30000 (69.77717821091315%)

INFO:searcharray.indexing:Tokenized 30000 (69.77717821091315%)

2026-05-20 13:03:56,513 - searcharray.indexing - INFO - Tokenized 40000 (93.03623761455087%)

INFO:searcharray.indexing:Tokenized 40000 (93.03623761455087%)

2026-05-20 13:03:56,656 - searcharray.indexing - INFO - Tokenization -- vstacking

INFO:searcharray.indexing:Tokenization -- vstacking

2026-05-20 13:03:56,658 - searcharray.indexing - INFO - Tokenization -- DONE

INFO:searcharray.indexing:Tokenization -- DONE

2026-05-20 13:03:56,664 - searcharray.indexing - INFO - Inverting docs->terms

INFO:searcharray.indexing:Inverting docs->terms

2026-05-20 13:03:56,672 - searcharray.indexing - INFO - Encoding positions to bit array

INFO:searcharray.indexing:Encoding positions to bit array

2026-05-20 13:03:56,679 - searcharray.indexing - INFO - Batch tokenization complete

INFO:searcharray.indexing:Batch tokenization complete

2026-05-20 13:03:56,681 - searcharray.indexing - INFO - (main thread) Processing 1 batch results

INFO:searcharray.indexing:(main thread) Processing 1 batch results

2026-05-20 13:03:56,700 - searcharray.indexing - INFO - Indexing from tokenization complete

INFO:searcharray.indexing:Indexing from tokenization complete

2026-05-20 13:03:56,715 - searcharray.indexing - INFO - Indexing begins w/ 4 workers

INFO:searcharray.indexing:Indexing begins w/ 4 workers

2026-05-20 13:03:56,720 - searcharray.indexing - INFO - 0 Batch Start tokenization

INFO:searcharray.indexing:0 Batch Start tokenization

2026-05-20 13:03:56,726 - searcharray.indexing - INFO - Tokenizing 42994 documents

INFO:searcharray.indexing:Tokenizing 42994 documents

2026-05-20 13:03:56,936 - searcharray.indexing - INFO - Tokenized 10000 (23.259059403637718%)

INFO:searcharray.indexing:Tokenized 10000 (23.259059403637718%)

2026-05-20 13:03:57,108 - searcharray.indexing - INFO - Tokenized 20000 (46.518118807275435%)

INFO:searcharray.indexing:Tokenized 20000 (46.518118807275435%)

2026-05-20 13:03:57,309 - searcharray.indexing - INFO - Tokenized 30000 (69.77717821091315%)

INFO:searcharray.indexing:Tokenized 30000 (69.77717821091315%)

2026-05-20 13:03:57,593 - searcharray.indexing - INFO - Tokenized 40000 (93.03623761455087%)

INFO:searcharray.indexing:Tokenized 40000 (93.03623761455087%)

2026-05-20 13:03:57,825 - searcharray.indexing - INFO - Tokenization -- vstacking

INFO:searcharray.indexing:Tokenization -- vstacking

2026-05-20 13:03:57,829 - searcharray.indexing - INFO - Tokenization -- DONE

INFO:searcharray.indexing:Tokenization -- DONE

2026-05-20 13:03:57,839 - searcharray.indexing - INFO - Inverting docs->terms

INFO:searcharray.indexing:Inverting docs->terms

2026-05-20 13:03:57,857 - searcharray.indexing - INFO - Encoding positions to bit array

INFO:searcharray.indexing:Encoding positions to bit array

2026-05-20 13:03:57,873 - searcharray.indexing - INFO - Batch tokenization complete

INFO:searcharray.indexing:Batch tokenization complete

2026-05-20 13:03:57,876 - searcharray.indexing - INFO - (main thread) Processing 1 batch results

INFO:searcharray.indexing:(main thread) Processing 1 batch results

2026-05-20 13:03:57,912 - searcharray.indexing - INFO - Indexing from tokenization complete

INFO:searcharray.indexing:Indexing from tokenization complete

keywords='medium clips' hallucinated_classification=['Hardware / Fasteners & Clips / Medium Clips', 'Home Organization / Cable & Wire Management / Medium Clips', 'Craft Supplies / Clamps & Clips / Medium Clips', 'Office & Desk Accessories / Paper Clips / Medium Clips', 'Industrial Supplies / Clamping Devices / Medium Clips']
Home Improvement
Clips
Storage & Organization
Furniture

(array([36813, 37397, 11295, 34050, 36809, 37396, 27888, 37398, 27886,
        36810]),
 array([85.35794735, 84.99754143, 72.97011852, 68.97158527, 68.62535572,
        67.39479828, 66.84630013, 66.0164814 , 65.3701973 , 64.83574677]))

In [ ]:
# categorized_search.sub_category_boost = 0
# categorized_search.category_boost = 0
# categorized_search.cat_subcat_boost = 0
top_k, scores = categorized_search.search('medium clips')
matched_products = corpus.iloc[top_k].copy()
matched_products['score'] = scores


matched_products[['product_name', 'category hierarchy', 'score']]

keywords='medium clips' hallucinated_classification=['Hardware / Fasteners & Clips / Medium Clips', 'Home Organization / Cable & Wire Management / Medium Clips', 'Craft Supplies / Clamps & Clips / Medium Clips', 'Office & Desk Accessories / Paper Clips / Medium Clips', 'Industrial Supplies / Clamping Devices / Medium Clips']
Home Improvement
Clips
Storage & Organization
Furniture

,product_name,category hierarchy,score
36813,"gem paper clips , plastic , medium size , 500/box",Clips/Clamps,85.357947
37397,"medium binder clips , 24/pack",Clips/Clamps,84.997541
11295,jaliah dining table with clipped corner medium...,Furniture / Kitchen & Dining Furniture / Dinin...,72.970119
34050,monett 10 piece medium clip set,NaN,68.971585
36809,"medium binder clips , steel wire , 5/8 '' capa...",Clips/Clamps,68.625356
37396,"paper clips , coated , jumbo , 80 clips per pa...",Clips/Clamps,67.394798
27888,fitting clips,Storage & Organization / Closet Storage & Orga...,66.846300
37398,"binder clips , medium,1-1/4 '' wide,5/8 '' cap...",Clips/Clamps,66.016481
27886,fretwell plastic hangers with clips for skirt/...,Storage & Organization / Closet Storage & Orga...,65.370197
36810,"regal clips , 100/box",Clips/Clamps,64.835747

In [ ]:
graded_fully_classified = run_strategy(categorized_search, judgments)
graded_fully_classified

Searching:   0%|          | 0/480 [00:00<?, ?it/s]

keywords='certified international melamine' hallucinated_classification=['Kitchen & Tabletop / Kitchen Storage & Organization / Melamine Dinnerware & Serveware', 'Home Decor / Kitchen & Dining Accessories / Melamine Tableware', 'Furniture / Kitchen & Dining Furniture / Melamine Cabinets & Shelving', 'Outdoor / Outdoor Dining & Entertaining / Melamine Picnicware & Serveware', "Children's Tableware / Melamine Plates & Cups / Kids' Dining Sets"]

Searching:   0%|          | 1/480 [00:00<03:13,  2.47it/s]

Outdoor
Furniture
Kitchen & Tabletop
keywords='tile backsplash' hallucinated_classification=['Home Improvement / Kitchen Backsplash & Wall Coverings / Tile Backsplash']
Home Improvement
keywords='small ladies rocker swivel recliner' hallucinated_classification=['Furniture / Living Room Furniture / Recliners & Armchairs', 'Furniture / Kids & Teen Furniture / Kids Recliners', 'Furniture / Lounge & Accent Chairs / Swivel Chairs', 'Furniture / Small Space Furniture / Compact Recliners', 'Furniture / Specialty Chairs / Rocking & Glider Chairs']

Searching:   1%|          | 3/480 [00:00<02:10,  3.67it/s]

Outdoor
Furniture
keywords='brunk ship wheel' hallucinated_classification=['Decor & Wall Art / Nautical & Maritime Decor / Ship Wheel Wall Hangings', 'Furniture / Themed Furniture / Nautical & Maritime Themed Furniture', 'Home Decor / Accent Pieces / Nautical & Maritime Accents', 'Outdoor / Garden & Patio Decor / Nautical Garden Decor', 'Kids & Teens / Nautical & Maritime Bedroom Decor / Ship Wheel Wall Art']

Searching:   1%|          | 4/480 [00:01<02:29,  3.18it/s]

Baby & Kids
Outdoor
Furniture
Décor & Pillows
keywords='queen ann style living room chair' hallucinated_classification=['Furniture / Living Room Furniture / Accent Chairs / Queen Ann Style Chairs', 'Furniture / Vintage & Antique Furniture / Queen Ann Style Chairs', 'Furniture / Classic & Traditional Furniture / Queen Ann Style Living Room Chairs', 'Home Decor / Antique & Vintage Decor / Queen Ann Style Chairs', 'Furniture / Custom & Handmade Furniture / Queen Ann Style Chairs']

Searching:   1%|          | 5/480 [00:01<02:39,  2.98it/s]

Outdoor
Furniture
keywords='bedroom accessories' hallucinated_classification=['Furniture / Bedroom Accessories / Bedside Lamps', 'Furniture / Bedroom Accessories / Jewelry & Valet Trays', 'Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows', 'Furniture / Bedroom Accessories / Vanity Mirrors', 'Storage & Organization / Closet Organizers / Drawer Dividers', 'Lighting / Table Lamps / Bedroom Table Lamps', 'Furniture / Bedroom Accessories / Headboard Decor', 'Décor & Pillows / Wall Art / Bedroom Wall Decor']

Searching:   1%|▏         | 6/480 [00:02<03:21,  2.35it/s]

Lighting
Furniture
Décor & Pillows
Storage & Organization
keywords='oliver parsons' hallucinated_classification=['Furniture / Designer Collections / Oliver Parsons Collection', 'Furniture / Customizable Furniture / Oliver Parsons Modular Systems', 'Home Decor / Artistic Furniture / Oliver Parsons Artistic Pieces', 'Furniture / Statement Pieces / Oliver Parsons Unique Designs', 'Living Room Furniture / Oliver Parsons Sofas & Armchairs', 'Bedroom Furniture / Oliver Parsons Bed Frames & Headboards']

Searching:   1%|▏         | 7/480 [00:02<03:19,  2.37it/s]

Furniture
Décor & Pillows
keywords='farmhouse hood vent' hallucinated_classification=['Home Improvement / Kitchen & Cooking / Kitchen Ventilation & Exhaust Fans / Range Hoods', 'Home Improvement / Kitchen & Cooking / Kitchen Ventilation & Exhaust Fans / Wall-Mounted Range Hoods', 'Home Improvement / Kitchen & Cooking / Kitchen Ventilation & Exhaust Fans / Island Range Hoods', 'Decor & Home Accessories / Kitchen Decor / Kitchen Wall Art & Signs', 'Furniture / Kitchen & Dining / Kitchen Islands & Carts / Kitchen Carts with Ventilation']

Searching:   2%|▏         | 8/480 [00:02<02:58,  2.65it/s]

Home Improvement
Furniture
Décor & Pillows
Appliances
keywords='sancroft armchair' hallucinated_classification=['Furniture / Accent Chairs / Armchairs and Lounge Chairs', 'Furniture / Vintage & Retro Furniture / Mid-Century Modern Chairs', 'Furniture / Upholstered Furniture / Fabric Armchairs', 'Furniture / Living Room Furniture / Armchairs & Lounge Chairs', 'Furniture / Custom & Handmade Furniture / Artisan Armchairs']

Searching:   2%|▏         | 9/480 [00:03<02:40,  2.94it/s]

Furniture
keywords='bed side table' hallucinated_classification=['Furniture / Bedroom Furniture / Bedside Tables & Nightstands', 'Furniture / Bedroom Furniture / Bedside Storage Solutions', 'Furniture / Bedroom Furniture / Nightstand with Drawers', 'Furniture / Bedroom Furniture / Modern Bedside Tables', 'Furniture / Bedroom Furniture / Vintage Nightstands', 'Furniture / Bedroom Furniture / Minimalist Bedside Tables', 'Furniture / Bedroom Furniture / Multi-functional Nightstands']

Searching:   2%|▏         | 10/480 [00:03<02:44,  2.86it/s]

Furniture
keywords='coffee table fire pit' hallucinated_classification=['Outdoor / Fire Pits & Heaters / Fire Pits / Coffee Table Fire Pits', 'Furniture / Outdoor Furniture / Coffee Tables with Built-in Fire Features', 'Home & Garden / Patio & Garden Decor / Fire Pit Tables', 'Outdoor / Fire Features / Fire Table Coffee Tables', 'Furniture / Multi-Functional Tables / Fire Pit Coffee Tables']

Searching:   2%|▏         | 11/480 [00:03<02:30,  3.12it/s]

Outdoor
Furniture
keywords='48" sliding single track, barn door for laundry' hallucinated_classification=['Home Improvement / Doors & Windows / Barn Doors / Sliding Barn Doors', 'Furniture / Laundry Room Furniture / Laundry Room Doors & Partitions', 'Home Decor / Wall Partitions & Room Dividers / Sliding Room Dividers', 'Hardware / Closet & Door Hardware / Sliding Door Hardware', 'Smart Home / Home Automation / Motorized Door Systems']

Searching:   2%|▎         | 12/480 [00:04<02:22,  3.29it/s]

Home Improvement
Furniture
keywords='parsons chairs' hallucinated_classification=['Furniture / Dining Room Furniture / Dining Chairs / Parsons Chairs', 'Furniture / Living Room Furniture / Accent Chairs / Parsons Style Chairs', 'Furniture / Office Furniture / Conference & Meeting Room Chairs / Parsons Chairs', 'Furniture / Custom & Designer Furniture / Modern Chairs / Parsons Design', 'Furniture / Vintage & Retro Furniture / Mid-Century Chairs / Parsons Inspired']

Searching:   3%|▎         | 13/480 [00:04<02:14,  3.46it/s]

Furniture
keywords='hawaii vintage art' hallucinated_classification=['Decor & Wall Art / Vintage Art / Hawaii Vintage Art', 'Home Decor / Wall Hangings / Tropical & Hawaiian Themes', 'Art & Collectibles / Vintage Prints / Hawaiian Vintage Art', 'Furniture / Accent Pieces / Vintage Hawaiian Art-inspired Decor', 'Outdoor / Garden & Patio Decor / Hawaiian Vintage Art Prints']

Searching:   3%|▎         | 14/480 [00:04<02:21,  3.29it/s]

Outdoor
Décor & Pillows
keywords='3 1/2 inch drawer pull' hallucinated_classification=['Hardware / Cabinet Hardware / Drawer Pulls and Handles', 'Furniture / Kitchen & Bathroom Hardware / Drawer Pulls', 'Home Improvement / Furniture Hardware / Drawer Handles and Knobs', 'Decor & Accessories / Cabinet Hardware / Drawer Pulls', 'DIY & Tools / Furniture Hardware / Drawer Handles']

Searching:   3%|▎         | 15/480 [00:04<02:20,  3.30it/s]

Home Improvement
keywords='outdoor sectional dining' hallucinated_classification=['Outdoor / Outdoor Dining & Entertaining / Outdoor Sectional Sets / Outdoor Sectional Dining Sets', 'Furniture / Patio & Garden Furniture / Sectional Sofas / Outdoor Sectional Sofas', 'Outdoor / Outdoor Furniture Accessories / Outdoor Cushions & Pillows / Outdoor Cushions for Sectionals', 'Home & Garden / Garden Decor / Outdoor Dining Accessories / Outdoor Dining Table Accessories', 'Outdoor / Outdoor Kitchen & Dining / Outdoor Dining Tables & Chairs / Outdoor Dining Sets']

Searching:   3%|▎         | 16/480 [00:05<02:28,  3.13it/s]

Outdoor
Décor & Pillows
keywords='tollette teal outdoor rug' hallucinated_classification=['Outdoor / Outdoor Rugs & Mats / Area Rugs / Teal Outdoor Rugs', 'Home Decor / Rugs / Teal Rugs / Outdoor Teal Rugs', 'Garden & Patio / Patio Accessories / Outdoor Rugs / Teal Patio Rugs', 'Furniture / Outdoor Furniture / Outdoor Rugs & Mats / Teal Outdoor Rugs', 'Decor & Pillows / Rug Accessories / Outdoor Rugs / Teal']

Searching:   4%|▎         | 17/480 [00:05<02:35,  2.97it/s]

Furniture
Décor & Pillows
Rugs
keywords='gray dresser' hallucinated_classification=['Furniture / Bedroom Furniture / Dressers & Chests / Modern Gray Dressers', 'Furniture / Storage & Organization / Wardrobes & Armoires / Gray Wardrobes', 'Furniture / Kids & Teens Furniture / Kids Dressers / Gray Kids Dressers', 'Furniture / Entryway Furniture / Console Tables & Storage / Gray Entryway Dressers', 'Furniture / Custom Furniture / Handmade Gray Dressers']

Searching:   4%|▍         | 18/480 [00:06<02:32,  3.03it/s]

Baby & Kids
Furniture
keywords='non slip shower floor tile' hallucinated_classification=['Home Improvement / Bathroom Renovation / Shower Flooring & Tiles / Non-Slip Shower Floor Tiles', 'Bathroom Accessories / Shower Safety / Non-Slip Shower Surfaces', 'Building Materials / Tiling & Flooring / Shower Floor Tiles / Non-Slip Coated Tiles', 'Smart Home / Bathroom Safety Devices / Non-Slip Shower Surfaces', 'Outdoor / Pool & Spa Accessories / Non-Slip Poolside Tiles']

Searching:   4%|▍         | 19/480 [00:06<02:26,  3.16it/s]

Outdoor
Home Improvement
Bed & Bath
keywords='grill cover 73' hallucinated_classification=['Outdoor / Outdoor Cooking & Grilling / Grill Accessories / Grill Covers', 'Home & Garden / Patio & Garden Furniture / Outdoor Furniture Accessories / Grill Covers', 'Kitchen & Dining / Outdoor Cooking / Grill Accessories / Protective Covers for Grills', 'Garden & Outdoor Living / Barbecue & Grilling / Grill Accessories / Coverings for Grills']

Searching:   4%|▍         | 20/480 [00:06<02:20,  3.28it/s]

Outdoor
Storage & Organization
Appliances
keywords='e12/candelabra' hallucinated_classification=['Lighting / Decorative Lighting / Candelabras and Candle Holders', 'Home Decor / Tabletop Decor / Candle Holders and Candelabras', 'Event & Party Supplies / Centerpieces / Candle Holders', 'Furniture / Dining Room Furniture / Dining Table Accessories / Candelabras']

Searching:   4%|▍         | 21/480 [00:06<02:14,  3.42it/s]

Furniture
Décor & Pillows
keywords='window wall accent' hallucinated_classification=['Home Decor / Wall Accents / Window Wall Art', 'Interior Design / Wall Treatments / Window Wall Coverings', 'Furniture / Wall Installations / Decorative Window Panels', 'Home Improvement / Window Enhancements / Accent Window Frames', 'Architectural Elements / Wall Features / Window Wall Molding']

Searching:   5%|▍         | 22/480 [00:07<02:11,  3.49it/s]

Home Improvement
Décor & Pillows
keywords='annex dresser' hallucinated_classification=['Furniture / Bedroom Furniture / Dressers & Chests / Annex Dressers', 'Furniture / Storage Solutions / Closet & Wardrobe Storage / Annex Wardrobes', 'Home Organization / Bedroom Storage / Annex Storage Units', 'Furniture / Custom & Modular Furniture / Annex Furniture Systems', 'Interior Design / Space Optimization / Annex Room Solutions']

Searching:   5%|▍         | 23/480 [00:07<02:05,  3.63it/s]

Furniture
Storage & Organization
keywords='candace wingback upholstered bed' hallucinated_classification=['Furniture / Bedroom Furniture / Upholstered Beds / Wingback Beds', 'Furniture / Bedroom Furniture / Upholstered Beds / Tufted Beds', 'Furniture / Bedroom Furniture / Canopy & Four-Poster Beds', 'Furniture / Bedroom Furniture / Platform Beds with Upholstery', 'Furniture / Bedroom Furniture / Custom Upholstered Bed Frames']

Searching:   5%|▌         | 24/480 [00:07<02:03,  3.68it/s]

Furniture
keywords='flour and sugar containers' hallucinated_classification=['Kitchen & Tabletop / Food Storage & Canisters / Flour and Sugar Containers', 'Kitchen & Tabletop / Baking Supplies / Flour and Sugar Storage Jars', 'Home Organization / Pantry Storage / Flour and Sugar Dispensers', 'Kitchen & Dining / Kitchen Storage / Flour and Sugar Canisters', 'Cooking & Baking / Baking Accessories / Flour and Sugar Containers']

Searching:   5%|▌         | 25/480 [00:07<02:03,  3.69it/s]

Kitchen & Tabletop
keywords='48 inch kitchen hood' hallucinated_classification=['Home Appliances / Kitchen Ventilation / Range Hoods / 48 Inch Kitchen Hoods', 'Kitchen & Tabletop / Kitchen Ventilation / Wall-Mounted Range Hoods / 48 Inch Models', 'Home Improvement / Kitchen & Cooking / Kitchen Exhaust & Ventilation / 48 Inch Range Hoods', 'Cooking & Baking / Kitchen Ventilation Equipment / 48 Inch Kitchen Hoods']

Searching:   5%|▌         | 26/480 [00:08<01:56,  3.90it/s]

Home Improvement
Appliances
keywords='croscill ashton' hallucinated_classification=['Bedding & Linens / Comforter Sets / Ashton Collection', 'Home Decor / Wall Art / Ashton Theme Art', 'Furniture / Bedroom Furniture / Ashton Bed Frames', 'Textiles & Curtains / Window Treatments / Ashton Drapes', 'Decorative Accessories / Tabletop Decor / Ashton Inspired Ornaments', 'Home Fragrance / Scented Candles / Ashton Scent Line', 'Luxury Bedding / Pillow Shams / Ashton Embroidered Shams']

Searching:   6%|▌         | 27/480 [00:08<02:08,  3.52it/s]

Bed & Bath
Décor & Pillows
Furniture
keywords='bowersville ladder writing desk' hallucinated_classification=['Furniture / Desks / Writing Desks', 'Furniture / Home Office Furniture / Desks & Workstations', 'Furniture / Entryway Furniture / Hall Trees & Entryway Desks', 'Furniture / Kids & Teen Furniture / Kids Desks & Study Tables', 'Furniture / Vintage & Antique Furniture / Ladder Desks & Bookcases', 'Home Office / Desks & Tables / Ladder Style Desks']

Searching:   6%|▌         | 28/480 [00:08<02:14,  3.36it/s]

Baby & Kids
Furniture
keywords='mobley zero gravity adjustable bed with wireless remote' hallucinated_classification=['Furniture / Bedroom Furniture / Adjustable Beds / Zero Gravity Beds', 'Furniture / Bedroom Furniture / Adjustable Beds / Wireless Remote Controlled Beds', 'Home Automation / Smart Furniture / Adjustable Beds with Wireless Control', 'Health & Wellness / Sleep & Comfort / Zero Gravity Sleep Systems']

Searching:   6%|▌         | 29/480 [00:09<02:27,  3.06it/s]

Bed & Bath
Furniture
keywords='salon chair' hallucinated_classification=['Furniture / Salon & Barber Chairs / Salon Chairs', 'Furniture / Styling & Barber Stations / Salon Stations', 'Furniture / Waiting Area Seating / Lounge Chairs for Salons', 'Furniture / Salon Equipment / Hair Styling Chairs', 'Furniture / Spa & Wellness Furniture / Massage & Treatment Chairs']

Searching:   6%|▋         | 30/480 [00:09<02:47,  2.69it/s]

Outdoor
Furniture
keywords='maryford queen tufted bed' hallucinated_classification=['Furniture / Bedroom Furniture / Beds / Upholstered Beds', 'Furniture / Bedroom Furniture / Bed Frames / Tufted Bed Frames', 'Luxury Furniture / Customizable Beds / Queen Size Tufted Beds', 'Home Decor / Bed Accessories / Upholstered Headboards', 'Furniture / Bedroom Furniture / Canopy & Four-Poster Beds']

Searching:   6%|▋         | 31/480 [00:10<02:55,  2.56it/s]

Furniture
keywords='ombre rug' hallucinated_classification=['Home Decor / Rugs & Carpets / Area Rugs / Ombre Rugs', 'Furniture / Floor Coverings / Rugs / Gradient Pattern Rugs', 'Decor & Pillows / Decorative Rugs / Color Gradient Rugs', 'Interior Design / Wall & Floor Coverings / Artistic Rugs / Ombre Style', 'Home Improvement / Flooring / Area Rugs / Color Fade Rugs']

Searching:   7%|▋         | 32/480 [00:10<03:11,  2.34it/s]

Décor & Pillows
Rugs
keywords='alter furniture' hallucinated_classification=['Furniture / Customizable Furniture / Modular Furniture Systems', 'Furniture / DIY Furniture Kits / Build-Your-Own Furniture Sets', 'Furniture / Upcycled & Repurposed Furniture / Vintage Furniture Makeovers', 'Furniture / Smart Furniture / Tech-Integrated Furniture', 'Furniture / Multi-Functional Furniture / Space-Saving Solutions', 'Furniture / Artistic & Sculptural Furniture / Statement Pieces', 'Furniture / Eco-Friendly Furniture / Sustainable Materials']

Searching:   7%|▋         | 33/480 [00:11<03:09,  2.36it/s]

Furniture
keywords='full bed with trundle' hallucinated_classification=['Furniture / Bedroom Furniture / Beds / Full Beds with Trundle', 'Kids & Teen Furniture / Beds / Trundle Beds', 'Custom Furniture / Modular Bedroom Sets / Beds with Integrated Trundle', 'Luxury Furniture / Designer Bedroom Sets / Full Beds with Hidden Trundle Storage', 'Convertible Furniture / Multi-Function Beds / Full Bed with Pull-Out Trundle']

Searching:   7%|▋         | 34/480 [00:11<02:48,  2.65it/s]

Baby & Kids
Furniture
keywords='minnestrista' hallucinated_classification=['Furniture / Bedroom Furniture / Bed Frames and Headboards', 'Home Decor / Wall Art and Murals', 'Furniture / Living Room Furniture / Sectional Sofas', 'Outdoor / Garden Furniture / Lounge Chairs', 'Home Improvement / Storage Solutions / Closet Organizers', 'Lighting / Floor Lamps and Reading Lights', 'Kitchen & Dining / Bar Stools and Counter Chairs', 'Kids & Baby / Nursery Furniture / Cribs and Changing Tables']

Searching:   7%|▋         | 35/480 [00:11<02:48,  2.65it/s]

Baby & Kids
Décor & Pillows
Outdoor
Furniture
Lighting
Storage & Organization
keywords='tall storage cabinet' hallucinated_classification=['Furniture / Storage & Organization / Tall Cabinets & Cupboards', 'Home Office / Storage Cabinets / Tall Storage Units', 'Garage & Workshop / Storage Cabinets / Tall Utility Cabinets', 'Entryway / Coat & Shoe Storage / Tall Cabinets', 'Bathroom / Linen & Storage Cabinets / Tall Bathroom Cabinets', 'Kitchen / Pantry & Storage / Tall Kitchen Cabinets', 'Living Room / Storage & Display / Tall Storage Cabinets']

Searching:   8%|▊         | 36/480 [00:12<02:41,  2.76it/s]

Storage & Organization
Kitchen & Tabletop
Furniture
keywords='real touch roses floral arrangements in glass vase' hallucinated_classification=['Home Decor / Artificial Flowers & Plants / Real Touch Roses', 'Floral Arrangements / Preserved & Dried Flowers / Glass Vase Arrangements', 'Event & Party Supplies / Floral Centerpieces / Real Touch Roses in Vases', 'Gift & Specialty Items / Floral Gifts / Real Touch Roses in Glass Vases', 'Interior Design / Wall & Tabletop Decor / Floral Arrangements in Glass Vases']

Searching:   8%|▊         | 37/480 [00:12<02:26,  3.02it/s]

Décor & Pillows
keywords='star wars rug' hallucinated_classification=['Décor & Pillows / Rugs & Carpets / Themed Rugs', 'Kids & Baby Furniture / Kids Room Decor / Themed Rugs', 'Home Decor / Wall & Floor Decor / Themed Floor Coverings', 'Collectibles & Memorabilia / Movie & TV Show Memorabilia / Star Wars Rugs']

Searching:   8%|▊         | 38/480 [00:12<02:12,  3.34it/s]

Baby & Kids
Home Improvement
Rugs
keywords='garage door mail slot' hallucinated_classification=['Home Improvement / Garage & Door Accessories / Mail Slots & Mailboxes / Garage Door Mail Slots', 'Security & Safety / Home Security / Mail Slot Locks & Covers / Garage Door Mail Slots', 'Outdoor / Garage & Driveway / Garage Door Accessories / Mail Slots for Garage Doors', 'Architectural Elements / Exterior Features / Mail Slots / Garage Door Mail Slots']

Searching:   8%|▊         | 39/480 [00:12<02:02,  3.61it/s]

Outdoor
Home Improvement
Storage & Organization
keywords='chrome bathroom 4 light vanity light' hallucinated_classification=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanity Lighting / Vanity Light Fixtures', 'Lighting / Bathroom Vanity Lights / 4-Light Chrome Vanity Fixtures', 'Hardware / Bathroom Hardware / Vanity Lighting / Chrome Bathroom Lights', 'Decor & Accessories / Bathroom Decor / Vanity Lighting Accessories']
Lighting
Home Improvement
Décor & Pillows

Searching:   8%|▊         | 40/480 [00:12<01:52,  3.91it/s]

keywords='iittala bowl' hallucinated_classification=['Kitchen & Tabletop / Serveware & Dinnerware / Bowls & Serving Dishes', 'Decor & Pillows / Decorative Accents / Artisanal Ceramics', 'Home Decor / Wall Art & Sculptures / Ceramic Wall Hangings', 'Furniture / Display & Storage / Shelving & Racks / Decorative Shelving', 'Outdoor / Garden Decor / Ceramic Garden Ornaments']
Décor & Pillows
Storage & Organization
Kitchen & Tabletop

Searching:   9%|▊         | 41/480 [00:13<01:54,  3.82it/s]

keywords='board game storage cabinet' hallucinated_classification=['Furniture / Storage & Organization / Game & Media Storage / Board Game Cabinets', 'Furniture / Living Room Furniture / Entertainment & Media Cabinets', 'Home Organization / Closet & Cabinet Organizers / Game Storage Solutions', 'Kids & Teens Furniture / Game & Toy Storage / Board Game Shelves', 'Decor & Accessories / Themed Storage / Game Night Storage Cabinets']
Baby & Kids

Searching:   9%|▉         | 42/480 [00:13<02:00,  3.63it/s]

Furniture
Storage & Organization
keywords='filaret outdoor sofa' hallucinated_classification=['Outdoor / Outdoor Sofas & Sectionals / Modular Outdoor Sofas', 'Furniture / Patio & Garden Furniture / Outdoor Lounge Chairs', 'Outdoor / Patio Furniture Accessories / Outdoor Cushion Sets', 'Furniture / Garden & Patio Furniture / Wicker & Rattan Sofas', 'Outdoor / Weatherproof Furniture / All-Weather Outdoor Sofas']

Searching:   9%|▉         | 43/480 [00:13<01:55,  3.78it/s]

Outdoor
keywords='twin over full bunk beds cool designs' hallucinated_classification=['Furniture / Kids & Teen Bedroom Furniture / Bunk Beds & Loft Beds', 'Furniture / Bedroom Furniture / Bunk Beds', 'Furniture / Kids & Teen Bedroom Furniture / Multi-Functional Beds', 'Furniture / Space-Saving Furniture / Convertible & Modular Beds', 'Furniture / Custom & Designer Furniture / Unique Bunk Bed Designs']

Searching:   9%|▉         | 44/480 [00:14<01:52,  3.86it/s]

Baby & Kids
Furniture
keywords='door jewelry organizer' hallucinated_classification=['Home Organization / Entryway & Mudroom Storage / Door-mounted Storage & Hooks / Door Jewelry Organizer', 'Furniture / Entryway Furniture / Wall-mounted Storage / Door Jewelry Organizer', 'Decor & Accessories / Wall Decor / Functional Wall Art / Door Jewelry Organizer', 'Home Improvement / Closet & Wardrobe Accessories / Jewelry & Accessory Storage / Door Jewelry Organizer', 'Storage & Organization / Wall-mounted Storage / Jewelry & Accessory Holders / Door Jewelry Organizer']

Searching:   9%|▉         | 45/480 [00:14<01:56,  3.75it/s]

Home Improvement
Storage & Organization
Décor & Pillows
Furniture
keywords='golub dining table' hallucinated_classification=['Furniture / Dining Room Furniture / Dining Tables / Modern Dining Tables', 'Furniture / Kitchen & Dining / Extendable Dining Tables', 'Furniture / Custom & Designer Furniture / Handcrafted Dining Tables', 'Furniture / Eco-Friendly & Sustainable Furniture / Reclaimed Wood Dining Tables', 'Furniture / Luxury & High-End Furniture / Designer Dining Tables']

Searching:  10%|▉         | 46/480 [00:14<01:55,  3.74it/s]

Outdoor
Furniture
keywords='rock climbing wall kids' hallucinated_classification=["Kids' Playroom Equipment / Climbing Walls and Play Structures / Indoor Climbing Walls for Kids", "Children's Fitness & Activity Equipment / Climbing and Adventure Gear / Kids' Climbing Walls", "Kids' Room Decor & Accessories / Themed Play Walls / Rock Climbing Wall Murals for Kids' Rooms", 'Educational & Developmental Toys / Physical Activity Toys / Climbing Wall Kits for Kids', "Outdoor Play Equipment / Climbing Structures / Kids' Outdoor Climbing Walls"]

Searching:  10%|▉         | 47/480 [00:14<01:56,  3.73it/s]

Baby & Kids
Outdoor
keywords='46 inch closet door' hallucinated_classification=['Home Improvement / Doors & Windows / Closet Doors / 46 Inch Closet Doors', 'Furniture / Bedroom Furniture / Closet Doors', 'Home Renovation / Storage Solutions / Closet Doors', 'Interior Design / Space Planning / Closet Doors', 'Building Materials / Doors / Closet Doors']

Searching:  10%|█         | 48/480 [00:15<01:50,  3.92it/s]

Home Improvement
Furniture
Storage & Organization
keywords='papasan chair frame only' hallucinated_classification=['Furniture / Lounge & Accent Chairs / Papasan Chairs / Frames']
Furniture
keywords='monthly calendar' hallucinated_classification=['Home Office & Organization / Desk Accessories / Monthly Planners and Calendars', 'Wall Decor / Calendar Art / Monthly Calendar Prints', 'Stationery & Office Supplies / Calendars / Monthly Wall Calendars', 'Living Room Decor / Wall Art / Calendar-themed Wall Hangings', 'Bedroom Decor / Bedside Accessories / Calendar Clocks']

Searching:  10%|█         | 50/480 [00:15<01:31,  4.68it/s]

Décor & Pillows
keywords='alyse 8 light' hallucinated_classification=['Lighting / Chandeliers & Pendant Lights / Multi-Light Chandeliers', 'Lighting / Ceiling Lights / Modern LED Ceiling Fixtures', 'Home Decor / Artistic Light Installations / Sculptural Light Art', 'Furniture / Customizable Lighting Furniture / Modular Light Tables', 'Smart Home / Connected Lighting / App-Controlled Multi-Light Systems']

Searching:  11%|█         | 51/480 [00:15<01:36,  4.47it/s]

Lighting
keywords='oriental vanity' hallucinated_classification=['Furniture / Bedroom Furniture / Vanities & Makeup Tables', 'Furniture / Entryway Furniture / Console Tables & Hall Trees', 'Decor & Pillows / Decorative Accessories / Oriental Style Decor', 'Furniture / Custom & Artistic Furniture / Handcrafted Vanities', 'Home Decor / Cultural & Themed Decor / Oriental Inspired Decor']

Searching:  11%|█         | 52/480 [00:15<01:38,  4.33it/s]

Furniture
Décor & Pillows
keywords='dining room tables' hallucinated_classification=['Furniture / Dining Room Furniture / Dining Tables & Sets / Extendable Dining Tables', 'Furniture / Kitchen & Dining Furniture / Kitchen & Dining Room Tables / Rustic Wooden Dining Tables', 'Furniture / Custom Furniture / Handcrafted Dining Tables / Live Edge Dining Tables', 'Furniture / Modern Furniture / Minimalist Dining Tables / Glass Top Dining Tables', 'Furniture / Vintage & Antique Furniture / Retro Dining Tables / Mid-Century Modern Dining Tables', 'Furniture / Eco-Friendly Furniture / Sustainable Dining Tables / Reclaimed Wood Dining Tables']

Searching:  11%|█         | 53/480 [00:16<02:14,  3.17it/s]

Outdoor
Furniture
keywords='wood bar stools' hallucinated_classification=['Furniture / Kitchen & Dining Furniture / Bar Stools & Counter Stools / Wooden Bar Stools', 'Furniture / Home Bar & Entertainment / Bar Furniture / Wooden Bar Stools', 'Furniture / Commercial & Restaurant Furniture / Bar Seating / Wooden Bar Stools', 'Furniture / Outdoor Furniture / Patio Bar Stools / Wooden Bar Stools', 'Furniture / Custom & Designer Furniture / Handmade Wooden Bar Stools']

Searching:  11%|█▏        | 54/480 [00:16<02:26,  2.91it/s]

Outdoor
Furniture
keywords='meade mirror' hallucinated_classification=['Decor & Wall Art / Mirrors / Decorative Wall Mirrors', 'Furniture / Entryway Furniture / Hallway Mirrors & Consoles', 'Home Improvement / Wall Decor / Mirror Frames & Accessories', 'Luxury Home Goods / Designer Mirrors / Statement Mirrors', 'Smart Home / Connected Mirrors / Smart Bathroom Mirrors']

Searching:  11%|█▏        | 55/480 [00:17<02:26,  2.90it/s]

Lighting
Décor & Pillows
keywords='edge chair mat' hallucinated_classification=['Home Office & Desk Accessories / Chair Mats / Edge Chair Mats', 'Furniture / Office Furniture / Desk Accessories / Chair Mats', 'Flooring & Carpets / Area Rugs / Chair Mat Rugs', 'Home Improvement / Floor Coverings / Chair Mat Pads', 'Workspace Accessories / Office Comfort / Chair Mat Solutions']

Searching:  12%|█▏        | 56/480 [00:17<02:24,  2.94it/s]

Furniture
Rugs
keywords='bathroom vanity with counter space' hallucinated_classification=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / Double Sink Bathroom Vanities', 'Furniture / Bathroom Furniture / Bathroom Vanities with Counter Space', 'Home Decor / Bathroom Accessories / Vanity Mirrors and Countertops', 'Kitchen & Bath / Vanity Units / Customizable Bathroom Vanities', 'Smart Home / Bathroom Tech / Automated Vanity Mirrors and Lighting']

Searching:  12%|█▏        | 57/480 [00:17<02:18,  3.05it/s]

Lighting
Home Improvement
Furniture
Décor & Pillows
keywords='48 in entry table with side by side drawer' hallucinated_classification=['Furniture / Entryway Furniture / Console Tables with Drawers', 'Furniture / Entryway Storage / Entry Tables with Side-by-Side Drawers', 'Home Organization / Entryway Storage Solutions / Entry Tables with Dual Drawers', 'Furniture / Hallway & Entryway Furniture / Narrow Entry Tables with Drawers', 'Furniture / Multi-Functional Tables / Entry Tables with Storage Compartments']

Searching:  12%|█▏        | 58/480 [00:18<02:20,  3.00it/s]

Furniture
Storage & Organization
keywords='pedistole sink' hallucinated_classification=['Home Improvement / Bathroom Fixtures / Pedestal Sinks', 'Furniture / Bathroom Furniture / Pedestal Sinks', 'Decor & Accessories / Bathroom Decor / Pedestal Sink Mounts', 'Kitchen & Bath / Vanity & Sink Accessories / Pedestal Sink Trims', 'Smart Home / Bathroom Automation / Pedestal Sink Sensors']

Searching:  12%|█▏        | 59/480 [00:18<02:16,  3.08it/s]

Home Improvement
Furniture
keywords='led light strip' hallucinated_classification=['Lighting / LED & Smart Lights / LED Light Strips and Tape', 'Home Decor / Ambient & Mood Lighting / LED Accent Lighting', 'Electronics / Smart Home Devices / Smart LED Light Strips', 'Furniture / Home Office / Under-Desk Lighting Solutions', 'Outdoor / Garden & Landscape Lighting / LED Garden Lights']

Searching:  12%|█▎        | 60/480 [00:18<02:12,  3.16it/s]

Lighting
Holiday Décor
keywords='elephant framed' hallucinated_classification=['Decor / Wall Art / Framed Animal Prints', "Children's Room Decor / Elephant Theme Decorations / Framed Elephant Art", 'Nursery & Kids Room Furniture / Themed Wall Hangings / Elephant Frames', 'Art & Collectibles / Framed Animal Artwork / Elephant Motifs', 'Gift & Novelty Items / Framed Elephant Illustrations']

Searching:  13%|█▎        | 61/480 [00:19<02:16,  3.08it/s]

Baby & Kids
Décor & Pillows
keywords='living room coffee table sets' hallucinated_classification=['Furniture / Living Room Furniture / Coffee Tables & Sets / Coffee Table Sets', 'Furniture / Living Room Furniture / Coffee Tables / Modular Coffee Tables', 'Furniture / Living Room Furniture / Coffee Tables / Vintage & Retro Coffee Tables', 'Furniture / Living Room Furniture / Coffee Tables / Contemporary Coffee Tables', 'Furniture / Living Room Furniture / Coffee Tables / Multi-functional Coffee Tables', 'Furniture / Living Room Furniture / Coffee Tables / Glass Top Coffee Tables']

Searching:  13%|█▎        | 62/480 [00:19<02:33,  2.72it/s]

Furniture
keywords='dorel vanity' hallucinated_classification=['Furniture / Bathroom Furniture / Bathroom Vanities', 'Furniture / Bedroom Furniture / Vanities & Makeup Tables', 'Home Decor / Vanity Mirrors & Accessories', 'Furniture / Custom & Modular Vanities / Dorel Vanity Series', 'Home Improvement / Bathroom Remodel & Fixtures / Vanity Cabinets']

Searching:  13%|█▎        | 63/480 [00:19<02:24,  2.88it/s]

Home Improvement
Furniture
Décor & Pillows
keywords='orren ellis l shaped desk' hallucinated_classification=['Furniture / Office Furniture / Desks / L-Shaped Desks', 'Furniture / Home Office / Desks & Workstations / L-Shaped Desks', 'Furniture / Executive & Conference Room Furniture / Desks / L-Shaped Desks', 'Home Office / Desks & Workstations / L-Shaped Desks', 'Furniture / Modern & Contemporary Furniture / Desks / L-Shaped Desks']

Searching:  13%|█▎        | 64/480 [00:20<02:15,  3.06it/s]

Baby & Kids
Furniture
keywords='outdoor seat/back cushion' hallucinated_classification=['Outdoor / Outdoor & Patio Furniture / Cushions & Pillows / Seat Cushions', 'Furniture / Patio Furniture / Outdoor Cushions & Pillows / Seat Back Cushions', 'Home Decor / Outdoor Decor / Cushions & Pillows / Seat Cushions', 'Garden & Patio / Garden Seating / Cushions & Pillows / Back Cushions', 'Outdoor Living / Outdoor Furniture Accessories / Cushions / Seat & Back Cushions']

Searching:  14%|█▎        | 65/480 [00:20<02:07,  3.25it/s]

Outdoor
Décor & Pillows
keywords='moen 5995 arbor one' hallucinated_classification=['Home Improvement / Bathroom Fixtures / Shower Systems / Shower Valves', 'Kitchen & Tabletop / Kitchen Fixtures / Kitchen Faucets', 'Bathroom Accessories / Shower & Bathtub Accessories / Shower Heads']
Home Improvement

Searching:  14%|█▍        | 66/480 [00:20<01:49,  3.80it/s]

keywords='kohler purist brushed bronze' hallucinated_classification=['Home Improvement / Bathroom Fixtures / Bathroom Faucets / Kohler Purist Brushed Bronze Faucets', 'Kitchen & Tabletop / Kitchen Fixtures / Kitchen Faucets / Brushed Bronze Kitchen Faucets', 'Decor & Pillows / Decorative Accents / Brushed Bronze Home Decor', 'Lighting / Bathroom Lighting / Vanity Lights / Brushed Bronze Finish', 'Furniture / Bathroom Furniture / Vanity Units / Brushed Bronze Finish', 'Hardware / Door Handles & Knobs / Brushed Bronze Finish']

Searching:  14%|█▍        | 67/480 [00:20<01:56,  3.55it/s]

Lighting
Home Improvement
Furniture
Décor & Pillows
keywords='nautical platters' hallucinated_classification=['Home & Kitchen / Kitchenware / Serving Platters & Trays / Nautical Themed Platters', 'Decor & Wall Art / Nautical & Marine Decor / Nautical Themed Wall Hangings', 'Outdoor / Patio & Garden Decor / Nautical Garden Decor / Nautical Themed Garden Accents', 'Tabletop & Dining / Tableware / Decorative Serving Dishes / Nautical Style Platters', 'Gift & Specialty Items / Nautical Gift Items / Nautical Themed Home Goods']

Searching:  14%|█▍        | 68/480 [00:21<02:05,  3.29it/s]

Décor & Pillows
Outdoor
Kitchen & Tabletop
keywords='fold in half table' hallucinated_classification=['Furniture / Space-Saving & Multi-Functional Furniture / Foldable & Collapsible Tables', 'Home Office / Compact & Portable Desks / Foldaway Desks', 'Outdoor / Portable & Folding Furniture / Folding Picnic Tables', 'Event & Party Supplies / Folding Tables for Events / Collapsible Event Tables', 'Kids & Teens / Space-Saving Furniture / Foldable Study Desks & Tables']

Searching:  14%|█▍        | 69/480 [00:21<02:20,  2.93it/s]

School Furniture and Supplies
Outdoor
Furniture
keywords='small loving roomtables' hallucinated_classification=['Furniture / Living Room Furniture / Coffee Tables & End Tables / Small Loving Roomtables', 'Furniture / Coffee & Side Tables / Compact Living Room Tables', 'Home Decor / Small Space Furniture / Loveseat Tables', 'Furniture / Multi-Functional Tables / Small Living Room Surfaces', 'Furniture / Customizable Living Room Tables / Personalized Small Tables']

Searching:  15%|█▍        | 70/480 [00:22<02:24,  2.85it/s]

Furniture
Décor & Pillows
keywords='medium clips' hallucinated_classification=['Hardware / Fasteners & Clips / Medium Clips', 'Home Organization / Cable & Wire Management / Medium Clips', 'Craft Supplies / Clamps & Clips / Medium Clips', 'Office & Desk Accessories / Paper Clips / Medium Clips', 'Industrial Supplies / Clamping Devices / Medium Clips']

Searching:  15%|█▍        | 71/480 [00:22<02:11,  3.11it/s]

Home Improvement
Clips
Storage & Organization
Furniture
keywords='palram harmony greenhouses' hallucinated_classification=['Garden & Outdoor / Greenhouses & Plant Shelters / Polycarbonate Greenhouses', 'Home Improvement / Garden Structures / Greenhouse Kits', 'Garden & Outdoor / Plant Care & Gardening Supplies / Greenhouse Accessories', 'Outdoor Living / Garden & Patio / Greenhouse Furniture & Equipment', 'Horticulture / Greenhouse Climate Control / Ventilation & Heating Systems']

Searching:  15%|█▌        | 72/480 [00:22<02:01,  3.35it/s]

Outdoor
keywords='memory foam rug galveston' hallucinated_classification=['Home Decor / Rugs & Carpets / Memory Foam Rugs', 'Furniture / Area Rugs / Memory Foam Rugs / Galveston Collection', 'Home Improvement / Flooring / Memory Foam Floor Coverings', 'Decor & Pillows / Memory Foam Mats / Galveston Style']

Searching:  15%|█▌        | 73/480 [00:22<01:50,  3.70it/s]

Furniture
Décor & Pillows
Rugs
keywords='industrial' hallucinated_classification=['Furniture / Industrial Style Furniture / Industrial Coffee Tables', 'Furniture / Industrial Style Lighting / Pendant Lights', 'Decor & Pillows / Industrial Decor / Metal Wall Art', 'Home Improvement / Industrial Kitchen Fixtures / Metal Sinks', 'Outdoor / Industrial Garden Furniture / Metal Patio Chairs', 'Storage & Organization / Industrial Shelving / Metal Wall Shelves', 'Lighting / Industrial Floor Lamps / Metal Floor Lamps']

Searching:  15%|█▌        | 74/480 [00:23<02:07,  3.20it/s]

Décor & Pillows
Outdoor
Home Improvement
Furniture
Lighting
Storage & Organization
keywords='floating bed' hallucinated_classification=['Furniture / Bedroom Furniture / Floating Beds & Canopy Beds', 'Furniture / Modern & Contemporary Furniture / Floating & Suspended Furniture', 'Home Decor / Innovative & Artistic Furniture / Floating Bed Installations', 'Luxury & Designer Furniture / Statement Beds / Floating Bed Designs', 'Sleep & Bedding / Specialty Beds / Floating Bed Frames']

Searching:  16%|█▌        | 75/480 [00:23<02:28,  2.73it/s]

Furniture
keywords='mexican art' hallucinated_classification=['Décor & Pillows / Wall Art & Murals / Mexican Art Prints', 'Home Decor / Cultural & Ethnic Decor / Mexican Folk Art', 'Furniture / Accent Pieces / Mexican Inspired Furniture', 'Kitchen & Tabletop / Serveware & Decor / Mexican Pottery & Ceramics', 'Lighting / Decorative Lighting / Mexican Lanterns & Lamps', 'Outdoor / Garden Decor / Mexican Tile & Statues', 'Textiles & Rugs / Area Rugs / Mexican Weavings & Rugs']

Searching:  16%|█▌        | 76/480 [00:24<02:48,  2.39it/s]

Décor & Pillows
Rugs
Outdoor
Kitchen & Tabletop
Furniture
Lighting
keywords='antique brass faucet' hallucinated_classification=['Home Improvement / Bathroom Fixtures / Faucets & Sink Fixtures / Antique Brass Faucets', 'Kitchen & Bath / Kitchen & Bathroom Hardware / Faucets / Antique Brass Faucets', 'Decor & Accessories / Vintage & Antique Decor / Brass Fixtures', 'Plumbing & Hardware / Faucets / Decorative Brass Faucets', 'Renovation & Remodeling / Bathroom Renovation / Antique Brass Fixtures']

Searching:  16%|█▌        | 77/480 [00:24<02:29,  2.70it/s]

Home Improvement
Décor & Pillows
keywords='rustic twig' hallucinated_classification=['Decor / Rustic Decor / Twig & Branch Accents', 'Furniture / Rustic Furniture / Twig-Themed Tables and Chairs', 'Garden & Outdoor / Garden Decor / Twig Garden Stakes', 'Lighting / Rustic Lighting / Twig Chandeliers and Lamps', 'Home Improvement / Wall Decor / Twig Wall Art and Frames']

Searching:  16%|█▋        | 78/480 [00:24<02:15,  2.97it/s]

Lighting
Outdoor
Décor & Pillows
keywords='ruckus chair' hallucinated_classification=['Furniture / Lounge & Accent Chairs / Ruckus Style Chairs', 'Furniture / Office & Gaming Chairs / Ruckus Design Chairs', 'Furniture / Outdoor Seating / Ruckus Patio Chairs', 'Home Decor / Statement Seating / Ruckus Artistic Chairs', 'Furniture / Kids & Teens Furniture / Ruckus Themed Chairs']

Searching:  16%|█▋        | 79/480 [00:24<02:03,  3.24it/s]

School Furniture and Supplies
Outdoor
Furniture
keywords='sheffield home bath set' hallucinated_classification=['Home & Living / Bathroom Accessories / Bath Sets and Collections', 'Home & Living / Bathroom Storage & Organization / Bath Caddies and Trays', 'Home & Living / Bathroom Decor / Bath Themed Decor Items', 'Home & Living / Bathroom Fixtures / Shower Caddies and Holders', 'Home & Living / Bathroom Linens / Bath Towels and Robes']

Searching:  17%|█▋        | 80/480 [00:25<01:56,  3.42it/s]

Home Improvement
Bed & Bath
Décor & Pillows
Storage & Organization
keywords='lowes tile' hallucinated_classification=['Home Improvement / Flooring / Ceramic & Porcelain Tiles', 'Home Improvement / Wall Coverings / Wall Tiles & Backsplashes', 'Decor & Wall Art / Wall Decor / Tile Murals', 'Outdoor / Garden & Patio / Tile Pavers & Stepping Stones', 'Kitchen & Tabletop / Backsplashes / Tile Backsplashes']

Searching:  17%|█▋        | 81/480 [00:25<01:53,  3.50it/s]

Outdoor
Kitchen & Tabletop
Home Improvement
Décor & Pillows
keywords='black 5 drawer dresser by guilford' hallucinated_classification=['Furniture / Bedroom Furniture / Dressers & Chests', 'Furniture / Bedroom Furniture / Wardrobes & Armoires', 'Furniture / Storage & Organization / Dressers & Chests', 'Home Decor / Furniture Accents / Dressers', 'Furniture / Kids & Teen Bedroom Furniture / Dressers & Chests', 'Furniture / Entryway Furniture / Console Dressers']

Searching:  17%|█▋        | 82/480 [00:25<01:56,  3.42it/s]

Furniture
Décor & Pillows
keywords='bohemian' hallucinated_classification=['Furniture / Bohemian Style Furniture / Boho Chic Sofas and Chairs', 'Décor & Pillows / Bohemian Decorative Pillows & Blankets / Boho Throw Pillows', 'Lighting / Bohemian Style Lighting / Macramé Pendant Lights', 'Home Accessories / Bohemian Wall Art & Tapestries / Boho Wall Hangings', 'Outdoor / Bohemian Patio Decor / Boho Garden Furniture & Accessories', 'Textiles & Rugs / Bohemian Rugs & Carpets / Boho Area Rugs', 'Storage & Organization / Bohemian Style Storage / Woven Baskets & Hampers']

Searching:  17%|█▋        | 83/480 [00:26<02:02,  3.25it/s]

Décor & Pillows
Rugs
Outdoor
Furniture
Lighting
Storage & Organization
keywords='adjustable height artist stool' hallucinated_classification=['Furniture / Studio & Art Equipment / Artist Stools & Chairs', 'Furniture / Adjustable Seating / Art & Drafting Stools', 'Home Office & Studio Furniture / Art Studio Furniture / Adjustable Artist Stools', 'Creative Workspace Furniture / Art & Craft Seating / Adjustable Artist Stools', 'Furniture / Specialty Seating / Adjustable Art Stools']

Searching:  18%|█▊        | 84/480 [00:26<01:54,  3.46it/s]

Outdoor
Furniture
keywords='gurney slade 56' hallucinated_classification=['Medical Equipment / Hospital & Gurney Equipment / Hospital Gurneys and Stretcher Beds', 'Furniture / Medical & Therapy Furniture / Gurneys and Treatment Tables', 'Healthcare & Medical Supplies / Patient Transport & Handling / Gurneys', 'Furniture / Specialty Furniture / Emergency & Rescue Furniture']

Searching:  18%|█▊        | 85/480 [00:26<01:43,  3.82it/s]

Furniture
Kitchen & Tabletop
keywords='rolande heavy duty power lift assist recliner' hallucinated_classification=['Furniture / Recliners & Lounge Chairs / Power Lift Recliners', 'Home Medical / Mobility & Assistive Devices / Power Lift Chairs', 'Furniture / Living Room Furniture / Recliners & Accent Chairs', 'Home Improvement / Aging in Place / Lift & Assist Chairs', 'Furniture / Ergonomic & Supportive Seating / Lift Assist Recliners']

Searching:  18%|█▊        | 86/480 [00:26<01:40,  3.90it/s]

Furniture
keywords='outdoor waterproof chest' hallucinated_classification=['Outdoor / Outdoor Storage & Organization / Weatherproof Storage Chests', 'Garden & Patio / Garden Storage / Waterproof Garden Chests', 'Outdoor / Patio Furniture / Storage Benches & Chests', 'Camping & Hiking / Camping Gear / Waterproof Storage Containers', 'Home & Garden / Storage & Organization / Weather-Resistant Storage Solutions']

Searching:  18%|█▊        | 87/480 [00:27<01:39,  3.93it/s]

Outdoor
Storage & Organization
Kitchen & Tabletop
keywords='royal blue counter height chairs' hallucinated_classification=['Furniture / Kitchen & Dining Room Furniture / Counter Height Chairs', 'Furniture / Bar & Counter Stools / Counter Height Stools', 'Furniture / Commercial Furniture / Restaurant & Bar Seating / Counter Height Chairs', 'Home Decor / Color Specific Furniture / Royal Blue Chairs', 'Furniture / Living Room Furniture / Accent Chairs / Counter Height Style Chairs']

Searching:  18%|█▊        | 88/480 [00:27<01:51,  3.52it/s]

Furniture
keywords='argenteuil' hallucinated_classification=['Furniture / Living Room Furniture / Coffee Tables & End Tables / Argenteuil Coffee Tables', 'Décor & Pillows / Decorative Pillows & Blankets / Argenteuil Themed Throw Pillows', 'Furniture / Bedroom Furniture / Dressers & Chests / Argenteuil Style Dressers', 'Outdoor / Outdoor & Patio Furniture / Patio Furniture Sets / Argenteuil Patio Sets', 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / Argenteuil Bathroom Vanities', 'Lighting / Wall Lights / Argenteuil Inspired Wall Sconces', 'Kitchen & Tabletop / Kitchen Organization / Food Storage & Canisters / Argenteuil Kitchen Accessories', 'School Furniture and Supplies / School Furniture / School Chairs & Seating / Argenteuil Design Chairs']
Décor & Pillows
Outdoor
Kitchen & Tabletop
Home Improvement
Furniture
School Furniture and Supplies
Lighting

Searching:  19%|█▊        | 89/480 [00:28<02:36,  2.49it/s]

keywords='light wood nightstand with silver accents' hallucinated_classification=['Furniture / Bedroom Furniture / Nightstands & Bedside Tables / Modern Nightstands', 'Furniture / Bedroom Furniture / Nightstands & Bedside Tables / Minimalist Nightstands', 'Furniture / Bedroom Furniture / Nightstands & Bedside Tables / Scandinavian Style Nightstands', 'Furniture / Bedroom Furniture / Nightstands & Bedside Tables / Silver Accented Nightstands', 'Furniture / Bedroom Furniture / Nightstands & Bedside Tables / Light Wood Finish Nightstands']

Searching:  19%|█▉        | 90/480 [00:28<02:39,  2.44it/s]

Furniture
keywords='indoor water fountain' hallucinated_classification=['Home Decor / Indoor Water Features / Indoor Water Fountains', 'Furniture / Indoor Fountains / Decorative Indoor Fountains', 'Garden & Outdoor / Indoor Water Gardens / Indoor Water Fountains', 'Wellness & Relaxation / Indoor Water Features / Indoor Water Fountains', 'Interior Design / Water Features / Indoor Water Fountains']

Searching:  19%|█▉        | 91/480 [00:28<02:39,  2.43it/s]

Home Improvement
Outdoor
Décor & Pillows
keywords='power lift chair' hallucinated_classification=['Furniture / Recliners & Lift Chairs / Power Lift Chairs', 'Medical & Mobility Equipment / Power Lift Chairs for Elderly and Disabled', 'Home Automation / Smart Furniture / Motorized Lift Chairs', 'Furniture / Living Room Furniture / Reclining & Lift Chairs', 'Healthcare / Medical Furniture / Power Lift Chairs for Therapy and Recovery']

Searching:  19%|█▉        | 92/480 [00:29<02:37,  2.46it/s]

Furniture
keywords='decorative wall clocks' hallucinated_classification=['Home Decor / Wall Decor / Clocks & Timepieces', 'Furniture / Wall-mounted Furniture / Decorative Wall Panels', 'Smart Home / Home Automation Devices / Smart Clocks', 'Art & Collectibles / Wall Art / Artistic Clocks', 'Gift & Novelty Items / Clocks & Timepieces / Decorative Clocks']

Searching:  19%|█▉        | 93/480 [00:29<02:20,  2.76it/s]

Décor & Pillows
keywords='shower hooks' hallucinated_classification=['Home Improvement / Bathroom Accessories / Shower Curtain Hooks', 'Bathroom & Shower / Shower Accessories / Shower Hooks & Rings', 'Bathroom Hardware / Shower Curtain Rods & Hooks / Shower Hooks']
Home Improvement
Bed & Bath

Searching:  20%|█▉        | 94/480 [00:29<01:57,  3.29it/s]

keywords='sunflower' hallucinated_classification=['Decor / Wall Art / Floral Wall Decor / Sunflower Wall Art', 'Garden & Outdoor / Garden Decor / Sunflower Garden Stakes', 'Home Fragrance / Scented Candles / Sunflower Scented Candles', 'Kitchen & Dining / Tableware / Sunflower Pattern Dinnerware', 'Crafts & DIY / Floral Arrangements / Sunflower Craft Kits', 'Kids & Teens / Room Decor / Sunflower Themed Wall Decals']

Searching:  20%|█▉        | 95/480 [00:30<02:08,  2.98it/s]

Kitchen & Tabletop
Outdoor
Décor & Pillows
keywords='side table with storage' hallucinated_classification=['Furniture / Living Room Furniture / Side Tables with Storage', 'Furniture / Bedroom Furniture / Storage Nightstands', 'Home Organization / Storage Solutions / Multi-Functional Side Tables', 'Furniture / Entryway Furniture / Console Tables with Storage', 'Decor & Accessories / Storage Ottomans & Benches']

Searching:  20%|██        | 96/480 [00:30<02:01,  3.15it/s]

Furniture
Storage & Organization
keywords='farmhouse cabinet' hallucinated_classification=['Furniture / Kitchen & Dining Furniture / Kitchen Cabinets & Cupboards', 'Furniture / Entryway & Hallway Furniture / Hallway Cabinets & Storage', 'Furniture / Bathroom Furniture / Bathroom Cabinets & Vanities', 'Furniture / Living Room Furniture / Storage Cabinets & Sideboards', 'Furniture / Bedroom Furniture / Wardrobes & Armoires', 'Home Improvement / Custom Cabinetry & Millwork / Custom Farmhouse Cabinets']

Searching:  20%|██        | 97/480 [00:30<02:07,  3.00it/s]

Home Improvement
Furniture
keywords='storage dresser' hallucinated_classification=['Furniture / Bedroom Furniture / Storage Dressers and Chests', 'Furniture / Entryway Furniture / Storage Benches and Dressers', 'Furniture / Kids and Teen Bedroom Furniture / Kids Storage Dressers', 'Furniture / Closet Systems and Wardrobes / Wardrobes with Storage', 'Furniture / Multi-purpose Furniture / Storage Cabinets and Dressers', 'Furniture / Vintage and Antique Furniture / Retro Storage Dressers']

Searching:  20%|██        | 98/480 [00:31<02:15,  2.82it/s]

Baby & Kids
Furniture
keywords='emma headboard' hallucinated_classification=['Furniture / Bedroom Furniture / Headboards & Bed Frames / Emma Style Headboards', 'Furniture / Customizable Headboards / Emma Design Series', 'Home Decor / Bed Frame Accessories / Emma Headboard Covers', 'Luxury Bedroom Furniture / Designer Headboards / Emma Collection', 'Kids & Teen Bedroom Furniture / Themed Headboards / Emma Character Headboard']

Searching:  21%|██        | 99/480 [00:31<02:09,  2.94it/s]

Bed Accessories
Furniture
keywords='toddler couch fold out' hallucinated_classification=['Baby & Kids / Toddler & Kids Bedroom Furniture / Convertible & Fold-Out Couches', 'Furniture / Kids Room Furniture / Foldable & Multi-Function Sofas', "Children's Furniture / Playroom Seating / Fold-Out Toddler Sofas", 'Nursery & Kids Room Decor / Convertible Seating / Toddler Couch Beds', 'Kids Furniture / Space-Saving Furniture / Fold-Out Toddler Sofas']

Searching:  21%|██        | 100/480 [00:31<02:06,  3.01it/s]

Baby & Kids
Furniture

Searching:  21%|██        | 101/480 [00:32<03:14,  1.95it/s]

keywords='drudge report' hallucinated_classification=['Media & News / News & Media Websites / News Aggregators / News Aggregator Platforms']
Furniture
keywords='jennie tufted upholstered low profile platform bed' hallucinated_classification=['Furniture / Bedroom Furniture / Platform Beds / Upholstered Platform Beds', 'Furniture / Bedroom Furniture / Low Profile Beds', 'Furniture / Upholstery & Fabric / Tufted Upholstered Furniture', 'Home Decor / Bed Frames & Headboards / Upholstered Bed Frames', 'Furniture / Modern & Contemporary Furniture / Low Profile Beds']

Searching:  21%|██▏       | 102/480 [00:33<02:48,  2.25it/s]

Furniture
keywords='wire basket with dividers' hallucinated_classification=['Home Organization / Storage Baskets & Bins / Wire Baskets with Dividers', 'Kitchen & Pantry / Food Storage / Wire Baskets with Adjustable Dividers', 'Office & Desk Organization / Wire Baskets / Divided Wire Baskets for Files and Supplies', 'Closet & Wardrobe / Closet Organizers / Wire Baskets with Dividers for Clothing and Accessories', 'Garage & Workshop / Tool Storage / Wire Baskets with Dividers for Hardware and Equipment']

Searching:  21%|██▏       | 103/480 [00:33<02:32,  2.48it/s]

Storage & Organization
Kitchen & Tabletop
keywords='cake cutlery' hallucinated_classification=['Kitchen & Tabletop / Cutlery & Utensils / Cake Cutting Sets', 'Party Supplies / Cake Servers & Cutlery / Cake Cutting Tools', 'Home Entertaining / Serving Utensils / Cake Slicers & Servers', 'Gourmet & Specialty Foods / Baking & Cake Accessories / Cake Cutting Tools']

Searching:  22%|██▏       | 104/480 [00:33<02:13,  2.82it/s]

Kitchen & Tabletop
keywords='nettie 5 pc bar set' hallucinated_classification=['Furniture / Bar Furniture / Bar Sets and Stations', 'Kitchen & Dining / Bar Accessories / Bar Tool Sets', 'Home Entertainment / Bar & Wine Storage / Wine Racks and Cabinets', 'Outdoor / Outdoor Bar Furniture / Bar Sets for Patio', 'Decor & Accessories / Bar Decor / Bar Signs and Art']

Searching:  22%|██▏       | 105/480 [00:33<02:03,  3.04it/s]

Décor & Pillows
Outdoor
Furniture
Kitchen & Tabletop
keywords='black freestanding tub with faucet' hallucinated_classification=['Home Improvement / Bathroom Fixtures / Freestanding Bathtubs', 'Bathroom Accessories / Bathtub Faucets & Fixtures', 'Luxury Home Goods / Spa & Wellness Equipment / Freestanding Bathtubs', 'Interior Design / Bathroom Design / Freestanding Bathtubs', 'Furniture / Bathroom Furniture / Freestanding Bathtubs']

Searching:  22%|██▏       | 106/480 [00:34<01:56,  3.21it/s]

Home Improvement
Bed & Bath
Furniture
keywords='deer coat hooks' hallucinated_classification=['Home Decor / Wall Hooks & Hangers / Animal-Themed Coat Hooks', 'Furniture / Entryway Furniture / Coat Racks & Hooks / Deer Design Hooks', 'Outdoor / Garden & Patio Decor / Animal-Shaped Garden Decor / Deer Hooks', 'Kids & Baby Furniture / Kids Room Decor / Animal-Themed Wall Hooks', 'Crafts & DIY / Home Decor Accessories / Animal Motif Wall Hooks']

Searching:  22%|██▏       | 107/480 [00:34<02:04,  2.99it/s]

Baby & Kids
Décor & Pillows
Outdoor
Home Improvement
Bed & Bath
keywords='light and navy blue decorative pillow' hallucinated_classification=['Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows', 'Home Decor / Accent Pillows / Navy Blue Decorative Cushions', 'Bedroom Accessories / Decorative Cushions / Light Blue & Navy Pillows', 'Living Room Decor / Throw Pillows / Navy and Light Blue Accent Pillows', 'Interior Decor / Textile Accents / Decorative Cushions in Navy and Light Blue']

Searching:  22%|██▎       | 108/480 [00:34<02:13,  2.78it/s]

Décor & Pillows
keywords='kitchen storage cabinet' hallucinated_classification=['Furniture / Kitchen & Dining / Kitchen Storage & Organization / Kitchen Cabinets', 'Home Improvement / Kitchen Remodel & Fixtures / Kitchen Cabinetry & Hardware', 'Furniture / Custom & Built-In Furniture / Kitchen Cabinets & Cupboards', 'Kitchen & Tabletop / Kitchen Storage & Organization / Pantry Cabinets & Shelves', 'Decor & Accessories / Kitchen Decor / Kitchen Storage Solutions']

Searching:  23%|██▎       | 109/480 [00:35<02:26,  2.54it/s]

Home Improvement
Furniture
Décor & Pillows
Storage & Organization
keywords='beach blue headboard' hallucinated_classification=['Furniture / Bedroom Furniture / Headboards & Bed Frames / Upholstered Headboards', 'Furniture / Bedroom Furniture / Headboards & Bed Frames / Wooden Headboards', 'Décor & Pillows / Decorative Pillows & Blankets / Nautical & Beach-themed Pillows', 'Home Decor / Wall Art / Beach-themed Wall Hangings', 'Furniture / Bedroom Furniture / Bed Frames / Canopy & Canopy Bed Frames', 'Furniture / Bedroom Furniture / Headboards & Bed Frames / Upholstered Headboards with Nautical Accents']

Searching:  23%|██▎       | 110/480 [00:35<02:42,  2.28it/s]

Furniture
Décor & Pillows
keywords='leather dining chairs' hallucinated_classification=['Furniture / Dining Room Furniture / Dining Chairs / Leather Dining Chairs', 'Furniture / Kitchen & Dining / Dining Room Furniture / Leather Dining Chairs', 'Home Decor / Upholstered Furniture / Leather Dining Chairs', 'Luxury Furniture / Premium Dining Chairs / Leather Upholstered Chairs', 'Eco-Friendly Furniture / Sustainable Dining Chairs / Leather Options']

Searching:  23%|██▎       | 111/480 [00:36<02:41,  2.28it/s]

Outdoor
Furniture
keywords='refrigerator with ice and water in door' hallucinated_classification=['Home Appliances / Refrigerators & Freezers / French Door Refrigerators with Water Dispenser', 'Kitchen & Tabletop / Kitchen Appliances / Built-in Refrigerators with Ice Maker', 'Smart Home / Home Automation / Smart Refrigerators with Water and Ice Dispenser', 'Appliance Accessories / Refrigerator Water Filters & Dispenser Parts', 'Home & Living / Kitchen & Dining / Kitchen Appliances / Refrigerators with Water Dispenser']

Searching:  23%|██▎       | 112/480 [00:36<02:24,  2.55it/s]

Kitchen & Tabletop
Appliances
keywords='kids chair' hallucinated_classification=["Kids Furniture / Children's Seating / Kids Chairs", 'Kids Room Decor / Kids Furniture Accessories / Kids Chair Cushions', 'Educational Furniture / Classroom Seating / Kids Desk Chairs', 'Outdoor Kids Furniture / Playroom Seating / Kids Patio Chairs', 'Nursery Furniture / Baby & Toddler Chairs / Rocking Chairs for Kids']

Searching:  24%|██▎       | 113/480 [00:36<02:08,  2.86it/s]

Baby & Kids
Outdoor
School Furniture and Supplies
Furniture
keywords='outdoor storage' hallucinated_classification=['Outdoor / Outdoor Storage & Organization / Weatherproof Storage Bins and Containers', 'Outdoor / Garden & Patio Storage / Garden Sheds and Cabinets', 'Outdoor / Patio & Garden Furniture Storage / Storage Benches and Ottomans', 'Home Improvement / Garage & Shed Storage / Wall-Mounted Shelving and Racks', 'Outdoor / Pool & Spa Storage / Pool Equipment Storage Cabinets']

Searching:  24%|██▍       | 114/480 [00:37<01:56,  3.14it/s]

Outdoor
Storage & Organization
keywords='worn leather office chair' hallucinated_classification=['Furniture / Office Furniture / Executive Chairs and Desks', 'Furniture / Vintage & Retro Furniture / Leather Seating', 'Furniture / Sustainable & Eco-Friendly Furniture / Reclaimed Leather Chairs', 'Furniture / Industrial Style Furniture / Leather & Metal Office Chairs', 'Furniture / Custom & Handmade Furniture / Leather Office Seating']

Searching:  24%|██▍       | 115/480 [00:37<01:49,  3.33it/s]

Outdoor
Furniture
keywords='jordanna solid wood rocking' hallucinated_classification=['Furniture / Rocking Chairs / Wooden Rocking Chairs', 'Furniture / Nursery & Kids Furniture / Wooden Rocking Chairs', 'Home Decor / Wooden Accents / Wooden Rocking Decor', 'Outdoor / Garden & Patio Furniture / Wooden Rocking Benches', 'Furniture / Vintage & Antique Furniture / Wooden Rocking Chairs']

Searching:  24%|██▍       | 116/480 [00:37<01:55,  3.16it/s]

Baby & Kids
Outdoor
Furniture
Décor & Pillows
keywords='rustic storage cabinet' hallucinated_classification=['Furniture / Storage & Organization / Cabinets & Cupboards / Rustic Storage Cabinets', 'Home Decor / Rustic & Farmhouse Style / Rustic Storage Solutions', 'Furniture / Living Room Furniture / Storage Cabinets & Sideboards / Rustic Storage Cabinets', 'Kitchen & Dining / Kitchen Storage / Rustic Pantry Cabinets', 'Outdoor / Garden Storage / Rustic Storage Sheds']

Searching:  24%|██▍       | 117/480 [00:38<02:06,  2.87it/s]

Furniture
Décor & Pillows
Storage & Organization
keywords='moen multi function dual shower head' hallucinated_classification=['Home Improvement / Bathroom Fixtures / Shower Heads & Accessories / Multi-Function Shower Heads', 'Bathroom & Spa / Shower & Bathtub Accessories / Dual Shower Head Systems', 'Plumbing / Shower Fixtures / Multi-Function Shower Units', 'Luxury Bathroom / Shower Systems / Dual Head Shower Panels', 'Smart Home / Bathroom Technology / Multi-Function Shower Controls']

Searching:  25%|██▍       | 118/480 [00:38<02:13,  2.72it/s]

Home Improvement
keywords='girl reading statue' hallucinated_classification=['Decorative Statues & Sculptures / Figurines & Art Pieces / Girl Reading Statue', 'Home Decor / Artistic Sculptures / Reading Girl Figurine', 'Garden & Outdoor Decor / Statues & Sculptures / Girl Reading Garden Statue', "Children's Room Decor / Themed Art & Sculptures / Girl Reading Statue for Kids Room", 'Art & Collectibles / Limited Edition Sculptures / Girl Reading Art Piece']

Searching:  25%|██▍       | 119/480 [00:39<02:19,  2.58it/s]

Baby & Kids
Outdoor
Décor & Pillows
keywords='wood coffee table set by storage' hallucinated_classification=['Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables with Storage', 'Furniture / Living Room Furniture / Coffee Tables & End Tables / Modular Coffee Tables', 'Furniture / Storage & Organization / Coffee Table Storage Solutions', 'Furniture / Multi-Functional Furniture / Coffee Tables with Built-in Storage', 'Furniture / Eco-Friendly Furniture / Reclaimed Wood Coffee Tables']

Searching:  25%|██▌       | 120/480 [00:39<02:27,  2.44it/s]

Furniture
keywords='closet storage with zipper' hallucinated_classification=['Furniture / Bedroom Storage / Closet Organizers with Zipper Enclosures', 'Home Organization / Closet Accessories / Zippered Closet Storage Bags', 'Furniture / Wardrobe & Closet Furniture / Zippered Closet Compartments', 'Storage & Organization / Closet Storage Solutions / Zippered Closet Caddies', 'Home Improvement / Closet Renovation / Zippered Closet Doors & Covers']

Searching:  25%|██▌       | 121/480 [00:39<02:10,  2.75it/s]

Home Improvement
Storage & Organization
Furniture
keywords='novara pergola' hallucinated_classification=['Outdoor / Garden Structures / Pergolas & Gazebos / Novara Pergola', 'Outdoor / Patio Coverings / Pergolas / Modern Pergola Designs', 'Home Improvement / Outdoor Living / Pergola Kits / Customizable Pergolas', 'Garden & Outdoor Decor / Garden Arbors & Trellises / Pergola Accessories']

Searching:  25%|██▌       | 122/480 [00:40<01:53,  3.14it/s]

Outdoor
keywords='modern farmhouse lighting semi flush mount' hallucinated_classification=['Lighting / Ceiling Lights / Semi-Flush Mount Lights', 'Furniture / Entryway & Hallway Furniture / Hall Tree & Coat Rack Sets', 'Décor & Pillows / Wall Art & Decor / Farmhouse Style Wall Decor', 'Home Improvement / Lighting & Ceiling Fans / Ceiling Fan Light Kits', 'Furniture / Living Room Furniture / Accent & Console Tables', 'Lighting / Pendant & Chandeliers / Farmhouse Pendant Lights']

Searching:  26%|██▌       | 123/480 [00:40<01:50,  3.24it/s]

Lighting
Furniture
Décor & Pillows
keywords='aloe vera plant pot' hallucinated_classification=['Home & Garden / Indoor Plants & Planters / Plant Pots & Containers / Aloe Vera Plant Pot']
Outdoor
keywords='burnt orange curtains' hallucinated_classification=['Home Decor / Window Treatments / Curtains & Drapes / Burnt Orange Curtains', 'Furniture / Living Room Furniture / Window Coverings / Curtain Panels', 'Interior Design / Color Themes / Burnt Orange Accents', 'Home Improvement / Window Treatments / Curtain Rods & Hardware / Burnt Orange Curtain Rods', 'Decor & Pillows / Decorative Accessories / Burnt Orange Home Accents']

Searching:  26%|██▌       | 125/480 [00:40<01:24,  4.20it/s]

Décor & Pillows
keywords='full metal bed rose gold' hallucinated_classification=['Furniture / Bedroom Furniture / Metal Beds / Rose Gold Metal Beds', 'Furniture / Bedroom Furniture / Modern Metal Bed Frames / Rose Gold Finish', 'Home Decor / Metal Bed Frames / Rose Gold Accents', 'Luxury Furniture / Designer Metal Beds / Rose Gold Finish', 'Kids & Teens Furniture / Metal Beds / Rose Gold']

Searching:  26%|██▋       | 126/480 [00:40<01:24,  4.20it/s]

Baby & Kids
Furniture
Décor & Pillows
keywords='unique coffee tables' hallucinated_classification=['Furniture / Living Room Furniture / Coffee Tables & End Tables / Artistic & Sculptural Coffee Tables', 'Furniture / Custom & Handmade Furniture / Unique Coffee Tables', 'Furniture / Eco-Friendly & Sustainable Furniture / Reclaimed Wood Coffee Tables', 'Furniture / Modern & Contemporary Furniture / Minimalist Coffee Tables', 'Furniture / Vintage & Retro Furniture / Retro Coffee Tables', 'Furniture / Multi-Functional Furniture / Convertible Coffee Tables & Storage Solutions']

Searching:  26%|██▋       | 127/480 [00:41<01:29,  3.95it/s]

Furniture
keywords='mystic swivel' hallucinated_classification=['Furniture / Swivel Chairs / Mystic Themed Swivel Chairs', 'Home Decor / Mystic & Spiritual Decor / Mystic Swivel Art Pieces', 'Furniture / Accent Chairs / Mystic Patterned Swivel Chairs', 'Home Office / Swivel Office Chairs / Mystic Design', 'Living Room / Lounge Chairs / Mystic Style Swivel Loungers']

Searching:  27%|██▋       | 128/480 [00:41<01:30,  3.89it/s]

Outdoor
Furniture
Décor & Pillows
keywords='tye dye duvet cover' hallucinated_classification=['Bedding & Linens / Duvet Covers & Comforters / Tye Dye Duvet Covers', 'Home Decor / Textiles / Tye Dye Fabric Accents', 'Bedroom Accessories / Decorative Bedding / Tye Dye Bedding Sets', 'Kids & Teens Bedroom Decor / Tye Dye Theme Bedding', 'Fashion & Apparel / Home Wear / Tye Dye Lounge Wear']

Searching:  27%|██▋       | 129/480 [00:41<01:29,  3.93it/s]

Baby & Kids
Décor & Pillows
Bed Accessories
Bed & Bath
Furniture
keywords='luau string lights' hallucinated_classification=['Outdoor / Outdoor Lighting / String Lights / Luau String Lights', 'Party & Event Supplies / Themed Party Decorations / Luau & Hawaiian Party Decor / String Lights', 'Home Decor / Festive & Seasonal Decor / Luau & Tropical Decor / String Lights', 'Garden & Patio / Garden Lighting / String Lights / Tropical & Luau Style']

Searching:  27%|██▋       | 130/480 [00:41<01:23,  4.18it/s]

Lighting
Holiday Décor
Décor & Pillows
keywords='kohler whitehaven farmhouse kitchen sink' hallucinated_classification=['Home & Kitchen / Kitchen Fixtures & Sinks / Farmhouse Kitchen Sinks', 'Home & Kitchen / Kitchen Renovation & Remodeling / Farmhouse Style Kitchen Fixtures', 'Home & Kitchen / Kitchen Accessories / Farmhouse Sink Accessories', 'Home & Kitchen / Plumbing & Fixtures / Kitchen Sinks & Basins', 'Home & Kitchen / Kitchen Design / Farmhouse Kitchen Elements']

Searching:  27%|██▋       | 131/480 [00:42<01:22,  4.22it/s]

Home Improvement
Bed & Bath
keywords='berenice 4 storage cabinet' hallucinated_classification=['Furniture / Storage & Organization / Cabinets & Cupboards / Storage Cabinets', 'Home Office / Office Storage / File Cabinets & Storage Cabinets', 'Living Room / Storage Furniture / Display Cabinets & Bookcases', 'Bedroom / Wardrobes & Armoires / Storage Cabinets', 'Entryway / Coat & Shoe Storage / Storage Cabinets']

Searching:  28%|██▊       | 132/480 [00:42<01:22,  4.20it/s]

Storage & Organization
Furniture
keywords='penny round tile' hallucinated_classification=['Home Decor / Wall & Floor Tiles / Penny Round Tiles', 'Kitchen & Bath / Backsplashes / Penny Round Tile Backsplash', 'Flooring / Specialty Tiles / Penny Round Pattern Tiles', 'DIY & Home Improvement / Tile Installation Supplies / Penny Round Tile Tools', 'Interior Design / Wall Accents / Circular Tile Wall Art']

Searching:  28%|██▊       | 133/480 [00:42<01:30,  3.84it/s]

Home Improvement
Décor & Pillows
keywords='stoneford end tables white and wood' hallucinated_classification=['Furniture / Living Room Furniture / End Tables & Side Tables', 'Furniture / Accent Furniture / Stone & Wood End Tables', 'Home Decor / Wooden & Stone Home Accents', 'Furniture / Bedroom Furniture / Nightstands & Bedside Tables', 'Furniture / Entryway Furniture / Console Tables & Entryway Tables']

Searching:  28%|██▊       | 134/480 [00:42<01:34,  3.67it/s]

Furniture
Décor & Pillows
keywords='dull bed with shirt head board' hallucinated_classification=['Furniture / Bedroom Furniture / Beds with Unique Headboards', 'Furniture / Kids & Teen Bedroom Furniture / Themed Beds', 'Home Decor / Wall Art & Headboard Decorations / Artistic Headboards', 'Furniture / Customizable Furniture / Personalized Beds', 'Furniture / Eco-Friendly & Sustainable Furniture / Reclaimed Wood Beds']

Searching:  28%|██▊       | 135/480 [00:43<01:37,  3.55it/s]

Baby & Kids
Furniture
Décor & Pillows
keywords='accent chairs living room' hallucinated_classification=['Furniture / Living Room Furniture / Accent Chairs', 'Furniture / Living Room Furniture / Lounge Chairs', 'Furniture / Living Room Furniture / Armchairs', 'Decor / Living Room Decor / Accent Seating', 'Furniture / Customizable Living Room Chairs / Modular Accent Chairs', 'Furniture / Eco-Friendly Living Room Furniture / Sustainable Accent Chairs']

Searching:  28%|██▊       | 136/480 [00:43<01:51,  3.09it/s]

Furniture
keywords='huge bookcase' hallucinated_classification=['Furniture / Storage & Organization / Bookcases & Shelving / Large Bookcases', 'Furniture / Living Room Furniture / Bookcases & Display Cabinets / Oversized Bookcases', 'Home Office / Bookcases & Shelving / Tall Bookcases', 'Decor & Home Accents / Wall Shelves / Large Wall-Mounted Bookcases', 'Kids & Teens / Kids Room Furniture / Large Bookcases & Storage Units']

Searching:  29%|██▊       | 137/480 [00:44<01:52,  3.04it/s]

Baby & Kids
Furniture
Décor & Pillows
Storage & Organization
keywords='sofa with ottoman' hallucinated_classification=['Furniture / Living Room Furniture / Sofas & Sectionals / Sofas with Ottomans', 'Furniture / Living Room Furniture / Ottomans & Poufs / Ottoman Sets with Sofas', 'Furniture / Multi-Functional Furniture / Sofa Beds & Sleeper Sofas / Sofas with Built-in Ottomans', 'Home Decor / Upholstered Furniture / Upholstered Sofas & Loveseats / Sofas with Matching Ottomans', 'Furniture / Customizable Furniture / Modular Sofas & Ottomans / Configurable Sofa Sets']

Searching:  29%|██▉       | 138/480 [00:44<01:56,  2.94it/s]

Furniture
keywords='brockham solid blackout thermal grommet curtain panels' hallucinated_classification=['Home Textiles / Window Treatments / Curtain Panels / Blackout Curtains', 'Home Improvement / Window Coverings / Thermal Insulated Curtains', 'Decor & Pillows / Curtains & Drapes / Grommet Curtains', 'Furniture / Living Room Furniture / Window Treatments & Accessories']

Searching:  29%|██▉       | 139/480 [00:44<01:48,  3.14it/s]

Décor & Pillows
keywords='70s inspired furniture' hallucinated_classification=['Furniture / Retro & Vintage Furniture / 70s Style Sofas and Chairs', 'Furniture / 70s Inspired Bedroom Furniture / Boho Bedroom Sets', 'Décor & Pillows / 70s Patterned Throw Pillows / Vintage Geometric Pillows', 'Lighting / 70s Style Floor Lamps / Retro Arc Floor Lamps', 'Furniture / 70s Inspired Dining Furniture / Vintage Dining Tables and Chairs', 'Home Decor / 70s Wall Art / Vintage Abstract Prints', 'Furniture / 70s Inspired Office Furniture / Retro Desks and Chairs']

Searching:  29%|██▉       | 140/480 [00:45<02:02,  2.78it/s]

Lighting
Furniture
Décor & Pillows
keywords='blk 18x18 seat cushions' hallucinated_classification=['Furniture / Seating / Seat Cushions & Pads', 'Home Decor / Cushions & Pillows / Seat Cushions', 'Outdoor / Patio & Garden / Seat Cushions', 'Furniture / Upholstery / Seat Cushions', 'Living Room / Accent & Throw Pillows / Seat Cushions']

Searching:  29%|██▉       | 141/480 [00:45<01:49,  3.09it/s]

Outdoor
Furniture
keywords='bubble guppies chair' hallucinated_classification=["Kids & Baby Furniture / Kids Chairs & Seating / Themed Children's Chairs", 'Kids & Baby Decor / Themed Room Decor / Bubble Guppies Room Accessories', 'Kids & Baby Furniture / Kids Room Storage & Organization / Themed Storage Solutions', 'Kids & Baby Furniture / Kids Bedroom Furniture / Themed Bed Frames and Furniture']

Searching:  30%|██▉       | 142/480 [00:45<01:38,  3.43it/s]

Baby & Kids
keywords='glinda upholstered bench' hallucinated_classification=['Furniture / Living Room Furniture / Benches & Ottomans / Upholstered Benches', 'Furniture / Entryway Furniture / Entryway Benches & Seating', 'Furniture / Bedroom Furniture / Bedroom Benches & Seating / Upholstered Bedroom Benches', 'Décor & Pillows / Decorative Pillows & Blankets / Upholstered Cushions', 'Home Decor / Accent Furniture / Upholstered Accent Pieces']

Searching:  30%|██▉       | 143/480 [00:45<01:36,  3.49it/s]

Furniture
Décor & Pillows
keywords='turquoise pillows' hallucinated_classification=['Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows', 'Furniture / Living Room Furniture / Accent Chairs & Ottomans / Poufs and Floor Cushions', 'Home Decor / Wall Hangings & Art / Textile Wall Hangings', 'Bedding / Bed Accessories / Pillow Shams and Covers', 'Outdoor / Outdoor & Patio Decor / Cushions and Pillows']

Searching:  30%|███       | 144/480 [00:46<01:32,  3.63it/s]

Outdoor
Furniture
Décor & Pillows
Bed & Bath
keywords='patio design' hallucinated_classification=['Outdoor / Outdoor & Patio Design / Patio Layout & Planning', 'Outdoor / Patio Decor & Accessories / Garden Statues & Ornaments', 'Furniture / Outdoor Furniture / Patio Dining Sets', 'Lighting / Outdoor Lighting / String & String Lights', 'Home Improvement / Landscaping & Garden / Garden Design & Planning', 'Décor & Pillows / Outdoor Cushions & Pillows / Patio Cushions', 'Storage & Organization / Outdoor Storage / Patio Storage Benches']

Searching:  30%|███       | 145/480 [00:46<01:39,  3.36it/s]

Lighting
Home Improvement
Outdoor
Storage & Organization
keywords='capricorn chest' hallucinated_classification=['Furniture / Bedroom Furniture / Chests and Dressers / Capricorn-themed Chests', 'Decor & Accessories / Themed Decor / Zodiac Sign Decor / Capricorn', 'Furniture / Living Room Furniture / Storage Cabinets / Zodiac Symbol Cabinets', 'Home Organization / Specialty Storage / Zodiac Symbol Storage Solutions', 'Furniture / Entryway Furniture / Storage Benches / Capricorn Design']

Searching:  30%|███       | 146/480 [00:46<01:35,  3.51it/s]

Furniture
Décor & Pillows
Storage & Organization
keywords='mila task chair' hallucinated_classification=['Furniture / Office Furniture / Task Chairs', 'Furniture / Ergonomic Office Chairs / Adjustable Task Chairs', 'Furniture / Conference & Meeting Room Furniture / Conference Chairs', 'Furniture / Specialty Seating / Task & Drafting Chairs', 'Home Office / Office Seating / Task Chairs']
Furniture

Searching:  31%|███       | 147/480 [00:47<01:56,  2.86it/s]

keywords='coat rack for bedroom' hallucinated_classification=['Furniture / Bedroom Furniture / Coat Racks and Hooks', 'Home Organization / Entryway & Closet Storage / Coat & Hat Racks', 'Furniture / Hallway & Entryway Furniture / Coat Stands and Hooks', 'Decor & Accessories / Wall Hooks & Hangers / Coat Hooks', 'Furniture / Multi-purpose Furniture / Hall Tree & Coat Rack Combo', 'Home Improvement / Storage & Organization / Wall-mounted Coat Racks']
Home Improvement
Furniture
Bed & Bath
Storage & Organization

Searching:  31%|███       | 148/480 [00:47<01:51,  2.97it/s]

keywords='comfortable accent chair' hallucinated_classification=['Furniture / Accent Chairs / Upholstered Accent Chairs', 'Furniture / Lounge Chairs / Modern Lounge Chairs', 'Furniture / Armchairs / Plush Armchairs', 'Furniture / Reading Nooks / Cozy Chairs', 'Furniture / Vintage & Retro Furniture / Retro Accent Chairs', 'Furniture / Eco-Friendly Furniture / Sustainable Accent Chairs', 'Furniture / Customizable Furniture / Modular Accent Chairs']
Furniture

Searching:  31%|███       | 149/480 [00:48<02:42,  2.03it/s]

keywords='bathroom vanity knobs' hallucinated_classification=['Home Improvement / Bathroom Fixtures & Accessories / Bathroom Vanity Knobs and Handles', 'Furniture / Bathroom Furniture / Vanity Cabinets and Hardware / Vanity Knobs', 'Decor & Accessories / Bathroom Decor / Vanity Hardware & Accessories', 'Hardware / Cabinet & Drawer Pulls / Bathroom Vanity Knobs', 'DIY & Home Repair / Bathroom Renovation / Vanity Hardware']

Searching:  31%|███▏      | 150/480 [00:48<02:31,  2.18it/s]

Home Improvement
Décor & Pillows
keywords='hulmeville writing desk with hutch' hallucinated_classification=['Furniture / Home Office Furniture / Desks with Storage', 'Furniture / Entryway Furniture / Console Desks with Shelves', 'Furniture / Kids & Teens Furniture / Study Desks with Hutch', 'Furniture / Vintage & Retro Furniture / Antique Desks with Hutch', 'Furniture / Modular Furniture / Convertible Desks with Storage']
Baby & Kids
Furniture

Searching:  31%|███▏      | 151/480 [00:49<02:37,  2.09it/s]

keywords='farmhouse bread box' hallucinated_classification=['Home & Kitchen / Kitchen Storage & Organization / Bread Boxes', 'Furniture / Kitchen & Dining Furniture / Kitchen Islands & Carts / Bread Box Cabinets', 'Decor / Kitchen Decor / Vintage & Rustic Kitchen Decor', 'Home Improvement / Kitchen Remodel & Fixtures / Kitchen Cabinet Accessories / Bread Box Inserts', 'Specialty Storage / Food Storage / Bread & Pastry Storage Containers']
Décor & Pillows
Kitchen & Tabletop
Home Improvement
Furniture
Storage & Organization

Searching:  32%|███▏      | 152/480 [00:49<02:16,  2.40it/s]

keywords='leather chairs' hallucinated_classification=['Furniture / Living Room Furniture / Lounge Chairs & Armchairs', 'Furniture / Office Furniture / Executive & Desk Chairs', 'Furniture / Bedroom Furniture / Accent Chairs', 'Furniture / Entryway & Hallway Furniture / Accent Chairs', 'Furniture / Outdoor Furniture / Patio Lounge Chairs', 'Furniture / Specialty Furniture / Leather Recliners & Armchairs', 'Furniture / Kids & Teens Furniture / Kids Lounge Chairs']

Searching:  32%|███▏      | 153/480 [00:49<02:17,  2.38it/s]

Baby & Kids
Outdoor
Furniture
keywords='driftwood mirror' hallucinated_classification=['Decor / Wall Decor / Mirrors / Driftwood Style Mirrors', 'Furniture / Entryway Furniture / Mirror Cabinets with Driftwood Accents', 'Home Improvement / Wall Treatments / Driftwood Wall Panels', 'Outdoor / Garden Decor / Driftwood Garden Art', 'Decor / Natural Elements / Driftwood Art Pieces']

Searching:  32%|███▏      | 154/480 [00:50<02:13,  2.44it/s]

Outdoor
Home Improvement
Décor & Pillows
keywords='above toilet cabinet' hallucinated_classification=['Furniture / Bathroom Storage / Over-Toilet Cabinets', 'Home Organization / Bathroom Cabinets / Wall-Mounted Bathroom Cabinets', 'Bathroom Accessories / Toilet Area Storage / Over-Toilet Shelves and Cabinets', 'Bathroom Furniture / Space-Saving Bathroom Cabinets / Above Toilet Storage Units', 'Home Improvement / Bathroom Renovation / Over-Toilet Cabinet Solutions']

Searching:  32%|███▏      | 155/480 [00:50<02:09,  2.51it/s]

Home Improvement
Furniture
Storage & Organization
keywords='ayesha curry kitchen' hallucinated_classification=['Kitchen & Dining / Kitchen Accessories / Ayesha Curry Kitchenware', 'Kitchen & Dining / Cookware & Bakeware / Ayesha Curry Cookware Sets', 'Kitchen & Dining / Kitchen Storage & Organization / Ayesha Curry Kitchen Storage Solutions', 'Kitchen & Dining / Small Appliances / Ayesha Curry Small Kitchen Appliances', 'Kitchen & Dining / Kitchen Decor / Ayesha Curry Kitchen Decor Items']

Searching:  32%|███▎      | 156/480 [00:50<01:55,  2.81it/s]

Décor & Pillows
Kitchen & Tabletop
Appliances
keywords='bar stool 24 inches height' hallucinated_classification=['Furniture / Kitchen & Bar Furniture / Bar Stools & Counter Stools / Standard Height Bar Stools', 'Furniture / Home Bar & Entertainment / Bar Furniture & Accessories / Bar Stools', 'Furniture / Outdoor & Patio Furniture / Patio Bar Stools / Counter Height Bar Stools', 'Furniture / Commercial & Hospitality Furniture / Restaurant & Bar Stools / 24 Inch Height Stools', 'Furniture / Custom & Modular Furniture / Modular Seating / Adjustable Height Bar Stools']

Searching:  33%|███▎      | 157/480 [00:51<01:45,  3.06it/s]

Outdoor
Furniture
keywords='led nightstand' hallucinated_classification=['Furniture / Bedroom Furniture / Nightstands & Bedside Tables / LED Nightstands', 'Lighting / Nightstand Lamps / LED Nightstand Lamps', 'Smart Home / Smart Furniture / LED-Integrated Furniture', 'Home Decor / Nightstand Accessories / LED Nightstand Decor']

Searching:  33%|███▎      | 158/480 [00:51<01:31,  3.52it/s]

Lighting
Furniture
Décor & Pillows
keywords='carpet 5x6' hallucinated_classification=['Home Decor / Area Rugs / Standard Area Rugs', 'Flooring / Carpets / Room-sized Carpets', 'Interior Design / Floor Coverings / Custom Size Rugs', 'Home Improvement / Flooring / Carpet Tiles', 'Furniture / Rugs & Mats / Large Area Rugs']

Searching:  33%|███▎      | 159/480 [00:51<01:27,  3.69it/s]

Home Improvement
Rugs
keywords='body pillow case' hallucinated_classification=['Home Textiles / Bedding Accessories / Pillow Cases and Covers / Body Pillow Cases', 'Furniture / Bedroom Accessories / Sleep Comfort Products / Body Pillow Covers', 'Health & Wellness / Sleep Support / Body Pillow Covers']
Bed & Bath
Décor & Pillows

Searching:  33%|███▎      | 160/480 [00:51<01:15,  4.26it/s]

keywords='geralyn upholstered storage platform bed' hallucinated_classification=['Furniture / Bedroom Furniture / Platform Beds with Storage', 'Furniture / Upholstered Beds / Storage Bed Options', 'Home Decor / Upholstered Furniture / Storage Beds', 'Furniture / Customizable Bedroom Sets / Storage Bed Units', 'Furniture / Eco-Friendly Bedroom Furniture / Upholstered Storage Beds']
Furniture

Searching:  34%|███▎      | 161/480 [00:52<01:15,  4.21it/s]

keywords='donaldson teak couch' hallucinated_classification=['Furniture / Living Room Furniture / Sofas & Sectionals / Teak Couches', 'Furniture / Outdoor Furniture / Teak Patio Sofas', 'Home Decor / Teak Furniture Accents / Teak Lounge Chairs', 'Furniture / Custom & Designer Sofas / Teak Upholstered Couches', 'Eco-Friendly Furniture / Sustainable Teak Sofas']
Outdoor
Furniture

Searching:  34%|███▍      | 162/480 [00:52<01:17,  4.12it/s]

keywords='butcher block island' hallucinated_classification=['Furniture / Kitchen & Dining / Kitchen Islands & Carts / Butcher Block Islands', 'Home Improvement / Kitchen Renovation / Kitchen Countertops / Butcher Block Countertops', 'Furniture / Kitchen & Dining / Kitchen Islands & Carts / Wooden Kitchen Islands', 'Kitchen & Tabletop / Kitchen Storage / Kitchen Islands with Storage', 'Furniture / Custom Furniture / Custom Kitchen Islands']
Home Improvement
Furniture
Kitchen & Tabletop

Searching:  34%|███▍      | 163/480 [00:52<01:17,  4.08it/s]

keywords='rug plum' hallucinated_classification=['Home Decor / Rugs & Carpets / Area Rugs / Plum Rugs', 'Furniture / Floor Coverings / Area Rugs / Plum Color Rugs', 'Decor & Pillows / Decorative Rugs / Plum Rugs', 'Home Improvement / Flooring / Area Rugs / Plum Pattern Rugs', 'Interior Design / Accent Rugs / Plum Accents']
Décor & Pillows
Rugs

Searching:  34%|███▍      | 164/480 [00:52<01:16,  4.12it/s]

keywords='brushed gold wall decor' hallucinated_classification=['Decor & Wall Art / Wall Decor / Metal Wall Art / Brushed Gold Wall Art', 'Home Accents / Wall Hangings / Metallic Wall Hangings / Brushed Gold Wall Hangings', 'Interior Design / Wall Decor / Metallic Accents / Brushed Gold Accents', 'Luxury Home Decor / Wall Decor / Gold Finish Wall Decor', 'Contemporary Home Accessories / Wall Decor / Metallic Finish Wall Art']
Décor & Pillows

Searching:  34%|███▍      | 165/480 [00:53<01:18,  4.00it/s]

keywords='outdoor sectional doning' hallucinated_classification=['Outdoor / Outdoor & Patio Furniture / Sectional Sofas & Couches', 'Furniture / Modular & Customizable Furniture / Outdoor Sectionals', 'Outdoor / Patio Decor & Accessories / Outdoor Cushions & Pillows', 'Garden & Yard / Outdoor Furniture Covers / Sectional Coverings', 'Home & Garden / Outdoor Living / Outdoor Dining & Lounge Sets']
Outdoor
Furniture
Storage & Organization

Searching:  35%|███▍      | 166/480 [00:53<01:17,  4.05it/s]

keywords='round outdoor patio cover' hallucinated_classification=['Outdoor / Outdoor Structures / Patio Covers & Awnings / Round Patio Covers', 'Garden & Outdoor Living / Patio & Garden Decor / Outdoor Canopies and Shelters / Round Canopies', 'Home Improvement / Exterior & Garden / Patio Coverings / Round Patio Covers', 'Outdoor Living / Shade & Shelter / Round Shade Structures / Patio Covers']
Outdoor
Storage & Organization
Décor & Pillows

Searching:  35%|███▌      | 168/480 [00:53<01:10,  4.45it/s]

keywords='nursery end table' hallucinated_classification=['Furniture / Nursery Furniture / End Tables and Nightstands / Nursery End Tables', 'Furniture / Kids & Baby Furniture / Nursery & Toddler End Tables', "Home Decor / Children's Room Decor / Nursery Furniture Accents", 'Furniture / Storage & Organization / Nursery Storage Solutions / End Table Storage']
Baby & Kids
Furniture
Décor & Pillows
keywords='full mattress padded liner' hallucinated_classification=['Home Textiles / Mattress Accessories / Mattress Liners and Protectors', 'Bedding / Mattress Pads and Toppers / Padded Mattress Liners', 'Sleep & Comfort / Mattress Enhancements / Padded Mattress Liners']

Searching:  35%|███▌      | 169/480 [00:53<01:03,  4.88it/s]

Bed & Bath
keywords='bathroom lighting' hallucinated_classification=['Lighting / Bathroom Lighting / Vanity Lights and Sconces', 'Home Improvement / Bathroom Remodel & Fixtures / Shower & Bath Lighting', 'Decor & Accessories / Bathroom Decor / Lighted Mirrors', 'Smart Home / Connected Lighting / Bathroom Smart Lights', 'Furniture / Bathroom Furniture / Vanity Cabinets with Integrated Lighting']

Searching:  35%|███▌      | 170/480 [00:54<01:07,  4.60it/s]

Home Improvement
Lighting
Décor & Pillows
keywords='podium with locking cabinet' hallucinated_classification=['Furniture / Presentation & Display Furniture / Podiums & Lecterns', 'Furniture / Storage & Organization / Locking Cabinets', 'Furniture / Commercial Furniture / Podiums & Lecterns', 'Home Office / Conference & Presentation Furniture / Podiums', 'Event & Exhibition Furniture / Podiums & Stands', 'Security & Safety / Lockable Storage / Locking Cabinets']

Searching:  36%|███▌      | 171/480 [00:54<01:14,  4.16it/s]

School Furniture and Supplies
Furniture
Storage & Organization
keywords='sliding closet mirror' hallucinated_classification=['Home Improvement / Closet & Storage Solutions / Sliding Closet Doors with Mirrors', 'Furniture / Bedroom Furniture / Mirrored Closet Doors', 'Home Decor / Mirrors / Full-Length Sliding Mirror Doors', 'Smart Home / Automated Closet Systems / Mirror-Integrated Sliding Doors', 'Renovation & Remodeling / Closet Makeover / Mirror Sliding Doors']

Searching:  36%|███▌      | 172/480 [00:54<01:14,  4.13it/s]

Home Improvement
Furniture
Décor & Pillows
keywords='osgood mirror' hallucinated_classification=['Home Decor / Wall Mirrors / Decorative Wall Mirrors', 'Furniture / Entryway Furniture / Hall Trees & Coat Racks / Mirror with Storage', 'Living Room / Accent Furniture / Mirror Cabinets', 'Bathroom / Bathroom Mirrors / Frameless Mirrors', 'Bedroom / Bedroom Decor / Vanity Mirrors / Osgood Style Mirrors', 'Art & Decor / Wall Art / Mirror Art Installations']

Searching:  36%|███▌      | 173/480 [00:54<01:19,  3.84it/s]

Lighting
Furniture
Décor & Pillows
keywords='chabely 5 draw chest' hallucinated_classification=['Furniture / Bedroom Furniture / Chests of Drawers and Dressers', 'Furniture / Storage & Organization / Bedroom Storage Solutions', 'Home Decor / Vintage & Antique Furniture / Retro Chests', 'Furniture / Kids & Teen Bedroom Furniture / Kids Chests of Drawers', 'Furniture / Custom & Handmade Furniture / Artisan Chests']

Searching:  36%|███▋      | 174/480 [00:55<01:23,  3.68it/s]

Furniture
keywords='coffee bar buffet' hallucinated_classification=['Furniture / Kitchen & Dining Furniture / Buffet & Sideboards / Coffee Bar Buffets', 'Furniture / Home Bar & Beverage Stations / Coffee Bar Units', 'Kitchen & Tabletop / Kitchen Islands & Carts / Coffee Bar Carts', 'Decor & Accessories / Bar & Beverage Accessories / Coffee Bar Decor', 'Furniture / Entryway & Hallway Furniture / Entryway Buffets & Consoles']

Searching:  36%|███▋      | 175/480 [00:55<01:29,  3.40it/s]

Furniture
Décor & Pillows
keywords='pasta tools' hallucinated_classification=['Kitchen & Tabletop / Pasta & Noodle Makers / Manual Pasta Machines', 'Kitchen & Tabletop / Pasta Tools / Pasta Drying Racks', 'Kitchen & Tabletop / Pasta Tools / Pasta Portioning Devices', 'Kitchen & Tabletop / Pasta Tools / Pasta Cutting & Shaping Tools', 'Kitchen & Tabletop / Pasta Storage & Organization / Pasta Containers']

Searching:  37%|███▋      | 176/480 [00:55<01:31,  3.31it/s]

Kitchen & Tabletop
Appliances
keywords='cake plates with tops' hallucinated_classification=['Kitchen & Tabletop / Serveware / Cake Plates & Stands', 'Kitchen & Tabletop / Food Presentation / Cake Display Stands', 'Dining / Serveware / Cake & Dessert Plates', 'Home Decor / Kitchen Decor / Cake Plate Displays', 'Party Supplies / Cake & Dessert Accessories / Cake Plate Toppers']

Searching:  37%|███▋      | 177/480 [00:56<01:33,  3.23it/s]

Décor & Pillows
Kitchen & Tabletop
keywords='anti fatigue mat' hallucinated_classification=['Home & Office Comfort / Anti Fatigue Mats / Ergonomic Floor Mats', 'Health & Wellness / Anti Fatigue Mats / Standing Desk Mats', 'Industrial & Commercial Equipment / Anti Fatigue Mats / Anti Slip Floor Mats', 'Fitness & Exercise / Anti Fatigue Mats / Workout Floor Mats', 'Home Improvement / Kitchen & Laundry / Anti Fatigue Mats for Kitchen & Laundry']

Searching:  37%|███▋      | 178/480 [00:56<01:35,  3.17it/s]

Home Improvement
Furniture
Rugs
Bed & Bath
keywords='hillsby oriental rug' hallucinated_classification=['Home Decor / Rugs & Carpets / Oriental Rugs', 'Furniture / Area Rugs / Traditional Oriental Rugs', 'Decor & Pillows / Wall Hangings & Tapestries / Oriental Style Wall Hangings', 'Home Improvement / Flooring / Area Rugs & Carpets / Oriental Pattern Rugs', 'Interior Design / Accent Pieces / Oriental Inspired Decor']

Searching:  37%|███▋      | 179/480 [00:56<01:32,  3.26it/s]

Décor & Pillows
Rugs
keywords='kelly clarkson light fixtures' hallucinated_classification=['Lighting / Celebrity-Inspired Lighting Fixtures / Kelly Clarkson Signature Series', 'Home Decor / Music-Themed Light Fixtures / Pop Icon Collection', 'Lighting / Modern Artistic Fixtures / Celebrity Musician Designs', 'Furniture / Music & Entertainment Inspired Lighting / Celebrity Fan Collection', 'Lighting / Custom Celebrity Light Fixtures / Kelly Clarkson Edition']

Searching:  38%|███▊      | 180/480 [00:57<01:32,  3.23it/s]

Outdoor
Lighting
Furniture
Décor & Pillows
keywords='liberty hardware francisco' hallucinated_classification=['Hardware / Cabinet Hardware / Pulls and Handles / Francisco Collection Handles', 'Furniture / Entryway Furniture / Coat Racks and Hooks / Francisco Style Hooks', 'Decor / Wall Decor / Metal Wall Art / Francisco Design Metal Art', 'Home Improvement / Kitchen & Bath Fixtures / Cabinet Knobs / Francisco Series Knobs', 'Outdoor / Garden & Patio Hardware / Gate Latches / Francisco Style Latches']

Searching:  38%|███▊      | 181/480 [00:57<01:37,  3.06it/s]

Pet
Home Improvement
Bed & Bath
Décor & Pillows
keywords='surge protector' hallucinated_classification=['Home Electronics / Power Strips & Surge Protectors / Surge Protectors']
Home Improvement
keywords='wishbone chair' hallucinated_classification=['Furniture / Iconic & Designer Chairs / Wishbone Chairs', 'Furniture / Dining Room Furniture / Dining Chairs / Wishbone Style', 'Home Decor / Scandinavian Style Furniture / Wishbone Chair', 'Furniture / Vintage & Retro Furniture / Wishbone Chairs', 'Furniture / Living Room Furniture / Accent Chairs / Wishbone Design']

Searching:  38%|███▊      | 183/480 [00:57<01:16,  3.90it/s]

Furniture
keywords='glass lamp shades' hallucinated_classification=['Lighting / Lamp Shades / Glass Lamp Shades', 'Home Decor / Lighting Accessories / Glass Light Covers', 'Furniture / Lighting / Glass Lamp Shades', 'Decor & Pillows / Decorative Lighting / Glass Lamp Shades', 'Home Improvement / Lighting Fixtures / Glass Lamp Shades']

Searching:  38%|███▊      | 184/480 [00:58<01:23,  3.53it/s]

Lighting
Décor & Pillows
keywords='china clock' hallucinated_classification=['Decor & Collectibles / Clocks / China Clocks', 'Antiques & Vintage / China Clocks', 'Home Decor / Tabletop Clocks / China Style Clocks', 'Specialty Clocks / Porcelain Clocks / China Porcelain Clocks', 'Gift & Novelty / China Clocks']

Searching:  39%|███▊      | 185/480 [00:58<01:30,  3.25it/s]

Home Improvement
Décor & Pillows
keywords='wall art fiji' hallucinated_classification=['Decor & Wall Art / Island & Tropical Wall Art / Fiji-themed Wall Decor', 'Home Decor / Tropical & Beach-inspired Art / Fiji Landscape Paintings', 'Wall Decor / Tropical Wall Hangings / Fiji Island Motifs', 'Interior Decor / Exotic Wall Art / Fiji Cultural Artwork', 'Outdoor Decor / Tropical Wall Art / Fiji Island Scenes']

Searching:  39%|███▉      | 186/480 [00:59<01:34,  3.10it/s]

Outdoor
Décor & Pillows
keywords='sinks bed frame' hallucinated_classification=['Furniture / Bedroom Furniture / Bed Frames and Headboards', 'Home Improvement / Bathroom Fixtures / Bathroom Sinks', 'Furniture / Bathroom Furniture / Vanity Sinks', 'Decor & Accessories / Bathroom Decor / Sink Accessories', 'Furniture / Living Room Furniture / Coffee Tables & End Tables']

Searching:  39%|███▉      | 187/480 [00:59<01:26,  3.37it/s]

Home Improvement
Furniture
Bed & Bath
keywords='feather wall art' hallucinated_classification=['Decor & Wall Art / Wall Hangings & Art / Feather Wall Art', 'Home Decor / Wall Decorations / Feather Art Panels', 'Art & Collectibles / Wall Art / Feather Themed Art', 'Interior Design / Wall Accents / Feather Motif Wall Decor', 'Crafts & DIY / Wall Art Projects / Feather Wall Art Kits']

Searching:  39%|███▉      | 188/480 [00:59<01:23,  3.49it/s]

Décor & Pillows
keywords='itchington butterfly' hallucinated_classification=['Home Decor / Wall Art / Butterfly Wall Hangings', 'Furniture / Accent Pieces / Butterfly-Shaped Decor', 'Kids & Baby Furniture / Themed Bedroom Decor / Butterfly Motif', 'Outdoor / Garden Decor / Butterfly Garden Stakes', 'Crafts & DIY / Butterfly Craft Supplies']

Searching:  39%|███▉      | 189/480 [00:59<01:18,  3.69it/s]

Home Improvement
Baby & Kids
Outdoor
Décor & Pillows
keywords='kraus kitchen sink faucet oletto kpf 2820 sfs' hallucinated_classification=['Home Improvement / Kitchen Fixtures & Accessories / Kitchen Faucets', 'Kitchen & Tabletop / Kitchen Fixtures / Kitchen Sink Faucets', 'Plumbing & Fixtures / Kitchen & Bathroom Faucets / Kitchen Faucets', 'Kitchen & Dining / Kitchen Hardware / Kitchen Sink Accessories']

Searching:  40%|███▉      | 190/480 [00:59<01:13,  3.96it/s]

Home Improvement
Kitchen & Tabletop
keywords='serta kleinmon' hallucinated_classification=['Furniture / Mattresses & Sleep Products / Memory Foam Mattresses', 'Furniture / Bedroom Furniture / Platform Beds', 'Home Decor / Bed Frames & Headboards / Upholstered Bed Frames', 'Bedding & Linens / Mattress Protectors & Toppers / Memory Foam Toppers', 'Furniture / Living Room Furniture / Sectional Sofas & Modular Seating', 'Furniture / Kids & Teen Bedroom Furniture / Youth Beds & Bunk Beds', 'Home Improvement / Bedroom Renovation / Custom Closet Systems']

Searching:  40%|███▉      | 191/480 [01:00<01:21,  3.55it/s]

Baby & Kids
Home Improvement
Furniture
Bed & Bath
keywords='mattress foam topper queen' hallucinated_classification=['Home Bedding / Mattress Accessories / Foam Mattress Toppers / Queen Size']
Bed & Bath
keywords='wayfair coffee table' hallucinated_classification=['Furniture / Coffee Tables & End Tables / Coffee Tables', 'Furniture / Living Room Furniture / Coffee Tables & End Tables', 'Home Decor / Coffee Table Accessories / Decorative Trays and Coasters', 'Furniture / Multi-Functional Furniture / Storage Coffee Tables', 'Outdoor / Patio Coffee Tables / Wicker and Rattan Coffee Tables', 'Furniture / Modern & Contemporary Furniture / Minimalist Coffee Tables', 'Furniture / Vintage & Retro Furniture / Antique Coffee Tables']

Searching:  40%|████      | 193/480 [01:00<01:08,  4.18it/s]

Outdoor
Furniture
Décor & Pillows
keywords='bathroom wastebasket' hallucinated_classification=['Home Organization / Bathroom Storage & Accessories / Wastebaskets and Trash Cans', 'Bathroom Accessories / Waste Management / Bathroom Wastebaskets', 'Furniture / Bathroom Furniture / Bathroom Wastebaskets & Bins', 'Home Decor / Bathroom Decor / Bathroom Wastebaskets', 'Cleaning & Maintenance / Waste Disposal / Bathroom Wastebaskets']

Searching:  40%|████      | 194/480 [01:00<01:08,  4.19it/s]

Home Improvement
Furniture
Storage & Organization
Bed & Bath
keywords='welcome sign' hallucinated_classification=['Decor & Wall Art / Welcome Signs & Door Hangers / Welcome Signs', 'Home Decor / Entryway Decor / Welcome Signs', 'Seasonal & Holiday Decor / Welcome Signs / General Welcome Signs', 'Personalized Home Decor / Custom Welcome Signs / Name Signs', 'Outdoor Decor / Garden & Yard Signs / Welcome Signs']

Searching:  41%|████      | 195/480 [01:01<01:07,  4.25it/s]

Outdoor
Holiday Décor
Décor & Pillows
keywords='hinged square ottoman' hallucinated_classification=['Furniture / Ottoman & Poufs / Storage Ottomans', 'Furniture / Living Room Furniture / Accent Ottomans', 'Furniture / Multi-Functional Furniture / Convertible Ottomans', 'Home Decor / Upholstered Furniture / Square Ottomans', 'Furniture / Footstools & Stools / Square Footstools']

Searching:  41%|████      | 196/480 [01:01<01:07,  4.19it/s]

Furniture
Décor & Pillows
keywords='wooden chair outdoor' hallucinated_classification=['Outdoor Furniture / Patio & Garden Chairs / Wooden Outdoor Chairs', 'Garden & Patio / Outdoor Seating / Wooden Garden Chairs', 'Furniture / Outdoor Furniture / Wooden Lounge Chairs', 'Decor & Accessories / Garden Decor / Wooden Garden Benches and Chairs', 'Home & Garden / Outdoor Living / Wooden Patio Furniture']

Searching:  41%|████      | 197/480 [01:01<01:06,  4.23it/s]

Outdoor
Furniture
keywords='day bed indian' hallucinated_classification=['Furniture / Bedroom Furniture / Day Beds & Trundle Beds', 'Furniture / Bedroom Furniture / Indian Style Furniture', 'Furniture / Guest & Day Beds / Indian Inspired Day Beds', 'Home Decor / Cultural & Ethnic Decor / Indian Themed Home Goods', 'Furniture / Specialty & Custom Furniture / Handcrafted Indian Day Beds']

Searching:  41%|████▏     | 198/480 [01:01<01:07,  4.20it/s]

Furniture
Décor & Pillows
keywords='nesting tray set' hallucinated_classification=['Home Organization / Kitchen & Pantry Storage / Nesting Tray Sets', 'Furniture / Kitchen Islands & Carts / Nesting Tray Carts', 'Decor & Accessories / Display & Serving Trays / Nesting Serving Trays', 'Storage & Organization / Closet & Drawer Organizers / Nesting Drawer Trays', 'Office & Craft Supplies / Desk Organizers / Nesting Tray Organizers']

Searching:  41%|████▏     | 199/480 [01:02<01:08,  4.12it/s]

Décor & Pillows
Furniture
Kitchen & Tabletop
Storage & Organization
keywords='bistro table and chairs' hallucinated_classification=['Furniture / Dining Room Furniture / Bistro Tables and Chairs', 'Outdoor / Patio Dining Sets / Bistro Tables and Chairs', 'Commercial Furniture / Restaurant & Cafe Furniture / Bistro Sets', 'Home Decor / Kitchen & Dining Accessories / Bistro Table Sets', 'Furniture / Small Space Living / Bistro Table and Chair Sets']

Searching:  42%|████▏     | 200/480 [01:02<01:08,  4.07it/s]

Outdoor
Furniture
Décor & Pillows
keywords='wayfair tension rod' hallucinated_classification=['Home Improvement / Window Treatments / Tension Rods and Curtain Rods', 'Home Organization / Closet & Storage Solutions / Tension Rods for Shelving', 'Furniture / Bathroom Accessories / Tension Rods for Shower Curtains', 'Decor & Pillows / Curtain & Drapery Hardware / Tension Rods for Curtains', 'Outdoor / Garden & Patio / Tension Rods for Outdoor Use']

Searching:  42%|████▏     | 201/480 [01:03<02:34,  1.80it/s]

Outdoor
Storage & Organization
Décor & Pillows
Bed & Bath
keywords='island estate coffee table' hallucinated_classification=['Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables', 'Furniture / Outdoor Furniture / Patio Coffee Tables', 'Luxury Home Decor / Statement Coffee Tables / Island-Inspired Designs', 'Eco-Friendly Furniture / Reclaimed Wood Coffee Tables / Island Style', 'Custom Furniture / Handcrafted Coffee Tables / Estate Collection']

Searching:  42%|████▏     | 202/480 [01:04<02:20,  1.98it/s]

Outdoor
Furniture
keywords='pastel pink desk chair' hallucinated_classification=['Furniture / Office Furniture / Desk Chairs & Swivel Chairs', 'Furniture / Kids & Teen Furniture / Kids Desk Chairs', 'Home Decor / Accent Furniture / Colorful Accent Chairs', 'Furniture / Lounge & Accent Chairs / Upholstered Chairs', 'Furniture / Vintage & Retro Furniture / Pastel Colored Chairs', 'Furniture / Custom & Designer Furniture / Custom Color Desk Chairs']

Searching:  42%|████▏     | 203/480 [01:04<02:01,  2.28it/s]

Baby & Kids
Furniture
keywords='writing desk' hallucinated_classification=['Furniture / Home Office Furniture / Desks and Workstations / Writing Desks', 'Furniture / Kids & Teen Furniture / Study Desks & Tables', 'Furniture / Entryway & Hallway Furniture / Console Desks', 'Furniture / Custom & Modular Furniture / Modular Desks & Workstations', 'Furniture / Vintage & Antique Furniture / Antique Writing Desks', 'Furniture / Multi-Functional Furniture / Convertible Desks & Tables']

Searching:  42%|████▎     | 204/480 [01:04<01:50,  2.51it/s]

Baby & Kids
Furniture
keywords='laundry basket with wheels' hallucinated_classification=['Home Organization / Laundry & Utility Storage / Rolling Laundry Baskets', 'Furniture / Laundry Room Furniture / Laundry Hampers with Wheels', 'Home Accessories / Laundry Room Accessories / Mobile Laundry Carts', 'Cleaning & Maintenance / Laundry Supplies / Rolling Laundry Bins', 'Eco-Friendly Living / Sustainable Home Storage / Reusable Laundry Baskets']

Searching:  43%|████▎     | 205/480 [01:04<01:37,  2.82it/s]

Storage & Organization
Bed & Bath
keywords='blue faux throw with pillows' hallucinated_classification=['Décor & Pillows / Throw Pillows & Cushions / Faux Throw Pillows', 'Furniture / Living Room Furniture / Accent Chairs & Ottomans / Faux Throw Chairs', 'Bedding & Linens / Throw Blankets / Faux Throw Blankets', 'Home Decor / Textiles & Fabrics / Faux Fur Textiles', 'Furniture / Bedroom Furniture / Bed Accessories / Faux Throw Bedding']

Searching:  43%|████▎     | 206/480 [01:05<01:29,  3.05it/s]

Bed Accessories
Furniture
Décor & Pillows
keywords='auburn throw pillows' hallucinated_classification=['Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows / Auburn Color']
Décor & Pillows

Searching:  43%|████▎     | 207/480 [01:05<01:12,  3.76it/s]

keywords='tall free standing pet gate' hallucinated_classification=['Home & Garden / Pet Supplies / Pet Gates & Barriers / Free Standing Pet Gates', 'Furniture / Home Office & Entryway Furniture / Hallway & Entryway Storage / Shoe & Coat Racks', 'Home Improvement / Pet Doors & Gates / Free Standing Pet Gates', 'Outdoor / Pet & Animal Enclosures / Free Standing Pet Fences', 'Furniture / Kids & Teen Furniture / Kids Room Dividers & Partitions']

Searching:  43%|████▎     | 208/480 [01:05<01:31,  2.98it/s]

Baby & Kids
Outdoor
Pet
Home Improvement
Furniture
keywords='waterfall faucet' hallucinated_classification=['Home Improvement / Bathroom Fixtures / Faucets / Waterfall Faucets', 'Kitchen & Bath / Kitchen & Bathroom Fixtures / Waterfall Sink Faucets', 'Decor & Accessories / Bathroom Decor / Waterfall Style Faucets', 'Luxury Home Goods / Spa & Wellness / Waterfall Showerheads', 'Plumbing & Hardware / Specialty Faucets / Waterfall Design Faucets']

Searching:  44%|████▎     | 209/480 [01:06<01:42,  2.65it/s]

Home Improvement
Décor & Pillows
keywords='parakeet toy' hallucinated_classification=['Pet Accessories / Bird Toys / Parakeet Toys', 'Pet Supplies / Bird Enrichment / Parakeet Play Equipment', 'Bird Care / Parakeet Toys and Accessories', 'Animal Enrichment / Bird Toys / Parakeet Chew Toys', 'Pet Toys / Small Animal Toys / Bird Toys']

Searching:  44%|████▍     | 210/480 [01:06<01:46,  2.53it/s]

Pet
Outdoor
Décor & Pillows
keywords='marlon tufted queen bed' hallucinated_classification=['Furniture / Bedroom Furniture / Queen Beds / Tufted Queen Beds', 'Furniture / Bedroom Furniture / Upholstered Beds / Tufted Beds', 'Luxury Bedroom Furniture / Upholstered & Tufted Beds / Queen Size', 'Home Decor / Bed Frames / Tufted Bed Frames / Queen Size', 'Custom Furniture / Upholstered Beds / Tufted Queen Bed']

Searching:  44%|████▍     | 211/480 [01:07<01:48,  2.47it/s]

Furniture
keywords='broadway lever' hallucinated_classification=['Hardware / Door Hardware / Door Levers and Handles', 'Furniture / Entryway Furniture / Coat Racks and Hooks', 'Home Improvement / Door & Window Hardware / Door Locks and Latches', 'Decor & Accessories / Wall Decor / Artistic Wall Mounts', 'Smart Home / Home Automation Devices / Smart Locks']

Searching:  44%|████▍     | 212/480 [01:07<01:37,  2.74it/s]

Home Improvement
Bed & Bath
Décor & Pillows
keywords='delta trinsic' hallucinated_classification=['Furniture / Smart Furniture / Connected Desks and Tables', 'Home Office / Ergonomic Desks / Adjustable Standing Desks', 'Furniture / Modular Furniture / Customizable Configurations', 'Home Decor / Tech-Integrated Decor / Smart Display Units', 'Furniture / Conference & Meeting Room Furniture / Collaborative Work Tables']

Searching:  44%|████▍     | 213/480 [01:07<01:29,  2.98it/s]

Furniture
Décor & Pillows
keywords='accent leather chair' hallucinated_classification=['Furniture / Accent Chairs / Leather Accent Chairs', 'Furniture / Living Room Furniture / Lounge Chairs & Armchairs', 'Furniture / Home Office Furniture / Leather Desk Chairs', 'Furniture / Reading Nooks / Leather Reading Chairs', 'Furniture / Vintage & Retro Furniture / Leather Vintage Chairs', 'Furniture / Custom & Designer Furniture / Handcrafted Leather Chairs']

Searching:  45%|████▍     | 214/480 [01:08<01:32,  2.88it/s]

Furniture
keywords='dining table vinyl cloth' hallucinated_classification=['Furniture / Dining Room Furniture / Dining Tables & Sets / Dining Tables', 'Home Decor / Table Linens / Vinyl Tablecloths', 'Kitchen & Dining / Table Accessories / Table Protectors & Covers', 'Furniture / Custom Furniture / Upholstered Dining Tables', 'Outdoor / Patio Dining Furniture / Dining Tables & Sets']

Searching:  45%|████▍     | 215/480 [01:08<01:30,  2.94it/s]

Outdoor
Furniture
Kitchen & Tabletop
keywords='acrylic clear chair' hallucinated_classification=['Furniture / Modern & Contemporary Furniture / Acrylic & Lucite Chairs', 'Furniture / Office & Desk Chairs / Transparent Office Chairs', 'Furniture / Dining Room Furniture / Acrylic Dining Chairs', 'Furniture / Accent & Side Chairs / Clear Accent Chairs', 'Furniture / Kids & Teen Furniture / Acrylic Kids Chairs', 'Furniture / Outdoor Furniture / Transparent Patio Chairs']

Searching:  45%|████▌     | 216/480 [01:08<01:32,  2.85it/s]

School Furniture and Supplies
Outdoor
Furniture
keywords='pennfield playhouse' hallucinated_classification=["Entertainment & Play Furniture / Playhouse Structures / Children's Playhouses", 'Outdoor & Garden / Playhouse & Treehouse Accessories / Playhouse Accessories', 'Kids & Baby / Play & Activity Furniture / Playhouses for Kids', 'Home & Living / Themed Furniture / Playhouse Themed Furniture', "Educational & Learning / Children's Play & Learning Spaces / Playhouse Learning Zones"]

Searching:  45%|████▌     | 217/480 [01:09<01:33,  2.81it/s]

Baby & Kids
Outdoor
Furniture
keywords='mahone porch rocking chair' hallucinated_classification=['Outdoor / Outdoor Furniture / Porch & Patio Chairs / Rocking Chairs', 'Furniture / Porch & Patio Furniture / Porch Swings & Rocking Chairs', 'Home & Garden / Garden & Patio Decor / Porch Decor & Accessories', 'Furniture / Vintage & Antique Furniture / Vintage Rocking Chairs', 'Outdoor / Garden Seating / Rocking & Glider Chairs']

Searching:  45%|████▌     | 218/480 [01:09<01:29,  2.92it/s]

Outdoor
Furniture
Décor & Pillows
keywords='meditation' hallucinated_classification=['Home Wellness & Relaxation / Meditation Spaces & Accessories / Meditation Furniture', 'Furniture / Relaxation & Wellness Furniture / Meditation Chairs & Cushions', 'Home Decor / Meditation & Mindfulness Decor / Zen & Meditation Art', 'Home Improvement / Spa & Wellness Rooms / Meditation Rooms & Pods', 'Outdoor / Zen Gardens & Meditation Spaces / Meditation Garden Furniture']

Searching:  46%|████▌     | 219/480 [01:09<01:27,  2.99it/s]

Kitchen & Tabletop
Outdoor
Furniture
Décor & Pillows
keywords='dumbbells' hallucinated_classification=['Fitness Equipment / Strength Training Equipment / Dumbbells and Free Weights', 'Home Gym / Exercise Equipment / Dumbbells', 'Sports & Outdoors / Fitness & Exercise / Dumbbells']

Searching:  46%|████▌     | 220/480 [01:09<01:16,  3.41it/s]

Outdoor
Home Improvement
Appliances
keywords='almost heaven sauna' hallucinated_classification=['Home & Wellness / Saunas & Steam Rooms / Infrared Saunas', 'Home & Wellness / Saunas & Steam Rooms / Traditional Finnish Saunas', 'Home & Wellness / Sauna Accessories / Sauna Heaters & Stoves', 'Home & Wellness / Sauna Accessories / Sauna Benches & Seating', 'Home & Wellness / Sauna Accessories / Sauna Lighting & Controls', 'Home & Wellness / Sauna Installation & Maintenance']

Searching:  46%|████▌     | 221/480 [01:10<01:23,  3.10it/s]

Home Improvement
Outdoor
Furniture
Appliances
keywords='mom urn' hallucinated_classification=['Home Decor / Memorial & Tribute Items / Urns & Keepsake Containers', 'Furniture / Specialty & Themed Furniture / Memorial & Tribute Furniture', 'Home Decor / Personalized & Custom Items / Custom Memorial Pieces', 'Outdoor / Garden & Memorial Statues / Memorial Garden Decor', 'Home Improvement / Interior Decor / Wall Art & Murals / Memorial Wall Art']

Searching:  46%|████▋     | 222/480 [01:10<01:24,  3.05it/s]

Outdoor
Furniture
Décor & Pillows
keywords='lunch bag' hallucinated_classification=['Kitchen & Tabletop / Food Storage & Canisters / Lunch Bags', 'Travel & Outdoor Gear / Lunch & Snack Bags / Insulated Lunch Bags', 'Kids & Baby / Kids Lunch Accessories / Kids Lunch Bags', 'Office & School Supplies / School Lunch Accessories / Reusable Lunch Bags', 'Eco-Friendly & Sustainable Products / Reusable Food Storage / Reusable Lunch Bags']

Searching:  46%|████▋     | 223/480 [01:10<01:18,  3.27it/s]

Baby & Kids
Outdoor
Kitchen & Tabletop
School Furniture and Supplies
Storage & Organization
keywords='chaves l-shape floating desk with hutch' hallucinated_classification=['Furniture / Home Office Furniture / Desks & Workstations', 'Furniture / Modular & Customizable Furniture / L-Shaped Desks', 'Furniture / Storage & Organization / Desk Hutch & Shelving Units', 'Home Improvement / Office & Study Room Renovations / Office Furniture Installation']

Searching:  47%|████▋     | 224/480 [01:11<01:10,  3.61it/s]

Furniture
Storage & Organization
keywords='king poster bed' hallucinated_classification=['Furniture / Bedroom Furniture / Canopy & Poster Beds', 'Luxury Bedroom Furniture / King Size Beds / Ornate Poster Beds', 'Kids & Teens Bedroom Furniture / Canopy & Poster Beds', 'Custom Furniture / Handcrafted Poster Beds / King Size', 'Vintage & Antique Furniture / Poster Beds / King Size']

Searching:  47%|████▋     | 225/480 [01:11<01:09,  3.69it/s]

Baby & Kids
Furniture
keywords='togo chair' hallucinated_classification=['Furniture / Lounge & Accent Chairs / Togo Style Chairs', 'Furniture / Modern & Contemporary Furniture / Togo-Inspired Seating', 'Home Decor / Statement Pieces / Togo Chair Designs', 'Furniture / Custom & Designer Chairs / Togo Collection', 'Outdoor / Patio & Garden Seating / Togo Style Outdoor Chairs']

Searching:  47%|████▋     | 226/480 [01:11<01:06,  3.82it/s]

Outdoor
Furniture
Décor & Pillows
keywords='kitchen anti fatigue mats' hallucinated_classification=['Home & Kitchen / Kitchen Mats & Rugs / Anti Fatigue Mats', 'Home & Kitchen / Kitchen Comfort & Safety / Anti Fatigue Mats', 'Home & Kitchen / Kitchen Accessories / Anti Fatigue Mats', 'Home & Kitchen / Kitchen Safety / Anti Fatigue Mats']

Searching:  47%|████▋     | 227/480 [01:11<01:01,  4.14it/s]

Furniture
Rugs
Bed & Bath
keywords='orren ellis l shape desk' hallucinated_classification=['Furniture / Office Furniture / Desks / L-Shaped Desks', 'Furniture / Home Office / Executive Desks / L-Shape Desks', 'Furniture / Modern Furniture / Modular Desks / L-Shape Configurations', 'Furniture / Custom Furniture / Bespoke Desks / L-Shape Designs', 'Home Office / Desks & Workstations / Corner Desks / L-Shape']

Searching:  48%|████▊     | 228/480 [01:12<01:03,  3.95it/s]

Baby & Kids
Furniture
keywords='calvin patio chair' hallucinated_classification=['Outdoor / Outdoor & Patio Furniture / Patio Chairs / Calvin Style Patio Chair', 'Furniture / Patio & Garden Furniture / Lounge Chairs / Calvin Design Lounge Chair', 'Outdoor / Patio Furniture Accessories / Patio Chair Cushions / Calvin Pattern Cushions', 'Furniture / Outdoor Furniture / Dining Chairs / Calvin Patio Dining Chair', 'Home Decor / Garden & Patio Decor / Patio Furniture Accents / Calvin Inspired Patio Decor']

Searching:  48%|████▊     | 229/480 [01:12<01:02,  4.04it/s]

Outdoor
keywords='super bright lights' hallucinated_classification=['Lighting / Specialty & Decorative Lighting / Super Bright LED Fixtures', 'Home Improvement / Electrical & Lighting / High-Intensity Lighting Solutions', 'Smart Home / Lighting & Controls / Brightness-Adjustable Smart Lights', 'Outdoor / Security & Flood Lights / Super Bright Flood Lights', 'Commercial & Industrial / Warehouse & Shop Lighting / High-Output Industrial Lights']

Searching:  48%|████▊     | 230/480 [01:12<01:01,  4.09it/s]

Lighting
keywords='printers' hallucinated_classification=['Electronics / Office Equipment / Printers & Scanners / Printers', 'Home Office / Office Machines / Printing Devices', 'Technology & Gadgets / Printing Solutions / Desktop Printers', 'Business & Commercial Equipment / Printing & Copying / Printers', 'Creative & Design Tools / Printing Equipment / Digital Printers']

Searching:  48%|████▊     | 231/480 [01:12<01:00,  4.13it/s]

Commercial Business Furniture
Furniture
Kitchen & Tabletop
keywords='wall design shelf' hallucinated_classification=['Furniture / Wall Decor / Wall Shelves & Racks', 'Home Organization / Wall-mounted Storage / Shelving Units', 'Decor & Accessories / Wall Art & Murals / Wall Stickers and Decals', 'Furniture / Living Room Furniture / Shelving & Bookcases', 'DIY & Home Improvement / Wall Mounting Hardware / Brackets and Mounts']

Searching:  48%|████▊     | 232/480 [01:13<01:03,  3.93it/s]

Home Improvement
Storage & Organization
Décor & Pillows
Furniture
keywords='merlyn 6' hallucinated_classification=['Furniture / Modern & Contemporary Furniture / Modular Shelving Units', 'Home Office / Desks & Workstations / Compact Desks', 'Living Room / Accent Furniture / Statement Chairs', 'Bedroom / Bed Frames / Platform Beds', 'Outdoor / Garden & Patio Furniture / Lounge Chairs', 'Decor & Accessories / Artistic Wall Hangings / Sculptural Art']

Searching:  49%|████▊     | 233/480 [01:13<01:06,  3.72it/s]

Outdoor
Storage & Organization
Décor & Pillows
Furniture
keywords='delta trinsic double towel hook in champagne bronze' hallucinated_classification=['Home Improvement / Bathroom Fixtures / Towel Hooks & Holders', 'Furniture / Bathroom Accessories / Towel Racks & Hooks', 'Decor & Pillows / Bathroom Decor / Towel Hooks', 'Hardware / Wall Mounts / Towel Hooks', 'Interior Design / Bathroom Accessories / Towel Hooks']

Searching:  49%|████▉     | 234/480 [01:13<01:04,  3.82it/s]

Home Improvement
Bed & Bath
keywords='mission double vanity' hallucinated_classification=['Furniture / Bathroom Furniture / Double Vanities', 'Furniture / Custom Bathroom Vanities / Mission Style Double Vanities', 'Home Improvement / Bathroom Remodel & Fixtures / Double Vanity Units', 'Decor & Accessories / Bathroom Decor / Mission Style Bathroom Accessories', 'Furniture / Luxury Bathroom Furniture / Double Vanities with Storage']

Searching:  49%|████▉     | 235/480 [01:13<01:04,  3.82it/s]

Home Improvement
Furniture
keywords='hussain handmade tufted magenta rug' hallucinated_classification=['Home Decor / Rugs & Carpets / Area Rugs / Tufted Rugs', 'Furniture / Floor Coverings / Rugs & Carpets / Handmade Rugs', 'Decor & Pillows / Rugs / Handmade Rugs', 'Home Improvement / Flooring / Area Rugs / Tufted Rugs', 'Art & Collectibles / Textile Art / Handmade Rugs']

Searching:  49%|████▉     | 236/480 [01:14<01:03,  3.86it/s]

Rugs
keywords='midcentury tv unit' hallucinated_classification=['Furniture / Living Room Furniture / TV Stands & Media Consoles / Midcentury TV Units', 'Furniture / Entertainment Centers / Retro TV Cabinets', 'Home Decor / Vintage & Retro Furniture / Midcentury Modern TV Furniture', 'Furniture / Customizable Furniture / Modular TV Units', 'Furniture / Eco-Friendly & Sustainable Furniture / Reclaimed Wood TV Units']

Searching:  49%|████▉     | 237/480 [01:14<01:03,  3.85it/s]

Furniture
keywords='desk for kids that are 10 year old' hallucinated_classification=['Furniture / Kids & Teen Furniture / Desks & Study Tables / Kids Desks', 'Furniture / Kids & Teen Furniture / Desks & Study Tables / Adjustable Height Desks for Kids', "Home Office / Children's Study Areas / Kids Desk Sets", 'School & Educational Furniture / Classroom Desks / Student Desks', 'Decor & Accessories / Kids Room Decor / Themed Desk Accessories']

Searching:  50%|████▉     | 238/480 [01:14<01:02,  3.84it/s]

Baby & Kids
School Furniture and Supplies
Décor & Pillows
Furniture
keywords='whimsical solar lights' hallucinated_classification=['Outdoor / Garden Decor / Solar Garden Lights and Lanterns', 'Lighting / Solar-Powered Decorative Lights / Whimsical Solar Lights', 'Home Decor / Themed Decorative Lighting / Whimsical Solar Light Fixtures', 'Outdoor / Pathway & Garden Lighting / Whimsical Solar Path Lights', 'Party & Event Decor / Themed Lighting / Whimsical Solar String Lights']

Searching:  50%|████▉     | 239/480 [01:14<01:01,  3.94it/s]

Lighting
Holiday Décor
keywords='laundry vanity cabinet' hallucinated_classification=['Home Improvement / Laundry Room Fixtures / Laundry Vanity Cabinets', 'Furniture / Utility & Storage Furniture / Laundry & Utility Cabinets', 'Home Organization / Laundry Room Storage / Vanity Cabinets for Laundry', 'Kitchen & Laundry / Laundry Room Furniture / Vanity Cabinets', 'Bathroom & Laundry / Laundry & Utility Furniture / Vanity Cabinets']

Searching:  50%|█████     | 240/480 [01:15<01:00,  3.97it/s]

Home Improvement
Furniture
Storage & Organization
keywords='modern outdoor furniture' hallucinated_classification=['Outdoor / Outdoor & Patio Furniture / Modern Patio Sets', 'Outdoor / Outdoor & Patio Furniture / Modular Outdoor Sofas', 'Outdoor / Outdoor & Patio Furniture / Contemporary Garden Chairs', 'Outdoor / Outdoor & Patio Furniture / Weather-Resistant Lounge Chairs', 'Outdoor / Outdoor & Patio Furniture / Minimalist Patio Tables', 'Outdoor / Outdoor & Patio Furniture / Sleek Outdoor Benches']

Searching:  50%|█████     | 241/480 [01:15<01:10,  3.41it/s]

Outdoor
keywords='coffee container' hallucinated_classification=['Kitchen & Tabletop / Food Storage & Canisters / Coffee Canisters', 'Home Organization / Kitchen Storage / Coffee & Tea Storage Solutions', 'Kitchen & Dining / Coffee & Tea Accessories / Coffee Storage Containers', 'Home Decor / Kitchen Decor / Coffee-Themed Decor Items', 'Appliances / Coffee Makers & Accessories / Coffee Storage & Dispensers']

Searching:  50%|█████     | 242/480 [01:15<01:17,  3.07it/s]

Décor & Pillows
Kitchen & Tabletop
Appliances
keywords='drum picture' hallucinated_classification=['Decor & Wall Art / Musical Instrument Wall Decor / Drum Art Prints', 'Home Decor / Musical Instrument Themed Decor / Drum Wall Hangings', 'Art & Collectibles / Music Memorabilia / Drum Artwork', 'Kids & Teens Room Decor / Music Theme Wall Art / Drum Pictures', 'Music & Instruments / Wall Art & Posters / Drum Illustrations']

Searching:  51%|█████     | 243/480 [01:16<01:21,  2.90it/s]

Baby & Kids
Décor & Pillows
keywords='dinosaur' hallucinated_classification=['Decor & Wall Art / Dinosaur Themed Decor / Dinosaur Wall Hangings and Art', 'Kids & Baby Furniture / Dinosaur Themed Bedroom Furniture / Dinosaur Bed Frames and Dressers', 'Toys & Games / Dinosaur Toys / Dinosaur Action Figures and Plush Toys', 'Outdoor & Garden / Dinosaur Garden Statues / Dinosaur Garden Decor', 'Party Supplies / Dinosaur Party Decorations / Dinosaur Balloons and Banners', 'Educational & Learning / Dinosaur Educational Toys / Dinosaur Puzzle and Learning Kits']

Searching:  51%|█████     | 244/480 [01:16<01:19,  2.98it/s]

Baby & Kids
Outdoor
School Furniture and Supplies
Décor & Pillows
keywords='antique silver entry table' hallucinated_classification=['Furniture / Entryway Furniture / Console Tables and Entry Tables', 'Decor / Antique Silver Home Decor / Silver Accents and Accessories', 'Furniture / Vintage & Antique Furniture / Silver Finish Furniture', 'Home Improvement / Entryway & Hallway Renovation / Hallway Storage Solutions', 'Decor / Silver Decor / Silver Decorative Items']

Searching:  51%|█████     | 245/480 [01:16<01:13,  3.21it/s]

Home Improvement
Furniture
Décor & Pillows
keywords='ergonomic chair' hallucinated_classification=['Furniture / Office Furniture / Ergonomic Chairs', 'Furniture / Lounge & Recliners / Ergonomic Lounge Chairs', 'Furniture / Gaming & Computer Chairs / Ergonomic Gaming Chairs', 'Furniture / Health & Wellness Furniture / Posture Support Chairs', 'Furniture / Customizable Furniture / Modular Ergonomic Seating']

Searching:  51%|█████▏    | 246/480 [01:17<01:08,  3.39it/s]

Furniture
keywords='wall sconce with usb port' hallucinated_classification=['Lighting / Wall Lights / USB Wall Sconce with Integrated Charging']
Lighting
keywords='5 gang light switch' hallucinated_classification=['Home Improvement / Electrical / Light Switches / Multi-Gang Light Switches', 'Smart Home / Home Automation / Light Control Panels / Multi-Gang Switch Panels', 'Electrical & Wiring / Switches & Dimmers / Multi-Gang Switches', 'Lighting / Wall Switches / Multi-Gang Light Switches']

Searching:  52%|█████▏    | 248/480 [01:17<00:51,  4.51it/s]

Lighting
Home Improvement
keywords='entrance table' hallucinated_classification=['Furniture / Entryway & Hallway Furniture / Entrance Tables & Benches / Entrance Tables', 'Furniture / Foyer & Mudroom Furniture / Console Tables / Entrance Console Tables', 'Home Decor / Entryway Decor / Hallway Racks & Shelves / Entryway Shelves', 'Furniture / Multi-Functional Furniture / Storage & Organization / Entryway Storage Units', 'Outdoor / Porch & Patio Furniture / Entryway Benches & Tables']

Searching:  52%|█████▏    | 249/480 [01:17<00:53,  4.36it/s]

Outdoor
Furniture
Storage & Organization
keywords='kisner' hallucinated_classification=['Furniture / Specialty & Niche Furniture / Kisner Collection', 'Home Decor / Artistic & Themed Decor / Kisner Style Decor', 'Furniture / Custom & Designer Furniture / Kisner Series', 'Living Room / Unique Coffee Tables / Kisner Design Coffee Tables', 'Bedroom / Themed Bedroom Furniture / Kisner Bedroom Set']

Searching:  52%|█████▏    | 250/480 [01:17<00:53,  4.31it/s]

Outdoor
Furniture
keywords='bar room wall decor' hallucinated_classification=['Decor & Wall Art / Bar Themed Wall Decor / Neon Bar Signs', 'Decor & Wall Art / Vintage Liquor & Cocktail Art / Framed Prints', 'Furniture / Bar & Lounge Furniture / Wall-Mounted Bar Shelves', 'Decor & Wall Art / Customizable Wall Murals / Cocktail & Bar Scenes', 'Home Improvement / Home Bar Accessories / Wall-Mounted Bottle Holders', 'Decor & Wall Art / Metallic Wall Sculptures / Bar & Liquor Motifs']

Searching:  52%|█████▏    | 251/480 [01:18<00:58,  3.93it/s]

Home Improvement
Storage & Organization
Décor & Pillows
keywords='queen wingback chair' hallucinated_classification=['Furniture / Living Room Furniture / Accent Chairs / Wingback Chairs', 'Furniture / Bedroom Furniture / Armchairs / Wingback Chairs', 'Furniture / Vintage & Antique Furniture / Wingback Chairs', 'Furniture / Custom & Designer Furniture / Wingback Chairs', 'Furniture / Eco-Friendly & Sustainable Furniture / Wingback Chairs', 'Furniture / Luxury & High-End Furniture / Wingback Chairs', 'Furniture / Small Space & Apartment Furniture / Compact Wingback Chairs']
Outdoor
Furniture

Searching:  52%|█████▎    | 252/480 [01:18<01:13,  3.11it/s]

keywords='indoor multi tiered plant stand' hallucinated_classification=['Home & Garden / Indoor Gardening / Plant Stands & Holders / Multi-Tiered Plant Stands', 'Furniture / Indoor Storage & Organization / Plant Display Shelves / Multi-Tiered Plant Racks', 'Decor & Accessories / Indoor Garden Decor / Tiered Plant Stands', 'Home Improvement / Indoor Plant Care / Plant Display Solutions / Multi-Tiered Stands']

Searching:  53%|█████▎    | 253/480 [01:19<01:19,  2.85it/s]

Outdoor
Storage & Organization
Furniture
keywords='rug for teen room' hallucinated_classification=['Home Decor / Rugs & Carpets / Area Rugs for Teen Rooms', 'Furniture / Teen Bedroom Furniture / Teen Room Rugs', 'Kids & Teens / Teen Room Accessories / Rug Collections', 'Home Improvement / Flooring / Area Rugs for Bedrooms', 'Décor & Pillows / Teen Room Decor / Rug Designs']

Searching:  53%|█████▎    | 254/480 [01:19<01:21,  2.76it/s]

Baby & Kids
Décor & Pillows
Rugs
keywords='wayfair comforters' hallucinated_classification=['Home Textiles / Bedding / Comforters & Duvets', 'Bedroom Accessories / Comforter Sets / Quilted Comforters', 'Home Decor / Bed Linens / Comforter Covers', 'Luxury Bedding / Comforters / Plush Comforters', 'Kids & Teens / Bedding / Comforters & Sets', 'Seasonal & Themed Bedding / Comforters / Holiday Comforters']

Searching:  53%|█████▎    | 255/480 [01:19<01:18,  2.87it/s]

Bed Accessories
Baby & Kids
Bed & Bath
Décor & Pillows
keywords='champagne velvet desk chair' hallucinated_classification=['Furniture / Office Furniture / Desk Chairs and Swivel Chairs', 'Furniture / Living Room Furniture / Accent Chairs', 'Furniture / Bedroom Furniture / Vanity Chairs', 'Home Decor / Upholstered Furniture / Velvet Chairs', 'Furniture / Home Office / Executive Desk Chairs', 'Furniture / Lounge & Club Chairs / Velvet Lounge Chairs']

Searching:  53%|█████▎    | 256/480 [01:20<01:13,  3.03it/s]

Furniture
Décor & Pillows
keywords='regner power loom red' hallucinated_classification=['Home Appliances / Sewing & Knitting Machines / Power Looms', 'Furniture / Vintage & Antique Furniture / Red Power Loom Decor', 'Home Decor / Textile Art / Power Loom Wall Hangings', 'Crafts & Hobbies / Textile Crafts / Power Loom Fabric Art', 'Industrial Equipment / Textile Manufacturing / Power Loom Machinery']

Searching:  54%|█████▎    | 257/480 [01:20<01:08,  3.27it/s]

Kitchen & Tabletop
Home Improvement
Décor & Pillows
Appliances
keywords='brush nickel faucet bathroom' hallucinated_classification=['Home Improvement / Bathroom Fixtures & Accessories / Faucets & Sink Fixtures / Nickel Bathroom Faucets', 'Bathroom Renovation / Fixtures & Fittings / Nickel Finish Bathroom Faucets', 'Plumbing & Fixtures / Bathroom Faucets / Nickel Finish / Modern Design', 'Decor & Accessories / Bathroom Decor / Nickel Accented Fixtures']

Searching:  54%|█████▍    | 258/480 [01:20<01:12,  3.08it/s]

Home Improvement
keywords='king size bed' hallucinated_classification=['Furniture / Bedroom Furniture / King Size Beds / Upholstered King Size Beds', 'Furniture / Bedroom Furniture / King Size Beds / Wooden Frame King Size Beds', 'Furniture / Bedroom Furniture / King Size Beds / Storage King Size Beds', 'Furniture / Bedroom Furniture / King Size Beds / Canopy King Size Beds', 'Furniture / Bedroom Furniture / King Size Beds / Modern King Size Beds', 'Furniture / Bedroom Furniture / King Size Beds / Vintage King Size Beds']
Furniture

Searching:  54%|█████▍    | 259/480 [01:21<01:32,  2.39it/s]

keywords='sugar canister' hallucinated_classification=['Kitchen & Tabletop / Food Storage & Canisters / Sugar Canisters', 'Kitchen & Tabletop / Kitchen Storage & Organization / Canisters & Jars', 'Home Decor / Kitchen Themed Decor / Kitchen Canister Sets', 'Kitchen & Dining / Kitchen Accessories / Spice & Canister Sets', 'Home & Living / Kitchen & Dining / Food Storage Containers']

Searching:  54%|█████▍    | 260/480 [01:21<01:26,  2.53it/s]

Décor & Pillows
Storage & Organization
Kitchen & Tabletop
keywords='ines shag rug w003096809' hallucinated_classification=['Home Decor / Rugs & Carpets / Shag Rugs', 'Furniture / Area Rugs / Shag Rugs', 'Decor & Textiles / Floor Coverings / Shag Rugs', 'Home Accessories / Floor Decor / Shag Rugs', 'Interior Design / Rugs & Carpets / Shag Rugs']

Searching:  54%|█████▍    | 261/480 [01:22<01:20,  2.71it/s]

Rugs
keywords='multi color rug' hallucinated_classification=['Home Decor / Rugs & Carpets / Area Rugs & Mats / Multi-Color Rugs', 'Furniture / Living Room Furniture / Area Rugs / Colorful Rugs', 'Decor & Pillows / Decorative Rugs / Multi-Color Patterned Rugs', 'Home Improvement / Flooring / Area Rugs / Multi-Color Rugs', 'Kids & Teens / Kids Room Decor / Colorful Rugs']

Searching:  55%|█████▍    | 262/480 [01:22<01:18,  2.79it/s]

Baby & Kids
Furniture
Rugs
keywords='small woven pouf' hallucinated_classification=['Furniture / Accent Furniture / Poufs & Ottomans', 'Décor & Pillows / Woven & Textured Home Accents', 'Furniture / Living Room Furniture / Footstools & Ottomans', 'Home Decor / Woven & Handcrafted Decor', 'Outdoor / Patio & Garden Furniture / Woven Poufs']

Searching:  55%|█████▍    | 263/480 [01:22<01:13,  2.96it/s]

Outdoor
Furniture
Décor & Pillows
keywords='front door cabinet with doors' hallucinated_classification=['Home Improvement / Entryway & Mudroom Storage / Front Door Cabinets', 'Furniture / Entryway Furniture / Hall Trees & Coat Racks with Storage', 'Home Organization / Wall-mounted Storage / Entryway Wall Cabinets', 'Decor & Accessories / Welcome Mats & Door Decor / Front Door Decor', 'Building Materials / Custom Cabinetry / Front Door Cabinet Doors']

Searching:  55%|█████▌    | 264/480 [01:22<01:12,  2.97it/s]

Home Improvement
Furniture
Décor & Pillows
Storage & Organization
keywords='navy and peach bedding' hallucinated_classification=['Home Textiles / Bedding / Bed Sheets and Sets', 'Home Decor / Bedding Accessories / Decorative Pillows and Throws', 'Bedroom Furniture / Bed Frames and Headboards / Upholstered Beds', 'Kids & Baby / Kids Bedding / Themed Bedding Sets', 'Luxury Home Goods / Designer Bedding / Custom Bedding Collections']

Searching:  55%|█████▌    | 265/480 [01:23<01:13,  2.92it/s]

Baby & Kids
Décor & Pillows
Bed Accessories
Bed & Bath
Furniture
keywords='wood floor protector mat' hallucinated_classification=['Home Improvement / Flooring & Tile / Floor Protection Mats', 'Furniture / Floor Coverings / Protective Mats', 'Cleaning & Organization / Floor Care / Floor Protectors', 'Interior Design / Room Accessories / Floor Safety Accessories', 'Eco-Friendly Home / Sustainable Materials / Recycled Floor Mats']

Searching:  55%|█████▌    | 266/480 [01:23<01:13,  2.91it/s]

Home Improvement
Furniture
Rugs
Storage & Organization
keywords='self enclosed planters' hallucinated_classification=['Garden & Outdoor / Planters & Garden Containers / Self Enclosed Planters', 'Home & Garden / Indoor Gardening / Self Contained Planter Systems', 'Furniture / Indoor Plant Stands & Planters / Self Enclosed Planters', 'Decor & Home Accents / Plant Holders & Containers / Self Enclosed Planters', 'Outdoor / Patio & Garden / Self Enclosed Planters']

Searching:  56%|█████▌    | 267/480 [01:24<01:18,  2.71it/s]

Outdoor
Furniture
Décor & Pillows
keywords='shoe bench entryway' hallucinated_classification=['Furniture / Entryway Furniture / Shoe Benches and Storage', 'Furniture / Mudroom & Entryway Furniture / Shoe Storage Solutions', 'Home Organization / Entryway & Mudroom Storage / Shoe Racks and Benches', 'Furniture / Multi-Functional Furniture / Entryway Seating with Storage', 'Decor & Accessories / Entryway Decor / Shoe Storage Decor']

Searching:  56%|█████▌    | 268/480 [01:24<01:25,  2.48it/s]

Furniture
Décor & Pillows
Storage & Organization
keywords='boho bed frame' hallucinated_classification=['Furniture / Bedroom Furniture / Boho Style Bed Frames', 'Furniture / Bedroom Furniture / Canopy & Canopy Bed Frames', 'Furniture / Bedroom Furniture / Upholstered Bed Frames', 'Furniture / Bedroom Furniture / Vintage & Retro Bed Frames', 'Furniture / Bedroom Furniture / Rattan & Wicker Bed Frames', 'Furniture / Bedroom Furniture / Minimalist Bed Frames', 'Furniture / Bedroom Furniture / Artistic & Sculptural Bed Frames']

Searching:  56%|█████▌    | 269/480 [01:24<01:20,  2.61it/s]

Furniture
Décor & Pillows
keywords='end table between recliners' hallucinated_classification=['Furniture / Living Room Furniture / End Tables / Sofa Side Tables', 'Furniture / Living Room Furniture / Coffee Tables & End Tables / End Tables', 'Furniture / Lounge & Recliner Furniture / Recliner Accessories / End Tables for Recliners', 'Home Decor / Accent Tables / Small Side Tables', 'Furniture / Custom Furniture / Modular End Tables / Recliner Companion Tables']

Searching:  56%|█████▋    | 270/480 [01:25<01:12,  2.90it/s]

Furniture
keywords='owl' hallucinated_classification=['Decor & Pillows / Themed Decor / Animal Themed Decor / Owl Decorations', 'Kids & Baby Furniture / Nursery Decor / Owl Wall Art', 'Outdoor / Garden Statues & Ornaments / Owl Garden Decor', 'Lighting / Themed Lamps / Owl Table Lamps', 'Home Accessories / Clocks & Wall Art / Owl Clocks & Art', 'Crafts & DIY Supplies / Home Decor Crafts / Owl Craft Kits']

Searching:  56%|█████▋    | 271/480 [01:25<01:11,  2.94it/s]

Lighting
Baby & Kids
Outdoor
Décor & Pillows
keywords='teal chair' hallucinated_classification=['Furniture / Accent Chairs / Teal Upholstered Chairs', 'Furniture / Office Chairs / Teal Desk Chairs', 'Furniture / Lounge Chairs / Teal Armchairs', 'Furniture / Dining Chairs / Teal Kitchen & Dining Chairs', 'Furniture / Kids & Teens Furniture / Teal Kids Chairs', 'Decor & Pillows / Color-specific Decor / Teal Home Accents', 'Home Improvement / Custom Furniture / Teal Painted Furniture']

Searching:  57%|█████▋    | 272/480 [01:26<01:24,  2.45it/s]

Baby & Kids
Furniture
Décor & Pillows
keywords='wisdom stone river 3-3/4' hallucinated_classification=['Home Decor / Decorative Stones & Sculptures / River Stone Accents', 'Garden & Outdoor / Water Features / River Stone Landscaping', 'Spiritual & Wellness / Meditation & Zen Gardens / Wisdom Stones', 'Furniture / Accent Pieces / Natural Stone Decor', 'Interior Design / Wall Art & Sculptures / Stone Wall Art']

Searching:  57%|█████▋    | 273/480 [01:26<01:26,  2.39it/s]

Outdoor
Décor & Pillows
keywords='wainscoting ideas' hallucinated_classification=['Home Improvement / Wall Treatments / Wainscoting & Wall Paneling', 'Interior Design / Wall Decor / Wall Paneling Ideas', 'Furniture / Wall Accents / Decorative Wall Panels', 'DIY & Crafts / Wall Paneling Projects', 'Renovation & Remodeling / Wall Cladding & Paneling']

Searching:  57%|█████▋    | 274/480 [01:26<01:24,  2.44it/s]

Outdoor
Home Improvement
Décor & Pillows
keywords='outdoor clock' hallucinated_classification=['Outdoor / Outdoor Decor / Clocks & Weather Instruments / Outdoor Clocks', 'Garden & Patio / Garden Decor / Garden Ornaments & Statues / Outdoor Clocks', 'Home Improvement / Exterior & Landscape Lighting / Outdoor Clocks & Timers', 'Furniture / Outdoor Furniture / Outdoor Accessories / Outdoor Clocks']

Searching:  57%|█████▋    | 275/480 [01:27<01:19,  2.58it/s]

Décor & Pillows
keywords='grantola wall mirror' hallucinated_classification=['Home Decor / Wall Mirrors / Statement Wall Mirrors', 'Furniture / Entryway Furniture / Wall-mounted Entryway Shelves with Mirror', 'Decor & Pillows / Mirror Art / Artistic Wall Mirrors', 'Home Improvement / Wall Treatments / Decorative Wall Panels with Mirror Accents', 'Furniture / Bathroom Mirrors / Frameless Wall Mirrors']

Searching:  57%|█████▊    | 276/480 [01:27<01:19,  2.56it/s]

Lighting
Décor & Pillows
keywords='cream queen duvet cover' hallucinated_classification=['Bedding & Sleep / Duvet Covers & Comforters / Queen Size Duvet Covers', 'Home Textiles / Bed Linens / Duvet Covers', 'Bedroom Decor / Bedding Accessories / Duvet Covers', 'Luxury Bedding / Designer Duvet Covers / Queen Size', 'Home Organization / Linen Storage / Duvet Cover Storage Solutions']

Searching:  58%|█████▊    | 277/480 [01:27<01:10,  2.87it/s]

Storage & Organization
Bed & Bath
Décor & Pillows
Furniture
keywords='54 in bench cushion' hallucinated_classification=['Furniture / Seating / Bench Cushions and Pads', 'Home Decor / Cushions & Pillows / Bench Cushions', 'Outdoor / Patio Furniture Accessories / Bench Cushions', 'Living Room / Furniture Accessories / Bench Cushions', 'Bedroom / Bed Accessories / Bench Cushions']

Searching:  58%|█████▊    | 278/480 [01:28<01:03,  3.18it/s]

Bed Accessories
Outdoor
Furniture
keywords='family lamp' hallucinated_classification=['Lighting / Family Room Lighting / Family Room Floor Lamps', 'Furniture / Living Room Furniture / Family Room Seating & Tables', 'Décor & Pillows / Family Room Decor / Family Room Wall Art & Accessories', 'Home Improvement / Lighting Fixtures / Floor Lamps for Living Spaces', 'Smart Home / Home Automation / Family Room Smart Lighting']

Searching:  58%|█████▊    | 279/480 [01:28<00:59,  3.35it/s]

Lighting
Furniture
Décor & Pillows
keywords='olive green console table' hallucinated_classification=['Furniture / Entryway & Hallway Furniture / Console Tables', 'Furniture / Living Room Furniture / Accent Tables', 'Home Decor / Color-themed Furniture / Olive Green Furniture', 'Custom Furniture / Color-specific Console Tables', 'Eco-friendly Furniture / Sustainable Console Tables', 'Vintage & Antique Furniture / Console Tables with Unique Finishes']

Searching:  58%|█████▊    | 280/480 [01:28<01:01,  3.27it/s]

Outdoor
Furniture
Décor & Pillows
keywords='hardwood beds' hallucinated_classification=['Furniture / Bedroom Furniture / Hardwood Bed Frames', 'Furniture / Customizable Bed Solutions / Hardwood Bed Designs', 'Furniture / Eco-Friendly Bedroom Furniture / Hardwood Bed Options', 'Furniture / Luxury Bedroom Sets / Hardwood Bed and Matchings', 'Furniture / Vintage & Antique Furniture / Hardwood Bed Frames', 'Furniture / Modern Bedroom Furniture / Hardwood Bed Styles']

Searching:  59%|█████▊    | 281/480 [01:29<01:13,  2.70it/s]

Furniture
Bed & Bath
keywords='french molding' hallucinated_classification=['Home Improvement / Molding & Trim / Decorative Molding / French Molding', 'Interior Design / Wall Treatments / Molding & Trim / French Style Molding', 'Architectural Elements / Wall Accents / French Molding', 'Furniture Accessories / Decorative Trims / French Molding']

Searching:  59%|█████▉    | 282/480 [01:29<01:14,  2.67it/s]

Home Improvement
Décor & Pillows
keywords='trundle daybed' hallucinated_classification=['Furniture / Bedroom Furniture / Daybeds & Trundle Beds', 'Furniture / Multi-Functional Furniture / Convertible & Modular Furniture', 'Furniture / Guest & Extra Beds / Trundle & Underbed Storage Beds', 'Home Decor / Space-Saving Furniture / Compact & Multi-Use Furniture', 'Furniture / Kids & Teen Bedroom Furniture / Trundle Beds for Kids']

Searching:  59%|█████▉    | 283/480 [01:30<01:18,  2.52it/s]

Baby & Kids
Furniture
keywords='pineapple' hallucinated_classification=['Décor & Pillows / Decorative Accents / Themed Ornaments', 'Kitchen & Tabletop / Kitchen Accessories / Fruit-Shaped Kitchenware', 'Outdoor / Garden Decor / Fruit-Themed Garden Statues', 'Furniture / Themed Furniture / Fruit-Inspired Furniture', 'Home Improvement / Wall Decor / Fruit Motif Wall Art', 'Kids & Baby / Kids Room Decor / Fruit-Shaped Wall Hangings']

Searching:  59%|█████▉    | 284/480 [01:30<01:25,  2.29it/s]

Baby & Kids
Décor & Pillows
Outdoor
Kitchen & Tabletop
Furniture
keywords='outdoor lounge cushions' hallucinated_classification=['Outdoor / Outdoor Comfort & Decor / Lounge Cushions & Pillows / Outdoor Lounge Cushions', 'Furniture / Patio & Garden Furniture / Lounge Seating / Outdoor Lounge Cushions', 'Home Decor / Textiles / Cushions & Pillows / Outdoor Lounge Cushions', 'Garden & Patio / Outdoor Furniture Accessories / Cushions & Pillows / Lounge Cushions']

Searching:  59%|█████▉    | 285/480 [01:30<01:14,  2.63it/s]

Outdoor
keywords='circle cabinet pulls' hallucinated_classification=['Hardware / Cabinet Hardware / Cabinet Pulls / Circular Cabinet Pulls', 'Furniture / Kitchen & Bathroom Hardware / Cabinet Handles / Round Cabinet Handles', 'Home Improvement / Kitchen & Bath / Cabinet Accessories / Circular Pulls', 'Decor & Home Accessories / Drawer Pulls / Round Drawer Handles', 'Furniture / Custom Furniture Components / Circular Handles']

Searching:  60%|█████▉    | 286/480 [01:31<01:06,  2.91it/s]

Home Improvement
Furniture
keywords='huntsville sectional sofa' hallucinated_classification=['Furniture / Living Room Furniture / Sectional Sofas & Couches', 'Furniture / Custom & Modular Sofas', 'Home Decor / Upholstered Furniture', 'Furniture / Modern & Contemporary Sofas', 'Furniture / Sectional Sofas with Storage']

Searching:  60%|█████▉    | 287/480 [01:31<01:00,  3.19it/s]

Furniture
Décor & Pillows
keywords='hub leaning full length mirror' hallucinated_classification=['Furniture / Mirrors / Full Length Mirrors / Leaning Full Length Mirrors', 'Home Decor / Wall Mirrors / Floor Standing Mirrors', 'Furniture / Bedroom Furniture / Full Length Mirrors', 'Decor & Accessories / Mirror Frames / Leaning Mirrors', 'Home Improvement / Entryway & Hallway Furniture / Full Length Mirrors']

Searching:  60%|██████    | 288/480 [01:31<00:58,  3.31it/s]

Home Improvement
Décor & Pillows
keywords='glow in the dark silent wall clock' hallucinated_classification=['Home Decor / Clocks / Wall Clocks / Glow in the Dark Wall Clocks', 'Lighting / Night Lights / Silent Wall Clocks with Glow Features', 'Furniture / Living Room Furniture / Wall Decor / Illuminated Wall Clocks', 'Smart Home / Home Automation / Silent and Glow-in-the-Dark Clocks', 'Kids & Teens / Bedroom Decor / Glow in the Dark Wall Clocks']

Searching:  60%|██████    | 289/480 [01:32<01:03,  3.00it/s]

Baby & Kids
Lighting
Décor & Pillows
keywords='amarillo' hallucinated_classification=['Decor / Wall Art / Abstract Paintings in Yellow Tones', 'Furniture / Accent Pieces / Yellow Accent Chairs', 'Lighting / Table Lamps / Yellow Ceramic Table Lamps', 'Home Decor / Vases & Planters / Yellow Ceramic Vases', 'Bedding / Comforters & Duvets / Yellow Patterned Comforters', 'Kitchen & Dining / Tableware / Yellow Ceramic Dinnerware', 'Outdoor / Garden Decor / Yellow Garden Statues']

Searching:  60%|██████    | 290/480 [01:32<01:15,  2.52it/s]

Baby & Kids
Décor & Pillows
Outdoor
Kitchen & Tabletop
Furniture
Lighting
keywords='cloud modular sectional' hallucinated_classification=['Furniture / Modular Sofas & Sectionals / Cloud-Inspired Modular Sofas', 'Home Decor / Themed Seating / Cloud-Shaped Sofas', 'Living Room Furniture / Contemporary Sectionals / Fluffy Cloud Design', 'Furniture / Customizable Sectional Systems / Cloud Modular Units', 'Interior Design / Themed Furniture / Cloud Motif Sofas']

Searching:  61%|██████    | 291/480 [01:33<01:17,  2.45it/s]

Furniture
keywords='urban outfitters duvet' hallucinated_classification=['Bedding & Sleep Accessories / Duvets & Comforters / Urban Style Duvets', 'Home Textiles / Bedding / Urban-Inspired Duvets', 'Bedroom Decor / Bedding / Trendy Duvets for Modern Bedrooms', 'Linen & Bedding / Duvets / Urban Chic Duvets', 'Home & Living / Bedroom Essentials / Stylish Duvets']

Searching:  61%|██████    | 292/480 [01:33<01:20,  2.32it/s]

Bed & Bath
Décor & Pillows
keywords='kitchen storage shelves' hallucinated_classification=['Home Organization / Kitchen Storage & Racks / Adjustable Kitchen Shelving', 'Furniture / Kitchen & Dining Room Furniture / Kitchen Shelves & Racks', 'Home Improvement / Kitchen Renovation & Accessories / Wall-Mounted Shelves for Kitchen', 'Decor & Accessories / Kitchen Decor / Open Shelving Units', 'Storage Solutions / Modular Storage / Kitchen Shelf Systems', 'Eco-Friendly / Recycled Material Furniture / Sustainable Kitchen Shelves']

Searching:  61%|██████    | 293/480 [01:33<01:23,  2.23it/s]

Home Improvement
Storage & Organization
Kitchen & Tabletop
Furniture
keywords='black fluffy stool' hallucinated_classification=['Furniture / Accent Furniture / Unique & Artistic Stools', 'Home Decor / Textured & Plush Furniture / Fluffy Seating', 'Furniture / Kids & Teen Furniture / Playful & Themed Stools', 'Outdoor / Garden & Patio Furniture / Plush Garden Stools', 'Furniture / Modern & Contemporary Furniture / Statement Pieces']

Searching:  61%|██████▏   | 294/480 [01:34<01:15,  2.47it/s]

Baby & Kids
Outdoor
Furniture
Décor & Pillows
keywords='ceramic tile sea shell' hallucinated_classification=['Home Decor / Wall Art & Murals / Ceramic Tile Art with Sea Shell Motifs', 'Kitchen & Tabletop / Backsplashes & Wall Tiles / Sea Shell Pattern Ceramic Tiles', 'Bathroom / Shower Walls & Surrounds / Sea Shell Design Ceramic Tiles', 'Outdoor / Garden & Patio Decor / Sea Shell Inspired Ceramic Tiles', 'Interior Design / Themed Room Decor / Nautical & Marine Theme Accessories']

Searching:  61%|██████▏   | 295/480 [01:34<01:11,  2.58it/s]

Home Improvement
Décor & Pillows
keywords='bathroom freestanding cabinet' hallucinated_classification=['Furniture / Bathroom Furniture / Freestanding Cabinets and Storage']
Furniture
keywords='3 piece rug set with runners' hallucinated_classification=['Home Textiles / Rugs & Carpets / Area Rugs & Runners', 'Home Decor / Floor Coverings / Rug Sets', 'Interior Design / Floor Accessories / Rug Collections', 'Home Improvement / Flooring / Carpet & Rug Sets', 'Decor & Pillows / Decorative Rugs / Runner Rugs']

Searching:  62%|██████▏   | 297/480 [01:35<00:53,  3.40it/s]

Rugs
keywords='peacock' hallucinated_classification=['Décor & Pillows / Decorative Pillows & Blankets / Peacock-themed Pillows', 'Home Decor / Wall Art & Murals / Peacock Wall Art', 'Furniture / Accent Furniture / Peacock-inspired Chairs & Stools', 'Outdoor / Garden & Patio Decor / Peacock Garden Statues & Ornaments', 'Lighting / Decorative Lamps & Lanterns / Peacock Table Lamps', 'Kids & Baby Furniture / Nursery Decor / Peacock-themed Nursery Accessories']

Searching:  62%|██████▏   | 298/480 [01:35<00:55,  3.26it/s]

Baby & Kids
Décor & Pillows
Outdoor
Furniture
Lighting
keywords='zodiac pillow' hallucinated_classification=['Décor & Pillows / Decorative Pillows & Blankets / Zodiac-Themed Pillows', 'Home Decor / Themed Cushions / Celestial & Zodiac Pillows', 'Furniture / Bedroom Decor / Zodiac Patterned Pillows', 'Kids & Teens Room Decor / Zodiac Theme Pillows', 'Gift & Novelty Items / Zodiac Constellation Cushions']

Searching:  62%|██████▏   | 299/480 [01:35<00:55,  3.26it/s]

Décor & Pillows
keywords='canvas map art' hallucinated_classification=['Decor & Wall Art / Canvas & Framed Prints / Map Art Canvas Prints', 'Home Decor / Wall Hangings / Artistic Canvas Maps', 'Living Room Decor / Wall Art / City & World Map Murals', 'Office & Study Decor / Wall Art / Educational & Inspirational Maps', 'Kids & Teens Room Decor / Wall Art / Adventure & Travel Map Posters']

Searching:  62%|██████▎   | 300/480 [01:36<00:56,  3.17it/s]

Baby & Kids
Décor & Pillows
keywords='bee' hallucinated_classification=['Home Decor / Nature-Inspired Decor / Bee Motif Wall Art', 'Furniture / Themed Furniture / Bee Design Accent Chairs', 'Outdoor / Garden Decor / Bee Garden Statues', 'Lighting / Themed Lighting / Bee-Shaped Lamps', 'Kids & Baby Furniture / Bee Theme Nursery Decor', 'Kitchen & Dining / Bee Pattern Tableware / Bee Print Plates and Mugs', 'Clothing & Accessories / Bee Motif Home Textiles / Bee Pattern Curtains and Rugs']

Searching:  63%|██████▎   | 301/480 [01:37<01:36,  1.85it/s]

Baby & Kids
Décor & Pillows
Outdoor
Kitchen & Tabletop
Furniture
Lighting
keywords='gray leather cocktail table' hallucinated_classification=['Furniture / Living Room Furniture / Cocktail Tables', 'Furniture / Accent Tables / Leather Top Tables', 'Home Decor / Statement Pieces / Leather Furniture Accents', 'Interior Design / Modern Furniture / Leather Cocktail Tables', 'Luxury Furniture / Leather Finish Tables']

Searching:  63%|██████▎   | 302/480 [01:37<01:20,  2.22it/s]

Furniture
Décor & Pillows
keywords='kari 2 piece' hallucinated_classification=['Furniture / Living Room Furniture / Sectional Sofas & Modular Seating', 'Furniture / Bedroom Furniture / 2-Piece Bedroom Sets', 'Home Decor / Wall Art & Decor Sets / Coordinated Wall Art Sets', 'Outdoor / Patio Furniture / 2-Piece Bistro Sets', 'Home Organization / Storage & Shelving / Modular Storage Units', 'Furniture / Office Furniture / 2-Piece Office Desk & Chair Sets']

Searching:  63%|██████▎   | 303/480 [01:37<01:12,  2.46it/s]

Outdoor
Furniture
Décor & Pillows
Storage & Organization
keywords='wine bar' hallucinated_classification=['Furniture / Bar & Lounge Furniture / Wine Bar Cabinets and Stations', 'Home Decor / Wine & Beverage Storage / Wine Racks and Cabinets', 'Kitchen & Dining / Bar Furniture / Wine Bar Carts and Islands', 'Event & Party Supplies / Bar Accessories / Wine Bar Sets', 'Outdoor / Outdoor Bar Furniture / Wine Bar Tables and Stools']

Searching:  63%|██████▎   | 304/480 [01:37<01:06,  2.65it/s]

Kitchen & Tabletop
Outdoor
Furniture
Décor & Pillows
keywords='coma inducer comforter king set' hallucinated_classification=['Home Textiles / Bedding / Comforter Sets / King Size Comforter Sets', 'Bedroom Accessories / Sleep Aids / Sleep-Inducing Comforters', 'Luxury Bedding / Specialty Comforters / Therapeutic Comforters', 'Sleep & Relaxation / Sleep Enhancers / Comforting Bedding Accessories', 'Home Decor / Themed Bedding / Relaxation-Inspired Comforter Sets']

Searching:  64%|██████▎   | 305/480 [01:38<01:07,  2.58it/s]

Bed Accessories
Baby & Kids
Bed & Bath
Décor & Pillows
keywords='wood rack wide' hallucinated_classification=['Furniture / Storage & Organization / Wall-Mounted Shelves & Racks', 'Furniture / Living Room Furniture / Bookcases & Shelving Units', 'Home Decor / Rustic & Vintage Decor / Wooden Wall Racks', 'Outdoor / Garden & Patio Storage / Wooden Garden Shelves', 'Home Improvement / Garage & Workshop Storage / Wooden Tool Racks']

Searching:  64%|██████▍   | 306/480 [01:38<01:08,  2.53it/s]

Storage & Organization
Décor & Pillows
Furniture
keywords='front porch furniture sets' hallucinated_classification=['Outdoor / Outdoor & Patio Furniture / Porch & Entryway Furniture / Porch Furniture Sets', 'Outdoor / Outdoor & Patio Furniture / Porch & Entryway Furniture / Porch Swing Sets', 'Outdoor / Outdoor & Patio Furniture / Porch & Entryway Furniture / Porch Bench Sets', 'Outdoor / Outdoor & Patio Furniture / Porch & Entryway Furniture / Porch Lounge Sets', 'Outdoor / Outdoor & Patio Furniture / Porch & Entryway Furniture / Porch Dining Sets']

Searching:  64%|██████▍   | 307/480 [01:39<01:04,  2.70it/s]

Outdoor
keywords='fortunat coffee table' hallucinated_classification=['Furniture / Coffee Tables / Artistic & Unique Coffee Tables', 'Home Decor / Statement Pieces / Artistic Coffee Tables', 'Living Room Furniture / Modern Coffee Tables / Custom Design Coffee Tables', 'Furniture / Eco-Friendly & Sustainable Furniture / Reclaimed Wood Coffee Tables', 'Interior Design / Custom Furniture / Bespoke Coffee Tables']

Searching:  64%|██████▍   | 308/480 [01:39<00:57,  2.98it/s]

Furniture
keywords='landis wall mounted bathroom shelves' hallucinated_classification=['Home Improvement / Bathroom Fixtures / Wall Mounted Shelves / Bathroom Shelves', 'Furniture / Bathroom Furniture / Wall Mounted Storage / Bathroom Shelves', 'Décor & Pillows / Wall Decor / Wall Mounted Shelves / Bathroom Shelves', 'Organization & Storage / Bathroom Storage / Wall Mounted Shelves / Bathroom']

Searching:  64%|██████▍   | 309/480 [01:39<00:50,  3.37it/s]

Home Improvement
Storage & Organization
Décor & Pillows
keywords='outdoor light fixtures' hallucinated_classification=['Outdoor / Outdoor Lighting / String Lights & Fairy Lights', 'Outdoor / Solar & LED Lights / Pathway & Spot Lights', 'Outdoor / Wall-Mounted Lights / Exterior Wall Sconces', 'Outdoor / Post & Pole Lights / Garden & Yard Lights', 'Outdoor / Decorative Lanterns & Torches / Tiki Torches', 'Outdoor / String & Festoon Lights / Patio & Garden Decor']

Searching:  65%|██████▍   | 310/480 [01:39<00:50,  3.37it/s]

Lighting
Holiday Décor
keywords='12v dirt bike' hallucinated_classification=['Outdoor / Motorized Vehicles / Electric Bikes and Scooters / Electric Dirt Bikes', 'Toys & Games / Ride-On Toys / Electric Ride-On Vehicles', 'Sports & Recreation / Off-Road Vehicles / Electric Off-Road Bikes', 'Automotive / Electric Vehicle Accessories / Battery Chargers for Electric Vehicles', 'Electronics / Power Supplies / 12V Power Supplies for Vehicles']

Searching:  65%|██████▍   | 311/480 [01:40<00:47,  3.53it/s]

Lighting
Outdoor
Appliances
keywords='chrome shower head and valve' hallucinated_classification=['Home Improvement / Bathroom Fixtures / Shower Heads and Valves / Chrome Shower Heads and Valves', 'Bathroom Accessories / Shower Systems / Chrome Shower Head and Valve Sets', 'Plumbing / Shower Fixtures / Chrome Shower Heads and Valves', 'Luxury Bathroom Hardware / Shower Components / Chrome Shower Head and Valve']

Searching:  65%|██████▌   | 312/480 [01:40<00:43,  3.89it/s]

Home Improvement
keywords='tall buffet cabinet' hallucinated_classification=['Furniture / Kitchen & Dining Furniture / Buffet Cabinets and Sideboards', 'Furniture / Living Room Furniture / Display Cabinets and Curio Cabinets', 'Home Storage & Organization / Pantry Cabinets and Storage Units', 'Furniture / Entryway Furniture / Hall Trees and Console Cabinets', 'Furniture / Bedroom Furniture / Wardrobes and Armoires', 'Home Improvement / Custom Cabinetry and Built-ins']

Searching:  65%|██████▌   | 313/480 [01:40<00:44,  3.73it/s]

Home Improvement
Furniture
Storage & Organization
keywords='gnome fairy garden' hallucinated_classification=['Outdoor / Fairy Garden Accessories / Gnome Statues and Figurines', 'Garden Decor / Fairy Garden Decor / Miniature Fairy Houses', 'Outdoor / Fairy Garden Accessories / Gnome Garden Stakes and Ornaments', 'Garden Decor / Enchanted Garden Decor / Mystical Fairy Garden Sets', 'Outdoor / Themed Garden Decor / Fantasy Gnome and Fairy Garden Kits']

Searching:  65%|██████▌   | 314/480 [01:40<00:43,  3.82it/s]

Outdoor
Décor & Pillows
keywords='cover set for outdoor furniture' hallucinated_classification=['Outdoor / Outdoor & Patio Furniture / Furniture Covers / Patio Furniture Covers', 'Outdoor / Outdoor & Patio Furniture / Cover Sets / Outdoor Furniture Cover Sets', 'Garden & Patio / Patio Accessories / Furniture Protectors / Outdoor Furniture Covers', 'Home & Garden / Patio & Garden Furniture / Cover Sets for Outdoor Furniture']

Searching:  66%|██████▌   | 315/480 [01:41<00:40,  4.04it/s]

Outdoor
Storage & Organization
keywords='3/4 size mattress' hallucinated_classification=['Furniture / Bedroom Furniture / Mattresses / Specialty Size Mattresses', 'Furniture / Kids & Teens Furniture / Toddler & Small Bed Mattresses', 'Home Bedding & Linens / Mattresses / Specialty Size Mattresses', 'Furniture / Guest & Extra Beds / Small Size Mattresses', 'Home Improvement / Bedroom Renovation / Small Mattress Options']

Searching:  66%|██████▌   | 316/480 [01:41<00:40,  4.04it/s]

Baby & Kids
Furniture
Bed & Bath
keywords='clear shower curtain' hallucinated_classification=['Home & Bath / Shower & Bathtub Accessories / Shower Curtains & Liners / Clear Shower Curtains']
Bed & Bath
keywords='bedroom wall decor floral, multicolored with some teal (prints)' hallucinated_classification=['Décor & Wall Art / Wall Hangings & Art / Floral Wall Art', 'Home Decor / Wall Decor / Floral Prints & Posters', 'Bedroom Decor / Wall Art / Colorful Floral Prints', 'Interior Design / Wall Accents / Multicolored Floral Wall Decor', 'Living Space Accessories / Wall Decorations / Teal Floral Art']

Searching:  66%|██████▋   | 318/480 [01:41<00:32,  4.94it/s]

Décor & Pillows
keywords='marble' hallucinated_classification=['Home Decor / Marble Accents & Accessories / Marble Coasters', 'Kitchen & Tabletop / Marble Cookware & Utensils / Marble Mortar & Pestle', 'Furniture / Marble Top Tables / Marble Coffee Tables', 'Bathroom / Marble Vanity Tops / Marble Bathroom Sinks', 'Outdoor / Marble Garden Statues & Ornaments / Marble Garden Decor', 'Lighting / Marble Lamp Bases / Marble Table Lamps', 'Decor & Pillows / Marble Decorative Items / Marble Sculptures']

Searching:  66%|██████▋   | 319/480 [01:41<00:37,  4.28it/s]

Décor & Pillows
Outdoor
Kitchen & Tabletop
Furniture
Lighting
keywords='large spoon and fork wall decor' hallucinated_classification=['Decor & Wall Art / Wall Hangings & Art / Themed Wall Decor', 'Home Accessories / Kitchen & Dining Decor / Utensil Wall Art', 'Furniture / Wall Decor / Novelty Wall Hangings', 'Gift & Specialty Items / Kitchen Gifts / Utensil Themed Decor', 'Outdoor / Garden & Patio Decor / Themed Wall Art']

Searching:  67%|██████▋   | 320/480 [01:42<00:38,  4.17it/s]

Outdoor
Décor & Pillows
keywords='enclosed shoe rack' hallucinated_classification=['Furniture / Storage & Organization / Shoe Storage / Enclosed Shoe Racks', 'Home Organization / Closet Systems / Shoe Cabinets', 'Furniture / Entryway Furniture / Shoe Storage Benches', 'Decor & Accessories / Entryway Decor / Shoe Racks & Holders', 'Furniture / Kids & Teen Furniture / Kids Shoe Storage']

Searching:  67%|██████▋   | 321/480 [01:42<00:38,  4.18it/s]

Storage & Organization
Décor & Pillows
Furniture
keywords='rooster decor' hallucinated_classification=['Décor & Pillows / Decorative Figurines & Statues / Rooster Decor', 'Home Accents / Wall Art & Hangings / Rooster Wall Decor', 'Garden & Outdoor / Garden Statues & Ornaments / Rooster Garden Decor', 'Kitchen & Dining / Kitchen Accessories / Rooster Kitchen Decor', 'Furniture / Entryway Furniture / Coat Racks & Hooks with Rooster Motifs', 'Holiday & Seasonal Decor / Spring & Easter Decor / Rooster Themed Decorations']

Searching:  67%|██████▋   | 322/480 [01:42<00:40,  3.93it/s]

Holiday Décor
Outdoor
Furniture
Décor & Pillows
keywords='nectar queen mattress' hallucinated_classification=['Furniture / Bedroom Furniture / Mattresses and Bed Frames / Queen Size Mattresses', 'Sleep & Bedding / Mattresses / Memory Foam Mattresses', 'Home Goods / Sleep Accessories / Mattress Protectors and Pads', 'Furniture / Bedroom Furniture / Bed Sets / Queen Bed Sets', 'Home Improvement / Bedroom Renovation / Mattress Buying Guides']

Searching:  67%|██████▋   | 323/480 [01:42<00:41,  3.81it/s]

Furniture
Bed & Bath
keywords='kitchen wooden stand' hallucinated_classification=['Furniture / Kitchen Furniture / Kitchen Stands & Racks', 'Home Organization / Kitchen Storage & Shelving / Wooden Kitchen Stands', 'Kitchen & Tabletop / Kitchen Accessories / Wooden Kitchen Accessories', 'Furniture / Multi-purpose Furniture / Wooden Stands and Holders', 'Decor & Home Accents / Wooden Decor / Wooden Kitchen Decor']

Searching:  68%|██████▊   | 324/480 [01:43<00:49,  3.17it/s]

Décor & Pillows
Furniture
Kitchen & Tabletop
Storage & Organization
keywords='cushion replacement insert' hallucinated_classification=['Home Textiles / Cushion Inserts & Pads / Replacement Cushions', 'Furniture Accessories / Cushion Covers & Inserts / Replacement Cushions', 'Living Room Accessories / Sofa & Chair Cushions / Replacement Inserts', 'Decor & Home Decor / Cushion Pads / Custom Cushion Inserts', 'Furniture Repair & Parts / Cushion Replacement / Sofa and Chair Cushions']

Searching:  68%|██████▊   | 325/480 [01:43<00:52,  2.96it/s]

Outdoor
Furniture
Décor & Pillows
keywords='48 inch bathroom vanity with trough sink' hallucinated_classification=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / Modern Trough Sink Vanities', 'Furniture / Bathroom Furniture / Bathroom Vanities with Integrated Sinks', 'Home Decor / Bathroom Accessories / Trough Sinks', 'Kitchen & Bath / Bathroom Fixtures / Trough Sinks', 'Interior Design / Bathroom Design Elements / Contemporary Bathroom Vanities']

Searching:  68%|██████▊   | 326/480 [01:44<00:51,  3.01it/s]

Home Improvement
Furniture
Décor & Pillows
keywords='white splashproof shiplap wallpaper' hallucinated_classification=['Home Decor / Wall Coverings / Wallpaper / Waterproof Wallpaper', 'Interior Design / Wall Treatments / Shiplap Wall Panels / Waterproof Shiplap', 'Renovation & Remodeling / Wall Finishes / Splashproof Wall Coverings', 'DIY & Home Improvement / Wall Decor / Water-Resistant Wallpaper']

Searching:  68%|██████▊   | 327/480 [01:44<00:45,  3.33it/s]

Outdoor
Home Improvement
Décor & Pillows
keywords='entertainment stand end table' hallucinated_classification=['Furniture / Living Room Furniture / Entertainment & Media Consoles', 'Furniture / Living Room Furniture / End Tables & Side Tables', 'Furniture / Multi-Functional Furniture / Storage & Display Units', 'Home Decor / Accent Furniture / Small Tables & Stands', 'Furniture / Custom & Modular Furniture / Modular End Tables']

Searching:  68%|██████▊   | 328/480 [01:44<00:43,  3.48it/s]

Furniture
keywords='kohen 5 drawer dresser' hallucinated_classification=['Furniture / Bedroom Furniture / Dressers & Chests / Five-Drawer Dressers', 'Furniture / Storage & Organization / Wardrobes & Armoires / Multi-Drawer Storage Units', 'Furniture / Kids & Teens Furniture / Dressers & Chests / Five-Drawer Dressers', 'Home Decor / Vintage & Retro Furniture / Mid-Century Dressers', 'Furniture / Custom & Modular Furniture / Modular Storage Solutions']

Searching:  69%|██████▊   | 329/480 [01:44<00:41,  3.65it/s]

Furniture
keywords='pull out sleeper loveseat' hallucinated_classification=['Furniture / Convertible & Multi-Function Furniture / Sleeper Sofas & Loveseats / Pull-Out Loveseats', 'Furniture / Living Room Furniture / Sofas & Couches / Sleeper Sofas', 'Furniture / Space-Saving Furniture / Murphy & Wall Beds / Pull-Out Sofers', 'Home Decor / Multi-Functional Furniture / Sofa Beds & Futons / Pull-Out Loveseats', 'Furniture / Custom & Modular Furniture / Modular Sofas / Pull-Out Loveseats']

Searching:  69%|██████▉   | 330/480 [01:45<00:41,  3.59it/s]

Furniture
keywords='burruss patio sectional with cushions' hallucinated_classification=['Outdoor / Outdoor & Patio Furniture / Patio Sectionals & Sofas', 'Furniture / Patio & Garden Furniture / Sectional Sofas', 'Outdoor / Patio Accessories / Cushions & Pillows for Outdoor Furniture', 'Furniture / Outdoor Furniture Accessories / Patio Cushion Covers']

Searching:  69%|██████▉   | 331/480 [01:45<00:38,  3.88it/s]

Outdoor
keywords='milk cow chair' hallucinated_classification=['Furniture / Novelty & Themed Furniture / Animal-Shaped Chairs', "Children's Furniture / Animal-Themed Chairs / Cow-Shaped Kids Chairs", 'Decor & Home Accents / Animal Figurines / Cow Decor', 'Furniture / Living Room Furniture / Conversation Chairs / Themed Animal Chairs', 'Home Decor / Whimsical & Artistic Furniture / Animal Sculptural Chairs']

Searching:  69%|██████▉   | 332/480 [01:45<00:38,  3.85it/s]

School Furniture and Supplies
Furniture
Décor & Pillows
keywords='promo codes or discounts' hallucinated_classification=['Promotional Offers / Discount Codes & Coupons', 'Furniture & Home Goods / Special Deals & Savings', 'Electronics & Appliances / Discounted Items & Promotions', 'Fashion & Apparel / Sale & Clearance', 'Beauty & Personal Care / Discounted Products', 'Sports & Outdoors / Promotional Discounts', 'Toys & Games / Special Offers']

Searching:  69%|██████▉   | 333/480 [01:45<00:40,  3.65it/s]

Décor & Pillows
Appliances
Outdoor
Bed & Bath
Furniture
Storage & Organization
keywords='closet pull out valet rod' hallucinated_classification=['Home Organization / Closet Accessories / Pull-Out Closet Rods', 'Furniture / Closet Systems / Custom Closet Components', 'Home Improvement / Closet Installation / Closet Hardware & Accessories', 'Storage & Organization / Closet Storage Solutions / Pull-Out Rods', 'Furniture / Bedroom Furniture / Closet Accessories']

Searching:  70%|██████▉   | 334/480 [01:46<00:47,  3.06it/s]

Home Improvement
Storage & Organization
Furniture
keywords='gravity feeder' hallucinated_classification=['Pet Supplies / Pet Feeding & Watering / Automatic Pet Feeders', 'Garden & Outdoor / Garden Decor / Bird Feeders & Bird Houses', 'Home & Living / Home Organization / Pet Food Storage Solutions', 'Smart Home / Home Automation / Automated Pet Care Devices', 'Farm & Ranch / Livestock Equipment / Animal Feeders']

Searching:  70%|██████▉   | 335/480 [01:46<00:54,  2.65it/s]

Kitchen & Tabletop
Pet
Décor & Pillows
keywords='door pulls bronze matte 4 inch' hallucinated_classification=['Home Improvement / Door Hardware / Door Pulls & Handles / Bronze Matte Door Pulls', 'Furniture / Cabinet Hardware / Drawer Pulls / 4 Inch Bronze Matte Pulls', 'Decor & Accessories / Wall Mounts / Decorative Door Handles / Bronze Finish', 'Architectural Hardware / Entryway Accessories / Door Handles / Matte Bronze Finish']

Searching:  70%|███████   | 336/480 [01:47<00:57,  2.48it/s]

Home Improvement
Décor & Pillows
keywords='hitchcock mid-century wall shelf' hallucinated_classification=['Furniture / Wall Shelves / Mid-Century Modern Wall Shelves', 'Decor / Wall Art & Decor / Artistic Wall Installations', 'Home Organization / Wall-Mounted Storage / Floating Shelves', 'Furniture / Entryway Furniture / Wall-Mounted Entry Shelves', 'Interior Design / Accent Pieces / Vintage-Inspired Wall Decor']

Searching:  70%|███████   | 337/480 [01:47<01:02,  2.28it/s]

Storage & Organization
Décor & Pillows
keywords='breakfast bar table' hallucinated_classification=['Furniture / Kitchen & Dining Furniture / Breakfast Bars & Islands', 'Furniture / Kitchen & Dining Furniture / Bar Stools & Counter Stools', 'Home Improvement / Kitchen Remodel & Fixtures / Kitchen Islands & Carts', 'Furniture / Home Office & Dining Room Furniture / Bar & Counter Tables', 'Outdoor / Outdoor & Patio Furniture / Outdoor Kitchen & Bar Furniture']

Searching:  70%|███████   | 338/480 [01:48<00:59,  2.40it/s]

Outdoor
Home Improvement
Furniture
keywords='large cushion outdoor chair' hallucinated_classification=['Outdoor / Outdoor Seating / Lounge Chairs & Recliners / Cushioned Lounge Chairs', 'Furniture / Patio & Garden Furniture / Outdoor Chairs / Cushioned Outdoor Chairs', 'Garden & Outdoor Decor / Outdoor Furniture Accessories / Cushioned Seat Pads', 'Outdoor / Outdoor Furniture / Sectional & Modular Outdoor Seating / Cushioned Outdoor Sections', 'Home & Garden / Outdoor Living / Outdoor Furniture Sets / Cushioned Outdoor Seating Sets']

Searching:  71%|███████   | 339/480 [01:48<00:55,  2.56it/s]

Outdoor
keywords='chair and a half recliner' hallucinated_classification=['Furniture / Recliners & Lounge Chairs / Recliner Chairs / Power Recliners', 'Furniture / Living Room Furniture / Armchairs & Accent Chairs', 'Furniture / Home Theater & Media Furniture / Recliner Sofas', 'Furniture / Custom & Modular Furniture / Modular Seating Systems', 'Furniture / Upholstered Furniture / Plush Lounge Chairs']

Searching:  71%|███████   | 340/480 [01:48<00:52,  2.69it/s]

Furniture
keywords='retractable side awning' hallucinated_classification=['Outdoor / Outdoor & Patio Accessories / Retractable Awnings & Canopies / Side Awnings', 'Home Improvement / Window Treatments / Retractable Window Awnings / Side Awnings', 'Garden & Patio / Shade Solutions / Retractable Shade Devices / Side Awnings', 'Outdoor Living / Patio Coverings / Retractable Side Coverings']

Searching:  71%|███████   | 341/480 [01:49<00:48,  2.84it/s]

Outdoor
Storage & Organization
Décor & Pillows
keywords='kitchen islands with seating' hallucinated_classification=['Furniture / Kitchen Furniture / Kitchen Islands with Seating', 'Furniture / Kitchen & Dining / Kitchen Islands & Carts / Kitchen Islands with Seating', 'Home & Living / Kitchen & Dining / Kitchen Islands / Seating-Integrated Kitchen Islands', 'Furniture / Multi-Functional Furniture / Kitchen Islands with Built-in Seating', 'Kitchen & Dining / Kitchen Storage & Organization / Kitchen Islands with Seating']

Searching:  71%|███████▏  | 342/480 [01:49<00:47,  2.88it/s]

Furniture
keywords='tufted upholstered bed diamond' hallucinated_classification=['Furniture / Bedroom Furniture / Upholstered Beds / Tufted Upholstered Beds with Diamond Pattern', 'Furniture / Customizable Bed Frames / Diamond-Tufted Bed Designs', 'Home Decor / Statement Beds / Diamond Pattern Upholstered Beds', 'Luxury Furniture / Designer Beds / Diamond Tufted Upholstery', 'Sleep & Rest / Premium Beds / Diamond-Tufted Upholstered Bed']

Searching:  71%|███████▏  | 343/480 [01:49<00:44,  3.07it/s]

Furniture
Décor & Pillows
Bed & Bath
keywords='gold' hallucinated_classification=['Decor & Pillows / Decorative Accents / Gold Decorative Items', 'Lighting / Chandeliers & Pendant Lights / Gold Chandeliers', 'Furniture / Accent Furniture / Gold Finish Accent Pieces', 'Home Improvement / Wall Decor / Gold Wall Art & Mirrors', 'Kitchen & Tabletop / Serveware / Gold Plated Serveware', 'Outdoor / Garden Decor / Gold Garden Statues & Ornaments']

Searching:  72%|███████▏  | 344/480 [01:50<00:43,  3.16it/s]

Décor & Pillows
Outdoor
Kitchen & Tabletop
Furniture
Lighting
keywords='twin bed frame' hallucinated_classification=['Furniture / Bedroom Furniture / Bed Frames / Twin Bed Frames', 'Furniture / Kids & Teen Furniture / Kids Bed Frames / Twin Bed Frames', 'Furniture / Custom & Modular Furniture / Modular Bed Frames / Twin Size', 'Furniture / Vintage & Antique Furniture / Vintage Bed Frames / Twin Size', 'Furniture / Eco-Friendly & Sustainable Furniture / Eco Bed Frames / Twin Size']

Searching:  72%|███████▏  | 345/480 [01:50<00:39,  3.41it/s]

Furniture
keywords='music plug wall plate' hallucinated_classification=['Home Improvement / Electrical & Wiring / Wall Plates & Switches / Specialty Wall Plates', 'Decor & Wall Art / Wall Decor / Music-themed Wall Decor / Music Plug Wall Plate', 'Smart Home / Home Automation Devices / Wall-Mounted Control Panels / Music Control Wall Plate', 'Furniture / Entryway Furniture / Wall-Mounted Key & Accessory Holders / Music Plug Wall Plate']

Searching:  72%|███████▏  | 346/480 [01:50<00:37,  3.61it/s]

School Furniture and Supplies
Home Improvement
Décor & Pillows
Appliances
keywords='picasso' hallucinated_classification=['Art-Inspired Home Decor / Wall Art & Canvas Prints / Picasso Artwork', 'Furniture / Artistic & Themed Furniture / Picasso-Design Chairs and Tables', 'Decor & Pillows / Artistic Pillows & Blankets / Picasso Motif Throw Pillows', 'Lighting / Artistic & Themed Lighting / Picasso-Inspired Lamps and Fixtures', 'Home Accessories / Artistic Sculptures & Figurines / Picasso-Style Art Pieces', 'Kids & Teens / Art-Themed Bedroom Decor / Picasso Art Wall Decals']

Searching:  72%|███████▏  | 347/480 [01:50<00:38,  3.45it/s]

Lighting
Furniture
Décor & Pillows
keywords='gracie oaks 62 oller 14 ceiling fan' hallucinated_classification=['Lighting / Ceiling Fans / Modern Ceiling Fans', 'Home Improvement / Ceiling Fan Accessories / Fan Blades & Parts', 'Furniture / Living Room Furniture / Accent Chairs', 'Home Decor / Wall Art / Ceiling Medallions', 'Smart Home / Home Automation / Smart Ceiling Fans']

Searching:  72%|███████▎  | 348/480 [01:51<00:35,  3.68it/s]

Home Improvement
Lighting
Furniture
Décor & Pillows
keywords='zakariyah twin platform' hallucinated_classification=['Furniture / Bedroom Furniture / Twin Bed Frames', 'Furniture / Kids & Teens Furniture / Twin Bed Platforms', 'Home Decor / Bed Accessories / Platform Bed Bases', 'Furniture / Bedroom Furniture / Platform Beds', 'Furniture / Kids & Teens Furniture / Kids Twin Beds']

Searching:  73%|███████▎  | 349/480 [01:51<00:34,  3.84it/s]

Bed Accessories
Baby & Kids
Furniture
keywords='trinaic towel rod' hallucinated_classification=['Home Improvement / Bathroom Fixtures / Towel Racks & Holders / Towel Rods', 'Furniture / Bathroom Furniture / Bathroom Storage / Towel Bars', 'Decor & Accessories / Bathroom Decor / Towel Hooks & Bars', 'Kitchen & Bath / Bathroom Accessories / Towel Bars & Rings', 'Luxury Home Goods / Spa & Wellness Accessories / Towel Racks']

Searching:  73%|███████▎  | 350/480 [01:51<00:33,  3.83it/s]

Home Improvement
Furniture
Décor & Pillows
Bed & Bath
keywords='overstreet rustic pub stools' hallucinated_classification=['Furniture / Bar & Pub Furniture / Pub Stools and Bar Chairs', 'Furniture / Rustic & Vintage Furniture / Rustic Pub Stools', 'Home Decor / Kitchen & Bar Accessories / Bar Stools', 'Outdoor / Patio & Garden Furniture / Outdoor Bar Stools', 'Furniture / Commercial & Hospitality Furniture / Pub & Bar Seating']

Searching:  73%|███████▎  | 351/480 [01:51<00:33,  3.90it/s]

Outdoor
Furniture
keywords='porcelain loaf pan' hallucinated_classification=['Kitchen & Tabletop / Bakeware / Loaf Pans', 'Kitchen & Tabletop / Porcelain Cookware / Porcelain Bakeware', 'Kitchen & Tabletop / Specialty Bakeware / Artisan Loaf Pans', 'Home Baking & Cooking / Baking Accessories / Loaf Pan Sets', 'Kitchen & Tabletop / Food Preparation / Baking Tools & Accessories']

Searching:  73%|███████▎  | 352/480 [01:52<00:32,  3.89it/s]

Kitchen & Tabletop
keywords='dark gray dresser' hallucinated_classification=['Furniture / Bedroom Furniture / Dressers & Chests / Modern Gray Dressers', 'Furniture / Storage & Organization / Wardrobes & Armoires / Gray Wardrobes', 'Furniture / Living Room Furniture / Console Tables / Dark Gray Console Tables', 'Furniture / Entryway Furniture / Shoe Storage / Gray Shoe Cabinets', 'Furniture / Kids & Teens Furniture / Kids Dressers / Gray Kids Dressers']

Searching:  74%|███████▎  | 353/480 [01:52<00:32,  3.89it/s]

Baby & Kids
Furniture
Storage & Organization
keywords='chinese flower stand' hallucinated_classification=['Decorative Garden & Patio / Garden Statues & Ornaments / Chinese Garden Statues', 'Furniture / Accent & Side Tables / Decorative Stands', 'Home Decor / Wall Hangings & Art / Asian-Inspired Wall Art', 'Outdoor / Garden & Patio Decor / Plant Stands & Holders', 'Crafts & DIY / Home Decor Projects / Flower Stand Kits']

Searching:  74%|███████▍  | 354/480 [01:52<00:32,  3.92it/s]

Outdoor
Furniture
Décor & Pillows
keywords='attleboro drum coffee table' hallucinated_classification=['Furniture / Coffee Tables / Drum-Shaped Coffee Tables', 'Furniture / Living Room Furniture / Unique & Artistic Coffee Tables', 'Home Decor / Statement Pieces / Drum Design Coffee Tables', 'Furniture / Custom & Artistic Furniture / Handcrafted Drum Coffee Tables', 'Interior Design / Themed Furniture / Musical Instrument-Inspired Coffee Tables']

Searching:  74%|███████▍  | 355/480 [01:52<00:31,  3.96it/s]

Furniture
keywords='ge top loading washer 4.5' hallucinated_classification=['Home Appliances / Laundry Appliances / Top Loading Washers']
Appliances
keywords='shoe closet' hallucinated_classification=['Furniture / Bedroom Furniture / Shoe Storage & Organizers', 'Furniture / Entryway Furniture / Shoe Cabinets & Racks', 'Home Organization / Closet Systems / Shoe Shelves', 'Furniture / Custom Storage Solutions / Shoe Drawers', 'Decor & Accessories / Shoe Display Stands']

Searching:  74%|███████▍  | 357/480 [01:53<00:25,  4.88it/s]

Outdoor
Storage & Organization
Furniture
keywords='outdoor welcome rug' hallucinated_classification=['Outdoor / Outdoor Decor / Welcome Mats & Door Rugs', 'Home & Garden / Garden Decor / Outdoor Rugs & Mats', 'Entryway & Hallway / Door Mats / Welcome Rugs', 'Patio & Garden / Patio Accessories / Welcome Rugs', 'Exterior Decor / Porch & Entryway Decor / Welcome Rugs']

Searching:  75%|███████▍  | 358/480 [01:53<00:27,  4.51it/s]

Rugs
keywords='counter top one cup hot water dispenser' hallucinated_classification=['Home Appliances / Kitchen Appliances / Water Dispensers / Countertop Water Dispensers', 'Kitchen & Tabletop / Coffee & Tea Accessories / Hot Water Dispensers', 'Home Improvement / Kitchen & Laundry Fixtures / Water Dispensers', 'Smart Home / Kitchen Gadgets / Automated Water Dispensers', 'Office & Commercial / Break Room Equipment / Hot Water Dispensers']

Searching:  75%|███████▍  | 359/480 [01:53<00:28,  4.27it/s]

Home Improvement
Kitchen & Tabletop
Appliances
keywords='artificial orchid arrangement' hallucinated_classification=['Décor & Pillows / Artificial Plants & Flowers / Artificial Orchids', 'Home Decor / Faux Floral Arrangements / Artificial Orchid Displays', 'Event & Party Supplies / Artificial Floral Decorations / Orchid Arrangements', 'Garden & Outdoor / Artificial Garden Plants / Orchid Arrangements', 'Interior Design / Artificial Botanical Art / Orchid Arrangements']

Searching:  75%|███████▌  | 360/480 [01:53<00:28,  4.28it/s]

Outdoor
Décor & Pillows
keywords='cortez pillow' hallucinated_classification=['Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows', 'Furniture / Bedroom Furniture / Bed Accessories / Pillow Accessories', 'Home Decor / Accent Pieces / Decorative Cushions']
Décor & Pillows

Searching:  75%|███████▌  | 361/480 [01:54<00:24,  4.83it/s]

keywords='decorative white pillow' hallucinated_classification=['Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows', 'Furniture / Living Room Furniture / Accent Pillows', 'Home Decor / Textile Accents / Decorative Cushions', 'Bedroom Accessories / Bed Decor / Decorative Pillows', 'Seasonal & Themed Decor / Holiday Pillows / White Decorative Pillows']
Furniture
Décor & Pillows

Searching:  75%|███████▌  | 362/480 [01:54<00:28,  4.14it/s]

keywords='dual monitor stand' hallucinated_classification=['Electronics / Computer Accessories / Monitor Stands and Mounts', 'Office Furniture / Desk Accessories / Monitor Risers', 'Home Office / Desk Organization / Monitor Stands', 'Technology & Gadgets / Computer Peripherals / Monitor Mounts', 'Furniture / Office Furniture / Desks & Workstations / Monitor Stands']

Searching:  76%|███████▌  | 363/480 [01:54<00:35,  3.33it/s]

School Furniture and Supplies
Furniture
keywords='toilet paper stand' hallucinated_classification=['Home Organization / Bathroom Storage & Accessories / Toilet Paper Holders and Stands', 'Furniture / Bathroom Furniture / Toilet Paper Stands & Dispensers', 'Home Decor / Bathroom Decor / Toilet Paper Holder Decor', 'Kitchen & Bath / Bathroom Accessories / Toilet Paper Dispensers', 'Bathroom Renovation / Bathroom Fixtures / Toilet Paper Holders']

Searching:  76%|███████▌  | 364/480 [01:55<00:37,  3.06it/s]

Home Improvement
Furniture
Bed & Bath
keywords='glass doors for bath' hallucinated_classification=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Shower & Bath Doors / Glass Shower Doors', 'Furniture / Bathroom Furniture / Bathroom Cabinets & Vanities / Glass Door Cabinets', 'Home Decor / Bathroom Accessories / Glass Shower Enclosures', 'Building Materials / Glass & Glazing / Shower Glass Panels', 'Smart Home / Home Automation / Bathroom Smart Glass Doors']

Searching:  76%|███████▌  | 365/480 [01:55<00:35,  3.27it/s]

Home Improvement
Furniture
Décor & Pillows
keywords='7qt slow cooker' hallucinated_classification=['Home Appliances / Kitchen Appliances / Slow Cookers & Crockpots', 'Kitchen & Tabletop / Small Kitchen Appliances / Electric Cookers', 'Home & Kitchen / Cooking & Baking Equipment / Slow Cooking Devices', 'Appliances / Countertop Cooking Appliances / Multi-Function Slow Cookers', 'Kitchen & Dining / Food Preparation / Slow Cooker Accessories']

Searching:  76%|███████▋  | 366/480 [01:55<00:33,  3.43it/s]

Kitchen & Tabletop
Appliances
keywords='low profile loveseat recliner' hallucinated_classification=['Furniture / Living Room Furniture / Reclining Sofas & Loveseats / Low Profile Loveseats', 'Furniture / Reclining Furniture / Loveseat Recliners / Low Profile Models', 'Home Decor / Space-Saving Furniture / Compact Loveseats / Reclining', 'Furniture / Modern Furniture / Minimalist Loveseats / Reclining', 'Furniture / Customizable Furniture / Modular Loveseats / Reclining']

Searching:  76%|███████▋  | 367/480 [01:56<00:32,  3.44it/s]

Furniture
keywords='block coffee table' hallucinated_classification=['Furniture / Coffee Tables / Block-Shaped Coffee Tables', 'Furniture / Modular Furniture / Block Modular Tables', 'Home Decor / Statement Pieces / Block Design Coffee Tables', 'Living Room Furniture / Contemporary Coffee Tables / Geometric Block Coffee Tables', 'Custom Furniture / Block Style Coffee Tables']

Searching:  77%|███████▋  | 368/480 [01:56<00:30,  3.71it/s]

Furniture
keywords='bistro sets patio' hallucinated_classification=['Outdoor / Outdoor & Patio Furniture / Bistro Sets & Small Tables', 'Furniture / Patio & Garden Furniture / Bistro Sets', 'Outdoor / Patio Dining Sets / Bistro Style', 'Furniture / Outdoor Furniture / Compact Bistro Sets', 'Home & Garden / Patio Decor & Accessories / Bistro Set Covers']

Searching:  77%|███████▋  | 369/480 [01:56<00:29,  3.76it/s]

Outdoor
Furniture
Décor & Pillows
keywords='home sweet home sign' hallucinated_classification=['Decor / Wall Art / Signs & Plaques / Home Signs', 'Home Decor / Welcome Signs / Housewarming & Greeting Signs', 'Interior Decor / Wall Hangings / Wooden Signs', 'Personalized Decor / Custom Signs / House Name Signs', 'Holiday & Seasonal Decor / Seasonal Signs / Home Sweet Home Signs']

Searching:  77%|███████▋  | 370/480 [01:56<00:28,  3.80it/s]

Holiday Décor
Décor & Pillows
keywords='upholstered girls bed' hallucinated_classification=["Furniture / Kids & Teens Furniture / Girls' Beds & Bed Frames / Upholstered Girls Beds", "Furniture / Kids & Teens Furniture / Girls' Bedroom Furniture / Upholstered Girls Beds", 'Furniture / Bedroom Furniture / Kids Beds / Upholstered Girls Bed', "Kids & Teens / Bedroom Furniture / Girls' Beds / Upholstered Bed"]

Searching:  77%|███████▋  | 371/480 [01:57<00:27,  3.97it/s]

Baby & Kids
Furniture
keywords='aiden black velvet bed' hallucinated_classification=['Furniture / Bedroom Furniture / Upholstered Beds / Velvet Beds', 'Furniture / Bedroom Furniture / Canopy & Four-Poster Beds', 'Furniture / Bedroom Furniture / Platform Beds / Black Velvet Finish', 'Luxury Furniture / Designer Beds / Velvet Upholstered Beds', 'Home Decor / Bed Frames / Velvet Bed Frames']

Searching:  78%|███████▊  | 372/480 [01:57<00:27,  3.93it/s]

Furniture
keywords='zachary 72.5' hallucinated_classification=['Furniture / Customizable Furniture / Modular Shelving Units', 'Home Office / Desks & Workstations / Adjustable Standing Desks', 'Decor & Accessories / Wall Art / Modern Abstract Paintings', 'Outdoor / Garden Decor / Sculptural Garden Art', 'Lighting / Unique Floor Lamps / Artistic Floor Lamps', 'Kitchen & Dining / Bar Stools & Counter Stools / Adjustable Height Stools', 'Bedroom / Bed Frames / Platform Beds with Storage', 'Living Room / Sectional Sofas / Modular Sectionals', 'Storage & Organization / Multi-purpose Storage Ottomans', 'Kids & Teens / Themed Bedroom Furniture / Space-Themed Beds']
Baby & Kids
Décor & Pillows
Outdoor
Furniture
Lighting
Storage & Organization

Searching:  78%|███████▊  | 373/480 [01:58<00:43,  2.46it/s]

keywords='light bulb' hallucinated_classification=['Lighting / Light Bulbs & Fixtures / LED Light Bulbs', 'Lighting / Specialty Light Bulbs / Smart Light Bulbs', 'Home Improvement / Electrical / Light Bulbs & Fixtures / Incandescent Bulbs', 'Decor & Accessories / Ambient Lighting / Decorative Light Bulbs', 'Outdoor / Garden & Landscape Lighting / Pathway & Spot Lights']

Searching:  78%|███████▊  | 374/480 [01:58<00:40,  2.61it/s]

Lighting
keywords='beds that have leds' hallucinated_classification=['Furniture / Bedroom Furniture / Beds with Integrated LED Lighting', 'Lighting / LED Bed Frames / Smart LED Bed Frames', 'Home Decor / Mood Lighting / Bedside LED Illumination', 'Smart Home / Sleep & Relaxation Devices / LED-Enhanced Beds', 'Furniture / Kids & Teen Bedroom Furniture / Beds with Built-in LEDs']

Searching:  78%|███████▊  | 375/480 [01:58<00:37,  2.83it/s]

Holiday Décor
Lighting
Furniture
Bed & Bath
keywords='velvet chaise' hallucinated_classification=['Furniture / Lounge & Accent Furniture / Chaise Lounges and Daybeds / Velvet Chaise Lounges', 'Furniture / Living Room Furniture / Sofas & Sectionals / Velvet Sofas and Loveseats', 'Home Decor / Upholstered Furniture / Velvet Upholstered Pieces / Velvet Lounge Chairs', 'Furniture / Bedroom Furniture / Upholstered Benches & Ottomans / Velvet Ottomans', 'Furniture / Custom & Designer Furniture / Velvet Statement Pieces / Velvet Designer Chairs']

Searching:  78%|███████▊  | 376/480 [01:58<00:34,  3.04it/s]

Outdoor
Furniture
keywords='elegant executive chair' hallucinated_classification=['Furniture / Office Furniture / Executive Chairs / Leather Executive Chairs', 'Furniture / Office Furniture / Conference Room Chairs', 'Furniture / Lounge & Reception Furniture / Lounge Chairs & Armchairs', 'Furniture / Home Office Furniture / Ergonomic Office Chairs', 'Furniture / Commercial Furniture / Executive Seating', 'Furniture / Luxury Furniture / Designer Executive Chairs']

Searching:  79%|███████▊  | 377/480 [01:59<00:32,  3.13it/s]

Furniture
keywords='card table' hallucinated_classification=['Furniture / Game Room Furniture / Card Tables and Poker Tables', 'Furniture / Compact & Portable Tables / Folding Card Tables', 'Furniture / Vintage & Retro Furniture / Mid-Century Card Tables', 'Furniture / Multi-Functional Furniture / Card Table with Storage', 'Furniture / Custom & Designer Furniture / Handcrafted Card Tables']

Searching:  79%|███████▉  | 378/480 [01:59<00:34,  3.00it/s]

School Furniture and Supplies
Furniture
keywords='pool floats' hallucinated_classification=['Outdoor / Pool & Beach Accessories / Pool Floats & Inflatables', 'Recreation & Sports / Water Sports Equipment / Pool Floats', 'Kids & Baby / Pool Toys & Floats / Pool Floats for Kids', 'Luxury & Decor / Poolside Decor / Inflatable Pool Loungers', 'Seasonal & Holiday / Summer Pool Accessories / Inflatable Pool Floats']

Searching:  79%|███████▉  | 379/480 [01:59<00:32,  3.07it/s]

Baby & Kids
Outdoor
Décor & Pillows
keywords='sheets for twinxl' hallucinated_classification=['Bedding / Bed Sheets / Twin XL Sheets', 'Bedroom Accessories / Mattress Protectors / Twin XL Mattress Covers', 'Home Textiles / Bedding Sets / Twin XL Bedding Sets', 'Kids & Teens / Dorm Room Essentials / Twin XL Bedding', 'Luxury Bedding / Premium Sheets / Twin XL']

Searching:  79%|███████▉  | 380/480 [02:00<00:31,  3.16it/s]

Bed Accessories
Baby & Kids
Bed & Bath
keywords='gaia driftwood table' hallucinated_classification=['Furniture / Living Room Furniture / Coffee Tables & End Tables / Driftwood Style Coffee Tables', 'Furniture / Eco-Friendly & Sustainable Furniture / Reclaimed Wood Tables / Gaia Driftwood Table', 'Home Decor / Natural & Organic Decor / Driftwood Accents / Gaia Driftwood Table', 'Outdoor / Garden & Patio Furniture / Natural Material Tables / Gaia Driftwood Table', 'Furniture / Custom & Artistic Furniture / Handcrafted Driftwood Tables / Gaia']

Searching:  79%|███████▉  | 381/480 [02:00<00:32,  3.04it/s]

Outdoor
Furniture
keywords='wall shelves' hallucinated_classification=['Furniture / Wall Storage & Shelving / Wall-mounted Shelves', 'Home Organization / Wall Shelves & Racks / Decorative Wall Shelves', 'Decor & Wall Art / Wall Shelves / Floating Wall Shelves', 'Living Room / Wall Shelves / Modern Wall Shelves', 'Bedroom / Wall Shelves / Bedside Wall Shelves', 'Entryway / Wall Shelves / Coat & Shoe Shelves', 'Kids & Teens / Wall Shelves / Themed Wall Shelves']

Searching:  80%|███████▉  | 382/480 [02:00<00:34,  2.82it/s]

Baby & Kids
Storage & Organization
Furniture
keywords='large bases' hallucinated_classification=['Furniture / Structural Components / Large Furniture Bases', 'Home Decor / Architectural Elements / Large Base Supports', 'Outdoor / Garden Structures / Large Base Pedestals', 'Furniture / Customizable Furniture Parts / Large Base Frames', 'Home Improvement / Flooring & Foundations / Large Base Mounts']

Searching:  80%|███████▉  | 383/480 [02:01<00:33,  2.90it/s]

Outdoor
Furniture
Décor & Pillows
Bed & Bath
keywords='brendon counter stool' hallucinated_classification=['Furniture / Kitchen & Dining / Counter Stools & Bar Stools', 'Furniture / Home Office / Counter Height Seating', 'Furniture / Entryway & Hallway / Entryway Seating & Benches', 'Furniture / Living Room Furniture / Accent Stools & Ottomans', 'Furniture / Bedroom Furniture / Vanity Stools & Chairs', 'Outdoor / Patio Furniture / Counter Height Bar Stools']

Searching:  80%|████████  | 384/480 [02:01<00:34,  2.78it/s]

Outdoor
Furniture
keywords='eiffel tower wall art' hallucinated_classification=['Decor & Wall Art / Metal Wall Art / Architectural & Landmark Designs', 'Home Decor / Themed Wall Hangings / Landmark & Cityscape Art', 'Wall Decor / Canvas & Framed Prints / Landmark & Iconic Structures', 'Interior Decor / Statement Wall Pieces / Architectural Landmark Art', 'Gift & Novelty Items / Landmark & Cityscape Wall Art']

Searching:  80%|████████  | 385/480 [02:02<00:34,  2.74it/s]

Décor & Pillows
keywords='love seat wide faux leather tuxedo arm sofa' hallucinated_classification=['Furniture / Living Room Furniture / Sofas & Couches', 'Furniture / Specialty Seating / Tuxedo Sofas', 'Furniture / Upholstered Furniture / Faux Leather Sofas', 'Home Decor / Statement Furniture / Wide Love Seats', 'Interior Design / Modern Furniture / Tuxedo Style Sofas']

Searching:  80%|████████  | 386/480 [02:02<00:31,  3.01it/s]

Reception Area
Outdoor
Furniture
keywords='king adjustable bed including mattress' hallucinated_classification=['Furniture / Bedroom Furniture / Adjustable Beds and Bases', 'Home Goods / Mattresses / Adjustable Mattress Sets', 'Furniture / Sleep Solutions / Adjustable Bed Frames', 'Home Improvement / Bedroom Renovation / Adjustable Bed Installations', 'Luxury Bedding / Adjustable Bed Accessories']

Searching:  81%|████████  | 387/480 [02:02<00:28,  3.24it/s]

Bed Accessories
Furniture
Bed & Bath
keywords='animal print handmade tufted wool beige/black area rug' hallucinated_classification=['Home Decor / Rugs & Carpets / Area Rugs', 'Furniture / Living Room Furniture / Rugs & Carpets', 'Decor & Pillows / Floor Coverings / Area Rugs', 'Home Improvement / Flooring / Area Rugs & Mats', 'Interior Design / Textiles / Wool Rugs']

Searching:  81%|████████  | 388/480 [02:02<00:26,  3.52it/s]

Furniture
Rugs
keywords='outdoor lounge chair' hallucinated_classification=['Outdoor / Outdoor Lounge & Seating / Lounge Chairs & Recliners / Outdoor Lounge Chairs', 'Furniture / Patio & Garden Furniture / Lounge Chairs & Sunbeds / Outdoor Lounge Chairs', 'Garden & Outdoor / Outdoor Furniture / Lounge & Reclining Chairs', 'Outdoor Living / Patio Furniture / Lounge Chairs & Ottomans / Outdoor Lounge Chairs', 'Home & Garden / Outdoor Furniture / Lounge Chairs & Sun Loungers']

Searching:  81%|████████  | 389/480 [02:03<00:26,  3.46it/s]

Outdoor
Furniture
keywords='desk and chair set' hallucinated_classification=['Furniture / Office Furniture / Desks & Workstations', 'Furniture / Office Furniture / Office Chairs', 'Furniture / Home Office Furniture / Desk and Chair Sets', 'Furniture / Kids & Teens Furniture / Kids Desk and Chair Sets', 'Furniture / Multi-Functional Furniture / Convertible Desk and Chair Sets', 'Furniture / Customizable Furniture / Modular Desk and Chair Systems']

Searching:  81%|████████▏ | 390/480 [02:03<00:28,  3.16it/s]

Baby & Kids
Furniture
keywords='rattan truck' hallucinated_classification=['Furniture / Unique & Artistic Furniture / Rattan & Wicker Art Pieces', 'Decor / Themed Decor / Vehicle-Shaped Decor Items', 'Outdoor / Garden & Patio Decor / Rattan Garden Sculptures', 'Kids & Teens / Playroom Furniture / Vehicle-Themed Storage Units', 'Home Decor / Statement Pieces / Rattan & Wicker Accents']

Searching:  81%|████████▏ | 391/480 [02:03<00:30,  2.89it/s]

Baby & Kids
Outdoor
Furniture
Décor & Pillows
keywords='chaise lounge couch' hallucinated_classification=['Furniture / Lounge & Recliners / Chaise Lounges', 'Furniture / Living Room Furniture / Sofas & Couches', 'Furniture / Sectional Sofas & Couches / Chaise Sections', 'Furniture / Custom & Modular Sofas / Chaise Modules', 'Furniture / Vintage & Retro Furniture / Mid-Century Modern Lounge Chairs', 'Furniture / Outdoor Lounge Furniture / Outdoor Chaise Lounges', 'Furniture / Upholstered Furniture / Plush Lounge Chairs']

Searching:  82%|████████▏ | 392/480 [02:04<00:37,  2.38it/s]

Outdoor
Furniture
keywords='led 60' hallucinated_classification=['Lighting / LED Lighting / LED Bulbs & Tubes / LED 60W Bulbs', 'Lighting / LED Fixtures / LED Ceiling Lights / 60W LED Ceiling Lights', 'Home Improvement / Lighting & Ceiling Fans / LED Recessed Lighting / 60W LED Recessed Lights', 'Smart Home / Smart Lighting / Wi-Fi LED Bulbs / 60W Smart LED Bulbs']

Searching:  82%|████████▏ | 393/480 [02:04<00:31,  2.78it/s]

Lighting
keywords='platform bed side table' hallucinated_classification=['Furniture / Bedroom Furniture / Bedside Tables and Nightstands', 'Furniture / Bedroom Furniture / Platform Beds', 'Furniture / Bedroom Furniture / Storage Beds', 'Furniture / Bedroom Furniture / Canopy & Four-Poster Beds', 'Furniture / Bedroom Furniture / Upholstered Beds', 'Furniture / Bedroom Furniture / Adjustable Beds', 'Furniture / Bedroom Furniture / Bed Frames & Headboards']

Searching:  82%|████████▏ | 394/480 [02:05<00:30,  2.78it/s]

Furniture
Bed & Bath
keywords='stainless steel free standing shower caddy' hallucinated_classification=['Home Improvement / Bathroom Accessories / Shower Caddies & Shelves / Free Standing Shower Caddies', 'Bathroom Storage / Shower Organizers / Stainless Steel Shower Caddies', 'Bathroom Fixtures & Accessories / Shower Caddies / Freestanding Stainless Steel Models', 'Bathroom Organization / Shower Storage Solutions / Stainless Steel Free Standing Caddies', 'Home & Bath / Shower & Tub Accessories / Free Standing Shower Caddies']

Searching:  82%|████████▏ | 395/480 [02:05<00:28,  2.98it/s]

Home Improvement
Bed & Bath
keywords='fleur de lis living candle wall sconce bronze' hallucinated_classification=['Home Decor / Wall Decor / Candle Sconces', 'Lighting / Wall Sconces / Decorative Wall Lighting', 'Home Decor / Decorative Accessories / Wall-mounted Decor', 'Furniture / Accent Furniture / Wall-mounted Accent Pieces', 'Holiday & Seasonal Decor / Themed Wall Decor']

Searching:  82%|████████▎ | 396/480 [02:05<00:25,  3.27it/s]

Holiday Décor
Lighting
Furniture
Décor & Pillows
keywords='turquoise chair' hallucinated_classification=['Furniture / Accent Chairs / Upholstered Chairs / Turquoise Upholstered Chair', 'Furniture / Kids & Teens Furniture / Kids Chairs / Turquoise Kids Chair', 'Furniture / Office Furniture / Desk Chairs / Turquoise Desk Chair', 'Décor & Pillows / Decorative Accents / Turquoise Decorative Chair', 'Outdoor / Patio Chairs / Turquoise Outdoor Chair', 'Furniture / Vintage & Retro Furniture / Mid-Century Modern Chairs / Turquoise Retro Chair']

Searching:  83%|████████▎ | 397/480 [02:05<00:25,  3.24it/s]

School Furniture and Supplies
Outdoor
Furniture
keywords='solid teak end table' hallucinated_classification=['Furniture / Living Room Furniture / End Tables & Side Tables / Solid Teak End Tables', 'Furniture / Bedroom Furniture / Nightstands / Teak Nightstands', 'Home Decor / Wooden Furniture / Teak Wood Furniture / Solid Teak End Tables', 'Outdoor Furniture / Teak Patio Tables / End Tables in Teak', 'Luxury Furniture / Custom Woodwork / Teak End Tables']

Searching:  83%|████████▎ | 398/480 [02:06<00:24,  3.37it/s]

Outdoor
Furniture
keywords='small space dining table and chairs sets' hallucinated_classification=['Furniture / Compact Living / Space-Saving Dining Sets', 'Furniture / Small Space Solutions / Multi-Functional Dining Tables', 'Furniture / Apartment Living / Space-Efficient Dining Furniture', 'Furniture / Modular Furniture / Convertible Dining Sets', 'Furniture / Kids & Teens / Small Space Dining Sets for Kids', 'Furniture / Studio & Loft Living / Small Dining Table & Chair Sets']

Searching:  83%|████████▎ | 399/480 [02:06<00:24,  3.34it/s]

Baby & Kids
Outdoor
Furniture
keywords='belchertown table lamp' hallucinated_classification=['Lighting / Table Lamps / Decorative Table Lamps', 'Furniture / Living Room Furniture / Accent Tables & Lamps', 'Home Decor / Lamps & Lighting Accessories / Table Lamps', 'Bedroom Furniture / Nightstand Lamps / Bedside Lamps', 'Office & Study / Desk & Table Lamps / Desk Lamps']

Searching:  83%|████████▎ | 400/480 [02:06<00:22,  3.53it/s]

Lighting
Furniture
keywords='body pillow and case' hallucinated_classification=['Home Textiles / Bedding & Sleep Accessories / Body Pillows', 'Bedding & Sleep Accessories / Pillowcases / Body Pillow Cases', 'Furniture / Bedroom Furniture / Specialty Pillows & Cushions', 'Home Decor / Comfort & Relaxation / Body Support Cushions', 'Sleep & Relaxation / Support Pillows / Body Pillows']
Outdoor
Bed & Bath
Décor & Pillows

Searching:  84%|████████▎ | 401/480 [02:07<00:39,  1.99it/s]

keywords='small curtain rods' hallucinated_classification=['Home Decor / Window Treatments / Curtain Rods & Hardware / Small Curtain Rods', 'Furniture / Window Accessories / Curtain Hardware / Small Curtain Rods', 'Home Improvement / Window & Door Hardware / Curtain Rods / Small Sizes', 'Decor & Textiles / Window Coverings / Curtain Rods / Compact Size']
Décor & Pillows

Searching:  84%|████████▍ | 402/480 [02:07<00:32,  2.38it/s]

keywords='outdoor movie screen' hallucinated_classification=['Outdoor / Outdoor Entertainment / Movie Screens & Projectors / Outdoor Movie Screens', 'Garden & Patio / Outdoor Decor / Outdoor Movie Screen Stands', 'Recreation & Sports / Outdoor Movie Equipment / Portable Movie Screens', 'Home Theater / Outdoor Home Theater / Outdoor Movie Screen Enclosures']
Outdoor
Furniture

Searching:  84%|████████▍ | 403/480 [02:08<00:27,  2.79it/s]

keywords='carolyn console table' hallucinated_classification=['Furniture / Entryway & Hallway Furniture / Console Tables', 'Furniture / Living Room Furniture / Accent Tables', 'Home Decor / Statement Pieces / Console & Entry Tables', 'Furniture / Custom & Designer Furniture / Unique Console Designs', 'Furniture / Small Space Furniture / Space-Saving Console Tables']
Furniture

Searching:  84%|████████▍ | 404/480 [02:08<00:24,  3.12it/s]

keywords='pantry grey' hallucinated_classification=['Home Organization / Pantry Storage / Grey Pantry Shelves and Cabinets', 'Kitchen & Tabletop / Food Storage / Grey Pantry Containers and Bins', 'Furniture / Kitchen & Dining Furniture / Grey Pantry Cabinets', 'Home Improvement / Kitchen Renovation / Grey Pantry Shelving Solutions', 'Décor & Pillows / Kitchen Decor / Grey Pantry Theme Accessories']
Décor & Pillows
Storage & Organization
Kitchen & Tabletop
Furniture

Searching:  84%|████████▍ | 405/480 [02:08<00:22,  3.31it/s]

keywords='smart coffee table' hallucinated_classification=['Furniture / Smart Home Furniture / Connected Coffee Tables', 'Furniture / Living Room Furniture / Modern Coffee Tables with Tech Features', 'Home Automation / Smart Furniture / Interactive Coffee Tables', 'Furniture / Tech-Integrated Living Room Furniture / Smart Coffee Tables', 'Smart Home Devices / Connected Home Furniture / Coffee Tables with Built-in Technology']
Furniture

Searching:  85%|████████▍ | 406/480 [02:08<00:21,  3.50it/s]

keywords='30 inch bathroom vanity' hallucinated_classification=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / Compact Bathroom Vanities', 'Furniture / Bathroom Furniture / Bathroom Vanities / 30 Inch Vanities', 'Decor & Accessories / Bathroom Decor / Vanity Mirrors & Accessories / 30 Inch Vanity Mirrors', 'Kitchen & Bath / Bathroom Storage / Vanity Cabinets / 30 Inch Vanity Cabinets']
Home Improvement
Furniture
Décor & Pillows
Storage & Organization

Searching:  85%|████████▍ | 407/480 [02:09<00:19,  3.78it/s]

keywords='garage sports storage rack' hallucinated_classification=['Home Improvement / Garage Storage & Organization / Sports Equipment Racks', 'Sports & Recreation / Garage & Storage Solutions / Sports Gear Storage Systems', 'Furniture / Garage & Workshop Furniture / Storage Racks & Shelving / Sports Equipment Racks', 'Outdoor / Garage & Shed Storage / Sports Equipment Storage']
Storage & Organization

Searching:  85%|████████▌ | 408/480 [02:09<00:17,  4.05it/s]

keywords='moen matte black hooks' hallucinated_classification=['Home Improvement / Bathroom Fixtures & Accessories / Towel Hooks & Holders', 'Home Organization / Closet & Wardrobe Accessories / Hook Racks', 'Decor & Accessories / Wall Hooks & Hangers / Decorative Hooks', 'Furniture / Entryway Furniture / Coat & Hat Hooks', 'Outdoor / Garden & Patio Accessories / Wall-Mounted Hooks']
Outdoor
Home Improvement
Furniture
Bed & Bath
Storage & Organization

Searching:  85%|████████▌ | 409/480 [02:09<00:17,  4.02it/s]

keywords='7 draw white dresser' hallucinated_classification=['Furniture / Bedroom Furniture / Dressers & Chests / Multi-Drawer Dressers', 'Furniture / Kids & Teen Furniture / Kids Dressers & Chests / White Drawers', 'Home Organization / Closet & Wardrobe Storage / Dresser Units', 'Furniture / Entryway Furniture / Console Dressers / White Finish', 'Furniture / Storage & Organization / Drawer Cabinets / White Dresser']
Furniture
Storage & Organization

Searching:  85%|████████▌ | 410/480 [02:09<00:17,  3.95it/s]

keywords='fawkes 36" blue vanity' hallucinated_classification=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / Modern Blue Vanities', 'Furniture / Bedroom Furniture / Vanities & Makeup Tables / Blue Vanity Tables', 'Decor & Pillows / Color-Themed Decor / Blue Accents & Accessories', 'Furniture / Custom & Artistic Furniture / Artistic Vanities / Fawkes Design Vanities', 'Home Decor / Statement Pieces / Unique Blue Furniture']
Home Improvement
Furniture
Décor & Pillows

Searching:  86%|████████▌ | 411/480 [02:10<00:17,  3.88it/s]

keywords='bar stool with backrest' hallucinated_classification=['Furniture / Kitchen & Bar Furniture / Bar Stools with Back Support', 'Furniture / Dining Room Furniture / Counter & Bar Stools', 'Furniture / Home Bar & Entertainment Furniture / Bar Seating', 'Furniture / Commercial & Restaurant Furniture / Bar Stools with Backrest', 'Furniture / Outdoor Furniture / Patio Bar Stools with Back Support', 'Furniture / Custom Furniture / Upholstered Bar Stools with Backrest']

Searching:  86%|████████▌ | 412/480 [02:10<00:18,  3.62it/s]

Outdoor
Furniture
keywords='dolomite subway tile' hallucinated_classification=['Home Improvement / Wall & Floor Tiles / Subway Tiles / Dolomite Subway Tiles', 'Kitchen & Bath / Backsplashes / Subway Tile Backsplashes / Dolomite Subway Tile Backsplash', 'Decor & Wall Art / Wall Coverings / Tile Wall Coverings / Dolomite Subway Tile', 'Architectural & Design / Building Materials / Specialty Tiles / Dolomite Subway Tile']

Searching:  86%|████████▌ | 413/480 [02:10<00:17,  3.80it/s]

Home Improvement
Décor & Pillows
keywords='verden callan' hallucinated_classification=['Furniture / Office Furniture / Executive Desks', 'Home Decor / Wall Art / Abstract Paintings', 'Lighting / Floor Lamps / Modern Floor Lamps', 'Outdoor / Garden Furniture / Lounge Chairs', 'Storage & Organization / Shelving Units / Modular Shelving', 'Home Improvement / Smart Home Devices / Voice-Activated Assistants']

Searching:  86%|████████▋ | 414/480 [02:10<00:17,  3.67it/s]

Décor & Pillows
Outdoor
Home Improvement
Furniture
Lighting
Storage & Organization
keywords='industrial pipe dining table' hallucinated_classification=['Furniture / Dining Room Furniture / Dining Tables / Industrial Pipe Dining Tables', 'Furniture / Kitchen & Dining / Kitchen Tables / Industrial Pipe Kitchen Tables', 'Home Decor / Industrial Style Decor / Pipe & Metal Accents', 'Furniture / Custom & Specialty Furniture / Industrial Pipe Furniture']

Searching:  86%|████████▋ | 415/480 [02:11<00:16,  4.02it/s]

Furniture
Décor & Pillows
keywords='ottoman bed queen' hallucinated_classification=['Furniture / Bedroom Furniture / Ottoman Beds', 'Furniture / Bedroom Furniture / Queen Size Beds', 'Furniture / Multi-Functional Furniture / Storage Beds', 'Furniture / Customizable Furniture / Modular Beds', 'Home Decor / Upholstered Furniture / Upholstered Beds', 'Furniture / Space-Saving Furniture / Compact Beds']

Searching:  87%|████████▋ | 416/480 [02:11<00:16,  3.83it/s]

Furniture
Décor & Pillows
keywords='small wardrobe grey' hallucinated_classification=['Furniture / Bedroom Furniture / Wardrobes & Armoires / Small Wardrobes', 'Furniture / Storage & Organization / Closet Storage / Small Wardrobes', 'Home Decor / Color Specific Furniture / Grey Wardrobes', 'Furniture / Kids & Teen Bedroom Furniture / Small Wardrobes for Kids', 'Furniture / Entryway Furniture / Small Wardrobes for Entryways']

Searching:  87%|████████▋ | 417/480 [02:11<00:16,  3.89it/s]

Baby & Kids
Furniture
Storage & Organization
keywords='westling coffee table' hallucinated_classification=['Furniture / Coffee Tables / Modern Coffee Tables', 'Furniture / Living Room Furniture / Coffee Tables & End Tables / Westling Style Coffee Tables', 'Home Decor / Coffee Table Accessories / Decorative Coffee Table Trays', 'Furniture / Custom & Designer Coffee Tables / Westling Collection', 'Furniture / Multi-Functional Tables / Convertible Coffee & Side Tables']

Searching:  87%|████████▋ | 418/480 [02:11<00:15,  3.90it/s]

Furniture
Décor & Pillows
keywords='white bathroom vanity black hardware' hallucinated_classification=['Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / Modern Bathroom Vanities', 'Furniture / Bathroom Furniture / Bathroom Vanities with Black Hardware', 'Decor & Accessories / Bathroom Decor / Vanity Mirrors and Hardware', 'Home Decor / Wall Mounts / Vanity Hardware Accessories', 'Kitchen & Bath / Vanity Storage / Custom Vanity Units']

Searching:  87%|████████▋ | 419/480 [02:12<00:16,  3.69it/s]

Home Improvement
Storage & Organization
Décor & Pillows
keywords='betty resin free standing umbrella' hallucinated_classification=['Outdoor / Outdoor Umbrellas & Shade / Free Standing Umbrellas', 'Garden & Patio / Patio Accessories / Umbrella Bases and Stands', 'Furniture / Outdoor Furniture / Umbrellas and Shade Structures', 'Home Decor / Garden Decor / Outdoor Shade Solutions', 'Sun Protection / Outdoor Sun Shelters / Free Standing Sun Umbrellas']

Searching:  88%|████████▊ | 420/480 [02:12<00:17,  3.46it/s]

Outdoor
keywords='anchor decor' hallucinated_classification=['Decor & Accessories / Nautical & Marine Decor / Anchor Wall Art', 'Home Decor / Nautical & Coastal Decor / Anchor Figurines', 'Furniture / Accent Furniture / Anchor-Shaped Ottomans', 'Outdoor / Garden & Patio Decor / Nautical Themed Garden Stakes', 'Lighting / Nautical & Coastal Lighting / Anchor Pendant Lights', 'Wall Decor / Nautical & Coastal Wall Hangings / Anchor Wall Hangings']

Searching:  88%|████████▊ | 421/480 [02:12<00:18,  3.26it/s]

Lighting
Outdoor
Furniture
Décor & Pillows
keywords='outdoor privacy wall' hallucinated_classification=['Outdoor / Outdoor Privacy & Security / Privacy Walls & Fences', 'Garden & Patio / Privacy Screens / Outdoor Privacy Panels', 'Outdoor / Garden Structures / Privacy Fences & Walls', 'Home Improvement / Exterior Improvements / Privacy Wall Systems', 'Landscaping / Garden Borders & Edging / Privacy Barriers']

Searching:  88%|████████▊ | 422/480 [02:13<00:17,  3.27it/s]

Home Improvement
Outdoor
keywords='blaylock bookcase headboard' hallucinated_classification=['Furniture / Bedroom Furniture / Headboards & Bed Frames / Bookcase Headboards', 'Furniture / Bedroom Furniture / Headboards & Bed Frames / Custom Headboards', 'Furniture / Bedroom Furniture / Headboards & Bed Frames / Multi-Functional Headboards', 'Furniture / Bedroom Furniture / Headboards & Bed Frames / Vintage & Antique Headboards', 'Furniture / Bedroom Furniture / Headboards & Bed Frames / Modern & Contemporary Headboards']

Searching:  88%|████████▊ | 423/480 [02:13<00:18,  3.08it/s]

Furniture
keywords='rose gold lounge' hallucinated_classification=['Furniture / Lounge & Accent Chairs / Lounge Chairs & Recliners', 'Furniture / Sofas & Sectionals / Lounge Sofas', 'Home Decor / Metallic Accents / Rose Gold Decor', 'Furniture / Bedroom Furniture / Lounge Benches & Ottomans', 'Outdoor / Patio Lounge Furniture / Lounge Chairs & Sets', 'Lighting / Metallic Finish Lighting / Rose Gold Lamps']

Searching:  88%|████████▊ | 424/480 [02:13<00:18,  3.05it/s]

Lighting
Outdoor
Furniture
Décor & Pillows
keywords='propane gas dryer' hallucinated_classification=['Home Appliances / Laundry Appliances / Gas Dryers / Propane Gas Dryers', 'Home & Garden / Heating & Cooling / Gas Appliances / Propane Gas Equipment', 'Outdoor / Camping & RV Equipment / Propane Appliances / Propane Dryers', 'Industrial & Commercial / Laundry Equipment / Gas-Powered Dryers']

Searching:  89%|████████▊ | 425/480 [02:14<00:17,  3.21it/s]

Appliances
keywords='barstool patio sets' hallucinated_classification=['Outdoor / Outdoor & Patio Furniture / Patio Barstools & Seating Sets', 'Furniture / Outdoor Furniture / Patio Sets with Barstools', 'Garden & Patio / Patio Dining Sets / Barstool Patio Sets', 'Home & Garden / Patio & Garden Furniture / Barstool Sets for Patios', 'Recreation & Leisure / Outdoor Bar & Seating / Barstool Patio Sets']

Searching:  89%|████████▉ | 426/480 [02:14<00:17,  3.08it/s]

Outdoor
Furniture
keywords='camper' hallucinated_classification=['Outdoor / Camping & Hiking Gear / Camper Accessories / Camper Interior Accessories', 'Furniture / RV & Camper Furniture / Camper Seating & Tables', 'Home Improvement / RV & Camper Renovation / Camper Insulation & Ventilation', 'Outdoor / Camper & RV Outdoor Equipment / Camper Awnings & Canopies', 'Travel & Leisure / Camper Travel Accessories / Camper Storage Solutions']

Searching:  89%|████████▉ | 427/480 [02:14<00:17,  3.09it/s]

Home Improvement
Outdoor
Furniture
Storage & Organization
keywords='stainless steel colander set' hallucinated_classification=['Kitchen & Tabletop / Kitchen Tools & Gadgets / Colanders & Strainers', 'Kitchen & Tabletop / Cookware & Bakeware / Colanders & Strainers', 'Home Organization / Kitchen Storage / Food Prep & Storage Containers', 'Kitchen & Tabletop / Kitchen Accessories / Utensil Sets', 'Home Improvement / Kitchen & Dining / Kitchen Fixtures & Accessories']

Searching:  89%|████████▉ | 428/480 [02:15<00:15,  3.29it/s]

Home Improvement
Kitchen & Tabletop
keywords='pictures to hang over fireplace' hallucinated_classification=['Decor / Wall Art / Framed Pictures and Prints', 'Home Decor / Wall Hangings / Art Panels', 'Furniture / Fireplace Mantel Decor / Picture Shelves', 'Interior Design / Wall Accents / Photo Collages', 'Living Room Decor / Wall Art / Canvas Prints', 'Architectural Elements / Wall Niches / Picture Recesses', 'Custom Framing / Picture Mounting Solutions']

Searching:  89%|████████▉ | 429/480 [02:15<00:15,  3.19it/s]

Furniture
Décor & Pillows
keywords='black hanging bookshelf' hallucinated_classification=['Furniture / Wall-Mounted Storage / Hanging Bookshelves', 'Home Organization / Wall-Mounted Shelving / Hanging Shelves', 'Decor & Accessories / Wall Decor / Hanging Wall Art & Shelves', 'Living Room / Wall Storage / Hanging Book Racks', 'Bedroom / Wall-Mounted Storage / Hanging Bedroom Shelves']

Searching:  90%|████████▉ | 430/480 [02:15<00:14,  3.35it/s]

Furniture
Décor & Pillows
Storage & Organization
keywords='odum velvet' hallucinated_classification=['Furniture / Upholstered Furniture / Velvet Sofas and Armchairs', 'Home Decor / Velvet Textiles / Velvet Curtains and Drapes', 'Bedroom Furniture / Velvet Bed Frames and Headboards', 'Living Room Accessories / Velvet Throw Pillows and Cushions', 'Furniture / Accent Pieces / Velvet Ottomans and Poufs', 'Decor & Pillows / Velvet Decorative Pillows / Velvet Floor Cushions']

Searching:  90%|████████▉ | 431/480 [02:16<00:14,  3.32it/s]

Furniture
Décor & Pillows
keywords='town & country living curtains' hallucinated_classification=['Home Decor / Window Treatments / Curtains & Drapes / Town & Country Style Curtains', 'Furniture / Living Room Furniture / Window Coverings / Country Style Curtains', 'Home Accessories / Curtain Accessories / Curtain Rods & Hardware / Town & Country Design', 'Interior Design / Window Treatments / Rustic & Vintage Curtains']

Searching:  90%|█████████ | 432/480 [02:16<00:12,  3.72it/s]

Décor & Pillows
keywords='chase utility laundry cart' hallucinated_classification=['Home Appliances / Laundry & Utility Rooms / Laundry Carts & Hampers', 'Furniture / Utility & Storage Furniture / Laundry Carts', 'Home Organization / Laundry Room Storage / Utility Carts', 'Cleaning & Laundry / Laundry Accessories / Utility Carts']
Storage & Organization
Furniture

Searching:  90%|█████████ | 433/480 [02:16<00:11,  4.05it/s]

keywords='beaded curtains' hallucinated_classification=['Home Decor / Window Treatments / Beaded Curtains', 'Interior Design / Decorative Partitions / Beaded Room Dividers', 'Furniture / Room Dividers & Screens / Beaded Curtain Screens', 'Home Accessories / Wall Hangings / Beaded Wall Decor', 'Specialty Home Goods / Bohemian & Ethnic Decor / Beaded Curtain Art']
Furniture
Décor & Pillows

Searching:  90%|█████████ | 434/480 [02:16<00:11,  4.02it/s]

keywords='wayfair sleep zippered' hallucinated_classification=['Home Goods / Bedding & Sleep Accessories / Zippered Mattress Protectors and Covers', 'Furniture / Bedroom Accessories / Zippered Mattress Encasements', 'Home Improvement / Sleep & Comfort / Zippered Sleep Masks and Covers', 'Home Decor / Textiles / Zippered Throw Pillows and Cushions', 'Furniture / Mattresses & Bedding / Zippered Mattress Covers']

Searching:  91%|█████████ | 435/480 [02:17<00:12,  3.49it/s]

Bed Accessories
Bed & Bath
Décor & Pillows
keywords='wrought tv stand' hallucinated_classification=['Furniture / Living Room Furniture / TV Stands & Media Consoles / Wrought Iron TV Stands', 'Furniture / Custom & Artistic Furniture / Wrought Metal Furniture / Wrought TV Stands', 'Home Decor / Metal & Wrought Iron Decor / Wrought Iron TV Stands', 'Furniture / Industrial Style Furniture / Wrought Iron TV Stands', 'Furniture / Entryway & Hallway Furniture / Wrought Iron Console Tables']

Searching:  91%|█████████ | 436/480 [02:17<00:14,  3.14it/s]

Furniture
keywords='tufted chair with gold legs' hallucinated_classification=['Furniture / Accent Chairs / Tufted Chairs', 'Furniture / Living Room Furniture / Armchairs & Lounge Chairs', 'Furniture / Modern & Contemporary Furniture / Gold Legged Chairs', 'Home Decor / Statement Pieces / Gold Accented Furniture', 'Furniture / Upholstered Chairs / Tufted Upholstery']

Searching:  91%|█████████ | 437/480 [02:17<00:13,  3.09it/s]

Furniture
Décor & Pillows
keywords='basket planter' hallucinated_classification=['Home & Garden / Indoor Plants & Planters / Basket Planters', 'Furniture / Indoor Plant Stands & Holders / Basket Style Plant Holders', 'Decor & Accessories / Plant Decor / Basket Planters', 'Outdoor / Garden & Patio / Planters & Pots / Basket Planters', 'Living Room / Indoor Gardening / Basket Planters for Living Spaces']

Searching:  91%|█████████▏| 438/480 [02:18<00:12,  3.34it/s]

Outdoor
Décor & Pillows
keywords='bicycle plant stands' hallucinated_classification=['Home & Garden / Indoor Plants & Planters / Bicycle-Shaped Plant Stands', 'Furniture / Indoor Plant Stands / Bicycle Design', 'Outdoor / Garden Decor / Bicycle Planter Stands', 'Decor & Accessories / Themed Plant Holders / Bicycle Style', 'Living Room Furniture / Unique Plant Stands / Bicycle Motif']

Searching:  91%|█████████▏| 439/480 [02:18<00:11,  3.54it/s]

Outdoor
Furniture
Décor & Pillows
keywords='Nespresso Vertuo Next Premium by Breville with Aeroccino' hallucinated_classification=['Kitchen Appliances / Coffee & Espresso Machines / Capsule Coffee Makers', 'Kitchen & Tabletop / Coffee & Tea Accessories / Milk Frothers & Steamers', 'Home Appliances / Small Kitchen Appliances / Coffee Makers & Espresso Machines', 'Kitchen & Dining / Coffee Station Accessories / Coffee Pod Storage & Organizers', 'Home & Living / Kitchen Gadgets & Tools / Coffee Brewing Equipment']

Searching:  92%|█████████▏| 440/480 [02:18<00:11,  3.59it/s]

Kitchen & Tabletop
Appliances
keywords='big basket for dirty cloths' hallucinated_classification=['Home Organization / Laundry & Utility Storage / Laundry Baskets & Hampers', 'Furniture / Laundry Rooms / Laundry Baskets & Hampers', 'Home Decor / Storage & Organization / Baskets & Biles', 'Cleaning & Laundry / Laundry Accessories / Laundry Baskets']

Searching:  92%|█████████▏| 441/480 [02:18<00:10,  3.86it/s]

Storage & Organization
Décor & Pillows
keywords='zen' hallucinated_classification=['Home & Lifestyle / Meditation & Relaxation Aids / Zen-inspired Decor', 'Furniture / Meditation & Yoga Furniture / Zen Garden Benches', 'Décor & Pillows / Zen-themed Wall Art / Tranquil Landscape Paintings', 'Home Improvement / Zen Garden & Outdoor Decor / Zen Rock Gardens', 'Lighting / Ambient & Mood Lighting / Zen-inspired Lanterns', 'Home Office / Meditation & Relaxation Spaces / Zen Retreat Corners']

Searching:  92%|█████████▏| 442/480 [02:19<00:10,  3.74it/s]

Lighting
Home Improvement
Furniture
Décor & Pillows
keywords='medium size chandelier' hallucinated_classification=['Lighting / Chandeliers / Medium Size Chandeliers', 'Home Decor / Ceiling Fixtures / Medium Chandeliers', 'Luxury Lighting / Statement Chandeliers / Medium Size', 'Interior Design / Ceiling Lighting / Medium Chandeliers', 'Event & Party Supplies / Decorative Chandeliers / Medium Size']

Searching:  92%|█████████▏| 443/480 [02:19<00:09,  3.80it/s]

Lighting
Décor & Pillows
keywords='arwen table lamp' hallucinated_classification=['Lighting / Table Lamps / Decorative Table Lamps', 'Furniture / Living Room Furniture / Accent Tables & Lamps', 'Home Decor / Statement Lighting / Artistic Table Lamps', 'Bedroom / Bedside Lamps / Designer Bedside Lamps', 'Outdoor / Garden & Patio Lighting / Decorative Outdoor Lamps']

Searching:  92%|█████████▎| 444/480 [02:19<00:09,  3.95it/s]

Lighting
Furniture
keywords='mud room sign' hallucinated_classification=['Home Decor / Entryway & Mudroom Decor / Mud Room Signs & Plaques']
Décor & Pillows
keywords='bathroom single faucet' hallucinated_classification=['Home Improvement / Bathroom Fixtures / Faucets & Sink Fixtures / Single-Hole Faucets', 'Bathroom Accessories / Shower & Bath Hardware / Single Faucet Sets', 'Kitchen & Bathroom Plumbing / Bathroom Sink Faucets / Single Handle Faucets', 'Smart Home / Bathroom Automation / Faucet Control Systems', 'Decor & Accessories / Bathroom Decor / Faucet-Themed Decor']

Searching:  93%|█████████▎| 446/480 [02:19<00:07,  4.47it/s]

Home Improvement
Décor & Pillows
keywords='high weight capacity bunk beds' hallucinated_classification=['Furniture / Bedroom Furniture / Bunk Beds & Loft Beds / Heavy Duty Bunk Beds', 'Furniture / Kids & Teen Furniture / Bunk Beds / High Weight Capacity Bunk Beds', 'Home Improvement / Garage & Workshop Storage / Heavy Duty Storage Solutions / Heavy Load Bunk Bed Frames', 'Outdoor / Outdoor & Patio Furniture / Kids & Teen Outdoor Furniture / Heavy Duty Bunk Beds for Outdoor Use', 'Furniture / Custom & Modular Furniture / Heavy Load Capacity Bunk Bed Systems']

Searching:  93%|█████████▎| 447/480 [02:20<00:09,  3.61it/s]

Baby & Kids
Outdoor
Furniture
keywords='living curtains pearl' hallucinated_classification=['Home Decor / Window Treatments / Curtain Panels / Pearl Finish Curtains', 'Furniture / Living Room Decor / Pearl Accented Drapes', 'Interior Design / Textiles / Pearl Embellished Curtains', 'Home Accessories / Decorative Curtains / Pearl Design Drapes', 'Window Coverings / Elegant Curtains / Pearl Color']

Searching:  93%|█████████▎| 448/480 [02:20<00:09,  3.25it/s]

Décor & Pillows
keywords='sunjoy lantern' hallucinated_classification=['Outdoor / Outdoor Lighting / Lanterns and String Lights / Solar Lanterns', 'Home Decor / Decorative Lighting / Tabletop Lanterns / Sunjoy Lanterns', 'Garden & Patio / Garden Decor / Garden Lanterns / Sunjoy Garden Lanterns', 'Event & Party Supplies / Party Lighting / Decorative Lanterns / Sunjoy Lanterns']

Searching:  94%|█████████▎| 449/480 [02:21<00:09,  3.43it/s]

Lighting
Décor & Pillows
keywords='accent chair recliner' hallucinated_classification=['Furniture / Living Room Furniture / Recliner Chairs', 'Furniture / Accent Chairs / Upholstered Accent Chairs', 'Furniture / Lounge & Recliners / Power Recliners', 'Furniture / Home Office Furniture / Recliner Office Chairs', 'Furniture / Custom Furniture / Handmade Recliners']

Searching:  94%|█████████▍| 450/480 [02:21<00:08,  3.64it/s]

Furniture
keywords='johan desk by laurel foundry' hallucinated_classification=['Furniture / Desks & Workstations / Executive Desks', 'Furniture / Home Office Furniture / Writing Desks', 'Furniture / Living Room Furniture / Accent Tables', 'Furniture / Entryway Furniture / Console Tables', 'Furniture / Custom & Modular Furniture / Modular Desks']

Searching:  94%|█████████▍| 451/480 [02:21<00:07,  3.73it/s]

Furniture
keywords='living room designs' hallucinated_classification=['Furniture / Living Room Design & Layouts', 'Decor & Accessories / Wall Art & Murals', 'Lighting / Ambient & Accent Lighting for Living Rooms', 'Flooring / Area Rugs & Carpets', 'Storage & Organization / Shelving & Cabinets', 'Furniture / Modular & Multi-Functional Living Room Furniture', 'Smart Home Devices / Home Automation & Controls', 'Textiles / Curtains & Drapes for Living Rooms']

Searching:  94%|█████████▍| 452/480 [02:21<00:08,  3.39it/s]

Décor & Pillows
Rugs
Home Improvement
Furniture
Lighting
Storage & Organization
keywords='black frame 22 x 36' hallucinated_classification=['Home Decor / Wall Art & Frames / Picture Frames', 'Furniture / Picture Frames / Black Frame Art Displays', 'Office & Study / Bulletin Boards & Pin Boards / Black Frame Bulletin Boards', 'Custom Framing & Art Services / Framing for 22 x 36 Artwork', 'DIY & Craft Supplies / Frame Making Materials / Black Frame Components']

Searching:  94%|█████████▍| 453/480 [02:22<00:07,  3.51it/s]

Home Improvement
Furniture
Décor & Pillows
keywords='writing desk 48"' hallucinated_classification=['Furniture / Office Furniture / Desks & Workstations / Writing Desks', 'Furniture / Home Office Furniture / Study Desks & Tables', 'Furniture / Custom Furniture / Made-to-Order Desks', 'Furniture / Vintage & Antique Furniture / Retro Desks', 'Furniture / Modular Furniture / Adjustable Desks & Workstations', 'Furniture / Eco-Friendly Furniture / Sustainable Desks']

Searching:  95%|█████████▍| 454/480 [02:22<00:07,  3.48it/s]

Furniture
keywords='seat cushions desk' hallucinated_classification=['Furniture / Office Furniture / Desk Accessories / Seat Cushions', 'Furniture / Office Furniture / Desk Chairs / Seat Cushions', 'Home Office / Desk Accessories / Seat Cushions', 'Furniture / Living Room Furniture / Accent Chairs / Seat Cushions', 'Home Decor / Cushions & Pillows / Seat Cushions']

Searching:  95%|█████████▍| 455/480 [02:22<00:06,  3.60it/s]

Outdoor
Furniture
keywords='living room ideas' hallucinated_classification=['Furniture / Living Room Furniture / Modular Sofas and Sectionals', 'Décor & Pillows / Artistic Wall Hangings and Murals', 'Lighting / Ambient and Accent Lighting for Living Rooms', 'Home Organization / Multi-Functional Storage Solutions', 'Smart Home Devices / Voice-Activated Home Assistants', 'Flooring / Area Rugs and Carpets', 'Furniture / Living Room Furniture / TV Stands and Media Consoles', 'Decor & Pillows / Statement Art and Sculptures', 'Furniture / Living Room Furniture / Recliners and Lounge Chairs', 'Home Improvement / Wall Treatments / Wallpaper and Wall Panels']

Searching:  95%|█████████▌| 456/480 [02:23<00:08,  2.81it/s]

Décor & Pillows
Rugs
Home Improvement
Furniture
Lighting
Storage & Organization
keywords='one alium way' hallucinated_classification=['Real Estate / Residential Properties / Address Listings / One Alium Way']
Outdoor
keywords='semi flush foyer light' hallucinated_classification=['Lighting / Ceiling Lights / Semi-Flush Mount Lights', 'Home Decor / Entryway & Foyer Decor / Foyer Lighting Fixtures', 'Lighting / Pendant & Chandeliers / Foyer Pendant Lights', 'Home Improvement / Entryway & Hallway Lighting / Foyer Lighting Solutions', 'Furniture / Entryway Furniture / Foyer Benches & Consoles']

Searching:  95%|█████████▌| 458/480 [02:23<00:05,  3.69it/s]

Home Improvement
Lighting
Furniture
keywords='malachi sled' hallucinated_classification=['Outdoor / Garden Decor / Garden Sleds and Play Equipment', 'Furniture / Kids & Teen Furniture / Kids Sleds and Winter Toys', 'Home Decor / Seasonal & Holiday Decor / Winter and Snow-themed Decor', 'Sports & Recreation / Winter Sports Equipment / Sleds and Toboggans', 'Toys & Games / Outdoor Play / Sleds and Snow Toys']

Searching:  96%|█████████▌| 459/480 [02:23<00:05,  3.69it/s]

Baby & Kids
Outdoor
Holiday Décor
keywords='mid century modern' hallucinated_classification=['Furniture / Mid Century Modern Furniture / Sofas & Sectionals', 'Furniture / Mid Century Modern Furniture / Dining Tables', 'Furniture / Mid Century Modern Furniture / Lounge Chairs', 'Décor & Pillows / Mid Century Modern Decor / Wall Art', 'Lighting / Mid Century Modern Lighting / Floor Lamps', 'Home Accessories / Mid Century Modern Accessories / Vases & Clocks', 'Furniture / Mid Century Modern Furniture / Coffee Tables & Side Tables']
Lighting
Furniture
Décor & Pillows

Searching:  96%|█████████▌| 460/480 [02:24<00:07,  2.86it/s]

keywords='entertainment console' hallucinated_classification=['Furniture / Entertainment & Media Furniture / TV Stands & Media Consoles', 'Furniture / Living Room Furniture / Entertainment Centers & Media Cabinets', 'Home Decor / Media & Entertainment Accessories / TV Mounts & Wall Brackets', 'Furniture / Custom & Modular Furniture / Modular Entertainment Units', 'Furniture / Vintage & Retro Furniture / Retro TV Cabinets']

Searching:  96%|█████████▌| 461/480 [02:24<00:07,  2.53it/s]

School Furniture and Supplies
Furniture
keywords='leather chair' hallucinated_classification=['Furniture / Lounge & Accent Chairs / Leather Armchairs', 'Furniture / Office & Desk Chairs / Leather Executive Chairs', 'Furniture / Recliners & Lounge Chairs / Leather Recliners', 'Furniture / Vintage & Retro Furniture / Leather Vintage Chairs', 'Furniture / Custom & Designer Furniture / Handmade Leather Chairs']

Searching:  96%|█████████▋| 462/480 [02:25<00:08,  2.19it/s]

Furniture
keywords='gas detector' hallucinated_classification=['Home Safety & Security / Gas Detectors & Monitors / Residential Gas Detectors', 'Home Improvement / Electrical & Safety Devices / Gas Leak Detectors', 'Smart Home / Home Safety Devices / Wireless Gas Detectors', 'Industrial & Commercial Safety / Gas Detection Equipment / Portable Gas Monitors', 'Appliances / Kitchen & Home Safety / Gas Leak Detectors']

Searching:  96%|█████████▋| 463/480 [02:26<00:07,  2.16it/s]

Home Improvement
Appliances
keywords='arched christmas tree' hallucinated_classification=['Decor / Holiday Decorations / Christmas Tree Decorations / Arched Christmas Tree']

Searching:  97%|█████████▋| 464/480 [02:26<00:05,  2.73it/s]

Holiday Décor
keywords='cliffside 5 light candle style drum chandelier' hallucinated_classification=['Lighting / Chandeliers / Candle Style Chandeliers', 'Lighting / Pendant Lights / Drum Pendant Lights', 'Home Decor / Ceiling Fixtures / Candle Style Ceiling Lights', 'Luxury Lighting / Statement Chandeliers / Multi-Light Chandeliers', 'Interior Design / Accent Lighting / Decorative Chandeliers']

Searching:  97%|█████████▋| 465/480 [02:26<00:06,  2.47it/s]

Lighting
Holiday Décor
keywords='vlad modular sectional' hallucinated_classification=['Furniture / Modular Sofas & Sectionals / Customizable Sectional Sofas', 'Furniture / Living Room Furniture / Sectional Sofas & Couches / Modular Sectionals', 'Home Decor / Modern Furniture / Modular Seating Systems', 'Furniture / Contemporary Living Room Furniture / Modular Sofas', 'Interior Design / Space Planning / Modular Furniture Solutions']

Searching:  97%|█████████▋| 466/480 [02:27<00:06,  2.30it/s]

Furniture
keywords='white abstract' hallucinated_classification=['Decor & Wall Art / Abstract Wall Decor / White Abstract Art Pieces', 'Furniture / Accent Furniture / Abstract White Sculptural Pieces', 'Home Decor / Tabletop Decor / White Abstract Centerpieces', 'Lighting / Decorative Lamps / White Abstract Lamp Designs', 'Outdoor / Garden Art / White Abstract Garden Sculptures', 'Kids & Teens / Art & Decor / White Abstract Wall Hangings']
Baby & Kids
Décor & Pillows
Outdoor
Furniture
Lighting
keywords='canadian' hallucinated_classification=['Home & Garden / Canadian-themed Decor & Accessories', 'Furniture / Canadian-inspired Furniture / Rustic Maple Tables', 'Outdoor / Canadian Wilderness Outdoor Gear / Camping & Hiking Equipment', 'Kitchen & Dining / Canadian Maple Kitchenware / Cutting Boards & Utensils', 'Decor & Wall Art / Canadian Landscapes / Nature Photography Prints', 'Lighting / Canadian Wilderness Lanterns / Rustic Outdoor Lighting', 'Home Improvement / Canadian Timber & Lumber / Building Materials']

Searching:  98%|█████████▊| 468/480 [02:28<00:05,  2.01it/s]

Décor & Pillows
Outdoor
Kitchen & Tabletop
Home Improvement
Lighting
keywords='wand bunk beds' hallucinated_classification=['Furniture / Kids & Teen Bedroom Furniture / Bunk Beds with Themed Designs', 'Furniture / Kids & Teen Bedroom Furniture / Fantasy & Themed Bunk Beds', 'Furniture / Kids & Teen Bedroom Furniture / Space & Adventure Bunk Beds', 'Furniture / Kids & Teen Bedroom Furniture / Multi-Functional Bunk Beds with Storage', 'Furniture / Kids & Teen Bedroom Furniture / Customizable Bunk Bed Sets']

Searching:  98%|█████████▊| 469/480 [02:28<00:04,  2.31it/s]

Baby & Kids
Furniture
keywords='chair pillow cushion' hallucinated_classification=['Furniture / Seating / Cushioned Chairs and Stools', 'Home Decor / Cushions & Pillows / Decorative Cushions', 'Furniture / Bedroom Furniture / Bedside Cushions and Pillows', 'Outdoor / Patio Cushions / Garden Chair Cushions', 'Kids & Baby / Nursery Accessories / Cushioned Seating for Kids']

Searching:  98%|█████████▊| 470/480 [02:28<00:03,  2.63it/s]

Baby & Kids
Outdoor
Furniture
keywords='upholstered bed' hallucinated_classification=['Furniture / Bedroom Furniture / Upholstered Beds / Modern Upholstered Beds', 'Furniture / Bedroom Furniture / Canopy & Four-Poster Beds / Upholstered Canopy Beds', 'Furniture / Custom Furniture / Upholstered Bed Frames / Custom Upholstered Bed Frames', 'Furniture / Kids & Teens Bedroom Furniture / Upholstered Beds for Kids & Teens', 'Furniture / Luxury & Designer Furniture / Upholstered Bed Collections']

Searching:  98%|█████████▊| 471/480 [02:29<00:03,  2.70it/s]

Baby & Kids
Furniture
keywords='rack glass' hallucinated_classification=['Home Decor / Display & Storage / Glass Racks and Holders', 'Kitchen & Dining / Barware & Glassware Storage / Glass Racks', 'Furniture / Specialty Storage / Glassware Racks', 'Living Room Furniture / Entertainment & Media Storage / Glass Display Cabinets', 'Bathroom Accessories / Shower & Bath Storage / Glass Shelving Units']

Searching:  98%|█████████▊| 472/480 [02:29<00:03,  2.45it/s]

Home Improvement
Furniture
Kitchen & Tabletop
Bed & Bath
keywords='fountains with brick look' hallucinated_classification=['Outdoor / Garden Decor / Fountains & Water Features / Brick Look Fountains', 'Home & Garden / Outdoor Decor / Water Features / Brick Style Fountains', 'Garden & Patio / Water Features / Brick Finish Fountains', 'Outdoor / Fountains & Water Features / Brick Design Fountains', 'Decor & Accents / Water Features / Brick Pattern Fountains']

Searching:  99%|█████████▊| 473/480 [02:30<00:02,  2.43it/s]

Home Improvement
Outdoor
Décor & Pillows
keywords='benjiamino faux leather power lift chair' hallucinated_classification=['Furniture / Recliners & Power Chairs / Power Lift Chairs', 'Furniture / Living Room Furniture / Armchairs & Accent Chairs', 'Home Comfort / Reclining & Lift Chairs / Power Lift Chairs', 'Medical & Mobility / Lift Chairs / Power Lift Chairs', 'Furniture / Upholstered Chairs / Faux Leather Chairs']

Searching:  99%|█████████▉| 474/480 [02:30<00:02,  2.43it/s]

Furniture
keywords='infant girl crib bedding' hallucinated_classification=['Baby & Kids / Nursery Bedding & Linens / Crib Bedding Sets', 'Baby & Kids / Nursery Decor / Crib Canopies & Accessories', 'Baby & Kids / Nursery Furniture / Crib Frames & Mattresses', 'Baby & Kids / Baby Bedding & Linens / Crib Sheets & Mattress Protectors', 'Baby & Kids / Nursery Storage & Organization / Crib Storage Solutions']

Searching:  99%|█████████▉| 475/480 [02:30<00:02,  2.40it/s]

Baby & Kids
Bed & Bath
Storage & Organization
keywords='bed risers' hallucinated_classification=['Furniture / Bedroom Furniture / Bed Accessories / Bed Risers', 'Home Organization / Under Bed Storage Solutions / Bed Risers', 'Furniture / Bedroom Furniture / Bed Frames & Supports / Bed Risers', 'Home Improvement / Furniture Accessories / Bed Support Accessories / Bed Risers', 'Decor & Home Accents / Space Enhancers / Bed Risers']

Searching:  99%|█████████▉| 476/480 [02:31<00:01,  2.38it/s]

Bed Accessories
Bed & Bath
Décor & Pillows
Furniture
keywords='gowdy height adjustable standing desk' hallucinated_classification=['Furniture / Office Furniture / Standing Desks / Height Adjustable Standing Desks', 'Furniture / Home Office Furniture / Adjustable Workstations', 'Furniture / Ergonomic Furniture / Sit-Stand Desks', 'Home Improvement / Office Renovation / Adjustable Desk Solutions', 'Furniture / Commercial Furniture / Adjustable Desks for Workspaces']

Searching:  99%|█████████▉| 477/480 [02:31<00:01,  2.44it/s]

Furniture
keywords='tressler rug' hallucinated_classification=['Home Decor / Rugs & Carpets / Area Rugs', 'Furniture / Floor Coverings / Rugs and Mats', 'Decor & Pillows / Decorative Rugs / Tressler Style Rugs', 'Interior Design / Floor Textiles / Tressler Pattern Rugs', 'Home Accessories / Floor Decor / Tressler Pattern Rugs']

Searching: 100%|█████████▉| 478/480 [02:32<00:00,  2.49it/s]

Rugs
keywords='desk for kids' hallucinated_classification=["Furniture / Kids' Furniture / Desks & Study Tables / Kids Desks", "Furniture / Educational & Playroom Furniture / Children's Desks & Tables", "Furniture / Bedroom Furniture / Kids' Study Desks", "Furniture / Home Office & Study Furniture / Kids' Study Desks & Workstations", "Furniture / Multi-Functional Furniture / Kids' Activity & Play Desks"]

Searching: 100%|█████████▉| 479/480 [02:32<00:00,  2.79it/s]

Baby & Kids
Furniture
keywords='flamingo' hallucinated_classification=['Decor / Themed Home Decor / Animal Themed Decor / Flamingo Decor', 'Garden & Outdoor / Garden Statues & Ornaments / Flamingo Garden Statues', 'Kids & Teens / Kids Room Decor / Flamingo Wall Art & Prints', 'Fashion & Accessories / Novelty Accessories / Flamingo-themed Accessories', 'Party Supplies / Themed Party Decorations / Flamingo Party Decor']

Searching: 100%|██████████| 480/480 [02:32<00:00,  3.06it/s]

Baby & Kids
Outdoor
Décor & Pillows

Searching: 100%|██████████| 480/480 [02:33<00:00,  3.13it/s]

,product_id,product_name,product_class,category hierarchy,product_description,product_features,rating_count,average_rating,review_count,features,...,score,query,query_id,rank,grade,discounted_gain,idcg,dcg,ndcg,mrr
0,26644,international harvester melamine serving tray,Serving Dishes & Platters|Licensed Products,Kitchen & Tabletop / Tableware & Drinkware / S...,this case ih serving tray is a perfect additio...,overalllength-endtoend:11.5|pattern : no patte...,NaN,NaN,NaN,"[overalllength-endtoend:11.5, pattern : no pat...",...,84.232885,certified international melamine,73,1,1.0,1.000000,8.786905,2.928968,0.333333,0.0
1,9709,certified international gather oval baking dish,NaN,Kitchen & Tabletop / Cookware & Bakeware / Bak...,simple crockery with the look of hand-thrown p...,overalllength-endtoend:14.25|productcare : dis...,2.0,5.0,1.0,"[overalllength-endtoend:14.25, productcare : d...",...,72.629265,certified international melamine,73,2,1.0,0.500000,8.786905,2.928968,0.333333,0.0
2,26646,international harvester melamine cereal bowl,Dining Bowls|Licensed Products,Kitchen & Tabletop / Tableware & Drinkware / D...,this four pack of cereal or soup bowls feature...,color : red/white|productcare : dishwasher saf...,NaN,NaN,NaN,"[color : red/white, productcare : dishwasher s...",...,72.511242,certified international melamine,73,3,1.0,0.333333,8.786905,2.928968,0.333333,0.0
3,9707,certified international piazzette 3d villa sal...,Salt And Pepper Shakers / Grinders (Mills),Kitchen & Tabletop / Tableware & Drinkware / S...,,productweight:1.5|trend : novelty|productcare ...,15.0,5.0,12.0,"[productweight:1.5, trend : novelty, productca...",...,67.439243,certified international melamine,73,4,1.0,0.250000,8.786905,2.928968,0.333333,0.0
4,26645,international harvester melamine chip and dip ...,Serving Dishes & Platters|Licensed Products,Kitchen & Tabletop / Tableware & Drinkware / S...,"perfect for the case ih enthusiast , serve you...",producttype : chips and dip platter|overallwid...,NaN,NaN,NaN,"[producttype : chips and dip platter, overallw...",...,65.514072,certified international melamine,73,5,1.0,0.200000,8.786905,2.928968,0.333333,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4795,17391,rondon a pink flamingo paper print,Kids Wall Décor,Baby & Kids / Baby & Kids Décor & Lighting / A...,perfect for the nursery or a little girl 's be...,gender : girl / woman+|primarymaterialdetails ...,1.0,5.0,1.0,"[gender : girl / woman+, primarymaterialdetail...",...,63.986856,flamingo,102,6,2.0,0.500000,8.786905,8.786905,1.000000,1.0
4796,3267,flamingos green by cat coquillette - print,Wall Art,Décor & Pillows / Art / All Wall Art / Green W...,showcasing a pair of flamingos encircled by ve...,holidayoccasion : no holiday|shape : square|co...,1.0,4.0,1.0,"[holidayoccasion : no holiday, shape : square,...",...,58.481298,flamingo,102,7,2.0,0.428571,8.786905,8.786905,1.000000,1.0
4797,2777,flamingo- unframed print on canvas,Wall Art,Décor & Pillows / Art / All Wall Art,bay isle home 15 '' x30 '' flamingo i & ii set...,foodbeverage : not food & beverage|orientation...,NaN,NaN,NaN,"[foodbeverage : not food & beverage, orientati...",...,55.176806,flamingo,102,8,2.0,0.375000,8.786905,8.786905,1.000000,1.0
4798,3264,slurping flamingo,Decorative Objects,Décor & Pillows / Home Accessories / Decorativ...,this handpainted indoor/outdoor accessory adds...,overallwidth-sidetoside:21|supplierintendedand...,14.0,4.5,13.0,"[overallwidth-sidetoside:21, supplierintendeda...",...,53.760254,flamingo,102,9,2.0,0.333333,8.786905,8.786905,1.000000,1.0
4799,2207,flamingo magnet wall décor,Wall Décor,Sale / Closeout / Wall Accents / Blue Wall Acc...,this beautifully handcrafted flamingo wooden d...,productcare : wipe clean with a dry cloth . do...,NaN,NaN,NaN,[productcare : wipe clean with a dry cloth . d...,...,50.694689,flamingo,102,10,2.0,0.300000,8.786905,8.786905,1.000000,1.0

### Check results - Observe still healthy NDCG bump

NDCG still pretty good (not as good as sending the Literal list). But still pretty healthy increase.

In [ ]:
ndcgs(graded_bm25).mean(), ndcgs(graded_fully_classified).mean()

(np.float64(0.5411098691836396), np.float64(0.5586509656926943))

In [ ]:
deltas = ndcg_delta(graded_fully_classified, graded_bm25)

In [ ]:
sig_improved = len(deltas[deltas > 0.1])
print(f"Num Significatly Improved: {sig_improved}")
deltas[deltas > 0.1]

Num Significatly Improved: 34

query
drum picture                                                       0.506435
non slip shower floor tile                                         0.458113
desk for kids                                                      0.412546
turquoise chair                                                    0.403107
modern outdoor furniture                                           0.365533
twin bed frame                                                     0.359391
wood rack wide                                                     0.346159
liberty hardware francisco                                         0.292914
storage dresser                                                    0.270289
podium with locking cabinet                                        0.256063
outdoor lounge chair                                               0.248431
hardwood beds                                                      0.235334
carpet 5x6                                                         0.210992
china clock                                                        0.189044
ayesha curry kitchen                                               0.180192
moen 5995 arbor one                                                0.179876
dark gray dresser                                                  0.175902
town & country living curtains                                     0.154089
acrylic clear chair                                                0.150386
oriental vanity                                                    0.149347
odum velvet                                                        0.139096
bedroom wall decor floral, multicolored with some teal (prints)    0.132006
wainscoting ideas                                                  0.125186
upholstered girls bed                                              0.125186
light and navy blue decorative pillow                              0.124690
auburn throw pillows                                               0.122341
medium size chandelier                                             0.119812
outdoor privacy wall                                               0.116786
closet storage with zipper                                         0.113806
small wardrobe grey                                                0.113806
driftwood mirror                                                   0.111096
teal chair                                                         0.109380
midcentury tv unit                                                 0.102425
outdoor welcome rug                                                0.100935
Name: ndcg, dtype: float64

In [ ]:
sig_harmed = len(deltas[deltas < -0.1])
print(f"Num Significatly Harmed: {sig_harmed}")
print(f"Prop improved/harmed: {sig_improved / (sig_harmed + sig_improved)} | {sig_harmed / (sig_harmed + sig_improved)}")
deltas[deltas < -0.1]

Num Significatly Harmed: 6
Prop improved/harmed: 0.85 | 0.15

query
bedroom accessories             -0.113173
zodiac pillow                   -0.113806
papasan chair frame only        -0.123290
bathroom freestanding cabinet   -0.155670
outdoor lounge cushions         -0.223547
sugar canister                  -0.224721
Name: ndcg, dtype: float64

### Look at a query

In [ ]:
QUERY = "outdoor lounge cushions"
fully_classified(QUERY), fully_classified(QUERY).cat_subcat

(QueryClassification(keywords='outdoor lounge cushions', hallucinated_classification=['Outdoor / Outdoor Comfort & Decor / Lounge Cushions & Pillows / Outdoor Lounge Cushions', 'Furniture / Patio & Garden Furniture / Lounge Seating / Outdoor Lounge Cushions', 'Home Decor / Textiles / Cushions & Pillows / Outdoor Lounge Cushions', 'Garden & Patio / Outdoor Furniture Accessories / Cushions & Pillows / Lounge Cushions']),
 {'Outdoor / Outdoor & Patio Furniture', 'Outdoor / Outdoor Décor'})

In [ ]:
graded_fully_classified[graded_fully_classified['query'] == QUERY][['product_name', 'category hierarchy', 'grade', 'score']]

,product_name,category hierarchy,grade,score
2840,classic outdoor lounge chair cushion,Outdoor / Outdoor Décor / Outdoor Pillows & Cu...,2.0,89.672464
2841,outdoor reclining chaise lounge with cushion,Outdoor / Outdoor & Patio Furniture / Outdoor ...,1.0,87.930735
2842,iola outdoor reclining chaise lounge with cushion,Outdoor / Outdoor & Patio Furniture / Outdoor ...,1.0,87.345481
2843,outdoor lounge chair cushion,Outdoor / Outdoor Décor / Outdoor Pillows & Cu...,2.0,86.526578
2844,make it rain cerulean indoor/outdoor chaise lo...,Outdoor / Outdoor Décor / Outdoor Pillows & Cu...,2.0,85.435493
2845,annoeska outdoor reclining chaise lounge with ...,Outdoor / Outdoor & Patio Furniture / Outdoor ...,1.0,85.104139
2846,french edge indoor/outdoor lounge chair cushion,Outdoor / Outdoor Décor / Outdoor Pillows & Cu...,2.0,83.353908
2847,achary outdoor reclining chaise lounge with cu...,Outdoor / Outdoor & Patio Furniture / Outdoor ...,1.0,82.629874
2848,alexandra outdoor reclining chaise lounge with...,Outdoor / Outdoor & Patio Furniture / Outdoor ...,1.0,82.133712
2849,cara indooroutdoor chaise lounge cushion,Outdoor / Outdoor Décor / Outdoor Pillows & Cu...,2.0,81.857544

In [ ]:
graded_bm25[graded_bm25['query'] == QUERY][['product_name', 'category hierarchy', 'grade', 'score']]

,product_name,category hierarchy,grade,score
1790,outdoor chaise lounge cushion,NaN,2.0,79.604049
1791,dorrington outdoor chaise lounge cushion,NaN,2.0,75.647600
1792,replacement pillows outdoor lounge chair cushion,NaN,2.0,75.266675
1793,indoor/outdoor sunbrella chaise lounge cushion,NaN,2.0,74.830838
1794,classic outdoor lounge chair cushion,Outdoor / Outdoor Décor / Outdoor Pillows & Cu...,2.0,74.672464
1795,tropical outdoor lounge chair cushion,NaN,2.0,73.328272
1796,outdoor reclining chaise lounge with cushion,Outdoor / Outdoor & Patio Furniture / Outdoor ...,1.0,72.930735
1797,jermaine outdoor lounge chair cushion,NaN,2.0,72.379733
1798,iola outdoor reclining chaise lounge with cushion,Outdoor / Outdoor & Patio Furniture / Outdoor ...,1.0,72.345481
1799,jermaine outdoor chaise lounge cushion,NaN,2.0,72.293746